### ISSUE TITLE
Using volume keys on keyboard opens friends menu

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#101]
I have two buttons on my keyboard dedicated to changing the volume, and whenever I press them the MT friends list menu opens. It doesn't have a keybind, which is double weird.
![image](https://user-images.githubusercontent.com/15698722/63747362-91d21c00-c86c-11e9-9782-6a876cf348de.png)

**Comment by Cloudhunter** [comment]
Does this issue occur if a key is bound?

**Comment by aaronhowser1** [comment]
I set it to NumLock and then hit the volume button, and it didn't open the Friends menu

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/66895377-401a5800-efb8-11e9-8e21-90d1ef76da25.png)
![image](https://user-images.githubusercontent.com/15698722/66895383-43154880-efb8-11e9-97f2-3e42ba240db2.png)

If this could be fixed pretty soon, that would be *great*. We're losing players because of this.

**Comment by CH-Paul-T** [comment]
A good initial fix would be to bind the key. This happens when the keybind is unset, for some reason java returns null for a lot of keys.

I know this is fixed in development version, but unsure if it’s made it to any production versions. Including the version number that it’s happening in helps.

________________________________

**Comment by aaronhowser1** [comment]
We shipped with changed default settings in 1.0.0, but not in 1.1.0 on because we don't want to overwrite their changes if they've made any.

Academy 1.1.0 is using minetogether-1.10.2-2.2.0-RC6

**Comment by gigabit101** [comment]
This has been fixed in dev already and will be available in the next release
