### ISSUE TITLE
Notification for new server chat messages while in minetogether chat

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#102]
When the server is empty, I like to hang out in the global chat. However, if someone joins the server and starts talking to me, they think I'm ignoring them because I don't respond. There should be like a small exclamation mark next to the server tab button if there are unread server messages I think.

**Comment by Cloudhunter** [comment]
This is technically supposed to be in (different colour) but it may have been broken in the latest release due to the group chat changes. Will look into it!

**Comment by gigabit101** [comment]
Fixed in version 2.2.1

**Comment by aaronhowser1** [comment]
I haven't checked the new version out yet, so idk if it addresses it, but let me specify. If I'm not active in chat, but I'm in MT chat and not Server chat, I will never see that the Server chat is now blue. The only way I can know if someone in the server is trying to talk to me is if I open chat, but I often lurk in global chat without ever actually opening chat.
