### ISSUE TITLE
StoneBlock Singleplayer world won't start 

### ISSUE THREAD

**Issue by Braedenkillsu** [CreeperHost/CreeperHostGui#104]
Game won't start and says the issue is Mine Together and Mine Together Server mod 
https://paste.dimdev.org/ugukihokor.mccrash this is crash report

**Comment by CH-Paul-T** [comment]
Please confirm the version of MineTogether being used.

It looks like a really old version (1.10.2-2.1.3)

**Comment by gigabit101** [comment]
It looks like the version of MineTogether you are using is outdated according to the log you provided, This should have already been fixed in newer versions

**Comment by gigabit101** [comment]
closing due to no response
