### ISSUE TITLE
Client banned for loging in multiple places too quickly

### ISSUE THREAD

**Issue by aivass** [CreeperHost/CreeperHostGui#107]
I use a laptop and a desktop to play minecraft, depending on if I'm home or not. The MineTogether moderation system has determined this to be a red flag. I haven't connected from my desktop client for over 24 hours.
![2019-09-19_12 25 42](https://user-images.githubusercontent.com/25469916/65286252-c2b41280-daf3-11e9-9c96-d1106acb45df.png)

**Comment by gigabit101** [comment]
Can I ask if you are still having this issue? This should be resolved by restarting your game

**Comment by Lelaxlp** [comment]
I have the same error message, restarting doesnt fix it :/

**Comment by gigabit101** [comment]
Fixed in version 2.2.1
