### ISSUE TITLE
my client got kicked/slienced???

### ISSUE THREAD

**Issue by silasahm** [CreeperHost/CreeperHostGui#108]
Hej so I was kicked, because I was "swearing", but I didn't say anything, the worst thing I said was "damn." which I don't think counts as a swear word.

Then after a day, I got silenced, this was what the system said "we've detected multiple clients attempting to join MineTogether chat from the same account. As such, we have disabled your ability to send messages from this client." but here is the thing, no one else has access to my account other than me, so I don't know how it thinks that "multiple clients attempting to join MineTogether chat." 

can someone please help me or at least explain it, I really want to get back and talk to people
![2019-09-20_12 19 46](https://user-images.githubusercontent.com/55583620/65320631-97d4c780-dba2-11e9-8b78-c22ab59b95a3.png)
 what is going on?

**Comment by Draylynn** [comment]
"we've detected multiple clients attempting to join MineTogether chat from the same account" this occurs if you try to reconnect too quickly, or with a second client whilst the first client is still chatting away.
From our side of the system, no kicks were issued by mods out. However, your messages as shown in the screenshot do not appear to have registered with our chat server _[11.10am(GMT) Friday-September-2019]_.

There is no 'kicks' in our system, only bans. You cannot connect at all (meaning no reading, or posting to chat) if there is a ban in place.
If you were muted, these are usually temporary, you can still type, but no one, not even the chat server will relay the messages.

**Comment by silasahm** [comment]
yeah I was first kicked, then silenced, so I could only see messages, but if I tried to write, the other people wouldn't see it, and I haven't tried to do anything for a couple of days but it still says I have been silenced. So I don't know what am suppose to do now, was kinda hoping one of the mods could help me out

**Comment by Draylynn** [comment]
There wasn't anyone at all on our mute list earlier.

This sounds like it may be a local connection problem, or, something may be interfering with the traffic: Your computer/home network isn't using a Net Nanny, OpenDNS content filter, or something like Covernant Eyes? We have had reports of these things causing unusual problems with MineTogether.
There's no chance there's a stuck Java process still running silently in the background that could be hogging the connection to MineTogether? (Have you tried a PC reboot?)

**Comment by gigabit101** [comment]
closing due to no response
