### ISSUE TITLE
Caught exception from MineTogetherServer

### ISSUE THREAD

**Issue by Calcaholic** [CreeperHost/CreeperHostGui#109]
Whenever I start my singleplayer world with the MineTogether mod included, my game will crash with the message "The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver);

Pastebin of crash report : https://pastebin.com/PUPbAbU6

**Comment by Jake-E** [comment]
You're using an old version of the mod (from 2018). Please consider updating.
