### ISSUE TITLE
Add a De-Pseudonymisation option

### ISSUE THREAD

**Issue by iComputerfreak** [CreeperHost/CreeperHostGui#110]
You could add a de-pseudonymisation option to allow users to disable the feature for themselves.
Meaning, showing their username to anybody, not only friends, if they enabled it.
For the Opt-Out, you could make a dialog like the EULA one, so the option is not stored in the config and modpacks cannot disable it in-before.
Since it is opt-out it would not decrease the privacy of other users and it would make the chat a bit more readable, reducing the number of generic usernames.

Optionally you could make it, so only players that opted out of the pseudonymisation could see other players that opted out. (Like you only see the "last seen" time on WhatsApp, if you have yours visible as well)

**Comment by CH-Paul-T** [comment]
We would, but this would require storing more user data and that is outside the scope of what we wish to do with the mod for political reasons.
