### ISSUE TITLE
Reloading Minecraft will silence you.

### ISSUE THREAD

**Issue by sweepea38** [CreeperHost/CreeperHostGui#112]
Unique Code : TOAy-HicS

It will say that you're connecting through too many clients and silence you, defeating most of the purpose of this for the user who just needed to quickly reboot his game.

**Comment by Draylynn** [comment]
Previously users were able to dual-login, however, this feature has been previously used to evade the ban system and was removed.
We are looking into reworking the reconnect system.

Were you reloading the client, or using F3+T to do a softer-reload?

**Comment by Lelaxlp** [comment]
I have Pretty much the same problem, just that it doesnt work at all and instantly kicks me out as soon as I open the Chat  :/

**Comment by Lelaxlp** [comment]
It even happens after I reinstalled the whole modpack :(

**Comment by gigabit101** [comment]
Fixed in version 2.2.1
