### ISSUE TITLE
Disconnected From Minetogether

### ISSUE THREAD

**Issue by Sclaraidus** [CreeperHost/CreeperHostGui#113]
I'm not sure if I was banned because I wasn't saying anything, all I was saying is "hi" and "how are u?". 
![image](https://user-images.githubusercontent.com/55774567/65565274-086a4400-df15-11e9-91f5-f9667c495cfc.png)

**Comment by CH-Paul-T** [comment]
Can’t see any ban there, only a disconnection.

________________________________

**Comment by Draylynn** [comment]
Confirmed, there is no ban around 3:22am (GMT) when these messages were posted.
NOTE: If you time out and the reconnects fail, eventually the mod will give up trying to reconnect and you will need to restart the client.

**Comment by Draylynn** [comment]
Are you still having issues with your connection?
