### ISSUE TITLE
Banned 10/5/2019 - user "hmcd"

### ISSUE THREAD

**Issue by SullySadface** [CreeperHost/CreeperHostGui#117]
Hi, I was banned for [quoting The Fifth Element](https://www.imdb.com/title/tt0119116/quotes/qt0464065). I can understand the logic behind it, as one unfamiliar with a 20-year-old movie could see it as inappropriate, and I apologize that I came off that way as it was not my intention.

I am raising this issue not because of the actions taken in regards to my silly quip, but more so as I did not receive a warning of any kind, which to my understanding is the protocol as evidenced in [this post](https://github.com/CreeperHost/CreeperHostGui/issues/81#issuecomment-508987877). I attempted to connect to the IRC server directly to see if there was a place there I could address this, but - as you already know - I received a ban for using an "unauthorized client." 

Again, I understand that my statement could be construed as inappropriate and I am not debating that. I simply wish to be unbanned, as I only play Minecraft in single-player and have grown to like interacting with others in the chat in lieu of having them present in my world. 

If permitted back in the chat I will make sure to not toe the line as far as acceptable conduct is concerned. If not, I understand, and I appreciate you taking the time to read this and hope you have an enjoyable weekend.

**Comment by CH-Paul-T** [comment]
Hello,

You where banned for the following;

Drugs being mentioned (definitely adult and clearly against the rules)
I exclaiming you where trying to push the rules
Saying you wished to be grossly incandescent
Using the words ‘thirsty incel’

I’m going to leave this here as a warning to everyone else that we see it all and will shame you when you come here and lie.

Regards,
Paul

________________________________
