### ISSUE TITLE
Ban 8/10/19

### ISSUE THREAD

**Issue by Slimey489** [CreeperHost/CreeperHostGui#118]
hello i belive that i have been banned mistakenly as i was simply anwsering a question that one of the fellow chatters posted the question was name a country in africa starting with the letter n so i replied with niger and i got banned for using innipropate laungage so after i looked it up to see if i spelt it correctly and i did and to show proof of the question i will link in a screenshot
![Screenshot (101)](https://user-images.githubusercontent.com/55477448/66352891-3479d080-e9bd-11e9-92e6-45c4430deaf8.png)
and i understand that this post may be left up for all to shame me and i also think that the question may have been a trap

**Comment by CH-Paul-T** [comment]
Hello,

I actually saw this in the logs.

You've been unbanned and the person you see here above as 'User244' has been banned for breaking Wheaton's law.

Paul

**Comment by Slimey489** [comment]
thanks
