### ISSUE TITLE
My client got banned

### ISSUE THREAD

**Issue by andrebore0** [CreeperHost/CreeperHostGui#119]
Hello, i got my client banned and i don't know the reason, so i'm hoping you could help me,
Ign: XenOn_
Thanks,
Andrea

**Comment by Draylynn** [comment]
We would need a ban ID, or a snippet of communication to track you down in MineTogether.
Chat moderators do not see your name, or UserNumber, we cannot identify you with your username.

**Comment by andrebore0** [comment]
Sorry for the ignorance, how do i get my ban id, i cannot see the chat anymore because im disconnected, and the only thing i know is my Unique-code on the friends list.

**Comment by Draylynn** [comment]
Your ban ID is shown when you get banned.
