### ISSUE TITLE
[API] SRV record support

### ISSUE THREAD

**Issue by Vankka** [CreeperHost/CreeperHostGui#12]
The api doesn't seem to support SRV records got: `{"status":"error","message":"Unable to verify server.","endPoint":"grantham-api"}` using an SRV record

**Comment by CH-Paul-T** [comment]
Please provide the full request sent and the actual connection details of the server so I can look into this.

If a full request is sent then SRV support should be obsolete, if I have all the information I can either identify and fix or provide information on how to use the API in your use case.

**Comment by VankkaGithub** [comment]
**Data sent**

Headers
```
Content-Type:application/json
content-length:104
```

Body
```
{
  "name": "BtB DW20",
  "port": 25565,
  "ip": "dw.beyondthebeast.eu",
  "projectid": 281999
}
```
**Response (Debugging Proxy)**

Headers
```
connection:keep-alive
x-apiary-transaction-id:5a57b98f8e33ad07001cf611
server:nginx/1.11.2
date:Thu, 11 Jan 2018 19:23:07 GMT
content-type:application/json
transfer-encoding:chunked
x-powered-by:PHP/7.0.18
expires:Mon, 26 Jul 1997 05:00:00 GMT
last-modified:Thu, 11 Jan 2018 19:22:56 GMT
cache-control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma:no-cache
access-control-allow-headers:Origin, X-Requested-With, Content-Type, Accept, Key, Secret, Cache-Control
access-control-allow-methods:GET, PUT, POST
api-version:Aries 1.0.2-livedev
access-control-allow-origin:*
x-newrelic-app-data:PxQDVFVRCQITVlZRDgcFV0YdFGQHBDcQUQxLA1tMXV1dSnwZQRNWERdcRE42NmwcH05DTgcfB1ZcHQcCTFVQUAdbCVAIDRgfAkkbUAICVgcHVQYDB1EBAwRUQ05RUFsVAWw=
via:1.1 vegur
```

Body
```
{
  "status": "error",
  "message": "Unable to verify server.",
  "endPoint": "buffalo-api"
}
```

**Response (Production)**

Headers
```
connection:keep-alive
server:nginx/1.13.7
date:Thu, 11 Jan 2018 19:26:08 GMT
content-type:application/json
transfer-encoding:chunked
x-powered-by:PHP/7.1.11
expires:Mon, 26 Jul 1997 05:00:00 GMT
last-modified:Thu, 11 Jan 2018 19:25:57 GMT
cache-control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma:no-cache
access-control-allow-headers:Origin, X-Requested-With, Content-Type, Accept, Key, Secret, Cache-Control
access-control-allow-methods:GET, PUT, POST
api-version:Aries 1.0.2-livedev
access-control-allow-origin:*
x-newrelic-app-data:PxQDVFVRCQITVlZRDgcFV0YdFGQHBDcQUQxLA1tMXV1dSnwZQRNWERdcRE42NmwcH05DTgcfB1ZWHQcCTFFbUQlTClQKDQQCA1UJUB1MAk5GAgMFAgcNBVMAVQFUBwNESFdXXxEDPg==
```

Body
```
{
  "status": "error",
  "message": "Unable to verify server.",
  "endPoint": "newyork-api"
}
```

**SRV Record**
https://i.imgur.com/Qe94umZ.png
dw-server.beyondthebeast.eu is a route to my bungeecord proxy for connecting directly to direwolf20

**Comment by Cloudhunter** [comment]
I'm a little confused. You say you are sending port 25565 - but there appears to be no port open on port 25565.

Your screenshot of the SRV record, also shows port 25564. Whilst our API won't currently support SRV records, specifying the wrong port certainly won't help matters. If you instead send a request of dw-server.beyondthebeast.eu with 25564, it should work.

Regarding SRV support, we'll leave it open as a feature request - but there's no reason you can't currently get this working if you send the right information.

**Comment by VankkaGithub** [comment]
the SRV record's port is intentionally 25564 and wouldn't setting the "port": to 25564 (wouldn't work) change the port on the server list, dw.beyondthebeast.eu only has port 80 open, the srv record is pointing to dw-server.beyondtgebeast.eu (and the proxy is listening for port 25564) if you try Dinnerbone's server pinger the server _gets found_ https://dinnerbone.com/minecraft/tools/status/

**Comment by Cloudhunter** [comment]
Thing is, the srv support in Minecraft is done so you can specify a port in a DNS entry for when you have shared hosting.

I'm aware that it is intentionally set to 25564 in your configuration - but I'm just confused as to why you are sending the SRV entry at all when you have an A record on dw-server.beyondthebeast.eu, and have the ability to set the port in the request.

If we do do SRV support in the future, and I'm honestly not quite sure on the use case for it, it'll require client changes as well as server changes due to the fact that even if the port is 25565 I currently append it to the server data as there was no harm in doing so. I'm assuming that would confuse Minecraft and is unlikely to work.

Please try sending the actual A record with the correct port and it should work.

**Comment by CH-Paul-T** [comment]
Will consider this as a low priority feature request, no immediate changes will be made as it's purely cosmetic, as the user never has to view or enter the server details, so no hardship or UX issue is created by receiving the A entry and port instead of us just parsing the SRV record to the A entry and port ourselves.

**Comment by VankkaGithub** [comment]
the thing is the CNAME record is protected by cloudflare to serve a website on the address (Dynmap) with a secured connection (to allow the main website to be protected as they cannot contain unsecured content), and thus cannot be done but i'm sure i can find a work around for dynmap

**Comment by Cloudhunter** [comment]
If Minecraft can see the redirected domain in the SRV record, then our API will be able to as well. You shouldn't have to alter your setup. CloudFlare will have nothing to do with it. 

Please try sending dw-server.beyondthebeast.eu with port 25564 - it should work without an issue.

**Comment by Cloudhunter** [comment]
I just sent this:

```
{
	"ip": "dw-server.beyondthebeast.eu",
	"port": 25564,
	"name": "Test server please ignore",
	"projectid": 666
}
```

Without an issue, getting a success back as anticipated:

```
{
    "status": "success",
    "message": "Server information registered.",
    "id": 3757,
    "secret": "pNgfCXVbeQzGsEfORUjAeapofqLvVBVIoenMnUNIov",
    "endPoint": "staging-api"
}
```

**Comment by VankkaGithub** [comment]
I found a workaround for dynmap and got rid of most of my srv record and all -server sub domains

**Comment by Cloudhunter** [comment]
Locked it now as issue sorted, and leaving this to remind us :)

**Comment by CH-Paul-T** [comment]
Got some basic SRV support in testing at the moment, expect to see it live within a week.

**Comment by Cloudhunter** [comment]
Live months ago, closing
