### ISSUE TITLE
Muted?

### ISSUE THREAD

**Issue by rer111** [CreeperHost/CreeperHostGui#120]
So eh i was playing with this mod and chatting and then this happend. 
![ahajadu](https://user-images.githubusercontent.com/56360144/66500206-6f652c80-eac1-11e9-8c26-4c9786dec9f1.PNG)

(Im rasmus_h_2002) 

Does this mean i have been muted for the whole chat? it would seem so. And is it permanent?

**Comment by Draylynn** [comment]
It means you were muted, anything you type is not seen by other users. Mutes are generally temporary, unless a bot has muted you, in which case the chat mod on shift will need to review your mute and decide whether to release it, or ban you.
NOTE: You should be unmuted already.
