### ISSUE TITLE
muted, dont know who is on, yada yada

### ISSUE THREAD

**Issue by Lavantant** [CreeperHost/CreeperHostGui#121]
![image](https://user-images.githubusercontent.com/29828908/66541208-7eb59b80-eafc-11e9-9110-711f63a97692.png)

well, i hope that whenever one of the mods sees this, they reccomend you guys also do something about false positives with the detection system for curses, or at least if its gonna automute for them to make it impossible to send the msg anyways, like you guys do with not letting people say "its exponential" ;)

**Comment by Lavantant** [comment]
but uh, yea for real false positives on thinking i was talking about coital action when i was trying to explain tinker tools levelups to someone actually annoyed me more than being auto-muted for explaining why one word might be acceptable and the other one isnt, only to find out it wasnt ok to the bot after all via instant auto-mute...

**Comment by Lavantant** [comment]
oh, right, you guys may also want to make it so that people can, even when muted, can still type into the chat to get the bot to send the rules, as im pretty sure you guys have a link to the right github in there (i dont think its this one, i think this one is more for tech issues than ban/kick/mute repeals)

**Comment by Lavantant** [comment]
but yea trying to automatically get people that are trying to get past the filters only works if you can think of every way that they might say things, AND are 100% okay with false positives (again, "its exponential" isnt okay, but "seex" is, and when you guys get that, putting a 0 in between each letter wont be gotten, until you get that and its just a never ending battle, and dont get me started on basic and obscure leetspeak XD ) so, i know i probably wont change all your minds on this but i think its probably a good thing to think about, and i figure someone has to say it eventually

**Comment by Draylynn** [comment]
These words are muted as a precaution, obviously "cock" is not used to refer to a male chicken ro to prime a weapon in MineTogether chat, quite often: 99% of cases, it's a ban. I know the detection/word system can be a pain in the backside, however, unfortunately, users cannot be trusted to behave themselves in front of other users. I'd avoid words that may be construed as lewd.
:(

Your mute has expired.
