### ISSUE TITLE
Banned on mine together for calling a cat a pussy.

### ISSUE THREAD

**Issue by Skrrtle** [CreeperHost/CreeperHostGui#122]
We were talking about owning cats user4414 said their cat is afraid of the outside. so i said "haha i guess you could say theyre a pussy" dunno if thats banable but i dont feel like it really was and i feel unjustly banned as ive said absolutely nothing else thats even on the verge of being banned and have avoided conflict with breaking the rules very well. A mod was there but i assume it was just word detection.

banid= mtg-ban=5da11b6ad46c34-42226969.

![image](https://user-images.githubusercontent.com/49124855/66691683-f9fb8680-ec8f-11e9-87ee-3633d54075c9.png)

**Comment by Draylynn** [comment]
Due to the context of the chat, this ban was reversed almost immediately.
NOTE: Certain words will trigger an auto-ban because 99% of the time, they are used as lewd or derogatory terms: this appears to be the first time it has not.

**Comment by Skrrtle** [comment]
sweet, thanks. I assume i just need to relog.
