### ISSUE TITLE
..Multiple clients attempting to join Minetogether'' wont go away, even after reinstalling

### ISSUE THREAD

**Issue by Lelaxlp** [CreeperHost/CreeperHostGui#126]
Hi, I was wondering if there was an solution for this problem.
I have tried pretty much everything, including waiting more than 24 hours before opening the chat.
Help, pls  :)

My unique code: wnqq-dJec
Link to screenshot:
[DropBox](http://www.dropbox.com/s/okht6r188cr6cvj/2019-10-29_16.49.11.png?dl=0.com)

**Comment by Draylynn** [comment]
Is this still occuring? There have been a number of changes to MineTogether's backend over the last few weeks.

**Comment by Lelaxlp** [comment]
Clientsided? Like an update

**Comment by Draylynn** [comment]
I believe the bot is server-sided, however, MT is on RC6, if you're using an earlier version it's always good to upgrade: https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files

**Comment by Lelaxlp** [comment]
Where did the buttons go? I actually am VERY cunfused.
[Dropbox](https://www.dropbox.com/s/7vre2sm3pe2qe12/2019-11-18_15.17.25.png?dl=0)

**Comment by Draylynn** [comment]
Which mod pack + Minecraft version + build are you playing?

**Comment by TheRealMakhulu** [comment]
I too am having this problem. I'm using FTB Ultimate Reloaded on 1.12.2 version 1.9.0 of FTB Ultimate Reloaded

**Comment by Lelaxlp** [comment]
Latest version of Academy (In Twitch)

**Comment by Draylynn** [comment]
We'll look into it more closely, hopefully we can get a fix on the next update.

**Comment by DoceenT** [comment]
Same problem also with FTB Academy (through FTB launcher)

**Comment by Draylynn** [comment]
> Same problem also with FTB Academy (through FTB launcher)

Can just "thumb" the original post to alert dev's to the 'kill count' of this issue. Also, note label: Fixed in dev. We're just waiting for dev's to release the new build.

**Comment by DoceenT** [comment]
> > Same problem also with FTB Academy (through FTB launcher)
> 
> Can just "thumb" the original post to alert dev's to the 'kill count' of this issue. Also, note label: Fixed in dev. We're just waiting for dev's to release the new build.

Okay did it. So now I'm just waiting for a new version.

**Comment by gigabit101** [comment]
It should be out soon, Fixing up a few other things at the same time :)

**Comment by Lelaxlp** [comment]
Ok, should I close this or wait till the update?

**Comment by gigabit101** [comment]
I will close this once the update is released

**Comment by chucky5150** [comment]
Same issue. 

Any ETA on a release?

**Comment by gigabit101** [comment]
Soon

**Comment by gigabit101** [comment]
Fixed in version 2.2.1
