### ISSUE TITLE
Banned 11/3/2018

### ISSUE THREAD

**Issue by Maybevin** [CreeperHost/CreeperHostGui#127]
Username: Maybevin
After getting softlocked in a modpack, I said, "I'm making my own modpack with blackjack and hookers."  As far as I know, "hookers" isn't profanity.  I would understand if I was talking about "banging hookers" as that's 16+.  However, I was loosely quoting Futurama, which is not rated 16+.  I'm not trying to make an excuse, merely trying to explain my own confusion.

I wasn't given a warning, and have a clean record as far as I know.  Is there any chance I could be unbanned just this once?

**Comment by Draylynn** [comment]
MineTogether is a public chat room, for all ages. Futurama might be rated 16+, but that's not a good example, nor is it all-age rated. Quite clearly "hookers" is a explicit term that is not appropriate in a kids-game chatroom (unless you're talking about fish hooks).
We'll see... You _may_ be shown mercy.

**Comment by Maybevin** [comment]
Doesn't look like it.  It's been a week and no replies.
