### ISSUE TITLE
Banned 11/6/19

### ISSUE THREAD

**Issue by FrozenToothpaste** [CreeperHost/CreeperHostGui#128]
Username: Cursed_Username
Hello,

I got banned from MineTogether. I do believe I committed an offense but very UNINTENTIONAL. Here's how it happened:

I load up my modpack (FTB Revelation), and click multiplayer out of curiosity. After that, my curiosity was sated after I found out about the existence of public servers. I proceed to go back to main menu and create a singleplayer world

My laptop is not a juggernaut. It would take about 30 minutes to load a very large modpack. So while the world is loading, **I decided to test how laggy it is by typing in the chat. I said the N-word (as a test) and after a very short time, my chat was flooded with what appears to be system messages**

I assure you that it was a SINGLEPLAYER world and I will never ever say the N-word at someone else. Singleplayer is supposed to be alone. I did not expect the something like MineTogether to be there in the first place. I also have a WPM of 80+ so I typed too fast and I clicked enter while the world was lagging. It was laggy that the words werent written or shown but pressing enter still sent it anyway

This is a habit that I do in most games to check the intensity of lag. I liked it as a form of testing because it was kind of effective; if messages show up, that means the lag has lessened or gone

This was an accident. If I knew about the existence of MineTogether and the fact that it also works on singleplayer, then I would've never typed anything in the first place. In fact, while the world was loading, there was nothing at all in chat 

 I would love to be unbanned because MineTogether is a nice feature, especially as someone who is new to the world of modded and its also nice as it provides that feeling of "you're not alone"

Thanks

**Comment by Lelaxlp** [comment]
Well, I am not an admin here or anything, but that sounds like a bunch of bs. First, you have to switch to the Minetogether-chat in order to write something in there, second, you have to accept the rules before you can even write something.

**Comment by Draylynn** [comment]
You can't say the N-word in the chat tab clearly marked 'global' (old versions) or 'server' (newer versions). It's an ugly word that should be buried by its own history, it has no practical use in modern life, not even as a 'test', it's derogatory/offensive and breaches basic netiquette.
The system auto-bans for this word, the chat mods will ban you if you're seen to be using ASCII or any other workarounds to avoid the filters, these bans are permanent.

Mistake or not, when connecting to chat the first time, you're warned of the GDPR with MineTogether and that to connect to this chat you must accept the GDPR - From this moment on: You are aware of a mod that is providing online chat functionality: Whether or not you paid attention to this, well, that's your mistake.

If _somehow_ you find yourself able to connect again: Learn from it.

~Signed: Draylynn_T
_The harsh chat moderator, who won't go playing 'guess which one of the possibly hundreds of MineTogether UUID's who said the N-word recently is yours, just to unban it' game._
