### ISSUE TITLE
Unexpected auto-mutes

### ISSUE THREAD

**Issue by Cheeseducksg** [CreeperHost/CreeperHostGui#129]
Auto-mutes occur when any user says "opened", "opener", "happened", "sharpened", and several other common innocuous words. This behavior causes extra work for the moderation team. 

Mods have responded with essentially "don't test the censor", however there is an innate curiosity when a mute happens for seemingly no reason, and testing often results in several additional auto-mutes before the offending word is isolated. I don't feel that "don't test the censor" is a fair response to such situations, because without testing we have no idea what words not to say.

I also want to say that I understand the need for an auto-moderator, and have noticed an appreciable lack of profanity since it was installed. Finally, thank you for all the hard work all of you put into this fantastic mod.

**Comment by Draylynn** [comment]
Any mutes wrongly issued were reversed.
I have let the dev's know that the filter is malfunctioning and they are looking into it.

**Comment by DizzyDJW** [comment]
Dralynn I was literally auto muted what must have been over an hour ago. Can you unmute me?

**Comment by Draylynn** [comment]
I'm not seeing any mutes in the last 3~4 hours, there are bans for inappropriate language.

**Comment by gigabit101** [comment]
This issue seems to have been resolved.
