### ISSUE TITLE
Is there documentation for the mod?

### ISSUE THREAD

**Issue by russfort** [CreeperHost/CreeperHostGui#13]
My server is not hosted by Creeper, but they have enabled the discoverability setting in the Server.Properties file, and the server is displayed on the Public List, but with the server name of "Fill this in if you have set the server to public!".

We haven't found that text in either the Server.Properties file or the minetogeather.cfg file.

Thanks,
Russ

**Comment by CH-Paul-T** [comment]
Hey Russ,
```
display-name=
```
 in server.properties from memory.

I thought we had this in the curseforge project page write-up, sorry if we forgot.

Paul.

**Comment by russfort** [comment]
Thanks Paul, 

I was looking at the code, do I need the hyphen?

Code snip ... 

MineTogetherPropertyManager manager = new MineTogetherPropertyManager(outProperties);
displayNameTemp = manager.getStringProperty("**displayname**", "Fill this in if you have set the server to public!");
discoverModeString = manager.getStringProperty("discoverability", "unlisted");

**Comment by CH-Paul-T** [comment]
Probably not then :) Was doing it from memory, should leave this here so Aaron is reminded to update the project page to show how to set the name :)

**Comment by Cloudhunter** [comment]
Already done - it's slightly outdated as it doesn't show there is a friends list feature, but the documentation on how to use the server feature is here:

https://minecraft.curseforge.com/projects/creeperhost-minetogether
