### ISSUE TITLE
Banned 11/11/19

### ISSUE THREAD

**Issue by TheRealMakhulu** [CreeperHost/CreeperHostGui#130]
Hello, I was banned today for, honestly, a really stupid reason. I want to be as mature about this situation which may sound hard to believe when I state why I was banned.

Someone in chat said pee, and then poo. SO as a meme, I typed "why everytime I poopoo I peepee but not everytime I peepee I poopoo"

Sounds stupid. I know, but like... I was automatically perma banned. Like. Whoa. It was just a meme and if I knew I would get banned for it, why would I say that?

**Comment by Draylynn** [comment]
Why is everyone validating bad behaviour with "it's a meme". We don't care if it was issued by the Queen of England, it's inappropriate chatroom conduct for a public age-all channel.
[Thwacks with a rolled up newspaper]

**Comment by TheRealMakhulu** [comment]
I understand where you’re coming from but honestly I had no idea it was gonna get me banned. I enjoy MineTogether and I want to continue using it, I haven’t had a bad past prior. It was in no way my attention to offend you guys or come off as angry, I was worked up over the situation and I understand if you keep the perma ban but I just thought I’d try to get it reversed since it was just an honest mistake, I thought it’d be funny but unfortunately it was the opposite and ended up biting me

**Comment by Draylynn** [comment]
The context of the chat at the time was inappropriate, from several users. You were also adding fuel to the fire. Don't let it happen again?

**Comment by TheRealMakhulu** [comment]
It won’t happen again, I forgot to mention my username in the original post, my username in MC and on MT is Makhulu , like I said previously, if there isn’t an unban I understand. You guys are just trying to keep things clean and I respect that

**Comment by Draylynn** [comment]
Your UserName is useless, we don't see that information. MineTogether uses your MC acc to generate your MineTogether UUID, this process is extremely quick, after which, MineTogether forgets who you are and uses your UUID.
However, I am able to identify you by your sentence quote.
When you get banned in future, a ban ID is displayed, this can also be used to identify you.

**Comment by TheRealMakhulu** [comment]
I got you, if you need to discuss things with other mods or such, I understand. But if you guys do decide that I am allowed to be unbanned please let me know, I'd love to come back since I actually met some nice guys that I hadn't yet gotten their Discords from

**Comment by Draylynn** [comment]
"Don't let it happen again?" you were unbanned.
