### ISSUE TITLE
Item sharing concept

### ISSUE THREAD

**Issue by FTC55** [CreeperHost/CreeperHostGui#132]
A nice little enhancement that could be made to the mod in order to add to the interaction between users would be item sharing. How I pictured it, it would work more or less like this:

- A player selects an item they want to share via the GUI (or does so through a craftable item/block in the game)
- The player is prompted to choose between players eligible for the sharing/exchange (say the ones that have the same modpack, which is already detectable)
- The item(s) are deleted from the sender's world and appear in the reciever's (either in some sort of "mailbox" block or item or right in their inventories)

**Comment by ThePaul-T** [comment]
We've decided against this, but we may be having something of a similar nature.

It'd be almost impossible to handle anti-cheat on this and we can't find a reasonable way to at least provide "reasonable" levels (Not even very high certainty) of security.
