### ISSUE TITLE
Compatibility with Wynntils ?

### ISSUE THREAD

**Issue by sossololpipi** [CreeperHost/CreeperHostGui#133]
Using Minetogether with Wynntils prevents you from talking in chat with Minetogether at all, could there be a fix for this?

**Comment by gigabit101** [comment]
Hmm, It looks like both mods override/replace chat, https://github.com/Wynntils/Wynntils

**Comment by gigabit101** [comment]
You will need to disable one of the chats, I have added a small check that should fix the crash but it will also force our chat over theirs, You can disable our chat via the minetogether.json config file.
