### ISSUE TITLE
Optional Merge Chat Window

### ISSUE THREAD

**Issue by Kittypire** [CreeperHost/CreeperHostGui#134]
Hello!

Typically when I play Minecraft, I play on servers or in a LAN with friends, etc. etc.

I have completely fallen in love with MineTogether, however the feature being split into different chat tabs entirely has added another layer of paying attention in either one chat or the other.

My request/suggestion would be to provide an optional merge chat window, which could essentially introduce a "Channel" system where the user's local chat and the MineTogether chat could be viewed from the same window and users could type something along the lines of /1 for local and /2 for MineTogether. 

This feature could also play in to the future development of multiple chats that I saw in a previous request.

The idea to leave it as an optional feature is for people who don't want to use it or just don't care.

In any case, thank you for an awesome service. Thank you!

**Comment by gigabit101** [comment]
We have considered this option the issue with it is finding a way to allow you to choose what channel you send your replies to, We already have had issues with the current system that has caused users to be banned due to them swearing in the public chat.
