### ISSUE TITLE
Your chat filter is unintentionally homophobic and it needs revising.

### ISSUE THREAD

**Issue by Egril** [CreeperHost/CreeperHostGui#135]
Recently I had an encounter in your chat where someone stated that they are homosexual. They were muted for 'inappropriate language', upon testing I observed that it was not a mutable offence to state that one is heterosexual.

Upon expressing my dismay that this double standard was present I used a scientific term which appears to be on your filter list and was subsequently excluded from taking part in community communication henceforth.

As someone who is involved very heavily in the LGBT+ social community who fights every single day for the rights of LGBT+ members and is a LGBT+ member myself I find it shocking that your service claims to be inclusive and protective of marginalized groups and yet it falls into the trap of being the very thing it seeks to prevent.

How on earth can it be considered unacceptable to state that you are homosexual and yet it is acceptable to state you are heterosexual. What kind of message does that send to children who may be present. Is it wrong for a boy to say they have a crush on a girl? If not, is it wrong for a boy to say they have a crush on another boy? Of course, I am sure you would all agree that neither scenario is wrong and yet look who would be excluded by your service. Look who has been excluded.

Of course, this is your service and you can choose who ever you want to be on it. I don't contest that. However the fact remains your filter is problematic and sometimes things should not be black and white. Of course if someone is trying to use homophobic slurs then yes of course, they should be excluded but your system has worked poorly here.

**Comment by Draylynn** [comment]
Can you provide the line that got you muted, exactly as it appeared in chat?

**Comment by Egril** [comment]
They wrote "i am gay" exactly like that. 

Unfortunately I did not grab any screenshots of what I wrote, however I believe it was: "It is kid friendly to be attracted to your own sex or gender". I didn't feel it would be necessary as I had seen other people use every word we used and they only received temporary mutes.

Of course, I can understand why the filter removed us in both cases, you don't want people being unpleasant to others and you don't want people to be talking about acts of sex however, neither has occurred here.

**Comment by CH-Paul-T** [comment]
Hey Egril,

Sorry to be blunt here, but I dislike being accused of what has been implied here.

So - unless you're paying wages for moderators to sit here and review the context of every message sent, you're unfortunate collateral damage.

I apologise for any distress this has caused, and it is far from our intent. However, logistics and the average user of the chat dictates that we cannot change that policy.

Hopefully, sometime in the near future, we live in a world where the younger generation (and the older in complete honesty) stop thinking it is fine to use specific words as derogatory insults against each other.

Regards,
Paul
