### ISSUE TITLE
Banned 12/3/19

### ISSUE THREAD

**Issue by TheYeti** [CreeperHost/CreeperHostGui#136]
I was sitting in my base AFK and when I came back I was greeted with a message stating I was banned for "Inappropriate content" with no further information.  I hadn't said anything in an hour or two, and the last thing I had said was answering someones question about NuclearCraft radiation spread.   I could understand if I had been cursing up a storm or doing any of the other stupid crap kids tend to do in the chat, sure insta ban with no warning.  But to just ban me out of the blue with no mention of what I did that was actually inappropriate or a warning seems a bit heavy handed.

Ban ID: 5de6221bdab5f5-03643556
Unique Code: LXfa-kvcK

**Comment by Draylynn** [comment]
Hi,

Thank you for contacting MineTogether support.
Please see attached image for the reason for your ban in this age-all chatroom.

![InappropriateConduct](https://user-images.githubusercontent.com/45239550/70044092-8ef86d00-15b9-11ea-9998-7f701b9da0eb.png)

~Draylynn_T
