### ISSUE TITLE
When internet disconnects for a fraction of a second or you leave the Minecraft window, Minetogether stops working.

### ISSUE THREAD

**Issue by sossololpipi** [CreeperHost/CreeperHostGui#138]
![image](https://user-images.githubusercontent.com/43117641/70093778-25935100-15ef-11ea-865d-1e3f49a6f018.png)

Picture of it happening; happened while I left the Minecraft window. This same exact thing also happens when my internet decides to stop working for a fraction of a second.

**Comment by sossololpipi** [comment]
UPDATE : people seem to be talking fine, but the spammed error messages keep on happening and I am unable to chat.

**Comment by gigabit101** [comment]
What version of the mod are you currently running?

**Comment by sossololpipi** [comment]
> What version of the mod are you currently running?

The latest available version.

**Comment by gigabit101** [comment]
Fixed in version 2.2.1
