### ISSUE TITLE
[Request] Remove friend toastie

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#139]
Can users get the option to disable friend notification toasties?

When people add a lot of people (because it's easier to track chat better), the notification system can become a bombardment of distracting flicker in the upper right every time someone logs in or out.

**Comment by gigabit101** [comment]
Added config to disable toasts when friends come online

**Comment by Draylynn** [comment]
> Added config to disable toasts when friends come online
And offline? [Trollface]

**Comment by gigabit101** [comment]
Fixed in version 2.2.1
