### ISSUE TITLE
Unexpected pregen behaviour

### ISSUE THREAD

**Issue by thisischrys** [CreeperHost/CreeperHostGui#14]
I've tried pregenning with and without setting the optional coordinates (used 0 0) as well, but I end up getting something like this:
https://i.imgur.com/k0ijwfU.png
where the area that was pregenned is far away from spawn.

Documentation is a bit sparse, I assume the numbers it takes are chunks, not blocks?

**Comment by Cloudhunter** [comment]
Hi,

Can you let me know what command exactly you ran - and what dimension you are pregenning too?

Did you do it from the server console or from in game?

Are you running anything like Sponge on your server?

Thanks :)

**Comment by thisischrys** [comment]
I ran /chpregen world 200 200 1 false at first, assuming it to start at spawn. (is that right?)
I was counting on dynmap 2.6 alpha for 1.12.2 to show me updated chunks after a fullrender, but it didn't so I ran
/chpregen world 200 200 0 0 1 false
to see if that would help, both from inside the server console

Dynmap not showing the chunks ended up being an issue with it, the latest 3.0 alpha solves it (and revealed the chunks near the bottom to me)

I DID have sponge on at some point when I first used it, but I've removed it since (the latest version crashes on startup)

I'm not sure if I've run it since removing sponge, I'll give that a try if you think it's useful.

**Comment by Cloudhunter** [comment]
Are you actually typing "/chpregen world" - or are you specifying a number?

Can you also let me know what version of the mod you're using?

**Comment by thisischrys** [comment]
you're right, it was chpregen 0
world is what I use for dynmap fullrender
I saw output from it running and from cascading worldgen

it's the latest version: 1.10.2-1.8.7

I'm running it again now to see if anything happens

**Comment by Cloudhunter** [comment]
Thanks - let me know how it goes. If it is still dodgy it's obviously something derpy in my code - got my suspicions (I could be using a block location as a chunk location, which obviously won't work right), but this will confirm!

**Comment by thisischrys** [comment]
Ran chpregen 0 200 200 0 0 again, it's generating chunks around the area it did before again as far as I can tell.
https://photos.app.goo.gl/wLOH3S7jIVBgZzCv2

**Comment by Cloudhunter** [comment]
Thanks! Can't look at fixing it right now but will soon - can you provide the seed for your world so I can try it out myself?

I also presume that you haven't changed the world spawn using commands or otherwise from the default?

**Comment by thisischrys** [comment]
I haven't changed the spawn at all no, but I do not use the default world generator, I use realistic from Quark if that matters. Seed 558680760.

I have quite an extensive modlist ( http://bonemarrowcold.com/minecraft/mcu/sas.xml )
I assume you don't see this behaviour without any mods? Haven't tried it.
I appreciate that it could be any combination of mods, I'd be willing to do a binary search to find the culprit time permitting.

**Comment by icha-senpai** [comment]
Hi, 
Not the OP but i was interested if this issue has been investigated further and what the result was, I wanted to pregen my server world but i'd like to wait to hear back if this issue is resolved.
Thanks and sorry for hijacking this thread!

**Comment by cha0s** [comment]
Ping? I will probably just go with something else that I know works, but I was going to give this a try. I'm not going to unless this is elaborated on, and I suspect doing so may convince people after me to use it if it's confirmed to now be working. 👍

**Comment by temotodochi** [comment]
Apparently not fixed. I did a pregen on 1.12.2 revelations for 500 chunks around the spawn, but chpregen decided to use 0, 4000 as zero point.

**Comment by gigabit101** [comment]
Looking at the code the Pregen will always start at world spawn.
/chpregen dimension, minX, maxX, minZ, maxZ,

As far as I can tell this is working as intended.
