### ISSUE TITLE
[Enhancement] CurseForge Information

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#141]
Would be handy to let users know which build the mod is compiled on for all versions of Minecraft that MineTogether is provided for, especially when not using the stable build of FML... Rather than leaving the Changelog (which is there for a reason) blank.

Additionally, if deviating from FML stable, can we not provide two builds/update, to accommodate the latest stable + the experimental update, to give users the option to create their mod packs on stable or experimental builds with MineTogether.

[Rolls up a newspaper] USE THE CHANGELOG [Thwacks].

**Comment by gigabit101** [comment]
The latest version on curse comes with a changelog and forge versions its compiled with.
