### ISSUE TITLE
[VR] Vivecraft Compatibility

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#142]
I don't expect this to get fixed (by all means, dev feel free to re-open this if you want to rise to the challenge), but this will alert other users to the cause and resolution, should they come wandering into MineTogether GitHub looking for a solution.

MineTogether is not compatible with Vivecraft **IF** using controllers (controller bindings conflict(?)), will work without crashes in 'seated' mode with 'keyboard'.

**Comment by gigabit101** [comment]
This might have been caused by the null key issue, This should be fixed in dev already
