### ISSUE TITLE
Banned for saying a G rated word?

### ISSUE THREAD

**Issue by chucky5150** [CreeperHost/CreeperHostGui#143]
Hello,

Seems like I was banned for saying something that was G rated. It is a word I  would say to a 7 year old. There is even a kids book with the word in the title. I gave it thought before hitting the enter key and didn't think it was breaking any rules, or even have reason for concern. The word I chose to use was one that came up in a chat topic last week or so while Draylynn was chatting about using other words. 

So, you can under stand why I am a little confused over this. Hopefully this is the right place for this. 

Thank you for your time,
Chucky5150

![2019-12-15_00 50 44](https://user-images.githubusercontent.com/25311417/70864807-7eca8100-1f1b-11ea-9743-8ad9adb52a55.png)

I don't know if the time would help y'all. 
Dec, 15 @ 12:40ish AM  Central time here in the states. Should be about 6:40ish AM GMT.

**Comment by Draylynn** [comment]
The word mentioned auto-banned you due to abuse of the word in previous weeks.
Your ban has been lifted.

**Comment by chucky5150** [comment]
Thank you for lifting it. I've checked a few times and the chat wasn't working. I've since moved on to restarting minecraft just to end up with the "we've detected multiple clients attempting to join MineTogether chat from the same account" message. 

I gave it some time and then rebooted my computer. 
Chat still isn't working. 

It is kind of hard to troubleshoot this on my end.

**Comment by Draylynn** [comment]
Check your Task Manager to make sure there aren't any duplicate instances of Java still running that may be eating the connection too.
Your ID is not on our ban list. 🌵

**Comment by chucky5150** [comment]
It's saying that y'all (MineTogether) have disabled my client from sending any messages.

Things I've tried. 
-Restarting Minecraft
-Rebooting my computer
-Checking task manager that only one instance of Java is running
-Disabled MineTogether via twitch for about an hour (see if it was timer related).

I can see chat now, so that is a 50% improvement.
