### ISSUE TITLE
[Question] Is this mod going to be in 1.7.10 and other old versions alike?

### ISSUE THREAD

**Issue by sossololpipi** [CreeperHost/CreeperHostGui#144]
Theres a plethora of modpacks in 1.7.10 and other versions, and it's a shame that we can't use Minetogether with them. Are there plans for making Minetogether available for 1.7.10?

**Comment by Draylynn** [comment]
There are no plans (that I've heard of) at this time to make MineTogether 1.7.10 compatible.

**Comment by gigabit101** [comment]
We have no plans in backporting the mod to such an old version of Minecraft, This would be a large amount of work for such a small amount of people that would use the mod.
This would also be a problem due to the ModPack creators not updating the packs anymore to include the mod.
