### ISSUE TITLE
MineTogether problem

### ISSUE THREAD

**Issue by Boogerman69** [CreeperHost/CreeperHostGui#145]
https://paste.dimdev.org/xebacevimu.mccrash

**Comment by gigabit101** [comment]
This was fixed a long time ago, please update to the latest version

**Comment by Boogerman69** [comment]
and how do i do that? :]

**Comment by gigabit101** [comment]
You download and install the latest version from the curse page https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether
