### ISSUE TITLE
Allow players to opt-out of hiding their usernames

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#146]
![image](https://user-images.githubusercontent.com/15698722/71314838-f285f580-2415-11ea-8284-ba90db225db9.png)
![image](https://user-images.githubusercontent.com/15698722/71314841-f87bd680-2415-11ea-8569-f9591eebe599.png)

Hiding usernames kind of stops global chat from developing a community. You have no idea if you've chatted with someone before. Adding someone as a friend isn't really a good solution either, because I don't have to be someone's friend to want to know who they are. I want people to know who I am, but I want my friends list to be my **actual friends**.

**Comment by CH-Paul-T** [comment]
Hey @aaronhowser1,

I'll make you a deal, get me something signed by the main names of the modding community saying they're happy to let us store usernames[needed to ensure nobody spoofs anyone else] (we'll likely let the user set the username theirselves as per the current friends system, but in reverse, so it doesn't always have to be their mc username if they don't want those linked) and we will do it.

The only reason we did not as there was a lot of concern as we're a company over people thinking we where just data-mining mc usernames or similar, so we've been very constrained by this fact.

Take this concern away and we'll make it so people can opt in to displaying a username instead.

Paul

**Comment by aaronhowser1** [comment]
Doesn't MT already ask for permission when you try to open the global chat for the first time?

Also, to prevent spoofing, you could create a server that you have to log in to, to prove that you are who you say you are. That's how LatvianModder does it for FTB Utilities' badges, IIRC.

**Comment by CH-Paul-T** [comment]
But then after that point we'd need to store data between to link between the two or they'd need to do it every single login.

The issue here isn't that of security, it's the backlash we got when we even created this mod, unless we have permission from the main names in the modding community, I'm not going near storing any more data than we absolutely need with a 10ft barge pole and you won't change my mind.

**Comment by CH-Paul-T** [comment]
Update on this...

I've come up with a solution I am happy with to make this happen.

We'll be working on it in January, it's a big project though so don't expect it til at least the second week.

It'll be really useful for a lot of other things too

**Comment by ThePaul-T** [comment]
An iteration of these suggestions now exists in the latest 1.12 build.
