### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by fatallica** [CreeperHost/CreeperHostGui#147]
So I'm on my private Minecraft server and was clicking on random things figuring out all the interfaces, didnt realize i activated minetogether. Didnt even know what it was and it said i was banned for inappropriate conduct? I cant even remember what i typed, i think i was trying to talk to my friend in my server not realizing i activated an online chat tab. Could someone unban me please? I will be more mindful next time now that im aware of a seperate chat. Sorry again.

**Comment by Draylynn** [comment]
We would need to know "exactly" what you said, or the ban-ID supplied when you was banned.
We do not see your UserNumber or Name, we have no way to identify you.
