### ISSUE TITLE
Banned for Profanity

### ISSUE THREAD

**Issue by redstery11** [CreeperHost/CreeperHostGui#149]
Hello,
So for a bit of context:
Someone asked what the slang word "lit" meant. I gave him a few definitions since it is a word that can mean many things. He then asked why does it mean so many things? So I gave him an example of what a placeholder word was, being "cyka blyat" for some stupid reason. I was then banned. I acted impulsively, which I do apologize for. Technically it is profanity, but I hope this can be looked at from another perspective and I can be unbanned.
Ban code:
mtg-ban=5e0b7d6fdd2e41-43857387

**Comment by redstery11** [comment]
Now I am banned again for ban evasion? I didn't do anything. When I logged in before making this post, I wasn't able to chat but then chat appeared with the rules (I assumed I was unbanned so I closed the issue). Then a mod just banned me for ban evasion.

**Comment by Draylynn** [comment]
I'm not sure how you got around the ban, you was on just now, was not the same as the ID you were banned with. However, I would have ignored it... Until you started boasting the ban was removed (it wasn't) and then dropped the "but context" bomb _[TRIGGERED]_.
There is no context in this situation, the **chat rules are clear: No swearing or profanity**, period.
As you clearly do not understand the rules of chat, your second ID has also been banned, apparently the first time wasn't clear enough for you to understand fully what you had done.

Whether that ban is removed in 24 hours or not, remains to be seen, however, during this time, I would advise looking up what is acceptable to an all-age audience and reflect on how to behave in a public gaming chatroom, especially one filled with kids as young as 5 (yes, we have had articulate 5 year olds in there) - Swearing in front of kids is not (in any language).

And for reference "lit" ("that party was lit", "my base is well lit" etc) is: to light something, to brightly shine, or in slang terms, something amazing.
I'm not sure how you even managed to link that to 18+ Russian vulgarity, I don't want to know how, but I will set the record straight for you.

**Comment by redstery11** [comment]
> I'm not sure how you got around the ban with the ID you was on just now, but that ID was not the same as the ID you were banned with. However, I would have ignored it... Until you started boasting the ban was removed (it wasn't) and then dropped the "but context" bomb _[TRIGGERED]_.
> There is no context in this situation, the **chat rules are clear: No swearing or profanity**, period.
> As you clearly do not understand the rules of chat, your second ID has also been banned, apparently the first time wasn't clear enough for you to understand fully what you had done.
> 
> Whether that ban is removed in 24 hours or not, remains to be seen, however, during this time, I would advise looking up what is acceptable to an all-age audience and reflect on how to behave in a public gaming chatroom, especially one filled with kids as young as 5 (yes, we have had articulate 5 year olds in there) - Swearing in front of kids is not (in any language).
> 
> And for reference "lit" ("that party was lit", "my base is well lit" etc) is: to light something, to brightly shine, or in slang terms, something amazing.
> I'm not sure how you even managed to link that to 18+ Russian vulgarity, I don't want to know how, but I will set the record straight for you.
