### ISSUE TITLE
An idea to help with the UserXXXX situation.

### ISSUE THREAD

**Issue by MyDepreshon** [CreeperHost/CreeperHostGui#151]
When you join the Global Chat for the first time. You get that warning that allows you to share your data. Upon agreeing to that warning, why don't you just choose your own username that you'd be identified with based on your account. That way you're avoiding the UUID scenario, saving money on that issue, and helping people with inappropriate usernames- like mine, to just play on the server without having to remove everyone's mask. 

This would be helpful because the sole reason people stay on servers and chats is because they have friends that keep them there. And with the right moderation, you can have people that emotionally or financially support the server. 

And this is the good part,
You could add a chat ranking system, and make people buy ranks to have specific perks in chat (Coloured chat, modified nicknames, a modified @'ing system, and other cosmetics). People enjoy helping servers they love. Making this chat a thing they love, could generate an eventually sustainable income.

**Comment by CH-Paul-T** [comment]
There is already an issue with a solution open.
