### ISSUE TITLE
Recently Banned For "Racial Slur"

### ISSUE THREAD

**Issue by Orrinw01** [CreeperHost/CreeperHostGui#152]
Username: Hadronikle
Ban ID: mtg-ban=5e11a543833d69-09879111

Reason:
I believe there was some misunderstanding, I was asking someone why i should download a mod and they said "why not" and I decided to reference a meme https://giphy.com/gifs/quentin-tarantino-pulp-fiction-samuel-l-jackson-3otPoJNzOTg207lvOw it is from pulp fiction but, I made it pg for the chat. I didn't realize this was an issue because the word negro is not a slur at all. thank you for your consideration.

**Comment by CH-Paul-T** [comment]
Given Barrack Obama outlawed the use of the word in US legislative works. I’ll go with using a 26(?) yr old film as a defence a poor choice. The word is used to denote a group of people, often in a negative light. Ban upheld.
