### ISSUE TITLE
Banned for cursing, wasn't aware it wasn't allowed

### ISSUE THREAD

**Issue by FireballHex** [CreeperHost/CreeperHostGui#153]
context, someone said to use bonsaid pots for every type of tree

this is for MineTogether
if wrong place to post, can someone direct me to the correct place?

I said "storage is a bitch"

was just wondering how long the suspension was/ban. can't tell if it was either. just wanted to say that I won't do that again, but wanted to know how to get unbanned/unsuspened

**Comment by CH-Paul-T** [comment]
Bans are permanent, the rules are displayed on entry.
