### ISSUE TITLE
Bans are permanent, the rules are displayed on entry.

### ISSUE THREAD

**Issue by FireballHex** [CreeperHost/CreeperHostGui#154]
Bans are permanent, the rules are displayed on entry.

_Originally posted by @CH-Paul-T in https://github.com/CreeperHost/CreeperHostGui/issues/153#issuecomment-573058098_

They never showed for me otherwise I defintely would have read them, I'm a huge stickler of rules. as well it said I was only kicked I can't rejoin. Would there be a way of getting an appeal done?

**Comment by Draylynn** [comment]
The GDPR is shown when first connecting, letting you know what you're connecting to.
The rules are shown on first connect... Now assuming, for some strange reason, you didn't get a flood of rules on connecting, you would have got the alternative message 'Type "Rules" to see the rules'.

Not paying even the slightest attention to the functionality of chat:
![bucket](https://user-images.githubusercontent.com/45239550/72203794-6c832a80-3468-11ea-8afd-f3fb7a934c9a.jpg)

Bans are usually permanent, you'll just have to keep trying everyday to see if the ban falls off (also, I was the one who banned you).
