### ISSUE TITLE
MineTogether caused IndexOutOfBoundsException when changing Friend list hotkey

### ISSUE THREAD

**Issue by jarquafelmu** [CreeperHost/CreeperHostGui#156]
## Description
Some how the open friends list option got bound to whenever I change my volume the friends list menu pops up.

In trying to fix this I went into my controls and saw that Friends List wasn't bound to anything. I tried binding it `LShift + +` but all that was recorded was `LShift` for the button before minecraft locked up and crashed with the `IndexOutOfBoundsException`. 

## Versions
**Minecraft** v1.12.2
**Forge** v14.23.5.2846
**MineTogether** v1.10.2-2.2.0
**FTB Revelations 2** v3.2.1

## Crashlog
https://gist.github.com/jarquafelmu/8bca5a26025aa64a1f80aa8087e01a25

**Comment by gigabit101** [comment]
This has been fixed in version 2.2.1, You will need to update the mod to the latest version

**Comment by jarquafelmu** [comment]
Thank you for the quick reply. I will get after the mod pack owner I am
using this in to get it updated.
