### ISSUE TITLE
Unable to connect to chat, apparently i'm spamming unknown connections?

### ISSUE THREAD

**Issue by technomancer21** [CreeperHost/CreeperHostGui#157]
![mt offline](https://user-images.githubusercontent.com/37243026/72785235-7c73e900-3c76-11ea-8fd9-a0c2b1b7d279.jpg)

Apparently theres too many unknown connections from my IP address. Does this mean something is wrong with my client?

**Comment by gigabit101** [comment]
This has been fixed in version 2.2.1, You will need to update the mod.
