### ISSUE TITLE
Can't connect to minetogether (Registration timeout)

### ISSUE THREAD

**Issue by BellKiller** [CreeperHost/CreeperHostGui#158]
![2020-01-22_14 24 40](https://user-images.githubusercontent.com/43792621/72912680-c0b8c500-3d1a-11ea-8aea-684e2bf2c512.png)

**Comment by Draylynn** [comment]
Which MineTogether build are you using?

**Comment by BellKiller** [comment]
2.2.0 RC6

**Comment by BellKiller** [comment]
> Which MineTogether build are you using?

2.2.0 RC6

**Comment by bobthecow111** [comment]
ive got the same problem

**Comment by gigabit101** [comment]
Update to 2.2.1 to fix the issue
