### ISSUE TITLE
Serious incompatibility with Lootbags and Enderpay (On server)

### ISSUE THREAD

**Issue by TheQKnight** [CreeperHost/CreeperHostGui#16]
I have both these mods on my modpack and server and I have been testing them for a while. I have no idea why this happens, but whenever you make a Filled banknote (From Enderpay mod) randomly spawn inside a lootbag (From lootbags mod), when you hover over it on a server, it just crashes the client. It works in singleplayer, but not multiplayer. To summarize, it happens with 3 mods installed: Enderpay, Minetogether, and Lootbags. I am using MC 1.12.2, forge version 2655, and the latest version of all the above mods.

**Comment by Cloudhunter** [comment]
Can you provide a log? There shouldn't be anything in this mod which would cause this.

**Comment by Cloudhunter** [comment]
If you could reproduce it that would be great :) Won't have time to test the modpack!

**Comment by TheQKnight** [comment]
[crash-2018-03-16_20.13.08-client.txt](https://github.com/CreeperHost/CreeperHostGui/files/2017758/crash-2018-03-16_20.13.08-client.txt)
Here, I think this was it.

**Comment by TheQKnight** [comment]
it only gave the error when i was playing on the server, and didn't happen with singleplayer

**Comment by Cloudhunter** [comment]
Definitely nothing to do with me - please report it to the EnderPay developers.
