### ISSUE TITLE
I updated Minetogether to 2.2.1 and cant connect due to username

### ISSUE THREAD

**Issue by bobthecow111** [CreeperHost/CreeperHostGui#160]
When ever i connect i get a similar response to 
"
Couldn't connect as your nick is in use. Waiting 5 minutes and trying again.

 Disconnected (Reason: : irc.minetogether.io 433 * mikethetrike :Nickname is already in use.). reconnecting
"
thats not the exact mesage just my best attempt to recreate it. Simply it didnt let me join before and i got told to simply update the mod and hence i did and now i cant join due to this. My username was and still is mikethetrike and also i got kicked earlier for use of profanity (which i wasn't using in the slightest). Im playing Minecraft 1.12 Ftb revelations if that helps. 

Thanks in advance.

**Comment by roxerkiller** [comment]
Hi ! Same for me, I tried to find any answer / answer . Nothing , is it a bug or something else?

**Comment by technomancer21** [comment]
Gonna put my name down on the list of affected people by this issue. Apparently someone ma aged to fix it by changing their username but I have no clue how. They were super vague on details when they posted here.

**Comment by BellKiller** [comment]
> Gonna put my name down on the list of affected people by this issue. Apparently someone ma aged to fix it by changing their username but I have no clue how. They were super vague on details when they posted here.

I meant changing my minecraft username on the mojang website

**Comment by technomancer21** [comment]
> > Gonna put my name down on the list of affected people by this issue. Apparently someone ma aged to fix it by changing their username but I have no clue how. They were super vague on details when they posted here.
> 
> I meant changing my minecraft username on the mojang website

Ahh, that would certainly do the trick but it's also something of an extreme solution to a problem that likely has an easy fix. But if it works out for people then I won't begrudge them a change of name. At least now there's a ticket open, the developers will see it and hopefully offer some solutions.

**Comment by gigabit101** [comment]
Changing your name should make no change to this as we are using UUID's and not your name.
Simply closing the game and waiting 5 minutes before starting it again should resolve the issue.

We are looking into what is causing this issue.

**Comment by technomancer21** [comment]
> Changing your name should make no change to this as we are using UUID's and not your name.
> Simply closing the game and waiting 5 minutes before starting it again should resolve the issue.
> 
> We are looking into what is causing this issue.

This has been happening for a week now, I have closed and relaunched several times with hours in between game sessions. Sorry mate but that fix might work for some but not for me at least.

**Comment by gigabit101** [comment]
I have added a small amount of logging to the mod and a possible fix, Can you try again with this version?
https://files.gigabit101.net/minetogether-1.10.2-2.2.1.debug.jar

If the issue continues can you provide us with your client logs so I can see what is going wrong?

**Comment by MaigonisRozenbergs** [comment]
So on the 1/28 went to sleep, everything worked great, did have spikes in CPU usage including freezes, could be smth else. Today, 1/29 went in to me s-player world and it crashed when loading the world, then removed the minetogether-1.10.2-2.2.0-RC6.jar (The FTB revelation) file from the mods folder, the reason for the crash was minetogether mod. Then installed minetogether-1.10.2-2.2.1.jar (from curseforge), it worked only on other worlds, but no the main s-play that made me crash. Then i tried to delete configs, but didn't work, still cries about reason 433(the same name).

**Comment by gigabit101** [comment]
Can I get the log files?

**Comment by technomancer21** [comment]
I'm not currently home, won't be for another two days. I'll post the log files when I get the opportunity.

**Comment by MaigonisRozenbergs** [comment]
> Can I get the log files?

https://pastebin.com/XFw5axT0
These should be the right ones, these are the last ones before reinstalling the modpack.

**Comment by TheMagicalHen** [comment]
[logs.txt](https://github.com/CreeperHost/CreeperHostGui/files/4142251/logs.txt)
This is my logs for the same problem. I also got banned then unbanned so that might be the reason.

**Comment by technomancer21** [comment]
> Can I get the log files?

Which log file are you after, does the debug jar you gave us write its own log file?

**Comment by gigabit101** [comment]
The issue was serverside and has been fixed, If anyone else is still having this issue please leave your IGN's on this issue and I will get them fixed

**Comment by technomancer21** [comment]
IGN is technomancer21
Glad to hear its been solved.

**Comment by rimoldi98** [comment]
I am still having this issue, my IGN is Rimoldi

**Comment by gigabit101** [comment]
> technomancer21

You have been ban for swearing in the chat, This will not be undone

**Comment by gigabit101** [comment]
> I am still having this issue, my IGN is Rimoldi

You have been ban by a moderator for spamming in chat, This will not be undone

**Comment by technomancer21** [comment]
My ban was lifted by draylynn the same day. A minor slip up that I apologised for and she let it slide.

**Comment by rimoldi98** [comment]
> > I am still having this issue, my IGN is Rimoldi
> 
> You have been ban by a moderator for spamming in chat, This will not be undone

I don't remember being banned, and why would it say that my username is already taken instead of saying I've been ban? I think it's a misunderstanding

**Comment by gigabit101** [comment]
The ban message is not saved so once the client is restarted it has no idea, I am fixing this now.
I have taken a look at both of your bans and why you have been banned, Both of these bans have been justified and no further action will be taken.

**Comment by technomancer21** [comment]
I feel this is not fair to those who know for a fact they were unbanned. I would like to request more information on the specifics of my ban. I can quote the exact phrase draylynn spoke to me when I spoke to her about the ban. "a minor slip up. I'll let it slide this time. Unbanned." I formally request that she be involved in this case. Having assured me that the ban was removed, I would seek an appeal.

**Comment by gigabit101** [comment]
After talking to other members of staff we have decided to unban you, Please do not allow this to happen again as we will not overlook this again.

**Comment by technomancer21** [comment]
You have my thanks.
