### ISSUE TITLE
Fatality.

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#161]
Enhancement suggestion to add a noise event when someone is banned in MineTogether...
Something along the lines of "Fatality"... Multikills: "Double Kill", "Triple Kill" etc.

Obviously, Mortal Kombat is a copyrighted game, any sound bites would need revising within the confines of the law: Thus any sound bites must be re-done to the similar voicing style of Jason Steel (Filmcow), such as Lolz and Roffle, not Charlie himself. Complete with chirpy sparkly music in the background, to highlight it's intended parody nature.
![MakeItSo](https://user-images.githubusercontent.com/45239550/73443285-4f969480-434e-11ea-8eb1-10142da56ac0.png)

**Comment by technomancer21** [comment]
I can get behind this. :D

**Comment by Mephisto72** [comment]
Yes, this invention is great.
