### ISSUE TITLE
[FTB][Sky Odyssey] chat not working. 

### ISSUE THREAD

**Issue by koen1993** [CreeperHost/CreeperHostGui#162]
When i click on the MineTogether chat tab nothing happens, just an empty tab. When i type something into that chat tab it does just vanish.    

I also tried to replace the mod with the newest Iteration (minetoghether-1.10.2-2.2.1.jar) and checked FTBSkyOdyssey/minecraft/config/minetogether inorder to reset the config to default. But in that folder there is only gdpr.txt so not much to do.  
I also checked config/minetogether.cfg and replaced it with a copy from my stoneblocks 2 folder (different beeing stoneblocks 2 had a promocode and a curseProjectID).  (On my Stoneblocks game i don't have any problem using minetogether)

If it is needed here is a pastebin from the launcher console[debug][minecraft]: https://paste.feed-the-beast.com/view/8b1cb7e2  
It records everything from me starting the game to going into singleplayer and trying to write "hello" to the minetogether tab.  

edit:
I also tried to remove anything related to minetogether, put the .jar back in and loaded it again. This time the GDPR thing agreemnent popt up but that about it. I will now check how to secure my safefile, and than reinstall skyodyssey...
Update:
I used "force update", Curse Project ID, and Promotional Code seem to be set now. Its different Project ID than the one i imported from my Stoneblocks 2 folder.
Still chat not working.

**Comment by gigabit101** [comment]
I will need your ingame name to look into this

**Comment by koen1993** [comment]
@gigabit101 Just to make sure, you are talking about minecraft username?

**Comment by gigabit101** [comment]
Yes

**Comment by koen1993** [comment]
@gigabit101 Minecraft Username is: Sternomator

**Comment by gigabit101** [comment]
So the issue is that you have been banned by a moderator for swearing and this is why you can no longer connect to the chat

**Comment by koen1993** [comment]
@gigabit101 Ah i remember that i was banned for writen "FK" some weeks ago.
But that is strange, after i was banned and found out why(read the TOS), i managed to get back into the chat in Stoneblocks 2 and have been able to ever since(checked it right now).  
Maybe a message "you are banned", would be nice to clear up confusion?  
Anyway, thanks you for clearing up the confusion.

**Comment by gigabit101** [comment]
Yeah, I am making that change as we speak, As you have been polite about all of this I have gone ahead and unbanned you, please make sure it does not happen again

**Comment by koen1993** [comment]
I will, thank you.
