### ISSUE TITLE
1.14.4 3.0.0 RC3 Chat missing, bouncing

### ISSUE THREAD

**Issue by RViper80** [CreeperHost/CreeperHostGui#163]
Occasionally when bringing the chat up most of the older history will be missing, until the MineTogether chat tab is clicked.  Then it all shows up like it should.

Also while looking around, the chat shifts up and down a pixel on the screen.

I am running this on the Enigmatica 4 modpack at the moment.  I will try MineTogether alone by itself a bit later.

**Comment by gigabit101** [comment]
Is the history from Minecraft chat or Minetogether chat?

**Comment by RViper80** [comment]
MineTogether chat

**Comment by RViper80** [comment]
I see what's causing the 1 pixel bouncing in the text, that one is probably not a problem on MT's end.  It's happening whenever the One Probe popup is appearing.

**Comment by gigabit101** [comment]
OK, I see what is going on, Should be an easy fix.

**Comment by gigabit101** [comment]
I also think that the pixel issue you are having might be our side as well, I will take a look at that at the same time

**Comment by gigabit101** [comment]
Fixed in RC4 https://jenkins.gigabit101.net/job/MineTogether%201.14.4/lastSuccessfulBuild/artifact/build/libs/minetogether-1.14.4-3.0.0-RC4.jar

**Comment by RViper80** [comment]
Seems to still be happening in RC4.  Some things I notice triggering it - achievement popups, and sorting to nearby chests using the button in the inventory interface addeded by the [Quickstack](https://www.curseforge.com/minecraft/mc-mods/quickstack) mod.
