### ISSUE TITLE
Ban appeal "Racial slur"

### ISSUE THREAD

**Issue by qwibqwib69** [CreeperHost/CreeperHostGui#164]
Username: qwibqwib69
Ban ID: 5e3e3faa807251-83922255
Said nigling chiggers and got banned
Nigling means to criticize, especially constantly or repeatedly, in a peevish or petty way;
Chiggers is a type of parasite.

**Comment by CH-Paul-T** [comment]
While not actually a racial slur, the intent to be close to one is well known and acknowledged.

As such the ban is upheld permanently.

**Comment by qwibqwib69** [comment]
I didn't call anyone that, someone said nagging and for some reason someone called it a racial slur, so I said a line from "words that sound like slurs" "The snigger was triggered by nigling chiggers.
