### ISSUE TITLE
I got banned from the mintogether chat idk why

### ISSUE THREAD

**Issue by Austinyantha35** [CreeperHost/CreeperHostGui#168]
I didnt say anything bad and I'm playing on a paid for account??

**Comment by Austinyantha35** [comment]
Mtg-
ban=5e40650a670f64-141191394

**Comment by Austinyantha35** [comment]
In game name mc account is ScarylovesNavi

**Comment by Draylynn** [comment]
In-game account isn't too helpful here, we don't see it.
I think I accidently clicked the wrong ID when issuing a ban. You are unbanned.

**Comment by Austinyantha35** [comment]
I'm still not unbanned:(Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Draylynn <notifications@github.com> Date: 2020-02-09  3:39 p.m.  (GMT-05:00) To: CreeperHost/CreeperHostGui <CreeperHostGui@noreply.github.com> Cc: Austinyantha35 <Austinyantha45@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CreeperHost/CreeperHostGui] I got banned from the mintogether chat idk why (#168) In-game account isn't too helpful here, we don't see it.
I think I accidently clicked the wrong ID when issuing a ban. You are unbanned.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6IGISGQV37EAZPYXLRCBSYLA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXNFI#issuecomment-583890581",
"url": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6IGISGQV37EAZPYXLRCBSYLA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXNFI#issuecomment-583890581",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Austinyantha35** [comment]
Im still not unbanned sorry for whatever I did:(

**Comment by Austinyantha35** [comment]
It says Removed from chat (reason kicked-inappropriate conduct [ban ID: mtg-ban=5e40650a670f64-14191394]).Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Draylynn <notifications@github.com> Date: 2020-02-09  3:39 p.m.  (GMT-05:00) To: CreeperHost/CreeperHostGui <CreeperHostGui@noreply.github.com> Cc: Austinyantha35 <Austinyantha45@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CreeperHost/CreeperHostGui] I got banned from the mintogether chat idk why (#168) In-game account isn't too helpful here, we don't see it.
I think I accidently clicked the wrong ID when issuing a ban. You are unbanned.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6IGISGQV37EAZPYXLRCBSYLA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXNFI#issuecomment-583890581",
"url": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6IGISGQV37EAZPYXLRCBSYLA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXNFI#issuecomment-583890581",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Draylynn** [comment]
Please do not spam our GitHub, one formulated response should help.
Did you restart the client?

**Comment by Austinyantha35** [comment]
Yeah nothing has worked yet sorry for the spam btwSent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Draylynn <notifications@github.com> Date: 2020-02-09  3:49 p.m.  (GMT-05:00) To: CreeperHost/CreeperHostGui <CreeperHostGui@noreply.github.com> Cc: Austinyantha35 <Austinyantha45@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CreeperHost/CreeperHostGui] I got banned from the mintogether chat idk why (#168) Please do not spam our GitHub, one formulated response should help.
Did you restart the client?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6WGVOUFYHE6ZW62DLRCBT6NA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXVGI#issuecomment-583891609",
"url": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6WGVOUFYHE6ZW62DLRCBT6NA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXVGI#issuecomment-583891609",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Austinyantha35** [comment]
I'm trying restarting my pc now Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Draylynn <notifications@github.com> Date: 2020-02-09  3:49 p.m.  (GMT-05:00) To: CreeperHost/CreeperHostGui <CreeperHostGui@noreply.github.com> Cc: Austinyantha35 <Austinyantha45@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CreeperHost/CreeperHostGui] I got banned from the mintogether chat idk why (#168) Please do not spam our GitHub, one formulated response should help.
Did you restart the client?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6WGVOUFYHE6ZW62DLRCBT6NA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXVGI#issuecomment-583891609",
"url": "https://github.com/CreeperHost/CreeperHostGui/issues/168?email_source=notifications\u0026email_token=AOQJTD6WGVOUFYHE6ZW62DLRCBT6NA5CNFSM4KSEEN6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELGXVGI#issuecomment-583891609",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Draylynn** [comment]
I see you've entered MT again. I shall close this issue.
