### ISSUE TITLE
Got banned from MineTogether for unknown reason. Would like to request an appeal

### ISSUE THREAD

**Issue by TheD0ct0r101** [CreeperHost/CreeperHostGui#171]
![2020-02-09_16 23 55](https://user-images.githubusercontent.com/11579139/74113540-b7708a80-4b59-11ea-80d0-6ffd784bebec.png)

Apparently I was banned for "attempting to get other users banned"
but the message that got removed above it that triggered the ban was just me giving tips on how to increase the lava speed in crucibles. The moment I pressed enter to send the tip, the message was deleted and I was banned. I enjoy MineTogether way too much as it is extremely helpful for gathering ideas from the community, so I would like to request an appeal.

**Comment by Draylynn** [comment]
Certain words are blacklisted for a reason, reversing them and telling other users what to avoid, defeats the point of weeding out the toxic and inappropriate users.
The reason should have been "filter evasion" alongside it.
Don't let it happen again.

**Comment by osirisgothra** [comment]
you will be banned even if you repeat an item's name that is legitimately in the game, if it is blacklisted, for good. I got a permanent ban for speaking of an item name (named by the mod that created it, which was included in a pack that also had Minetogether in it, not made by me) that was one of those grey-area words that are not bad if used in proper context, and had no alternative word, but still they don't care about that. Why the mod doesn't just reject the messages with texts it deems inappropriate is beyond me. Furthermore, game item names shouldn't be part of it, unless the author is just oblivious to what item names there generally are in modded Minecraft. Be prepared to walk on eggshells and banana peels should use this mod.

**Comment by Draylynn** [comment]
Do not hijack other people's issues and necro; If you have feedback, bugs or a problem with the mod. Create your own issue or contact MineTogether staff on MineTogether's Discord
