### ISSUE TITLE
Banned for miscommunication. (MineTogether Chat)

### ISSUE THREAD

**Issue by Leaqy** [CreeperHost/CreeperHostGui#172]
My close friend added me on MineTogether chat with the name of "STUPID FA**OT.) I typed his name hoping it would draw his attention from the red chat thing. I knew before that if you type a friend's name it corrects it to "User____" for everyone else. I really didn't want to be mean or disrespectful in any way. Before I was banned I was very active and helping people constantly. Is there any way I could get an unban?

Thanks
-Leaqy

**Comment by gigabit101** [comment]
This is no excuse and the appeal has been denied

**Comment by Leaqy** [comment]
ur dumb af. i didnt do anything. learn how to read

**Comment by ThePaul-T** [comment]
Given that reply... Yes you did.
