### ISSUE TITLE
1.15.2 - Poor text visibility

### ISSUE THREAD

**Issue by RViper80** [CreeperHost/CreeperHostGui#173]
The CreeperHost icon in the background of the chat area is full-bright and makes it hard to see text that is over it.

![image](https://user-images.githubusercontent.com/5312414/74595667-0a3ebc00-500a-11ea-8eca-0a2ca1b86a91.png)

Running on the Forager modpack, MT 4.0.0-RC1, Forge 31.1.1

**Comment by gigabit101** [comment]
Fixed in RC2 https://cdn.discordapp.com/attachments/670996283820867604/679720706413428874/minetogether-1.15.2-4.0.0-RC2.jar
