### ISSUE TITLE
1.14.4 & 1.15.2 - Chat history vanishing

### ISSUE THREAD

**Issue by RViper80** [CreeperHost/CreeperHostGui#174]
Made an issue about this already (#163), and it was reported fixed in 1.14.4 3.0.0-RC4, however it is still occuring there, and in 1.15.2 4.0.0-RC1 as well.

Sometimes after hitting T, all chat is blank except for new lines that came in after everything was gone.  Clicking on the MineTogether tab at this point makes all the missing chat history reappear.

After spending more time watching it, it seems like it happens whenever something prints something to the main game chat window.  Advancements trigger it for sure, and using two different beds so the game prints 'respawn point set'.

**Comment by gigabit101** [comment]
I have not been able to get this to happen but I have made some changes in RC5 that might resolve the issue https://cdn.discordapp.com/attachments/670996283820867604/679741656471568400/minetogether-1.14.4-3.0.0-RC5.jar

**Comment by RViper80** [comment]
No idea... still happening in RC5 for me.

[Video](https://drive.google.com/open?id=1Wn8ksdjitAusJnyTcIcMaoCUq8k3XfPv)

**Comment by gigabit101** [comment]
I am still having no luck getting this to happen, Can I ask for a mod list?

**Comment by RViper80** [comment]
It happens with only MT loaded.  Need to trigger an advancement with only MineTogether loaded, the bed printing must be from some other mod, maybe Quark.

The fastest way to get an advancement is to collect a cobblestone on a new world.

[Video](https://drive.google.com/open?id=1zgP8JcAHqIdtTbdrpUDhY-r1OlYhym1R)

**Comment by gigabit101** [comment]
Can you try this one? https://cdn.discordapp.com/attachments/670996283820867604/682582354459623527/minetogether-1.15.2-4.0.0-RC4.jar

**Comment by RViper80** [comment]
That one seems to work :smile:

**Comment by gigabit101** [comment]
\o/ Wish it didn't take so long to track down but happy its fixed :)
