### ISSUE TITLE
1.15.2 - Name tab completion not working

### ISSUE THREAD

**Issue by RViper80** [CreeperHost/CreeperHostGui#175]
In the 1.12.2 version of MineTogether, to send a message to a friend, I type a few letters then hit tab to fill in the rest.  That seems to also be the way to direct a message to them so it translates into User#### for everyone who doesn't have friends.

This doesn't seem to be working in the 1.15.2 version (maybe also in 1.14.4, don't remember)  Sometimes when I hit tab it will bring up my username, like maybe it's trying to auto-complete commands in the main tab instead of intercepting it for the MT tab.

**Comment by gigabit101** [comment]
This has not been readded yet due to the large changes of how tab completion works in these versions.

**Comment by covers1624** [comment]
Should be implemented as of: https://github.com/CreeperHost/CreeperHostGui/commit/89f4c3a974fed8dd6caf1c54952eebb9a0d4e85b
