### ISSUE TITLE
Appeal for for the minetogether chat

### ISSUE THREAD

**Issue by gamingskullGamer** [CreeperHost/CreeperHostGui#176]
yea i literaly said 4 msgs and someone asked if anyone is playing minecraft illegal (like cracked probably) and i jokingly said that my pc is smokin weed so its illegal cuz you know my pc is weak so its burning and smoking. so is there any chance to get unbaned. sorry never used the chat so didnt know it was so harsh. Thanks

**Comment by Draylynn** [comment]
You're in a public gaming chat-room for all ages. Drug talk isn't allowed, not endorsed and certainly don't want to give kids the impression it's cool: This is why you was banned.
Chance to get unbanned? Guess you'll just have to wait and see.
