### ISSUE TITLE
1.15 server refresh button

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#177]
The server refresh button has a chat icon

![image](https://user-images.githubusercontent.com/18720460/74862793-07ff9900-534d-11ea-9d2b-66da639883f5.png)

**Comment by gigabit101** [comment]
Fixed in 1.14 just need to merge changes to 1.15, Will do tonight or tomorrow

**Comment by gigabit101** [comment]
Fixed in RC3 https://cdn.discordapp.com/attachments/670996283820867604/682241436804055089/minetogether-1.15.2-4.0.0-RC3.jar

**Comment by Sunekaer** [comment]
Still an issue in RC4

**Comment by gigabit101** [comment]
Fixed again, Not sure how I reverted that...
