### ISSUE TITLE
1.15 crash

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#178]
Crash
https://hastebin.com/asahigimug.rb
Clicked cancel on the pack selection page

**Comment by gigabit101** [comment]
Fixed in 1.14 just need to merge changes to 1.15, Will do tonight or tomorrow

**Comment by gigabit101** [comment]
Fixed in RC3 https://cdn.discordapp.com/attachments/670996283820867604/682241436804055089/minetogether-1.15.2-4.0.0-RC3.jar
