### ISSUE TITLE
Unhelpful error messages

### ISSUE THREAD

**Issue by Sir-Will** [CreeperHost/CreeperHostGui#18]
hey,

I keep getting "Unable to update server" errors but those messages could mean anything. It worked for a while but recently it keeps failing.

**Comment by Shybella** [comment]
Samething, my server isn't showing up on the list now and I'm getting those errors too.

**Comment by CH-Paul-T** [comment]
Unable to update server errors come with an error code which is useful to us.

Please provide the full error or we won't be able to resolve the issue.

**Comment by Sir-Will** [comment]
`Unable to update server. (#0)`

**Comment by Shybella** [comment]
![download](https://user-images.githubusercontent.com/4436776/44310154-15307600-a3ac-11e8-90f3-63e8183d8dd9.png)

**Comment by CH-Paul-T** [comment]
Is this still ongoing? We rolled out quite a few changes last night that solved some edge cases caused by our move to MySQL 8 on the server side (we had to scale up the database server into two servers a bit back due to load, 1.8bn requests/m is quite a bit :))

**Comment by Sir-Will** [comment]
Didn't see the error show up again so far.

**Comment by Shybella** [comment]
Same, not seeing it anymore. 

Thank you.

**Comment by Cloudhunter** [comment]
Closed as fixed and better error messages
