### ISSUE TITLE
Banned for making a bad taste joke

### ISSUE THREAD

**Issue by DinisFPaulino** [CreeperHost/CreeperHostGui#181]
I was on the chat talking about how to make a coke coal furnace and commented that saying I'm making a coke furnace makes me feel like Pablo Escobar, now I understand it's not appropriate and only noticed its forbidden when I re-read the rules and since it was my first time using this Mod I wasn't familiar  with the rules and regulations and admit I should payed more attention to the rules, this won't happen again please give me a second chance

My Minecraft username is DinisFPaulino

**Comment by CH-Paul-T** [comment]
Ignorance is not a defence.
