### ISSUE TITLE
Appealing a ban

### ISSUE THREAD

**Issue by planetera00** [CreeperHost/CreeperHostGui#182]
Hello, yesterday when I was talking to my friend on MineTogether Chat, I got banned.
It was my fault because I typed inappropriate thing in chat but it wasnt really that bad, but I accept my fault. Is there a way I can get unbanned? I won't type any inappropriate thing in chat again, thanks in advanced.

My Minecraft name is Planetera

**Comment by Draylynn** [comment]
Your name is irrelevant, we cannot find your ban with that.
A) What did you say?
B) What is your ban-ID (Shown when you got banned).

**Comment by planetera00** [comment]
I dont remember the BAN ID, But you are the mod that was in chat when I got
banned or possibly timed out??
But here is the issue, If I am not banned, I was timed out, but then again,
right now when I try to log in to MineTogether chat, there is a message,
saying that the nickname is already in chat, trying to reconnect in 5
minutes.
What I said was "cuckold"

So like i said, if i am not banned I was timed out, but I can not log in to
minetogether chat right now. My nick is in use somehow

**Comment by Draylynn** [comment]
No, you're certainly banned I was there, I issued the ban, I remember it clearly, as I do all my bans (and with 900+ bans, that's a lot of bans).
I'm sorry... You came into a public gaming chatroom (for all ages) and decided to drop the "any c******'s in here" line, no context, no respect for the other users and certainly against the rules.
It's basic fundamentals of public chat: You keep the X rated and offensive language to yourself.

No, not happening, learn from this, do better. This isn't COD or BO3 who don't care about their players behaviour.
The ban will cause your client to fail to connect to MineTogether's chat server, you will disconnect and timeout: Your connection is denied.

**Comment by planetera00** [comment]
Well, can you forgive me for this time? I will not say anything bad again.
I won’t use any bad words in the chat, I accept my fault and I promise you
to do better in the future.
Thanks in advance

**Comment by 40niner** [comment]
oh  ok so mods here are so much worst then discord mods, bruh, get a life you idiot. we say one word wrong by accident, and its like nope, good bye, your a lethal human to our perfect infrastructure
