### ISSUE TITLE
authentification account verification does not work

### ISSUE THREAD

**Issue by sossololpipi** [CreeperHost/CreeperHostGui#186]
the part where verification is sent to you email does not work. I've tried multiple times to resend the email and waited about 3 hours, still no response. anything i'm doing wrong here?

**Comment by gigabit101** [comment]
Are you still having this issue? We have not seen any other reports about this?

**Comment by sossololpipi** [comment]
unfortunately, yes. I've also verified that I used the right email, by trying to register a new account with the exact settings and seeing "email already in use!"

**Comment by gigabit101** [comment]
Check your spam folder as emails have been sent out and no one else has reported this issue

**Comment by sossololpipi** [comment]
not there. also contacted a moderator to help, and it still didn't send.

**Comment by gigabit101** [comment]
I assume you are connected to the discord server, Can you send me a DM with the email address you used so we can check the email was sent.

I use the same name on discord so should be easy to find

**Comment by ThePaul-T** [comment]
Closing due to lack of updates.
