### ISSUE TITLE
[question] where do i appeal?

### ISSUE THREAD

**Issue by sossololpipi** [CreeperHost/CreeperHostGui#187]
i feel like i've been wrongly banned and wish to appeal for said ban, but do not know where to appeal, and have no other way that i know of where i can ask this question. if it's here, then i'll reply with the ban appeal.

**Comment by gigabit101** [comment]
Yes ban appeals can be posted here

**Comment by sossololpipi** [comment]
okay, so here's the ban appeal :

about 3-4 days ago, I was banned by a moderator because of replying to a question asking of how to cut entire trees with one hit and saying "treecuntator" instead of tree truncator. apparently it'd have been because it looked like I purposefully tried to bypass the filter, but I've no way to prove that I actually believed it to be called like that. by the way, the tree truncator is an axe from Botania.

**Comment by gigabit101** [comment]
You have been unbanned, Do NOT let it happen again as next time the ban will be permanent

**Comment by gigabit101** [comment]
NOTE: You might need to restart the game for this to take effect

**Comment by sossololpipi** [comment]
thank you very much! i'll try my best not to let this happen again.
