### ISSUE TITLE
[1.15.2] Some buttons don't work

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#189]
This is using `minetogether-1.15.2-4.0.0-RC4`

![image](https://user-images.githubusercontent.com/15698722/76154079-cd5f6580-609b-11ea-8ee1-7befb88ab5da.png)
This just opens the regular "Order CreeperHost Server" menu

![image](https://user-images.githubusercontent.com/15698722/76154085-faac1380-609b-11ea-979a-ec282d8899d1.png)
The Cancel button makes a sound when clicked but does nothing else

**Comment by gigabit101** [comment]
Fixed in RC6
