### ISSUE TITLE
Find a better model than connecting to an IRC server to find your friends.

### ISSUE THREAD

**Issue by Zarthus** [CreeperHost/CreeperHostGui#19]
Most networks don't serve to be a collection of friends (in the way the code is using it, at least.), and the extra online connectivity is really rather pointless overhead. If you're going to do it, do it at least on a self-hosted ircd.

https://github.com/CreeperHost/CreeperHostGui/blob/cf4f88cc4f02f6ff46978d1b4cf5b785f4a5d0fd/src/main/java/net/creeperhost/minetogether/chat/ChatUtil.java#L56-L76

Please refer to most of the rules for [bridge bots in the EsperNet bot policy](https://esper.net/bots.php)

**Comment by CH-Paul-T** [comment]
Hey Jos,

We’re actually in the process of doing that now 😊 We’re just defaulting to that network until ours is tested.

If you don’t like the functionality it can be disabled in the configs.

Also, this is not a bridge bot as the client connects directly with their own client.

Paul

**Comment by Zarthus** [comment]
I've scoured the source code and I don't see any added functionality beyond the purpose of getting a "friends list" / sharing "friend codes", in the end it's rather similar to a 1:1 bridge bot connection, and thus we've removed their ability to connect to said network. The "clients" seemed disinterested in talking to me and I couldn't find such functionality in the code; therefore I concluded they were bots and removed them from the network.

If you'd like to discuss this on IRC feel free to hop by on the MOTD-forementioned channel.

**Comment by CH-Paul-T** [comment]
Hey Jos,

It’s fine, we’d have moved off this weekend anyway, we didn’t actually expect any use until it was bundled into a mudpack.

We where unsure if to contact and offer servers in exchange for our use or roll our own, we’ll roll our own now.

Thanks for your input.

Paul

**Comment by Zarthus** [comment]
Sounds good, have a nice weekend.
