### ISSUE TITLE
1.15.2 Crash

### ISSUE THREAD

**Issue by Naxanria** [CreeperHost/CreeperHostGui#190]
**version:** RC4
Index out of bounds exception, see crash log 
[crash-2020-03-08_15.39.47-client.txt](https://github.com/CreeperHost/CreeperHostGui/files/4303344/crash-2020-03-08_15.39.47-client.txt)

**Comment by CH-Paul-T** [comment]
This is happening inside the super call which is just vanilla code, we pass nothing to it and do no rendering at this code position.

So based off what we have here, this looks like a vanilla bug.
