### ISSUE TITLE
ban appeal 

### ISSUE THREAD

**Issue by glados1235** [CreeperHost/CreeperHostGui#191]
I was playing with a friend On LAN and somehow I accidentally switched to Global chat as I was unaware that I was in global chat and I didn't think to look at the messages I was just typing I said a bad and I immediately got banned I can promise you this was 100% unintentional I would not break the rules of the chat considering I enjoy using it 

thank you

**Comment by Draylynn** [comment]
Do you have the ID you were provided with when you got banned?
Or an 'exact' copy of what you said?
We can't find your ban without it (we don't see your number or name and cannot identify you).

**Comment by Draylynn** [comment]
If you decide to appeal, please provide the information requested.
