### ISSUE TITLE
1.15.2 Crash when pressing button when chat is unslected

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/CreeperHostGui#193]
Version : RC4 and  RC6

Open Chat - click off chat - press a key - crash
https://ss1.manmaed.net/1584051535.mp4
ClassCastException see log
https://pastebin.com/4GaruwrD

**Comment by gigabit101** [comment]
Fixed in RC7 https://cdn.discordapp.com/attachments/670996283820867604/688360109016875073/minetogether-1.15.2-4.0.0-RC7.jar
