### ISSUE TITLE
appeal: banned for inappropiate conduct.

### ISSUE THREAD

**Issue by GLSparrow** [CreeperHost/CreeperHostGui#194]
I was banned just minutes ago (2:00 P.M. March 13, 2020), for "inappropriate conduct".
![image](https://user-images.githubusercontent.com/25560194/76651862-6296aa00-6533-11ea-8e4c-2a4eca5c00c7.png)
  The present chat mod, Draylynn, had posted an image informing people about the @report function in-game. In response and in brief sarcastic humor, I stated "chat mod simps." I stated this to tease players who followed the rules and helped the moderators complete their job. But as it was in sarcastic humor I meant nothing by it. The @report function is actually very helpful to rid the chat of toxic players, and efficient for the mods. I do apologize for making a joke that was apparently harmful to others. 
Though despite this, the word I used was not in an inappropriate context (that being a 16+ topic). Here below are the definitions with both appropriate contexts. 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/25560194/76651905-78a46a80-6533-11ea-84bf-524f8ed825f4.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/25560194/76651920-7fcb7880-6533-11ea-8311-662e1365713c.png">

I do apologize my comment was genuinely offensive to the mods or the fellow chat users. MineTogether is a mod/chat I enjoy. I have made friends and great conversations whilst using it. I have times before reported toxic or offensive users to help keep the chat clean and friendly. I meant no ill intent, toxicity, offensiveness etc. by my actions. I wish to be unbanned so I can continue using the great mod whilst playing my game. I will do my best in the future to prevent any supposed toxic or inappropriate comments in chat.

**Comment by Draylynn** [comment]
SIMP also has several other meanings that are not as 'lightly worded' as the example you have provided... Which you should know given that you've also included 2 bullet points for the urban dictionary version and not the other points.

**Comment by GLSparrow** [comment]
Yes "simp" has more than those meanings I listed above and yes, I did purposely exclude the other following points on Urban Dictionary. The reason for this exclusion is to show the context in which I used the term and not to confuse with the more harmful contexts of such word. This also gives for my argument that my comment was not meant in a 16+ manner nor generally offensive as it was used for light fun. My apology if any harm was meant is listed in original post.

**Comment by Draylynn** [comment]
The great thing about appealing here, is having the time to research and formulate an appropriate response you think we'll agree with.
Whilst I agree with unbanning you based on your appeal, I do not agree with unbanning you based on your actions: _You had a chance to avoid the ban, the moment you said it, you was asked to elaborate and stayed completely silent._

As this term is often used in a very adult manner, you didn't defend yourself at the time, I simply don't believe you.

**Comment by GLSparrow** [comment]
I was banned before I even realized it. I didn't manipulate taking a ban in order to create a better defense in a longer period. I made a silly comment thinking of it as unharmful, looked away as I was crafting multiple items in-game then coming back to see that I was banned. I understand if you think what I just said was an excuse, because I would think so too, but I am saying all of this in pure honesty that though you gave me a chance I never saw it. You can tell me that it was my fault that I was playing the game or I should've been watching chat for a reply for my comment but there's nothing I can do about the past. I apologize for playing my game and poking light fun in an idiotic manner but if you're gonna use this to "teach me a lesson" because I didn't act is unfair. I'm sorry if you don't believe me, think this is an excuse, or I'm just trying prove you wrong because I don't blame you. But if you want to believe me that's the truth.

**Comment by sharkbait246** [comment]
Do you guys know how to unban yourself in sketchful.io?

**Comment by K-4U** [comment]
Wait.. what?

**Comment by Draylynn** [comment]
![image](https://user-images.githubusercontent.com/45239550/80840170-a41f0980-8bf4-11ea-9a48-6bd2ef3823bf.png)

**Comment by CH-Paul-T** [comment]
![why](https://user-images.githubusercontent.com/7502714/80840264-d7619880-8bf4-11ea-83cc-771abfe81ee9.gif)

**Comment by K-4U** [comment]
![](https://media.giphy.com/media/rI9O6UXkCjvTG/giphy.gif)
