### ISSUE TITLE
Hide until next update

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/CreeperHostGui#195]
RC: 7

The  Hide until next update X dosn't hide the message and instead brings up the Order CreeperHost Server GUI

**Comment by gigabit101** [comment]
Looks like the click x, y is slightly off, Easy fix

**Comment by gigabit101** [comment]
Fixed in RC8 https://cdn.discordapp.com/attachments/670996283820867604/689804992671907953/minetogether-1.15.2-4.0.0-RC8.jar
