### ISSUE TITLE
Removing the irc style disconnect messages

### ISSUE THREAD

**Issue by gigabit101** [CreeperHost/CreeperHostGui#197]
removing the irc style disconnect messages

**Comment by TemporaryForToday20200324-1** [comment]
I second this enhancement request.

I have been known to a) have an imperfect service provider and b) at times change my connection properties while in-game and while I happen to be connected to MineTogether. This does not make the connect and reconnect message gods happy. This feature would help for multiple reasons.

**Comment by gigabit101** [comment]
Fixed in beta4
