### ISSUE TITLE
Ban appeal?

### ISSUE THREAD

**Issue by HackMan37** [CreeperHost/CreeperHostGui#199]
I get banned i don't know why, i think that i didn't say any bad word or avoid ban.
![2020-03-23_11 40 44](https://user-images.githubusercontent.com/61872690/77334652-7bede200-6cfb-11ea-9c0c-24e8120fb301.png)
@Draylynn 
If i said something that it's on black list, i'm sorry about that.

**Comment by CH-Paul-T** [comment]
In what world do you think it's acceptable to make a reference to paedophilia in a chatroom with children?

No, just no.
