### ISSUE TITLE
FTB Beyond Client Crash

### ISSUE THREAD

**Issue by phit** [CreeperHost/CreeperHostGui#2]
Heyo, I just updated my Beyond server to 1.8.0 which includes your mod.
When connecting to my server this crash happens, removing your mod resolves the issue. Adding it back makes me crash again when joining. I have not modified the pack otherwise.

https://gist.github.com/phit/bc06c56371121898c802fe43db8fd0c0
Mod Version: creeperhost-1.10.2-1.2.3

**Comment by phit** [comment]
Updating your mod to 1.2.4 resolves this issue, would be great if you could poke your friends at FTB and tell them to push a hotfix for Beyond including the latest version.. not so great publicity when your advertising mod crashes clients.

**Comment by Slowpoke101** [comment]
Passsed this on to the modpack team. Thanks

**Comment by CH-Paul-T** [comment]
Just thought I'd throw an explanation in here of what happened.

If you have ServerInfoProvider on your server, the mod polls the server for the port ServerInfoProvider is on, if the query packet is too small, someone forgot to trim the null data from the receiving buffer.

This meant a lot of whitespaces, which then meant for some reason the int parsing failed, it's a fairly "edge" case, but was fixed.
