### ISSUE TITLE
Getting bunch of errors after client is loaded

### ISSUE THREAD

**Issue by chaos234** [CreeperHost/CreeperHostGui#20]
For more details, please take a look at my client log: https://paste.ee/p/kJXtf - there you can see a bunch of errors coming after mc is fully loaded.

**Comment by Cloudhunter** [comment]
It appears you have some kind of non standard setup and web calls are failing. It requires more investigation, but I'll make it less "noisy" when there are failures of this kind.

**Comment by Cloudhunter** [comment]
Fixed
