### ISSUE TITLE
Got banned for calling someone out as a pedophile.

### ISSUE THREAD

**Issue by GhostHax0r** [CreeperHost/CreeperHostGui#200]
Title says it all.
![Screenshot_22](https://user-images.githubusercontent.com/62583147/77385479-6d2c1d00-6d45-11ea-8d2c-2a1ba75cf408.png)
![Screenshot_24](https://user-images.githubusercontent.com/62583147/77385483-6dc4b380-6d45-11ea-921e-aac9763dc5fd.png)
![Screenshot_23](https://user-images.githubusercontent.com/62583147/77385484-6dc4b380-6d45-11ea-8789-7acbfb441433.png)

**Comment by CH-Paul-T** [comment]
Honestly, as long as the other person is banned too, I will uphold this ban, that was NOT the place for that conversation, that is what @ report is for.

I will go and review this now.

**Comment by CH-Paul-T** [comment]
I have now removed the offending user, we will review your ban in 48 hours and decide internally if the intent behind your message will allow us to make an exception.

However, you must understand, discussing the subject, even when calling someone out for it, is still against the rules.
