### ISSUE TITLE
[Issue] Spam From a Muted User

### ISSUE THREAD

**Issue by TemporaryForToday20200324-1** [CreeperHost/CreeperHostGui#201]
CreeperHost,

There is an issue with MineTogether somewhere within the user muting process. I have the ability to mute a user, which has the intended effect. Unfortunately, I have found that a user that I have previously muted and that's on my Muted Player's List is still able to send and/or even spam friend requests to me.

Not all conversations via MineTogether are perfect. Having a system to block is a highly desirable feature. When I brought this issue to light via MineTogether, the recommendation was to standby and see if the problem didn't just go away. The recommendation also included submitting a post to here, if it were necessary. It is.

I don't take screenshots every time I receive post-mute friend requests. Still, I am attaching two here that were post-mute to demonstrate that they are still occurring. It seems whenever this user is online when I am, friend requests come in. 

Sometimes, they are spammed in groups that fill up the MineTogether chat window.

![1](https://user-images.githubusercontent.com/62623390/77477232-44edfe00-6dd9-11ea-8bf2-0c00a312c64f.png)
![2](https://user-images.githubusercontent.com/62623390/77477244-47e8ee80-6dd9-11ea-8a09-3a2c3aab0f6e.png)

Below is my usually untouched block list. It's been this way for some time and was prior to the above crops and many friend requests ago.

![3](https://user-images.githubusercontent.com/62623390/77477638-e4ab8c00-6dd9-11ea-990a-ce8556f868d0.png)

Please address this issue. Even if I am gone, it should still be addressed for future users.

Thanks!

**Comment by gigabit101** [comment]
This is fixed in 1.15 already, I will get this ported over to 1.12.2 soon

**Comment by TemporaryForToday20200324-1** [comment]
@gigabit101 Thanks!

**Comment by TemporaryForToday20200324-1** [comment]
Well, this is new...

I can now see regular messages coming from that user while. They are still on my muted list. Should any of us be concerned about that or is it to be expected?

TIA
