### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Lolicon2110** [CreeperHost/CreeperHostGui#203]
I can send messages in chat but i can't see other people's messages  in game, i can still see them on discord (this happens randomly and fixes itself when i leave the game and join again)

**Comment by Lolicon2110** [comment]
Now even leaving and joining the game again doesn't fix it

**Comment by gigabit101** [comment]
What version of the Mod are you using?

**Comment by Lolicon2110** [comment]
the latest

**Comment by gigabit101** [comment]
This does not help as we have multiple versions out for multiple versions of Minecraft, I am going to need an exact version number

**Comment by Lolicon2110** [comment]
sorry, 2.2.1

**Comment by gigabit101** [comment]
Can you try and use version 2.2.2?

**Comment by Lolicon2110** [comment]
Well, it seems to have fixed the other problem i had of constant disconnects (i know disconnects are common, but i'm talking about disconnecting as soon as i connect and this happening every time), but it didn't fix the problem of me not seeing messages

**Comment by Lolicon2110** [comment]
Actually, it looks like it wasn't updating that fixed the disconnecting issue, from a test i just did now,

**Comment by Lolicon2110** [comment]
And now the disconnecting issue is back

**Comment by Lolicon2110** [comment]
So, yeah, this didn't fix any of the issues i had

**Comment by Lolicon2110** [comment]
So, i think the disconnection issue fixed itself, so it was probably on my end, but the issue i made this, well, issue about in the first place, not receiving the messages is still happening

**Comment by gigabit101** [comment]
Can I ask for your In-game name?

**Comment by Lolicon2110** [comment]
Lolicon21

**Comment by Lolicon2110** [comment]
Hmm, i seem to be receiving the messages now, but with a delay from when they appear in the discord, i will have to test this more

**Comment by Lolicon2110** [comment]
And now it stopped working again, it seems to be really random when it works and when it doesn't

**Comment by Lolicon2110** [comment]
Using a vpn seems to have fixed the disconnection issue for some weird reason (or maybe it's just a coincidence, i will keep you updated) and it seems to have fixed the not receiving the messages issue too, if i don't get this problem anymore for 3 days, i will close this issue
