### ISSUE TITLE
messages from banned users still display

### ISSUE THREAD

**Issue by sossololpipi** [CreeperHost/CreeperHostGui#205]
when a user gets banned, I can still see the message(s) that got them banned. this has happened to me every time a user got banned on the MC Eternal modpack for some reason.

**Comment by Draylynn** [comment]
Which MineTogether version + build are you using?

**Comment by sossololpipi** [comment]
6.2.2 I believe

**Comment by CH-Paul-T** [comment]
Considering the latest, which is for 1.15 is 2.2.0...

**Comment by sossololpipi** [comment]
My bad, it's 2.2.2
![image](https://user-images.githubusercontent.com/43117641/77784365-c8555c80-7030-11ea-87c6-7e6a4788cefc.png)

**Comment by CH-Paul-T** [comment]
I'll get the devs to check what version the deletion logic was added and make sure it hasn't been accidentally removed.

**Comment by sossololpipi** [comment]
The messages also seem to change into italics when the user is banned

**Comment by gigabit101** [comment]
Can you roll back to version 2.2.1 the version you are using is not a released version https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/2844742

**Comment by sossololpipi** [comment]
alright. all I have to do now is wait for someone to get banned.

**Comment by sossololpipi** [comment]
![image](https://user-images.githubusercontent.com/43117641/77795400-d9f42f80-7043-11ea-8370-c77369ba9eba.png)
unfortunately the bug still persists after having reverted to 2.2.1

**Comment by gigabit101** [comment]
fixed in 2.2.2
