### ISSUE TITLE
MineTogether Disconnect Lag

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#206]
MT: minetogether-1.10.2-2.2.0-RC6.jar
Pack: SB2
Log: [MineTogetherReconnectLagFreeze.log](https://github.com/CreeperHost/CreeperHostGui/files/4391115/MineTogetherReconnectLagFreeze.log)
Java: 1.8.0_231 (64Bit)

When internet is lost or the connection to MT, it's causing **_excessive_** lag and client freezes etc.
It claims it'll give up reconnecting in chat, then tries again, repeatedly, anyways.

Similar to(?): https://github.com/CreeperHost/CreeperHostGui/issues/7 (2017)

**Comment by CH-Paul-T** [comment]
Old version of the mod, issue was fixed in later versions.
