### ISSUE TITLE
Appeal: Banned for trying to get people to break the rules

### ISSUE THREAD

**Issue by tonicsense** [CreeperHost/CreeperHostGui#207]
Hey yall,

I'm unaware of the time i was banned but it was a few minutes ago but i was banned for trying to get people to break the rules. I admit I did it with malicous intend and would just like to say I'm sorry I had a very bad day and tried to harm others to make myself feel a little better. I'm aware this is no excuse for what I did but if you concider the possibility to unban me I'd be grateful since MineTogether can actually be a big help if you need help with things like information. Its also fun to talk to others and make great friends. 
If I am unbanned I promise that I will not let whatever happened that day make a difference in the chat and wont be toxic or rude to others. 

I hope you can forgive me for my really inappropriate behaviour.
-tonicsense

Thanks for reading

**Comment by tonicsense** [comment]
And I suppose if i hadnt been banned for trying to get people to break the rules it'd have been filter evasion so i outta say im sorry for that too.

**Comment by tonicsense** [comment]
Idk if im actually banned. i got kicked and wasnt able to reconnect since

**Comment by Draylynn** [comment]
You were also marked for saying "s***", swears are not allowed (not even censored in this fashion), or filter evasion.
Don't let it happen, again, ever.

Set a good example to other chatters, and do not encourage them to break the rules.
