### ISSUE TITLE
Text goes grey after typing "i miss ex" and I can't hit enter

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#208]
![image](https://user-images.githubusercontent.com/15698722/77840467-7c4c0a00-714d-11ea-8d67-234ee8582e5f.png)

**Comment by Draylynn** [comment]
![image](https://user-images.githubusercontent.com/45239550/77851879-6a14af00-71d3-11ea-97d5-93c786419ac8.png)
Will not be changed.

**Comment by aaronhowser1** [comment]
oh lmao that makes sense yeah
