### ISSUE TITLE
Client freezes while control and tab are held down at the same time

### ISSUE THREAD

**Issue by adventurerok** [CreeperHost/CreeperHostGui#21]
Whenever I hold down control and tab at the same time, my client will freeze until about 1-2 seconds after I release either key. I ran a sampler while holding down both control and tab, and got the following result indicating that this mod is responsible for this:

![minetogetherlag](https://user-images.githubusercontent.com/1076294/43020328-9041416a-8c57-11e8-98af-91cbc02ef8e2.png)

Other players on my server have said that they have the same issue.

**Comment by Cloudhunter** [comment]
Does it happen every time, or only the first time? It is checking for the presence of ServerInfoProvider, but on the first failure it shouldn't happen again.

That being said, I can move the check off thread easily enough to prevent this (I think).

**Comment by adventurerok** [comment]
It happens every time

**Comment by Cloudhunter** [comment]
Thanks for the report - I'll look into this.

**Comment by Cloudhunter** [comment]
Fixed in latest release
