### ISSUE TITLE
Ban in Global Chat

### ISSUE THREAD

**Issue by CaptainTrips182** [CreeperHost/CreeperHostGui#211]
Ban ID:  mtg-ban=5e82bc5cb8d955-72735771

Looking through these it appears not many bans are actually removed, so this will probably fall on deaf ears.  That being said, I would not have used foul language if I had read the rules or fully understood the "global" chat that appeared to have 3 or 4 people talking in it.  I do enjoy the idea of having a community within the modded minecraft world where people can share ideas and just chat.  For that reason, I am requesting a repeal on the account, with my deepest apologies for using the popular slang, "that sh** slaps"

**Comment by CH-Paul-T** [comment]
Ignorance is not an excuse.
