### ISSUE TITLE
Crash: KeyDown. FTB Academy 1.12.2

### ISSUE THREAD

**Issue by Scipio3** [CreeperHost/CreeperHostGui#214]
I started to play this modpack and when i turned in the MineTogether mod my game crashed.
Every time if i go into any map i have 3 seconds and i've got a crash report and it says it is because of MineTogether. I updated it but didn't work.
Here is my crash report: https://paste.dimdev.org/yosisusaci.mccrash

**Comment by gigabit101** [comment]
This was fixed in version 2.2.1+ You will need to update the mod to resolve this issue.
