### ISSUE TITLE
Crash when attempting to display rules

### ISSUE THREAD

**Issue by louisereay** [CreeperHost/CreeperHostGui#215]
I attempted to display the minetogether rules and Experienced a crash. The modpack was Omnia and I'm attaching a crash report

[crash-2020-04-03_16.00.22-client.txt](https://github.com/CreeperHost/CreeperHostGui/files/4428191/crash-2020-04-03_16.00.22-client.txt)

**Comment by gigabit101** [comment]
Fixed in beta4
