### ISSUE TITLE
Clicking hide until next update on multiplayer crashes the game

### ISSUE THREAD

**Issue by AKTheKnight** [CreeperHost/CreeperHostGui#221]
4.0.0 beta 4
https://pste.ch/mejozeseti.rb

**Comment by AKTheKnight** [comment]
Clicking on any part of the CH bit throws this: https://pste.ch/guyiputupe.rb

**Comment by gigabit101** [comment]
As a temp fix, I have spun up a server to stop the list from being null

**Comment by AKTheKnight** [comment]
Just FYI that seems to have an unintended side effect of the refresh button crashing the game now:
https://pste.ch/sopipupetu.rb

Sorry for all the issues :P

**Comment by CH-Paul-T** [comment]
Keep them coming, @gigabit101 will never live this down.

Maybe we'll have a stable release by 2027

**Comment by gigabit101** [comment]
The same issue Still fixed in Dev :P

**Comment by gigabit101** [comment]
Fixed in Beta5 https://cdn.discordapp.com/attachments/670996283820867604/700024549399461968/minetogether-1.15.2-4.0.0-Beta5.jar
