### ISSUE TITLE
Minetogether Ban 

### ISSUE THREAD

**Issue by FernandAuxton** [CreeperHost/CreeperHostGui#223]
Hi ! Sorry in advance because my english isn't perfect but I'll try to make it simple

During the last 2 days I wasn't able to reconnect to the minetogether chat system, I've thought that it was a problem with the mod version so I updated it but it seems like that if I wasn't allowed to reconnect, it was for a ban purpose : mtg-ban=5e8ed255505d90-91639191

I'm kind of oblivious to what I could have written 2 days ago that would have infringed the filter rule because I genuinely don't feel like someone who will purposely said something malicious nor harmful to someone.

If so I would like to know, if it's possible, which sentence I've written that was ban-worthy (the context may be important too) before asking for a ban appeal 

Again, english isn't my primary language so I've perhaps used a word incorrectly in a sentence without considering it provocative and again I'm sorry if that said sentence have infringed the Minetogether's rules and have hurts someone in the process.

Thank you for taking what I've written in consideration :)

**Comment by CH-Paul-T** [comment]
You were banned by a moderator for deliberately bypassing the filter by modifying a banned word.

**Comment by Draylynn** [comment]
For reference: "Ok zoomer (I'm wondering if this one is on the blacklist)"
Now you know.

**Comment by FernandAuxton** [comment]
Okay then, not gonna contest the ban there (even though I'm a zoomer myself)^^'

**Comment by Draylynn** [comment]
Doesn't matter what you are, the term is being used offensively, thus it is banned, much like the world "gay" is innocent when used in correct context, is often misused. The filter is there for a reason, evading it makes our job harder.

If you wanted to see if the world was on the ban list, it would have been smarter to just say something like "Has anyone seen that new robotic zoomer toy dog?".

Use your noodle in future, kay? Don't break the chat rules.

Your ban _may_ fall off within the next 48 hours.

**Comment by FernandAuxton** [comment]
I didn't know that manual filtering was time consuming.. sorry about that
I'm sort of dense but next time I'll use my noodle's of mine I promise 👍 (I didn't know that noodle refers to the head !)

**Comment by Draylynn** [comment]
It is, especially since it's mostly me that has to scroll back an inordinate number lines of text, when I wake up just to double check the previous mod and people haven't slipped through the cracks.
Super laggy to read through.
God forbid when we have 3000+ users on with at least 20% of them all typing and scrolling by so fast.
Have some consideration for everyone in chat, mods included. =p
