### ISSUE TITLE
Minetogether Ban Appeal

### ISSUE THREAD

**Issue by Talan122** [CreeperHost/CreeperHostGui#225]
I accidentally said something without thinking about it, won't happen again. My username is Cmyskill

(If you want details:
One of the mods was in chat and was called a hacker [jokingly, obviously]. So, I thought it would be funny to severely mess up the spelling of "hacker" and ended up typing something which was against the rules [which I obviously won't say here], and pressed Enter before I had time to think about it.)

**Comment by Draylynn** [comment]
How do you confuse the 'A' and 'C' key, with the 'O' key on a completely different typing hand on the other side of the keyboard!?
Also, me, it's me you called it... And I'm a "She".

For shame! Don't let it happen again.
https://www.learn2type.com/ 10 mins before bed, for a week.
