### ISSUE TITLE
minetogether ban appeal

### ISSUE THREAD

**Issue by mypsycho90** [CreeperHost/CreeperHostGui#226]
Ban ID: mtg-ban=5e92f65bc913f7-85249030

Well, I'm not sure why I got banned. Some guy called me a simp so i jest followed the joke and said something like "yeah, I'm a simp", and was joking about marying draylynn, because I thought jokes like "i wanna marry gamer girl" are pretty popular and harmless.

**Comment by CH-Paul-T** [comment]
And have no place on MineTogether chat.

**Comment by mypsycho90** [comment]
isn't there any way to get unbanned? I really love the community and didn't mean to offend anyone
