### ISSUE TITLE
Appeal for minetogether ban

### ISSUE THREAD

**Issue by asenseofcommunity** [CreeperHost/CreeperHostGui#227]
I was kicked on account of "inappropriate references" recently. I believe I was being too rash and defensive. I didn't realize it was something that would be against the rules. I can't see the messages I had sent (they all deleted) and I can't check back on the rules- so I wont know exactly which thing I said that was worth this infraction. I will continue speaking and acting with good intentions, however this time with more consideration.

mtg-ban=5e92f6717a7883-62715411

**Comment by CH-Paul-T** [comment]
Ignorance is not a defence.

**Comment by asenseofcommunity** [comment]
My apologies. I was being too conversational. I didn't intend to defend myself with my statement of not knowing what exactly broke the rules.

What I said could have been breaking a rule- with that said, it wasn't my intention to break any rules. Had I known it was against the rules to say what I said I simply wouldn't have said it. 

Regardless of what was said, and regardless of what rule it broke, I didn't mean to break a rule, and I don't mean to do it again. Should I be appealed, I would not act in the same way in the chat, knowing now that what I did was bannable.

I want to have access to minetogether chat. I apologize for breaking the rule(s), and I would like to be reasonably given a second chance here.
