### ISSUE TITLE
Nickname Already in use

### ISSUE THREAD

**Issue by Thepowerisreal** [CreeperHost/CreeperHostGui#228]
I cannot connect to Chat as my nickname is currently in use.
Version: 1.12
Mod version: minetogether-1.10.2-2.2.1
IGN: Thepowerisreal
thank you.

**Comment by Draylynn** [comment]
Does this occur on an updated version?
https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files (2.2.2)

**Comment by Thepowerisreal** [comment]
> Does this occur on an updated version?
> https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files (2.2.2)

Updated and tested it. I still get the same error of Nickname already in use.

**Comment by gigabit101** [comment]
What is your in-game name?

**Comment by Thepowerisreal** [comment]
> What is your in-game name?

Thepowerisreal

**Comment by gigabit101** [comment]
This is because you have been banned from chat for a racial comment made in chat on the 08/02/2020
