### ISSUE TITLE
Mine together Ban Appeal

### ISSUE THREAD

**Issue by youngposty** [CreeperHost/CreeperHostGui#229]
Hello, Draylynn I asked in the Minetogether chat why there was a coke furnace as it subjects drugs and was banned from the chat. I didn't know that this was a bannable offense and was wondering if I could catch a break because I enjoy using the chat to ask about certain ftb features. If there is a way for you to check the logs, I would  assure you that I have never said anything offensive or demeaning before. If you don't want to unban me, would there be anyway that I could know how long a ban lasts.

Kind Regards.

**Comment by youngposty** [comment]
Also, I now realize that this was inappropriate and will most definitely never say anything like this ever again. I truly enjoy your service as it really helps with gathering community ideas. Thank you for your hard work moderating the large servers

**Comment by youngposty** [comment]
Here is my ban code btw mtg-ban=5e934bd47a6200-95085267

**Comment by Draylynn** [comment]
I don't need your ban ID, I know who you are... Just waiting for an excuse as to why you didn't follow the chat rules and said such a thing in a public gaming chatroom.

I mean, unless stated otherwise, it's good netiquette especially in a gaming chatroom that is rated young, to expect there to be kids... And making light of such topics in front of them isn't exactly appropriate or a good example.

Make it a good one.
![popcorn](https://user-images.githubusercontent.com/45239550/79079354-7ab24280-7d06-11ea-82b5-a1d7b6d1cbe0.gif)

**Comment by youngposty** [comment]
ok, how long will the ban last

**Comment by youngposty** [comment]
also the mod literally includes coke how is that not appropriate.

**Comment by Draylynn** [comment]
> also the mod literally includes coke how is that not appropriate.

That is also entirely not related to what you said.

**Comment by youngposty** [comment]
Draylynn can you please tell me how long the ban will last im not trying to be mean sorry if you caught that vibe from me. Why do you have to be so passive aggressive.

**Comment by CH-Paul-T** [comment]
Forever

________________________________

**Comment by FourDolla** [comment]
Howdy Dray
I was just banned for spam even though all I did  was post a message regarding a school class after a group of other players also said something. I think this was an understandable mistake for spam as groups of people often do so. An appeal on this would be much appreciated, Thanks!

**Comment by pr0ff** [comment]
can you unban me pllllease i will follow the rules

**Comment by pr0ff** [comment]
5f54e7c04528a6-47838906 please unban me i like to use minetogether and i will look at the rules

**Comment by OllePlayz** [comment]
Can you please unban me i was joking around saying i was an AI, i know it was stupid but it seemed as if you were getting it as a joke but then i got banned (I think) so i was just wondering if you could unban me,

My gamertag is OllePlayzCool

**Comment by BullxMoose** [comment]
@Draylynn 

what did i do to get banned and how can i get unbanned? the name is NetherStarRabbit#5B3F4. and if i am unable to get unbanned how long is the ban?

Ban ID: mtg-ban=63dcd33fb8fe95.89061826

Moderator: draylynn

Reason: Banned

Message: p1675390384615459

Timestamp: 2023-02-03 09:26:23

**Comment by manpan9282** [comment]
I dont really know how i got banned i was just playing yesterday with friends on stoneblock and now i can play anymore

User name is The_Scotts_man

**Comment by Draylynn** [comment]
> I dont really know how i got banned i was just playing yesterday with friends on stoneblock and now i can play anymore
> 
> User name is The_Scotts_man

Do not hijack other people's issue reports. Ban appeals are made on MineTogether.io

**Comment by BullxMoose** [comment]
I didn't hijack anything
