### ISSUE TITLE
Banned for asking "Are there any gay mods on minecraft?"

### ISSUE THREAD

**Issue by xXBulletEyeXx** [CreeperHost/CreeperHostGui#231]
I've been gay for almost 1 year now, and I was wondering if there are any MODS for gay comunity. And I got "Muted 5 mins", it've been almost 30 mins and I'm still muted

**Comment by Draylynn** [comment]
'gay pride mods' would be the terminology, context matters.
It's a public gaming chatroom for all ages, 'gay' is muted as a precaution. 98% of occurrences of the word are used offensively, your mute was 5 mins.
