### ISSUE TITLE
Crash after clicking on MineTogether tab in chat

### ISSUE THREAD

**Issue by pinterp117** [CreeperHost/CreeperHostGui#232]
As in the title, after I rejoined, saw couple guys also saying that they crashed with the same issue.
Modpack: Stoneblock 2.
[Log](https://pastebin.com/w4YZ4MAX)

**Comment by eXtreme2810** [comment]
I have also experienced same issue doing nothing intensive in game but upon switching to MineTogether chat tab game instantly crashed.
Modpack: FTB Revelation
Crash log: [crash-2020-04-17_21.04.48-client.txt](https://github.com/CreeperHost/CreeperHostGui/files/4494941/crash-2020-04-17_21.04.48-client.txt)

**Comment by Icarius89** [comment]
also experienced https://paste.dimdev.org/egasohideb.mccrash

**Comment by wipie44** [comment]
Same here.
I was playing FTB Revelation and had the singleplayer chat open for some time. It crashed once I switched back into the MineTogether tab. Noteworthy is that it didn't crash straight away, but was loading for a good few seconds.
[crash-2020-04-18_19.49.34-client.txt](https://github.com/CreeperHost/CreeperHostGui/files/4497248/crash-2020-04-18_19.49.34-client.txt)

**Comment by Lolicon2110** [comment]
Yeah this has also been happening to me https://pastebin.com/vAuqVR7k

**Comment by gigabit101** [comment]
Fixed in 2.2.3
