### ISSUE TITLE
Chat colors wrongly displayed

### ISSUE THREAD

**Issue by eXtreme2810** [CreeperHost/CreeperHostGui#235]
**Modpack:** FTB Revelation
**MineTogether version:** 2.2.3

I have updated to newest version of MineTogether as I have heard that the crashing issue has been fixed. Now the new issue seems to be chat colors as everyone is shown playing same modpack as I am even if they are not (as shown in screenshot below). I have tried restarting client and even whole computer but without success. Mod was downloaded through CurseForge repository.

![BugScreenshot](https://user-images.githubusercontent.com/26391917/79913962-b941ae80-8424-11ea-8239-fbf3d1b03128.png)

**Comment by Lolicon2110** [comment]
yep, same for me, i'm on PO3

**Comment by gigabit101** [comment]
Fixed in 2.2.4, Should be live on curse soon
