### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Tyrius1** [CreeperHost/CreeperHostGui#237]
https://pastebin.com/sqMyFq1N

I hit / to open chat and it crashed

**Comment by Tyrius1** [comment]
another when double left clicking the server icon to join
https://pastebin.com/JhPdbfXp

**Comment by gigabit101** [comment]
Can I ask what launcher you are using?

**Comment by GabrielloEsk** [comment]
When i join i cannot chat cuz it says username already in use but and its reconecting

**Comment by Zalkortis** [comment]
I have the same issue with FTB Revelation in different versions of MineTogether, tried latest one and the one that was in the pack with 3.2.1.

In 2 out of 3 cases when I hit the MineTogether tab in chat window the game crashes with java.lang.ArrayIndexOutOfBoundsException: 1

Using MultiMC as launcher. Here is the whole crash log:
https://pastebin.com/LJ1R0jWP

I have removed the mod now as I'm struggling with it now the whole weekend. And everytime I need to reload the complete game. :(

**Comment by Tyrius1** [comment]
Twitch launcher

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue
