### ISSUE TITLE
Ban Appeal for MineTogether

### ISSUE THREAD

**Issue by TheJozebee** [CreeperHost/CreeperHostGui#238]
I don't have the screenshot, but people were having a conversation about "simps" and I piped in after not talking for a bit, and said that there is "nothing wrong with simping" and out of nowhere, I was banned. Nobody else got banned from my knowledge, and I didn't know that was against the rules? My IGN is TheJozebee

**Comment by Draylynn** [comment]
Please explain the contextual meaning of 'simping' in your comment.

**Comment by Draylynn** [comment]
As there has been no response on this ticket, I will close it.
