### ISSUE TITLE
unable to add my server to public list

### ISSUE THREAD

**Issue by Buzz1971** [CreeperHost/CreeperHostGui#24]
I woke up this morning to find this error messages in my console
"[minetogetherserver]: unable to do call to server list - will try again in 90 seconds. reason: Unable to verify server"
my server.properties for ip= line is blank am I supposed to place the IP address for my server in there?
reason for edit
I just added my ip to the server.proteries ip= line
Also here is my IP for you to look into this please and thank you in advance
158.69.116.80:40677
after I restart my server the server ip resets to blank
I am no longer getting this error message also

**Comment by Cloudhunter** [comment]
If you're no longer getting this message everything is fine :)

**Comment by Cloudhunter** [comment]
https://twitter.com/Cloudhunter/status/1031231152152035331
