### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by robsonld04** [CreeperHost/CreeperHostGui#241]
Ok so after a bit of research i learnt that Mine Together is a thing. Playing on FTB Omnia for fist time i had no idea this was a thing. No rules popped up or anything and i said something silly in passing and got banned from the chat. as a 30yr old i would like to be un-banned and be given a second chance.

Thanks

p.s i muted 2 people by accident and have no idea how to un-mute them

**Comment by Draylynn** [comment]
We would need to know your ban-ID or something you said in chat exactly as it was typed.
Note: Friends list has a mute list button.

**Comment by robsonld04** [comment]
it didnt give me a ban ID, tbh im only assuming i was banned as it just keeps saying my nikname in use. It was right after i said "no you add me B***h"

**Comment by Draylynn** [comment]
... And 30 years old too. Tut, tut, tut.

**Comment by robsonld04** [comment]
> ... And 30 years old too. Tut, tut, tut.

yes i know, mistakes were made.

case closed as in tough luck or case closed ban will be lifted?
