### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Tominjishi** [CreeperHost/CreeperHostGui#243]
I started playing a pack with minetogether just a while ago and I really like it, but I got banned like a couple of minutes ago. Someone misspelled a bad word (pedophile) and I, as the grammar police I am, corrected him without really thinking about it. Now I am perma banned. I know it was a stupid thing to do and I'll try to refrain from doings such things again.

**Comment by Draylynn** [comment]
What was the correct word you were trying to spell out for them?

**Comment by Tominjishi** [comment]
Yeah i know that it's very inappropriate. Someone spelt it wrong, and then somone corrected them, also spelling it wrong and I found that funny, and without really thinking too much about it and without realizing that it's a chat room for a 7+ game, I told him that he's also wrong and it's actually spelled like this.
