### ISSUE TITLE
Crash when tabbing to global chat

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#244]
Using `minetogether-1.10.2-2.2.4.jar`

FTBTeam/FTB-Academy/issues/296

https://pastebin.com/fBw1jMwC

**Comment by seco-plr** [comment]
It appears as if this is the same issue which has been reported already by several users. I'm playing FTB Revelation and have experienced crashes. Even though FTB Revelation is a 1.12.2 modpack it includes the 1.10.2 version of this mod. `minetogether-1.10.2-2.2.0-RC6.jar` to be specific.
I asked on their discord and was given the following version:
> https://cdn.discordapp.com/attachments/670996283820867604/703746087529218088/minetogether-1.10.2-2.2.5.jar

I don't think it's been released yet but it works flawlessly for me. Just drop it into your `mods` folder of your modpack and **do not forget to remove the old version**, `minetogether-1.10.2-2.2.4.jar` in this case.
**Backup your game and game data before doing so. I haven't had any problems but you never know what may happen. It's an unreleased version.**

**Comment by K4su** [comment]
It appears as if this is the same issue which has been reported already by several users. I'm playing FTB Revelation and have experienced crashes. Even though FTB Revelation is a 1.12.2 modpack it includes the 1.10.2 version of this mod. `minetogether-1.10.2-2.2.0-RC6.jar` to be specific.
I asked on their discord and was given the following version:

> https://cdn.discordapp.com/attachments/670996283820867604/703746087529218088/minetogether-1.10.2-2.2.5.jar

I don't think it's been released yet but it works flawlessly for me. Just drop it into your mods folder of your modpack and **do not forget to remove the old version**, `minetogether-1.10.2-2.2.4.jar` in this case.
**Backup your game and game data before doing so. I haven't had any problems but you never know what may happen. It's an unreleased version.**

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue
