### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by TheSuperUltimate** [CreeperHost/CreeperHostGui#245]
Hi, I was banned in the chat for using profanity.
It was never my intention to hurt anyone in anyway.
If given the chance I will be on my best behavior on all times from now on. 
I apologise for my mistakes and really miss the chat.
Thanks in advance.

Ban ID: mtg-ban=5ea5b79062cfe8-57752806

**Comment by Draylynn** [comment]
Don't let it happen again.
