### ISSUE TITLE
Improved bad word handling

### ISSUE THREAD

**Issue by K4su** [CreeperHost/CreeperHostGui#246]
If you're typing a message which contains a "bad word", the chat is greyed out and you can not send the message. I suppose special characters and spaces are ignored and the bad words are searched for in the string. Causing the following string to be rejected, even though perfectly valid (I will let you spot the bad word on your own):

`Spanish, Italian`

Of course removing the restriction allows people to type these bad words. Instead it might be a good idea to hide these text fragments until a moderator approves of them?
Here's an example of what it could look like:
![image](https://user-images.githubusercontent.com/64333895/80484005-4fab2e00-8957-11ea-80bc-5720b089a93b.png)

Additionally your list of bad words contains 5 words in total. If I understood it correctly, you get them through an API of creeperhost. If that fails, you'll fallback to a bad word list of 19 words in total. Is that intentional?

**Comment by ThePaul-T** [comment]
We should just remove the in-client one and people can just deal with their bad decisions.
