### ISSUE TITLE
Different Launchers

### ISSUE THREAD

**Issue by VPetterv** [CreeperHost/CreeperHostGui#247]
I normally play modpacks with the Twitch Launcher, (Don't judge me I'm new) and I wanted to play SB2 but potato pc. and then I heard that with the FTB App you can pre-allocate memory. So I downloaded it then I needed help went to the MT chat and it kept telling me nick is already used try again in 5m.

**Comment by VPetterv** [comment]
Here is the image of the issue ![image](https://user-images.githubusercontent.com/64741928/80920208-92617180-8d6e-11ea-91d7-788ec56c6dd9.png)

**Comment by gigabit101** [comment]
If your nick is already in use currently you will need to close your game and wait a few minutes, better handling for this is on the way
