### ISSUE TITLE
Banned from MineTogether Chat

### ISSUE THREAD

**Issue by Distion55x** [CreeperHost/CreeperHostGui#250]
I have been banned from the Minetogether Chat and would like to appeal to remove the ban. As far as I know, I have been banned for using the word "exactly" subsequent to a word ending with the letter "s". This might have triggered the system, thinking I typed a word that would be registered as inappropriate.

**Comment by Draylynn** [comment]
Do you have a ban ID? What word/sentence do you think (typed exactly as you typed it in chat) caused the ban?

**Comment by Distion55x** [comment]
The ban ID is mtg-ban=5eb6e1c2ebd583-91671363 and no, I'm afraid I don't remember it. I only know that the word "exactly" was in it for sure, and since that word had gotten me a warning before, I automatically assumed it must have been the reason.

**Comment by Draylynn** [comment]
You were banned by following an inappropriate train: One user (also banned) started making sexual references, and you responded with "Kinda kinky".

Moderators job is to ensure the rules are abided by and that the chat does not get derailed in such a fashion: Whilst you may have deemed it harmless, there's a lot of immature people in chat who would quickly spin the conversation into the more adult-only area of the internet.
There are kids and adults in chat: Make sure to set an example and keep the chat aimed towards gaming and kid-friendly topics.

Bare this in mind next time [Unbans].
_Note: If that particular mod bans you again, there will be no hope for you. :3 _
