### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Pilo-Pilo** [CreeperHost/CreeperHostGui#251]
Hello to the members of the moderation team

I'm writing here to kindly ask to revise a ban to the minetoghether chat.
One, or more than one, of my behaviors had broken the rules.

The context was: an user had just seen the bot being activated during its work, he asked which word was not allowed in the room; i proceeded to clarify  answering him the word by changing one of the letters and thus going against the rules.

Some details: 
-date and time
11 may 2020, 21:20 (GMT +1)

-last line of chat
zoomer

-ban ID:
mtg-ban=5eb9a549187cc6-65093326

Thank you for your attention
Pilo

**Comment by Draylynn** [comment]
You got banned for taking the absolute biscuit.
Someone used the b word and got muted, there was an entire discussion on why it's unacceptable, after which, you decided to test your luck and started using other ageist terms ignoring my warnings.

![image](https://user-images.githubusercontent.com/45239550/81720446-57e68b80-9476-11ea-93d1-1907068e9b6d.png)
Should be familiar...
