### ISSUE TITLE
Crash report in my ftb revelation modpack

### ISSUE THREAD

**Issue by daviidxestrada** [CreeperHost/CreeperHostGui#253]
I was playing last night and everything went well, and I stopped playing so I closed the game, today I entered to play but theres a crash report and It puts something about minetogether I dont know how to fix it, hope you can help, Ill attach the latest log and the crash report to see if you can help me
[latest.log](https://github.com/CreeperHost/CreeperHostGui/files/4638160/latest.log)
[crash-2020-05-16_11.49.32-server.txt](https://github.com/CreeperHost/CreeperHostGui/files/4638164/crash-2020-05-16_11.49.32-server.txt)

**Comment by daviidxestrada** [comment]
I fixed this by updating the mod but now when Im in game, when trying to enter the chat it puts Disconnected: Nickname is in use 
My nickname is xEmperial

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue
