### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by LDzonis** [CreeperHost/CreeperHostGui#256]
Got banned not really sure for what can I get an unban?

What I said that I got banned after: "hey mods is it true u cant use swear words here like f***?"
and after this got this message show in the image which I donw know what it really means
![image](https://user-images.githubusercontent.com/34076437/82386355-1c2a6380-9a2c-11ea-90a3-c84ef7e2b2f4.png)

**Comment by ThePaul-T** [comment]
For evading the filter when the rules are clear.

________________________________

**Comment by LDzonis** [comment]
huh? what filter I was trying to evade it was a genuine question and I censored it out so the question is clear but with no swear words

**Comment by ThePaul-T** [comment]
The intended word is obvious, the starring was to avoid the ban you knew would happen.
