### ISSUE TITLE
Unable to verify server

### ISSUE THREAD

**Issue by DeadRaider37** [CreeperHost/CreeperHostGui#257]
I've recently started a modpack on CurseForge, and was working on a Server pack. I setup the minetogether.cfg with the Project ID, copied it to the Server file, and then started the server. Once the server started, I got this:

[11:38:07] [Thread-9/ERROR] [minetogetherserver]: Unable to do call to server list - will try again in 90 seconds. Reason: Unable to verify server.

My minetogether.cfg file looks like this:

{
  "curseProjectID": "384493",
  "promoCode": "38aB674G3",
  "creeperhostEnabled": true,
  "mpMenuEnabled": true,
  "mainMenuEnabled": true,
  "serverHostButtonImage": true,
  "serverHostMenuImage": true,
  "sivIntegration": true,
  "serverListEnabled": true,
  "chatEnabled": true,
  "autoMT": true,
  "enableFriendOnlineToasts": true,
  "pregenDiameter": 120
}

Did I set it up wrong?
Or is this a bug?

**Comment by gigabit101** [comment]
Can I get a your full log file?

**Comment by DeadRaider37** [comment]
Here's the latest log:
https://pastebin.com/t30Wv5pX

**Comment by ThePaul-T** [comment]
Does 'api.creeper.host' resolve for you?

**Comment by Draylynn** [comment]
Closing: No further information has been provided.
