### ISSUE TITLE
If creeperhost.net is down launching a client or server crashes

### ISSUE THREAD

**Issue by hadn69** [CreeperHost/CreeperHostGui#258]
minetogether returns §null if creeperhost.net goes down. I have attached my crash log and debug log. 
[crash-2020-05-22_23.04.53-server.txt](https://github.com/CreeperHost/CreeperHostGui/files/4670745/crash-2020-05-22_23.04.53-server.txt)
[debug-1.log](https://github.com/CreeperHost/CreeperHostGui/files/4670746/debug-1.log)

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue
