### ISSUE TITLE
Banned for saying 'you're a stinky poopoo here'

### ISSUE THREAD

**Issue by Tw3n7y** [CreeperHost/CreeperHostGui#260]
Someone said that they were an op, so i thought it would be funny to 'insult' them in a light-hearted way by saying 'you're a stinky poopoo here', and immediately after I was banned without warning. I am appealing because I don't believe there was anything wrong with that. 
Images:
 ![1](https://user-images.githubusercontent.com/65868493/82762467-13a1a680-9df9-11ea-82d1-d5d136c67658.JPG)
 ![3](https://user-images.githubusercontent.com/65868493/82762540-81e66900-9df9-11ea-9dab-b92f5dd2e7e3.JPG)

**Comment by Draylynn** [comment]
Bob (Bannius Hammerius) the chatbot got you, I was there when it happened.

![](https://i.ibb.co/XDj3CNj/tenor.gif)
