### ISSUE TITLE
GuiMTChat.formatLine crashes

### ISSUE THREAD

**Issue by LatvianModder** [CreeperHost/CreeperHostGui#262]
I have been getting these a lot: 

https://mcmc.dev/crashes/client/DnQ5cltMo8cO
https://mcmc.dev/crashes/client/XNU5cltHi9hc

Strangely, only recently, maybe its one person

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue
