### ISSUE TITLE
Updated, cannot connect due to "nick already in use"

### ISSUE THREAD

**Issue by OscarFRA** [CreeperHost/CreeperHostGui#264]
I have just updated from 2.2.0 on the ftb revelations pack to 2.2.5, and receive the following message every 5 minutes:

<System> Couldn't connect as your nick is in use.
Waiting 5 minutes and trying again.
<System> Disconnected (Reason: :
irc.minetogether.io 433 * Blaxconiox :Nickname is already in
use.). Reconnecting.

This repeated since I entered my SP world, but only after the rules message and the following:

<System> Disconnected (Reason:
:BanniusHammerius!CreeperHost@noc.as201971.net MODE
#superspecialpirateclub +v User3680). Reconnecting

I am aware that there is another thread related to updating to/from 2.2.0, however it is closed.
Please help :)
P.S. I'm not happy about being muted for mentioning Roblox :P

**Comment by gigabit101** [comment]
Simply exit the game and wait up to 5 minutes for your user to disconnect from the IRC channel, We have made some changes in the next version that should fix the reconnect issue when this happens
