### ISSUE TITLE
Cant connect anymore

### ISSUE THREAD

**Issue by Kaathnar** [CreeperHost/CreeperHostGui#268]
This morning I could talk with others normally, but after leaving for the day, when I reconnected, this message was displayed and I can no longer connect. I don’t know what to do, help :(
![minetogether-issue](https://user-images.githubusercontent.com/63322024/83819043-281f5200-a6c9-11ea-8f4a-cb1e291a58fb.PNG)

**Comment by Kaathnar** [comment]
I tried on another modpack to see if that was the problem but I have this message now:
![minetogether-issue2](https://user-images.githubusercontent.com/63322024/83819604-97497600-a6ca-11ea-9455-6ad0bc4d86f5.PNG)
But now im even more confused because
1) "Nickname is already in use" just what???
2) "Ban" ???
I'm pretty sure last time I was connected it was around 14h-15h and the last message I sent was something like: "I have a enormous headache rn so i gonna leave you there" "bye"
If a mod tells here at least me why I'm banned if I'm really being, because I'm always being respected with everyone and i really like this mod.
(sorry if I made grammatical mistakes, English is not my first language)

**Comment by Draylynn** [comment]
You were banned by another chat moderator after the chat was reviewed last night.
"thanks for joining, we're trying to give dray a burn out"
Purposely making chat moderators job harder: Wheaton's Law violation.

**Comment by Kaathnar** [comment]
im getting banned for this??? I was joking, of course and there was a context:
me and overs were having fun with you because someone got banned from saying roblox and you tried to justify, and an other moderator joinned then i send this. You cant tell me that you didn't understand.
This is stupid to ban someone for that, if you guys can understand jokes, the blacklist should be already few miles long...

**Comment by ThePaul-T** [comment]
If you can't understand when not to make specific jokes, perhaps you should re-evaluate what you find funny.
