### ISSUE TITLE
Crash when clicking the "Support the modpack creator!" button

### ISSUE THREAD

**Issue by SnowShock35** [CreeperHost/CreeperHostGui#269]
# Crash when clicking the "Support the modpack creator!" button

![Multiplayer Menu in Minecraft showcasing MineTogether mod bug](https://user-images.githubusercontent.com/8388680/84077112-c0ba1880-a9ce-11ea-8023-03b577aca3a0.png)

## Description

When clicking the "Support the modpack creator!" button in the Multiplayer screen the game crashes to desktop and outputs the below crash report. The config is also listed below.

## Relevant Information

- Minecraft 1.15.2
- Forge 31.2.9
- MineTogether 1.15.2-4.0.0-Beta4

## Steps to Reproduce

1. Load Minecraft with Forge and MineTogether with the versions listed above
2. Close the game
3. Open the config file in your favourite text editor and use the below config
4. Save and close the file
5. Relaunch Minecraft
6. Open the Multiplayer menu and click the "Support the modpack creator!" button
7. 😭 and report the bug to CreeperHost 😜 

### minetogether.json
```json
{
  "curseProjectID": "239076",
  "promoCode": "snowshock35xbe",
  "creeperhostEnabled": true,
  "mpMenuEnabled": true,
  "mainMenuEnabled": true,
  "serverHostButtonImage": true,
  "serverHostMenuImage": true,
  "sivIntegration": true,
  "serverListEnabled": true,
  "chatEnabled": true,
  "autoMT": true,
  "enableFriendOnlineToasts": true,
  "enableMainMenuFriends": true,
  "pregenDiameter": 120
}

```

### Crash Report

<https://pastebin.com/bSRd9UFp>

**Comment by gigabit101** [comment]
This has already been fixed, Release coming soon

**Comment by SnowShock35** [comment]
Brilliant, thanks 😄

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue
