### ISSUE TITLE
Disconnected : Nickname already in use

### ISSUE THREAD

**Issue by VVilsonPH** [CreeperHost/CreeperHostGui#270]
After getting this message : 
Disconnected (Reason:
:BanniusHammerius!CreeperHost@noc.as201971.net MODE
#superspecialpirateclub). Reconnecting
I tried restarting the game, waiting 30 minutes, restarting it again but nothing seemed to help.
This is FTB : Academy
![screensht](https://user-images.githubusercontent.com/62387234/84376423-cc355b80-abe9-11ea-87a7-79524161d3a7.png)

**Comment by Tw3n7y** [comment]
I had the same issue on Sky Odyssey as of 1.2.0
![2020-06-11_12 13 40](https://user-images.githubusercontent.com/65868493/84378997-00564f80-abdd-11ea-88de-06d22a851cf9.png)

**Comment by gigabit101** [comment]
This has been fixed in newer builds, You will need to update to the latest version to resolve this issue

**Comment by VVilsonPH** [comment]
This is the latest version

**Comment by gigabit101** [comment]
You will need the latest version of the mod, not the Modpack, If you are unable to do this yourself you will need to wait for the Modpack to update.
