### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by mobfighter6000** [CreeperHost/CreeperHostGui#271]
I asked to be banned and they said see you in 5 minutes on github and its been 5 mins unban or bad.
its now been 7 minutes as my ban was at 9:18 and it is now 9:25

**Comment by KatouMegumi-osu** [comment]
lmao

**Comment by Draylynn** [comment]
Why do you want to be unbanned?
How have you learnt from this experience?
What will you aim to be better at in future in MineTogether chat?
Do you have a moment to talk about our lord and saviour, Sir-Creep'A'Lot?
Do you know why the chicken crossed the road?
Do you play Stoneblock 2, and do you find cows just as amooosing as chickens?

**Comment by mobfighter6000** [comment]
Draylynn 
1. I want to be unbanned cuz it scam
2. nothing
3.not asked to be banned
4.no
5.up
6.no chickens are more amooosing then your dumb joke :)

**Comment by K-4U** [comment]
*than

**Comment by mobfighter6000** [comment]
:(

**Comment by mobfighter6000** [comment]
unban me or bad

**Comment by ThePaul-T** [comment]
Not ever being unbanned.

**Comment by Draylynn** [comment]
We take fraud very seriously here at CreeperHost, we do not scam users - We do have verified server logs of you requesting to use this feature which can be produced on request, and logs of the request being granted in a timely fashion, as per our Terms of Service.
MineTogether's rules include not spreading slander and libel, no toxic behaviour and no breach of Wheaton's Law.

I think you need to remind me on exactly what you've learnt from this experience... Namely, that my jokes obviously far surpass your original joke and what the rules of MineTogether are.
