### ISSUE TITLE
Mephisto72's Ban Appeal.

### ISSUE THREAD

**Issue by Mephisto72** [CreeperHost/CreeperHostGui#275]
Minecraft Username: Mephisto72

Why you were banned: Innapropriate Link/Content

Given Ban Length: Permanent

What were you doing last on the server: Sending a link of a r/mademesmile video.

Why you think you should be pardoned: I regret sending the link, I want to rejoin the community. I need both their help and them to cheer me up if something happens. I will not break any more rules, I promise. I will also stop pushing it (If what I did before was pushing it), If you don't accept this ban appeal, I understand. I just hope I can be apart of the community again.

Please contact me if you have made a decision,

Mephisto72

(I have taken a ban appeal format since I don't know if there is an official one for this mod/GitHub)

**Comment by Draylynn** [comment]
Can you provide the URL you linked in chat (Please censor any inappropriate words in the URL)? Or a ban-ID.
There have been a few people linking inappropriate content lately, I need to confirm you are who I think you are.

**Comment by Mephisto72** [comment]
It's this one. https://www.youtube.com/watch?v=B7zzJPJJUuk&list=PLxnRKDVhX8u9c25SXTAH4r7eoFZm3giUV&index=10&t=0s

**Comment by Draylynn** [comment]
Please make sure the content you post in MineTogether abides ESRB10+ (Minecrafts own rating) rules. Don't let it happen again.
