### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Shiov** [CreeperHost/CreeperHostGui#278]
**Minecraft Username:**  Shio_v

**Ban ID:** mtg-ban=5ef20af0236e24-384080094

**What was the reason for your ban?**  i said ''sex'' 

**Why you think you should be unbanned:** okay so me and my friends made a server with direwolf and we never played that modpack so this global chat was really now to all of us and we are like very close friends so we have a lot of insider. We all joined the global chat and wanted to se if it work and i just said ''sex'' (its one of our insiders, its just (in our opinion) funny to say it as reaction or statement etc) i knew there were rules but i was pretty exited to just try it out and type so i type the first world that came to my mind and yea well 

**What steps will you take to make sure this doesn't happen in the future:** i didnt mean to like purposly be ''rude'' or say stupid stuff i am sorry :(

**Comment by Draylynn** [comment]
![image](https://user-images.githubusercontent.com/45239550/85421767-b8381500-b56c-11ea-9c14-5cf8e0939ce0.png)

Auto-banned by the bot. Make sure to type "rules" to see the chat rules, as you are instructed at the start of chat.

**Comment by Shiov** [comment]
when i try to type rules nothing happens though :(

**Comment by Draylynn** [comment]
Something always happens, I call baloney! Screenshot or it didn't happen.
