### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by BaconShrub** [CreeperHost/CreeperHostGui#282]
**Minecraft Username:** 

BaconShrub

**Ban ID:** 

mtg-ban=5ef539afd990d4-96200227

**What was the reason for your ban?** 

I *think* it was because I used the word 'suck' in chat. I'm not used to this being a blacklisted word as context is what makes it inappropriate. I was under the impression that I was already using family friendly phrasing. I was wrong.

**Why you think you should be unbanned:**

I'm friendly and helpful. I'm not a troublemaker. I have no intention of being a troublemaker. I have made friends using this mod and would like to continue talking to the friends I have made.

**What steps will you take to make sure this doesn't happen in the future:**

Be extra careful about what words I use. Probably seek a word blacklist if there is one.

**Comment by Draylynn** [comment]
You're not banned (as of 9am this morning when I did my morning rounds in MineTogether). Also, you did trigger the filter, but under the context, I don't understand why a chat moderator decided to go ahead and ban you.
