### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Duhmonkey** [CreeperHost/CreeperHostGui#284]
**Minecraft Username: Duhmonkey** 

**Ban ID: I'm not sure, the chat said I was kicked and needed to rejoin, so I closed the window and restarted minecraft to try to rejoin, when it didn't I assumed it was because of a ban.**

**What was the reason for your ban? I'm think it's because I said pornhub.com trying to make a joke** 

**Why you think you should be unbanned: I think i should be unbanned, because I did not realize that 'pornhub.com' was considered a bad word, and it wont happen again. I really enjoy talking with the people on the chats and in the servers when I play singleplayer, I don't feel so alone.**

**What steps will you take to make sure this doesn't happen in the future: to make sure this will not happen again in the future, I will filter what I say before I send it in the Chat**

**Comment by ThePaul-T** [comment]
Just no, not ever.
