### ISSUE TITLE
Ban with first mute

### ISSUE THREAD

**Issue by Polonoria** [CreeperHost/CreeperHostGui#285]
**Minecraft Username:** 
Polonoria
**Ban ID:**
mtg-ban=5efba7bd908551-94283763
**What was the reason for your ban?** 
Inappropriate, saying "oh shit"

**Why you think you should be unbanned:**
Two things, first of all I didnt know there were rules in this mod, it came with a modpack and didnt know this could happen, second, because it was my first mute and I havent got muted never before, I just didnt know the rules
Here is a photo of the ban
![2020-06-30_23 16 59](https://user-images.githubusercontent.com/67499454/86178171-2f027e80-bb28-11ea-85a6-a9e545ebb664.png)

**What steps will you take to make sure this doesn't happen in the future:**

I've read the rules and now know not to swear in the chat

**Comment by Polonoria** [comment]
I forgot to say, the modpack Im using is Stoneblock 2

**Comment by Draylynn** [comment]
Usually temp mutes are minor infractions, these are not enforced as bans by mods unless there was another rule being broken at the same time/it's being frequently triggered by the same user, or, you have been warned and are blatantly ignoring the chat moderator.
I have already unbanned you this morning during my morning rounds in chat and have noted my... Displeasure at seeing this happen, to the other chat moderators [Polishes her newspaper].
