### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by petereggman** [CreeperHost/CreeperHostGui#288]
PeterEggman.

mtg-ban=5efc4e98a05b33-93658292.

Toxic Behaviour to my friend.

Because it was a joke and i'm very sorry for my toxic behaviour and it will never happen again.

 
I will communicate in discord for private messages and never be toxic in public chat.

**Comment by Draylynn** [comment]
The joke might be seen between 2 friends, but other people are watching too. We don't know if that's a joke or not. Don't let it happen again.

**Comment by ThePaul-T** [comment]
To add to this (and explain why even in this situation it's still not allowed even between friends in the public chat):

You act like this in front of people, this has the effect of "normalizing" the behaviour, so others, potentially more impressionable, will go out and potentially treat everyone, strangers, friends, family alike this way.
