### ISSUE TITLE
Ban appeal for swearing.

### ISSUE THREAD

**Issue by Saenaria** [CreeperHost/CreeperHostGui#290]
Saenaria

mtg-ban=5f093003abd079-12021132

I dropped an F-Bomb in the Mine Together chat. 

I honestly thought I was on the local server tab and pulled up the chat to talk to the person that just logged in right in front of me. My apologies. 

Make sure I am in the right tab before typing.

**Comment by Draylynn** [comment]
Pay attention to the intro in chat.
