### ISSUE TITLE
i did nothing wrong

### ISSUE THREAD

**Issue by VapenMods** [CreeperHost/CreeperHostGui#292]
**Minecraft Username:** 
VapenMods
**Ban ID:**

**What was the reason for your ban?** 
i have no idea

**Why you think you should be unbanned:**
i did nothing wrong

**What steps will you take to make sure this doesn't happen in the future:**

the message i got was. your muted some one is looking into it... long ago
if the message i sent wasnt deleted i would have that screen shot. i will get as close to it as i can though
"i dont like death metal the screaming is stupid but i do like MUSHROOMHEAD - The Heresy ... odd."
its a real band and song all the mod had to do was google it

**Comment by Draylynn** [comment]
This ban was already removed during my morning rounds, also, the word that triggered the ban from another mod: Retarded

**Comment by VapenMods** [comment]
ty sorry
