### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by GamingPenguin** [CreeperHost/CreeperHostGui#293]
**Minecraft Username:** 
GamingPenguin_YT

**Ban ID:**
mtg-ban=5f10d565c9be13-54509577

**What was the reason for your ban?** 
I Used MF as an abbreviation and didn't know that could get me into trouble because and it was the first time i had used the chat in general

**Why you think you should be unbanned:**
Because the rules never popped up for me and before i knew it. it was too late 

**What steps will you take to make sure this doesn't happen in the future:**
Stop swearing all together, use chat to only as questions and follow the rules.

**Comment by Draylynn** [comment]
The rules are stated on first join, subsequent visits tell you to type "rules", additionally, I'm frequently in the chatroom reminding people about the rules and what the colour codes mean.

You were told to watch the use of your abbreviations.
You demonstrated you clearly knew what it meant.

Then for the love of cheesus and I don't know why, trying to be funny, just being insolent, I don't know? **YOU REPEATED IT**
I didn't see a single "I'm sorry" or "I will do better" etc.
Honestly, what did you expect? If you can't behave, you can't chat there, it's simple.

![image](https://user-images.githubusercontent.com/45239550/87854079-0d1a4180-c907-11ea-9ce9-af4f0070ae5f.png)

**Comment by GamingPenguin** [comment]
i said it once and then asked about it and another it shows the rules when you join a game or single player world if you dont- click on the mine together tab it wont be there if your not fast enough
