### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by GamingPenguin** [CreeperHost/CreeperHostGui#295]
*Minecraft Username:*
GamingPenguin_YT

*Ban ID:*
mtg-ban=5f10d565c9be13-54509577

*What was the reason for your ban?*
I Used MF as an abbreviation and didn't know that could get me into trouble because and it was the first time i had used the chat in general.

*Why you think you should be unbanned:*
because i never saw the rules i rarely looked at the chat and when i did it was the server chat i was in and before i knew it i was banned. i only said it once and then i asked a moderator about it.

*What steps will you take to make sure this doesn't happen in the future:*
Stop swearing all together, use chat to only ask questions and follow the rules.

**Comment by Draylynn** [comment]
Do not open multiple tickets for the same issue. Your appeal has already been addressed and denied.
