### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Glitxed** [CreeperHost/CreeperHostGui#298]
**Minecraft Username:** 
GlitXed
**Ban ID:**
mtg-ban=5f172b0256ccd8-01640544
**What was the reason for your ban?** 
I don't really know, i think i said something that was picked up by the bad word filter

**Why you think you should be unbanned:**
I don't really even know the reason i was banned except that i said inappropiate terminology, without even knowing what is innapropriate

**What steps will you take to make sure this doesn't happen in the future:**
I won't use any risky words, or words with double meaning

**Comment by Draylynn** [comment]
"S U C C"... I shouldn't really need to explain it should I?
