### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by TowlieeNetworks** [CreeperHost/CreeperHostGui#300]
**Minecraft Username: FancyCat420** 

**Ban ID: not sure where to find it**

**What was the reason for your ban: i sayed the f word in a dutch sentence on accident** 

**Why you think you should be unbanned: i wasnt paying attention and i miss my friend in that chat**

**What steps will you take to make sure this doesn't happen in the future: actually take the time to look in what chat i am typing in and quit cursing all together because i love mineTogether**

**Comment by Draylynn** [comment]
We require a ban-ID to locate the ban, or an exact mention of what was said and when.

**Comment by TowlieeNetworks** [comment]
is there anywhere is can find the ban-ID

**Comment by Draylynn** [comment]
It's shown when you get banned.
`...or an exact mention of what was said and when.`

**Comment by TowlieeNetworks** [comment]
it would be "fuck wrong chat" just before 01:10:52 Central European Summer Time (CEST) 21-07-2020

**Comment by Draylynn** [comment]
It appears you also used abbreviation swearing a few times too, when you clearly demonstrated you knew which chat you were in (referencing purple names and fellow mod pack users).

[Stamps application] **_DENIED._**

**Comment by TowlieeNetworks** [comment]
where did you see abbreviation swearing? i would like to see what you are talking about to maybe clear up a misunderstanding and otherwise is will just accept it

**Comment by Draylynn** [comment]
12:09 AM (GMT): later tonight bruv its -swear- 01:09am here XD
