### ISSUE TITLE
website security issue

### ISSUE THREAD

**Issue by TowlieeNetworks** [CreeperHost/CreeperHostGui#301]
**Describe the bug**
i tried opening the minetogether chat and i got 2 links of your website and me being me i clicked both of them wanting to see what happened. i found a security issue and part of a not completed site.

**To Reproduce**
1. Go to the link
3. And read what it says

**Expected behavior**
nothing really

**Screenshots**
If applicable, add screenshots to help explain your problem. ADDED
![Screenshot_6](https://user-images.githubusercontent.com/11318066/88426524-a1960f80-cdf1-11ea-8a93-c2656d1bfc36.png)
![Screenshot_7](https://user-images.githubusercontent.com/11318066/88426542-a8248700-cdf1-11ea-9307-f5e7e0569685.png)

**Versions**
Please give all the versions you are using:

Minecraft: 1.12.2

Forge: 14.23.5.2846

Minetogether: minetogether-1.10.2-2.2.0-RC6

Additional
unfinished page,
unsafe to have part of you file structure on your site /usr/share/nginx/html/404/html

**Comment by ThePaul-T** [comment]
Knowing the path to a file on the filesystem is not a security issue, at least 50% of the websites on the internet are likely ran in /var/www/html or /usr/share/nginx/html, there is pretty much nothing I can do with that information.

**Comment by TowlieeNetworks** [comment]
it would be considered a security issue because it gives out that you are using nginx and probably did not change anything in the filestructure and there for a hacker can get in way easyer because he knows where to find stuff

**Comment by K-4U** [comment]
While yes, every webserver is so vain that it sends you the information about itself in every request.
I get that you're trying to help, but it's really a non-issue. If a hacker really wants in, he can get in.

**Comment by TowlieeNetworks** [comment]
thats true if a hacker is bored he can get in either way but its best in my opinion to minimize the risk
