### ISSUE TITLE
Toasttz's Ban Appeal

### ISSUE THREAD

**Issue by Toasttz** [CreeperHost/CreeperHostGui#302]
**Minecraft Username:** 
Toasttz

**Ban ID:**
mtg-ban=5d5650c4076721-17342520

**What was the reason for your ban?** 
Just played a FTB pack, then realized that I was banned from Minetogether last year (2019-09-06). I have used Minetogether before, but I'm not sure why I was banned, nor do I recall getting banned. I did have some connectivity issues to Minetogether, but that's probably unrelated to the ban. (Are bans stored via usernames or UUIDs? Someone else seems to have used my current username before I did).

**Why you think you should be unbanned:**
I'm pretty sure that I haven't done anything that broke Minetogether rules, and as I stated, I do not recall getting banned (or recall doing anything that would lead to a ban). Regardless of whether or not my ban was just, I will do my best to follow the rules in the future. I am sorry for whatever I did before, and would like to ask for another chance. I do not wish to, and have no intention to do harm to the community, but rather contribute to it.

**What steps will you take to make sure this doesn't happen in the future:**
In the future, I will pay extra attention to what I send in the global chat, and will follow the rules as best as I can.

**Comment by Draylynn** [comment]
You were banned for abusing the @report feature, by reporting absolutely nothing at all.
This feature flags all online members of staff to chat.
Then proceeded to repeatedly ask "What are the rules?" (to which the chat bot responds to the world "rules" every time).
