### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by ShadyProfile** [CreeperHost/CreeperHostGui#305]
**Minecraft Username:** 
Shady_profile
**Ban ID:**  Inappropriate conduct
mtg-ban=5f1e06eddebb43-068815])
**What was the reason for your ban?** 
I called one of the rules that I didn't agree with lame, didn't break that rule but I expressed that I didn't agree with it by calling it "lame". Someone said "say it's 'lame' again." Simply to humor him I did and got banned for it. 

**Why you think you should be unbanned:**
I don't really think I've done much wrong, at least not that I'm aware of that warrants something so absolute of being banned on the spot. No warning no nothing.  My intentions were never to be malicious about it or anything just said my opinion and that was meant to see how others felt about it as well. 

**What steps will you take to make sure this doesn't happen in the future:** Keep my opinion to myself so this doesnt happen again. I'll try not to get myself in a situation like that again and simply keep talking about the game and trying to help people should they need it.
![Banned](https://user-images.githubusercontent.com/68829323/88491814-f1044900-cf73-11ea-810d-0d47d6e66d7f.PNG)

**Comment by Draylynn** [comment]
24 hours.
