### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by SteveTheDino** [CreeperHost/CreeperHostGui#308]
Minecraft Username: TepigIsHot

Ban ID: mtg-ban=5f20341492a739-85732606

What was the reason for your ban?: I hadn't read the rules and I used a no no word.

Why you think you should be unbanned: I admitted my wrong-doing and I am sorry for breaking the rules. I promise not to do it again.

What steps will you take to make sure this doesn't happen in the future: I will read the rules properly and make sure to actually follow them.

**Comment by Draylynn** [comment]
No more no-no words.
