### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by KrimsonBullet** [CreeperHost/CreeperHostGui#310]
Krimson_Bullet

mtg-ban=5f21edb5aa6013-19220869

Flooding chat

It was an accident, I had finished cleaning my keyboard, and was putting it back together when I forgot the minetogether was still open, and I guess it was flooding chat

I will not clean my keyboard while I am afk in another game that has a server chat

**Comment by Draylynn** [comment]
Unbanned.
When cleaning ones keyboard, one always keeps Notepad/Notepad++ open and in-focus.
