### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Scotchleaf** [CreeperHost/CreeperHostGui#313]
**Minecraft Username:** 
Scotchleaf
**Ban ID:**
mtg-ban=5f26347ed52f34-80934158
**What was the reason for your ban?** 
Inappropriate language

**Why you think you should be unbanned:**
I wasn't aware that one of the rules was no inappropriate language.

**What steps will you take to make sure this doesn't happen in the future:**
I will mind my tongue.

**Comment by Draylynn** [comment]
Whilst I can totally see where you were coming from, the frustration and difficulty of the spooder army sent to kill you, please... In future, mind the language.
There be kids there and adults, set a good example to all.

Pro-tip: Replace the F word with fudge, or some other comical kid-friendly term.
Type "rules" in chat to see the rules.
