### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by JakeTheDrake8** [CreeperHost/CreeperHostGui#318]
I said "feces" in minetogether chat. I guess that was enough to get banned for inappropriate conduct.

mtg-ban=5f31ed3b42ce76-94703533

(idk how to flair)

**Comment by Draylynn** [comment]
You were purposely following a bait train where people were inappropriately mentioning various words for poop, for no particular reason, flooding and spamming chat, even after you saw the bot mute someone for it.

I don't see anything in this appeal demonstrating you understand the rules of chat or any inclination you understand what you did wrong.

**DENIED**

**Comment by JakeTheDrake8** [comment]
I didn't see that anyone got muted before me and to assume I did and ban me, I think is unreasonable. A warning or a mute, i feel, would've been a better way to handle that. I know what I did was childish but c'mon.

**Comment by Draylynn** [comment]
This stupid behaviour resulted in 4 users being banned, for lack of common sense, for being stupid, baiting, breaching Wheatons Law, being disruptive, flooding and contributing absolutely nothing to chat that was remotely in context with the topic at the time, with one of them attempting to evolve chat into some cesspit of poop related fetishism, in the space of <60 seconds. Whilst another chat moderator lost connectivity, it was a mere stroke of luck I was even there at the time to quickly issue bans.

I think it's unreasonable that you didn't bother paying attention to the rule introduction at the start of the chat, or type "rules" as instructed at the start of the chat, making life more difficult for other users and chat moderators. I think it's unreasonable you even think this is remotely appropriate public behaviour and that you had 'zero' consideration for the other users in chat.

Actions have consequences: It's still denied.
