### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by cptqrk** [CreeperHost/CreeperHostGui#319]
I was trying to be vague about an old wave file, mod wanted clarification, got banned for saying he was 'self gratifying'

Oooff... 

I was trying to be as PC as possible, always have been, but that was not fair man... :(

**Comment by Draylynn** [comment]
What did you say?
When did you get banned?
What was the ban ID?

**Comment by Draylynn** [comment]
Was this the comment referring to Donald Duck?

**Comment by cptqrk** [comment]
Yes it was, and i think you were the one that banned me LOL.

Can I get back in?  I'll get even more PC than before, it's just soo boring to play without chat

**Comment by Draylynn** [comment]
User: "that's old school... took your hours to download a 30sec clip of donald duck wacking"
Mod: "Donald Duck what?"
User: "you heard me..."
Mod: "I don't understand the context."
User: "performing self gratification"
"Banned user for Inappropriate Conduct (thanks, just checking)."

You're in an ESRB 10+ rated game, in a public global gaming channel.... And you're talking about X-rated acts and cartoon porn, in front of kids.

Do you think you can get back in?
![image](https://user-images.githubusercontent.com/45239550/90131502-28d90200-dd64-11ea-96fa-54fe93e82f33.png)
