### ISSUE TITLE
I said eeeeeeeeeeee and uuuuuuuuuuuu and would like to be unbanned

### ISSUE THREAD

**Issue by atlanticie** [CreeperHost/CreeperHostGui#320]
**Minecraft Username:** 
Atlanticie

**Ban ID:**
mtg-ban=5f339d0d6dc2e9-77146064

**What was the reason for your ban?** 
spam/flooding

**Why you think you should be unbanned:**
So basically i randomly said eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee in the chat (i dont know why) and then someone said "i personally prefer the letter u over e" so i was like "ok" and i said uuuuuuuuuuuuuuuuuuuuu
(also in the past i have said mike oxmall which was kinda inapropriate but i ment to say it in server chat o.o)

**What steps will you take to make sure this doesn't happen in the future:**
be more careful about where im typing and dont spam letters in chat

![image](https://user-images.githubusercontent.com/69646697/90170467-1794f300-dd6e-11ea-86a3-25ea3e9f0b0e.png)

**Comment by Draylynn** [comment]
You were banned for spam/flooding, you were posting letters in excessive amounts per submission.
After a player complained, you continued doing it.
As a result of your behaviour, other users thought it was funny to join in and also spam/flood: All of you were banned.

You showed no respect for yourself, other users in chat, or the rules; why should I show you any respect and unban you?
I shouldn't.
**DENIED**

**Comment by atlanticie** [comment]
yeah i was kinda stupid saying eeeeeeeeee in 1 message then joking when someone said i prefer u over e by saying uuuuuuuuuuuu once 
then doing nothing
and getting banned
cringe /:
