### ISSUE TITLE
Manual reconnect option

### ISSUE THREAD

**Issue by Discusser** [CreeperHost/CreeperHostGui#322]
**Is your feature request related to a problem? Please describe.**
Whenever I have a power cut, the power goes away for about a minute, and it takes around 2 minutes for my internet to come back. The problem is that MineTogether gives you a few seconds to reconnect once you disconnect so I end up being disconnected until I re-launch MC.

**Describe the solution you'd like**
A "reconnect" button would be great whenever you get disconnected from the MineTogether chat, maybe with a delay to prevent spam or anything similar.

**Describe alternatives you've considered**
The only current solution is re-launching MC which could take lots of time depending on the modpack and the user's PC. For me, launching enigmatica 2 takes 10 minutes and I can't be bothered to relaunch MC just for that.

**Comment by gigabit101** [comment]
It has one but it will only show up after 5 attempts and only works in dev currently

**Comment by Discusser** [comment]
Alright that's good. I'm excited for the upgrade :D
