### ISSUE TITLE
I feel like i didnt really do much wrong and would like to be unbanned

### ISSUE THREAD

**Issue by atlanticie** [CreeperHost/CreeperHostGui#324]
https://github.com/CreeperHost/CreeperHostGui/issues/320 <----- original appeal

i really dont understand why im banned permanantly or at least muted because saying maybe just a full chat row of eeeeee isnt really bad at all

and the response to the appeal didnt make a whole lot of sense it was like "since you showed no respect to other players-" how may i ask did i show no respect? "Why would i show respect to you and get you unbanned?" i still dont unerstand how i showed no respect -_-

and the part where "other people saw you were doing it joined in-" honestly, i didnt realize that this  was going to happen and i am sorry for that but after that, "-they were all banned as well" jeez, if someone does something a little bit wrong you just give them no mercy and slam a perm ban? that isnt very reasonable.

anyways i am just genuinely confused on how i dont deserve at least a temp mute instead of perma ban, i find minetogether very useful to just talk or ask questions when im confuesd - you dont need to unban me but i just wanted to state my opinions on why i think this ban was dumb.

thank you.

**Comment by Draylynn** [comment]
One of the first things you said in chat was "hi", "I am exist"... Followed by "popo", directly after you witnessed another user get muted for an associated vulgar version.
Continued with something obfuscated and random (which, on further investigation and detective work, was HIGHLY inappropriate in this chatroom), then random spam relating to EA games, then single-word submission flooding... And random iconic character names...
Not getting the attention (at this point, I don't know what attention, as users were trying to engage with you and you ignored them) you wanted, you started flooding even harder...

Your original appeal was denied with good reason, spamming/flooding. But on reflection, also explicit references in a children's gaming chatroom.

This isn't your mod, you don't contribute positively to the mod.
You don't code the mod.
You don't work for CreeperHost.
You certainly do not have a have a good reputation in chat.
You clearly don't know how to behave in public, let alone how to interact with other people amicably online.

To be blunt: You deserve nothing, you are not entitled to use our chat, it's a privilege to use our chat.
You can take that "I deserve" nonsense and false sense of self-entitlement to another part of the internet.
**Do not open another appeal.**
You will not overturn this ban, another member of staff will not overturn this ban, if you were the Queen of England, the ban would still be in effect.
I hope this makes things exceptionally clear for you.
