### ISSUE TITLE
I was stupid and would like to be unbanned <-- not incredibly wrong

### ISSUE THREAD

**Issue by malicemillenium** [CreeperHost/CreeperHostGui#325]
MaliceMillenium

mtg-ban=5f39a6f32e2a60-46060491

Saying the word "nazi" 

My usage of the word was historical presentation of the party's policies regarding human rights and how they are relevant and related to current events.

I'll avoid comparing modern politicians and their policies no matter how much they infringe on human rights to the former German nazi party. I am sorry that was very wrong.

**Comment by Draylynn** [comment]
Do not bring politics into a gaming chatroom. People play games to escape the nonsense of IRL, relax and chill.
