### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by RepoDraghon** [CreeperHost/CreeperHostGui#326]
**Minecraft Username:**
epoDraghon

**Ban ID:**
Don't remember what it was

**What was the reason for your ban?** 
Typed in binary then explained what I said in binary (I am not a robot) which I think it saw as spamming chat.

**Why you think you should be unbanned:**
It was just a silly thing, I was being funny to a person who asked if everyone in chat was a bot...

**What steps will you take to make sure this doesn't happen in the future:**
not do it again, I realize the text was too long and too repetitive.

**Comment by Draylynn** [comment]
You were banned under Wheaton's Law, spamming/flooding and breaking the language rules.
What makes this even worse, is you continued to pull a stunt like this, after several people heavily spammed the chat with their face-typing, with no consideration to other users or the chat moderators, AFTER a chat moderator pointed out no spamming or flooding was allowed... Resulting in 5 bans in under 60 seconds.

It wasn't just a 'silly thing' and the bot didn't ban you, I did: You need a better ban appeal.

**Comment by RepoDraghon** [comment]
Well, I will say that translating something from Binary to English is not spam... but the term "spam" is only defined by the person who's in charge, so, I'm not going to fight it though the dictionary definition of spam is not what I did.

**Comment by Draylynn** [comment]
Spam: Irrelevant messages, which can be repeated or are used to purposely flood chat.
Ok, but fine, whatever, let's say you didn't spam.

You broke the language rule.
You broke Wheaton's Law.
You ignored a chat moderator.
