### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by ZdravkoWare** [CreeperHost/CreeperHostGui#329]
**Minecraft Username:** DragonWare1917

**Ban ID:** mtg-ban=5f4523e5adaca4-84339531

**What was the reason for your ban?** I was banned because I explained what I meant by shoot. I had used shoot as a PG version of the sh-word, and when a player asked what I meant by this I censored the sh-word, and because of this I was banned.

**Why you think you should be unbanned:** I wasn't careful, and I was stupid. I know, sh was used to offend a certain group, and I have brushed up the ban hammer several times ago, but I will make sure this never happens again.

**What steps will you take to make sure this doesn't happen in the future:** I will be extremely careful and to prevent situations like this from ever happening, I will also never swear, so I don't have to use PG versions of swear words and have to explain them.

**Comment by ThePaul-T** [comment]
I recommend using our new appeal system as it'll allow us to look at your ban closer and make decisions based on context.

You can do this at https://minetogether.io, log in, use the mod (settings in latest beta for 1.12, Link Account button), from there you'll see "Account Standing", in here you'll be able to appeal your ban.

**Comment by ZdravkoWare** [comment]
![image](https://user-images.githubusercontent.com/56683028/91213000-aa903e80-e719-11ea-900a-fbb7ccb50936.png)
It has been stuck like that for half an hour

**Comment by Draylynn** [comment]
You knew what the rules of chat were, tried to avoid them, then used vulgarity in chat. You don't need to explain anything in chat that isn't PG, because it's a PG chat.
