### ISSUE TITLE
Change the MC version of the jar name to match MC

### ISSUE THREAD

**Issue by MAndrewSprong** [CreeperHost/CreeperHostGui#33]
It would be a good idea to change the mc version in the jar name to match the minecraft version it is appropriate for lest users get confused and try to use it on minecraft 1.10.2 when it is built for 1.12.2 instead.

It's a minor annoyance and can be ignored at your pleasure.

**Comment by CH-Paul-T** [comment]
The mod version will work on 1.10.2 upwards on all versions.
