### ISSUE TITLE
[minetogetherserver]: Enabling server list. Servers found to be breaking Mojang's EULA may be removed if complaints are received.

### ISSUE THREAD

**Issue by mihionmc** [CreeperHost/CreeperHostGui#331]
Hi! 

I have just seen this message. 

I have installed revelation 3.2.0 and Sponge with Magibridge, Nucleous and Lukperms. 

Is this well known that servers revive this message if sponge or some of the plugins are acitve?

**Comment by ThePaul-T** [comment]
All servers receive this, regardless.
