### ISSUE TITLE
Configuration sat to "Public" but listed in "Community"  And EULA Warning

### ISSUE THREAD

**Issue by mihionmc** [CreeperHost/CreeperHostGui#332]
**Describe the bug**
I have configuration sat  to "discoverability=public" in server.properties but my server is listen in "Community" server list not "Public" - I think that this may happened after setting up sponge and lukperms  on my FTB Revelation server. I'm not sure. I also get an information regarding EULA - saying that mys server is breaking it and if you receive complains then the server will be  removed. I also think that this happened after Sponge setup.   

**Versions**
Please give all the versions you are using:

Minecraft: FTB Revelation 3.2.0

Forge:Sponge

MineTogether:The one that came with FTB v. 3.2.0

**Comment by Draylynn** [comment]
Which build of MineTogether are you using?
What does your MOTD have listed in it?
Is there a whitelist in effect? (Can't be public if there is a whitelist)
"I also get an information regarding EULA" every server gets this, it's a 'warning' about server conduct and what happens if you breech EULA.
