### ISSUE TITLE
I was stupid and would like to be unbanned. And I didn't know what's speak in chat with other players is actually possible 

### ISSUE THREAD

**Issue by biuske** [CreeperHost/CreeperHostGui#333]
**zknife00:** 

**mtg-ban:5f49f75ad98d05-15388659:**

**I said "that fuk. Because I was surprised that people can see what I say in my game and they in their game* 

**Why you think you should be unbanned:**
I WANNA TALK TO DIFERRENT PEOPLE AROUND THE WORLD 

**What steps will you take to make sure this doesn't happen in the future:**

I'll be careful about that kinda of words 
Sorry for my bad English

**Comment by Draylynn** [comment]
I don't accept your excuse: 'I swore because I was surprised, that people on an ESRB 10+ rated game, in a chatroom possibly full of kids, can see my chat', it doesn't make sense, neither does your lack of basic netiquette.

**Comment by biuske** [comment]
But I didn't do by purpose. What I said is because I didn't know
I'm not even speak English
And didn't know that the word "that fuck" is bad
That bad
I didn't said that for anyone
I just said because I was surprised that stoneblock 2 have a away to speak
with others person in chat global. Because that is kinda cool, you play
your game, a offline game and in the time can speak with others person.
About anything or about the modpack
If you can see me other messages there
I was saying something like
"You guys can see my messages"
So I say "that fuck" in a expression of surprise




Em sáb, 29 de ago de 2020 13:28, Draylynn <notifications@github.com>
escreveu:

**Comment by biuske** [comment]
Like. I entering to play stoneblock 2 in my world solo 
Not multiplayer
And I didn't know that in Minecraft have a mod that do something like that 
So I was playing and I notice someone say something in chat
And I was suprised because I was solo in Minecraft. In my own world 
I didn't know about that mod, that mod do something like that
I apolize to say that world
I really didn't know
