### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by biuske** [CreeperHost/CreeperHostGui#334]
**Minecraft Username:** 
Zknife00
**Ban ID:**
mtg-ban:5f49f75ad98d05-15388659
**What was the reason for your ban?** 
I said the word "that fuk" 

**Why you think you should be unbanned:**
Because. I'm I didn't know about creeper host. I didn't know that I can speak with a global chat playing in their worlds of Minecraft
So. I was playing like always. And see someone typing in chat but I didn't know that it's possible and I'm not in a server. So I was suprised
And said "that fuk" showing that I'm surprised
I didn't know about the rules, and didn't know about that chat
I didn't said it to anyone.
I sorry for saying that word
It not gonna happen again

**What steps will you take to make sure this doesn't happen in the future:**
I not gonna say anything that can offend anyone 

Sorry for my bad english. I'm from Brazil.

**Comment by Draylynn** [comment]
But you'd already clocked on there was a global chat before you swore... "I didnt know that this modpack have something like that".
To express surprise in a chat about the mod, people usually go "What?! I didn't know" or "NO WAI!". They don't start throwing vulgarities around.
Rules are shown at the start of chat, either in full, or providing required instruction to access them.

The lack of Minecraft usernames < clue.
The chat tab is called "Global" < big clue there.
The chat frame has a logo on the background < even bigger clue there.
