### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Gamemaster21981** [CreeperHost/CreeperHostGui#335]
**Minecraft Username:** Gamemaster2198

**Ban ID:** mtg-ban=5f508f01eee115-05700184

**What was the reason for your ban?** Inappropriate language

**Why you think you should be unbanned:**
Honestly saying this will probably give you guys a better reason to leave me banned, but I was not exactly aware about the strict filter on profanity and did not read the rules (this could easily be blamed on my irresponsibility, but you guys decide).

**What steps will you take to make sure this doesn't happen in the future:**
Make sure to think twice about what I am typing into chat as well as remember to be respectful people. I apologise for not being aware of my actions.

**Comment by ThePaul-T** [comment]
I'll make you a deal.

Help us test the new appeals system at minetogether.io (must login and go to account standing)

Once I get your appeal there, I will approve it and await your feedback on the process.
________________________________

**Comment by Gamemaster21981** [comment]
Thank you!

**Comment by ThePaul-T** [comment]
Let me know when it is submitted, you'll need your Minecraft account linked from the linking page as a FYI

**Comment by Gamemaster21981** [comment]
I'm having an issue where after I hit submit it's stuck there loading.

**Comment by ThePaul-T** [comment]
Mind submitting it again for me?

**Comment by Gamemaster21981** [comment]
I have tried again to no avail.

**Comment by ThePaul-T** [comment]
Hey @Gamemaster21981,

This is 100% our end, but you're assisting me with fixing one of our developers work to get it working properly.

Hopefully, if you try now, it'll work, I fixed another bug that was causing it not to submit.

**Comment by Gamemaster21981** [comment]
I have submitted the appeal. Hopefully it goes through.

**Comment by ThePaul-T** [comment]
Looks like it worked :)
