### ISSUE TITLE
I Enjoy Stargate Atlantis and will be rewatching it soon

### ISSUE THREAD

**Issue by Rhaebus** [CreeperHost/CreeperHostGui#337]
**Minecraft Username:** 
Rhaebus

**Ban ID:**
Didnt get one? Just said DCed from server for suspected inappropriate language.

**What was the reason for your ban?** 
Honestly don't know, think maybe because I said Stargate SG-1 is as good as Star Trek TNG? Dont get me wrong I love Picard and TNG but Stargate SG-1 has a good place in the Sci Fi world too. The ultimate Star Trek for me is still Voyager though, I liked it way better than TNG, Captain Janeway is awesome!

**Why you think you should be unbanned:**

Didn't do anything wrong or break any rules; either a TNG fan got me or the bot dosnt like the word boogieman that I was using to describe the "Wraith" cause I didnt remember their name (Had to google it for this, been a good 10 years since I watched Atlantis). They are boogiemen snatching people up in the middle of the night. Guess I wont use that word anymore?

**What steps will you take to make sure this doesn't happen in the future:**
Dont call the wraith boogiemen, dont say TNG is just "Okay" and keep being a overall nice guy :D

**Comment by ThePaul-T** [comment]
Hey there,

You was actually unbanned immediately, auto bot-ban and boogie/boogiemen has been whitelisted.

We use a service called WebPurify and it is quite strict, so people will every so often find words which trigger it and we have to whitelist.

Paul
