### ISSUE TITLE
Chat tabs overlay on tooltips v2.1.3

### ISSUE THREAD

**Issue by tfox83** [CreeperHost/CreeperHostGui#34]
![image](https://user-images.githubusercontent.com/4246308/46684810-be277000-cba8-11e8-8048-7e1d3bd49fb2.png)

**Comment by Cloudhunter** [comment]
Woah. That's a monster tool tip.

Either way I'll look into fixing :)

**Comment by tfox83** [comment]
Bees... (enough said) But it does overlay on most tooltips that have any NBT tags.

**Comment by Cloudhunter** [comment]
Fixed in next version
