### ISSUE TITLE
MT logo is missing on auth page

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#340]
![image](https://user-images.githubusercontent.com/15698722/92399606-2dd56b00-f0f0-11ea-86c7-57058cd432ec.png)

**Comment by aaronhowser1** [comment]
Also, would I log in to this with the same account I use for my `partners.creeper.host` account?

**Comment by ThePaul-T** [comment]
Not yet, but hopefully soon.

**Comment by Rushmead** [comment]
This should now be fixed :)

**Comment by TeamDman** [comment]
Seems to be working when testing with a browser that hadn't cached the page.
