### ISSUE TITLE
Logout functionality doesn't log out of auth provider; login button skips auth portal

### ISSUE THREAD

**Issue by TeamDman** [CreeperHost/CreeperHostGui#343]
**Describe the bug**
The "Logout" button on the profile page doesn't fully log out the user.
After 'logging out', clicking login remembers the user's previous login and brings them to the profile page.

**To Reproduce**
1. Log in to your account (The "remember-me" checkbox state doesn't matter)
2. Visit profile page
3. Click "Logout"
4. Click "Login"
5. The user is automatically logged in.

**Expected behaviour**
1. User logs out
2. Single Log Out (SLO) logs the user out of the auth service (even if remember-me was checked)
3. User clicks "Log in"
4. User is presented with username+password form, rather than being auto logged in

**Screenshots**
None atm, can take a video if needed.

**Versions**
N/A

**Additional context**
Tested in:
- Firefox 80.0.1 (64-bit)
- Edge 85.0.564.44 (64-bit)

**Comment by Draylynn** [comment]
MineTogether.io had an overhaul, try breaking the logout button now.

**Comment by TeamDman** [comment]
Confirmed resolved!
Nitpicking, the login button opens a new tab, then doesn't bring you to the previous page when login complete.

Example:

1. https://minetogether.io/servers
2. Click login
3. Get redirected to https://auth.minetogether.io/auth/realms/MineTogether/protocol/openid-connect/auth?response_type=code&client_id=mt-mod&redirect_uri=https://minetogether.io/api/redirect
4. Login
5. Get redirected to profile page instead of https://minetogether.io/servers

**Comment by ThePaul-T** [comment]
We have the allowed redirect uri's at the oAuth end set up very strict, and until we've had time to make sure the site is 100% bug free, it'll likely stay so. Wildcards are bad. May try and do something on the actual site end.
