### ISSUE TITLE
Was stupid, got banned on my first message

### ISSUE THREAD

**Issue by ZygZagGaming** [CreeperHost/CreeperHostGui#344]
**Minecraft Username:** 
ZygZagGaming
**Ban ID:**
mtg-ban=5f5dbe1d9267b1-15486744
**What was the reason for your ban?** 
I was stupid and didn't read the rules for profanity, and got banned for cursing on my first message.

**Why you think you should be unbanned:**
I was unclear about the rules, and won't curse again.

**What steps will you take to make sure this doesn't happen in the future:**
I will read through the rules thoroughly, and make sure I follow every single one of them.

**Comment by ThePaul-T** [comment]
You can place your ban appeal at https://minetogether.io these days and it makes it a lot easier for us to find why you were banned and unban you if we feel it appropriate.
