### ISSUE TITLE
No indication that linking accounts works

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#345]
**Describe the bug**
I click this
![image](https://user-images.githubusercontent.com/15698722/93014633-327aa300-f578-11ea-8ab2-bb89205098db.png)
I log in to the website
![image](https://user-images.githubusercontent.com/15698722/93014638-37d7ed80-f578-11ea-9d2c-64ec39c7fcf3.png)
I go back to the game, and nothing has changed

**Versions**
Please give all the versions you are using:

Minecraft: 1.12.2

Forge: 14.23.5.2847

MineTogether: MineTogether-1.12.2-1.12.2-2.3.2

**Comment by ArgonileFTW** [comment]
How exactly did you link your account in general? I got banned and not getting help sadly and thought of reaching out to others.

**Comment by gigabit101** [comment]
Working as intended, Feedback is provided by the website
