### ISSUE TITLE
Apparently, starting to say "fudge" is ban worthy

### ISSUE THREAD

**Issue by ghost** [CreeperHost/CreeperHostGui#348]
**Minecraft Username:** 
ZeroZX0

**Ban ID:**
mtg-ban=5f65e72d3029e2-06442636

**What was the reason for your ban?** 
I'm willing to bet it's because i typed "what the fu..." and it was supposed to be "fudge."
I'll admit i was angry my entire overworld world gen straight up rewrote itself on me, but seriously?

**Why you think you should be unbanned:**
Is fudge really worth banning someone over?

**What steps will you take to make sure this doesn't happen in the future:**
I won't stop at the letter "u" next time.

**Comment by Draylynn** [comment]
Wasn't 'what the fudge' though, was it.
