### ISSUE TITLE
Error message 'Error formatting line, Please report this to the issue tracker" in chat

### ISSUE THREAD

**Issue by IcemanDs** [CreeperHost/CreeperHostGui#349]
By occasion it throws this error as stated above in chat and chats are replaced by the error.
![Screenshot_2020-09-21_17-24-55](https://user-images.githubusercontent.com/45338739/93773368-572de500-fc20-11ea-9656-520fe2f02969.png)

**Comment by gigabit101** [comment]
Fixed in latest releases.
