### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by OWNEDGAMING** [CreeperHost/CreeperHostGui#352]
Zatusrex

mtg-ban=5f7875367250f2-04708070

Inappropriate Conduct 

this is just an honest mistake. people was joking and saying uwu and i responded with "notices bulge" i didin't think it was that inappropriate but thinking back it might have been a little too much.

I'm gonna see too it that i do not make jokes that might be a little too much for kids that are on the younger side.

**Comment by ThePaul-T** [comment]
Appeals should be done at https://minetogether.io now please :)
________________________________
