### ISSUE TITLE
[1.16.1] Multiplayer Screen Crash 

### ISSUE THREAD

**Issue by YOYOK9** [CreeperHost/CreeperHostGui#354]
**Describe the bug**
Basically what is happening is in my custom (public) modpack crashes if a player hits the refresh button more than just once (ex: a server is still loading)  to connect to our private server the game will crash to desktop. The server is not part of creeperhosting. 

**To Reproduce**
Steps to reproduce the behaviour:
Unfortunatly this seems to only happen with my modpack (as far as I know)
1. Boot pack
2. Go to multiplayer
3. Add an ip to a none creeper host server
4. Spam click Refresh

**Expected behaviour**
To refresh the server list without crashing

**Screenshots**
N/A

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.1

Forge: 32.0.108

MineTogether: 1.16.1-4.1.0-Beta2

**Additional context**
Packs mod list: https://pastebin.com/fP96JUWz
Crash Report: https://pastebin.com/mi7hAaaS
Testing: Tried booting a pack with just MineTogether alone and spammed the refresh button with my servers ip, no crash.

**Comment by gigabit101** [comment]
Fixed in newer versions, update to the latest version and try again.
