### ISSUE TITLE
IRC Ban Appeal (Invalid Client)

### ISSUE THREAD

**Issue by TheArcaneBrony** [CreeperHost/CreeperHostGui#356]
Hello, I was trying to connect through an external IRC client so i could stay in touch without having minecraft open. I didn't realise this would get me banned, but it did.

I would like to appeal for this ban, and ask if theres any external way to join the chat.

Username: TheArcaneBrony
Screenshot of ban message: https://i.imgur.com/PjlysJw.png
Screenshot of ingame effects: https://i.imgur.com/mkLuvjL.png

Thank you for your time!

**Comment by Draylynn** [comment]
Will not fix - Working as intended: Don't go poking around where you shouldn't be and no you can't.
The ban will auto-expire on it's own, when, that's for you to find out.
