### ISSUE TITLE
strange autoban

### ISSUE THREAD

**Issue by sossololpipi** [CreeperHost/CreeperHostGui#357]
**Minecraft Username:** Sossololpipi

**Ban ID:** unable to find in menu chat where it should be for unknown reason.

**What was the reason for your ban?** autobanned by typing "it was never known what he crapped about" in response to someone saying "crap", me sending an interrogation mark as i wanted to know what caused them to say that first message and the person who said "crap" responding with "nvm".

https://cdn.discordapp.com/attachments/166630061217153024/763945203488391199/unknown.png for proof

as an aftermath of the ban, i repeatedly get "username already in use" as an error message in the MT chat

**Why you think you should be unbanned:** i don't think there was anything wrong with that message. if there was, i'd like to know what.

**What steps will you take to make sure this doesn't happen in the future:** hope that the autobanning system doesn't break yet again.

to note : i was banned in the past, and told i couldn't be unbanned from mispelling something again.

**Comment by Draylynn** [comment]
A) Are you on the updated version?
B) Ban appeals are now handled via MineTogether.io
C) "Crapped" is vulgar slang, avoid any vulgar or offensive language in chat.

**Comment by sossololpipi** [comment]
oh, then it's unlikely i'll ever get unbanned, due to that site's verification being bugged for me. thanks.
