### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by KingDan27** [CreeperHost/CreeperHostGui#36]
here is now a config option to set gdpr to true for servers to be listed however my curl command i was Tsending to update for my bungee server no longer works i tried adding "gdpr": true to it but that doesnt seem to have worked and i dont see any documention in the api for the new GDPR option.

**Comment by Cloudhunter** [comment]
We haven't changed anything in the API with regards to GDPR - not sure where you are seeing this!

**Comment by KingDan27** [comment]
Any reason why my curl command stopped working when minetogther added the update that added the GDRP acceptance then?

**Comment by KingDan27** [comment]
My script is as follows 

curl -X PUT -H "Content-Type: application/json" -d '{"name": "Ardent Gaming",  "port": 25565, "ip": "play.ardentgaming.ca", "projectid": 304542}' https://api.creeper.host/minetogether/update

Executed every 3 min.

**Comment by Cloudhunter** [comment]
What is the return from those calls? I note you are not storing the secret anywhere?

**Comment by KingDan27** [comment]
This is the return 
{"status":"success","message":"Server information updated.","id":21841,"endPoint":"newyork-api","requestTime":0.98632287979125977} 

As for the secret I’m not sure what you mean I’ve never had that and not sure what that is and it worked on the continuum pack and then just stopped.

**Comment by KingDan27** [comment]
Looking at the other issue tickets this might actually be the problem #38 . Might actually be working but cant tell because the server lists aren’t loading in the client?

**Comment by Cloudhunter** [comment]
Yeah that's the most likely reason. I'll close this for now - can re-open when our fix is in place if it still isn't working for you.
