### ISSUE TITLE
MineTogether.io Gives Server Error 500 When Logging In

### ISSUE THREAD

**Issue by DoobliheimGH** [CreeperHost/CreeperHostGui#360]
**Describe the bug**
Attempting to log in with an email and password, the MineTogether.io website gives a server error when loading the post-login page. I've tried with Edge, Chrome, and Firefox (all with the cache disabled) and it still gives the same results. Screenshot_1.png shows the page I'm using to log in, and screenshot_2.png shows the network inspector and the GET response

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://minetogether.io/
2. Click "Login"
3. Enter username and password. Click "Log In"
4. Receive "Error 500 Response"

**Expected behaviour**
Account page should load

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/72723523/95706948-13ba0b80-0c0d-11eb-908c-4a3db7e09d72.png)
![Screenshot_2](https://user-images.githubusercontent.com/72723523/95706958-174d9280-0c0d-11eb-922e-209bc40bade4.png)

**Additional context**
The same issue seems to occur when using any of the alternate sign-in methods like Discord and Google. The issue seems to effect some people but not others. CreeperHost staff member said it looks like an API issue

**Comment by ThePaul-T** [comment]
Thanks for the report, taken a quick look and just, if you ever see someone named "Stuart_P" or "Rushmead" on our platform, say the word "Encloding" to him. He will understand.

Should be fixed now :) Please assist us in making him suffer for your issues.
