### ISSUE TITLE
question / issue (?) about global chat

### ISSUE THREAD

**Issue by wynfirdolf** [CreeperHost/CreeperHostGui#361]
i have downloaded the new version(2.3.6) for 1.12.2 from curseforge.com. and i cant find the global chat option anymore. i would like to get help about that.

**Comment by gigabit101** [comment]
We will need logs in order to help you with this, I will leave a link below on how to do this https://wiki.creeper.host/books/minecraft-java-edition/page/retrieving-modpack-logs-from-twitch

**Comment by wynfirdolf** [comment]
https://pste.ch/pocovogopi.md there you go i hope this helps

**Comment by ThePaul-T** [comment]
Line 907; [19:55:22] [Client thread/ERROR] [minetogether]: Client is in offline mode

We can't generate a MineTogether name without a UUID, and you don't have a UUID without a Mojang/Minecraft account.

**Comment by wynfirdolf** [comment]
yeah im using a cracked client (unfortunately) but i was able to use it before the new version

**Comment by ThePaul-T** [comment]
We recently had to lock everything (server authoritative) due to people abusing cracked clients to bypass bans, so now no cracked clients can use MineTogether, even on previous versions.

Sorry, one bad egg ruins it for everyone :( We left it hoping nobody would abuse it so we could include everyone.

**Comment by wynfirdolf** [comment]
That is so sad to hear. 😢 Do you have plans in the future to fix the "abuse" without making the global chat for online mode only?

**Comment by ThePaul-T** [comment]
Unfortunately, no, the whole system relies on Mojang UUID's, we knew this day would come and had already planned for it three years ago (Hence why it took us < 24h to implement), we just hoped nobody would abuse it.

**Comment by wynfirdolf** [comment]
well that is even sadder 😭  but i still hope that you guys can find a better way to implement the protection 
until then i have to play in complete silence 🤫 😞 
anyways thanks a lot for the answers
