### ISSUE TITLE
[Bug] Add Friend Bug

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/CreeperHostGui#363]
**Describe the bug**
When trying to add a friend the game crashes!

**Minecraft Version**
- 1.16.3

**Forge Version**
- 34.1.22

**Mod Version**
- 1.16.2-4.1.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Friends list
2. Click on Add friend
3. Input Friends Details
4. Click on Add friend

**Expected behaviour**
For it it send a friend requst!

**Crash Reports**
https://pastebin.com/MB5kiqNt - MC CrashReport File
https://pastebin.com/k7fzauAg - latest.log

**Comment by gigabit101** [comment]
Fixed in the latest release
