### ISSUE TITLE
Mouse Click Event

### ISSUE THREAD

**Issue by DinnerBeef** [CreeperHost/CreeperHostGui#364]
**Describe the bug**
Crashed When Clicked inside the MT chat. No idea where

**To Reproduce**
Steps to reproduce the behaviour:
Click inside the MT chat somewhere 

**Expected behaviour**
Not crashing

**Screenshots**
https://pastebin.com/afm6npr1

**Versions**
MineTogether-1.16.2-4.1.1.jar

Minecraft:
1.12.2
Forge:

MineTogether:

**Additional context**

**Comment by gigabit101** [comment]
Not sure what caused this but should be fixed in the latest build.
