### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by supermonkey654** [CreeperHost/CreeperHostGui#366]
**Minecraft Username:** 
supermonkey654

**Ban ID:**
Unknown
"Account in good standing"
Unable to join chat due to nick in use

**What was the reason for your ban?** 
"You have been banned due to suspected inappropriate language"

**Why you think you should be unbanned:**
I did not realize that this action would result in a ban. I saw someone in chat say the same word and was only muted for 5 minutes, it wasn't really fair to be banned for this when someone else only got muted. 

**What steps will you take to make sure this doesn't happen in the future:**
Not use swear words. Try to find out what words count as a "swear".

**Comment by gigabit101** [comment]
If you appeal at https://minetogether.io we can see the chat message which got you banned etc and then work from there.

**Comment by supermonkey654** [comment]
How do I do that?  I don't see any option for an appeal.

**Comment by supermonkey654** [comment]
> If you appeal at https://minetogether.io we can see the chat message which got you banned etc and then work from there.

How do I do that, I don't see any option for a ban appeal. I am assuming it would be under account standing but it does not for me.
![Screenshot](https://user-images.githubusercontent.com/5412330/96915425-73ad7f00-1463-11eb-9260-896818a6f28c.png)
