### ISSUE TITLE
Mod Loading Yet Not

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/CreeperHostGui#367]
**Describe the bug**
It Looks like the mod loads yet nothing shows up like friends list or chat

**To Reproduce**
Open MC

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/3998288/96636510-4bb00580-1315-11eb-88fa-f0e0c1bd5119.png)
![image](https://user-images.githubusercontent.com/3998288/96636582-65e9e380-1315-11eb-8c33-1a619750bdbc.png)

** Them Logs **
Latest Log - https://pastebin.com/iamvD4AX
Debug Log - https://pastebin.com/HMzjmLuk

**Versions**
Please give all the versions you are using:

Minecraft: 
- 1.16.3

Forge:
- 34.1.23

MineTogether:
- 4.1.2

**Additional context**

**Comment by ThePaul-T** [comment]
No logs.

Chances are if you check them it'll say you failed to verify against mojang session servers.

**Comment by gigabit101** [comment]
Still gonna need the latest.log

**Comment by manmaed** [comment]
Pastebin Updated

**Comment by manmaed** [comment]
Added a Debug Log

**Comment by gigabit101** [comment]
Looking at the log it does indeed seem like your failing to auth with Mojangs servers, Unfotantally there is nothing we can do about this since people started to abuse the mod to get around bans
