### ISSUE TITLE
Can see chat, but can't send messages (like I've been muted)

### ISSUE THREAD

**Issue by DoobliheimGH** [CreeperHost/CreeperHostGui#368]
**Describe the bug**
Last night I got muted for saying the word "boomer" and "zoomer" (10/10 chat filtering), and today when I got on none of my messages are actually sending in chat. I can see the chat and everyone else's messages, and I can send messages that appear for me, but my messages don't appear in #in-game on Discord, and no one else can see them. MineTogether.io shows my username as User#396DD, but my in-game name is VoidJarStabilizer (MC name is Doobliheim)

**To Reproduce**
I honestly have no idea short of muting someone and then having them log off for the night? It might not even be the cause of the issue

**Expected behaviour**
My messages should send, be seen in #in-game, and seen in everyone else's chat

**Versions**
Minecraft: 1.12.2

Forge: forge-1.12.2-14.23.5.2846

MineTogether: MineTogether-1.12.2-2.3.6

**Additional context**
I was muted the night before and logged off before the mute timer expired, and the issue started the next day (this morning)

**Comment by gigabit101** [comment]
Has this issue been resolved in the latest bot update? For the last few days, there have been some issues with voicing users causing people not to be able to talk.

**Comment by DoobliheimGH** [comment]
Yeah, the most recent update to the chat bot seems to have fixed the issue. Thanks!
