### ISSUE TITLE
Troubles with the sending messages in chat.

### ISSUE THREAD

**Issue by NoName161** [CreeperHost/CreeperHostGui#370]
I am running FTB Omnia throught the FTBapp and have had no problems in the past connecting to Mine Together, about a week ago all my messages appeared not to go through. I tried to check the website and I could not find anything about it. It says my account is not banned or anything like that. I was just curious if anyone else was having the same problems.

**Comment by gigabit101** [comment]
Can I ask what version of the mod you are using?
Can you also provide us with the latest.log from your client?

**Comment by NoName161** [comment]
I am running FTB Omnia version 1.7.0, which is for Minecraft 1.15.2
[latest.log](https://github.com/CreeperHost/MineTogether/files/5424081/latest.log)
@gigabit101

**Comment by gigabit101** [comment]
MineTogether is not in this log file, Can you update the version of MineTogether to the latest?
https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/3089674

**Comment by NoName161** [comment]
I attempted to do so, but not Omnia refuses to launch at all, prompting an error with the newer version of MineTogether. The latest log is below.
[latest.log.log](https://github.com/CreeperHost/MineTogether/files/5431664/latest.log.log)
@gigabit101

**Comment by gigabit101** [comment]
Fixed in latest release https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/3091493
