### ISSUE TITLE
Crash due to mouseClick event handler

### ISSUE THREAD

**Issue by Gaz492** [CreeperHost/CreeperHostGui#371]
**Describe the bug**
It crashed after clicking on one of the tabs

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Chat
2. Click on one of the tabs
3. Game crashed

**Expected behaviour**
Game to not crash

**Screenshots**
N/A

**Versions**
1.16.3-4.1.3

Minecraft:
1.16.3

Forge:
34.1.23

MineTogether:
1.16.3-4.1.3

**Additional context**
Heres a crash report https://pste.ch/ibijicarez.pl

**Comment by Rushmead** [comment]
I also got this crash when I clicked on a message in the main menu chat screen

https://pste.ch/uyucuvamew.rb

**Comment by gigabit101** [comment]
sigh... I found it

**Comment by gigabit101** [comment]
fixed in the latest release
