### ISSUE TITLE
Headcrumbs Integration?

### ISSUE THREAD

**Issue by Rynslet** [CreeperHost/CreeperHostGui#373]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
If someone has Mine Together and Headcrumbs installed, it should throw people you know into the headcrumbs pool.

**Describe alternatives you've considered**
I don't know any other headcrumbs-style mods.

**Additional context**
Original Post:

Hi, I've just discovered the chat function on the MineTogether mod. I think it'd be neat if this mod worked in conjunction with HeadCrumbs, and users you were chatting with came to hunt you down. Maybe even named like "User#xxxxx" or whatever, so you know who it was. Obviously with their actual minecraft skin if it's available. Just a suggestion.

**Comment by moon-st0ne** [comment]
yo @Rynslet this doesn't follow the feature request template so it will probably be discarded and you'll have to resend; also add me on discord at #7777 because minetogether quit working all of the sudden

**Comment by gigabit101** [comment]
The mod is only required on the client-side so summoning a mob with a custom name like headcrumbs will not be possible at this time.
