### ISSUE TITLE
auto banned for saying "grape"?

### ISSUE THREAD

**Issue by moon-st0ne** [CreeperHost/CreeperHostGui#374]
**Minecraft Username:** 
JDLENL

**Ban ID:**
minetogether.io says my account is in good standing in public chat, yet it won't let me connect. my minetogether chat is constantly blank, and the fullscreen chat says _Cannot send messages as not connected_ and shows a yellow circle and connecting forever.

**What was the reason for your ban?** 
i think i said the word "grape" which contains a banned word, in the context of "GrapeGrapeJuice" as a valid minetogether chat name, and the automoderator detected the banned word and shadowbanned me.

**Why you think you should be unbanned:**
just because grape contains a banned word doesn't mean "grape" is a banned word. get a better chat filter.

**What steps will you take to make sure this doesn't happen in the future:**
not talk about grapes or minetogether usernames which contain the word "grape".

**Comment by Rynslet** [comment]
You said "GrapeGrapeJuice" then another line, which I didn't see, then all of your messages were deleted. So I think it was after that. but idk.

**Comment by Draylynn** [comment]
Appeal here: http://minetogether.io/
