### ISSUE TITLE
I was banned by a sensitive automoderator without it taking context into account. Now I know better.

### ISSUE THREAD

**Issue by Thecman50** [CreeperHost/CreeperHostGui#375]
**Minecraft Username:** 
I_am_Offline/thecman50 (I'm not sure which will show)
**Ban ID:**
I_am_Offline
**What was the reason for your ban?** 
Upon looking at other posts I think I may have figured it out. Someone in chat typed "gay". I responded with "Woah" followed by "gay isn't an insult" and was subsequently banned.

**Why you think you should be unbanned:**
Context matters. I think I tripped the automod because the word "gay" was typed; even though I was questioning and correcting someone's offensive use of the word.

**What steps will you take to make sure this doesn't happen in the future:**
I wasn't aware there was even an automod; I'm glad there is, but it's a bit trigger sensitive. 

Avoid words that trip the automod.

**Comment by Draylynn** [comment]
Appeal here: http://minetogether.io/
