### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by ArttyKun** [CreeperHost/CreeperHostGui#376]
**Minecraft Username:** 
Artty_Kun
**Ban ID:**
mtg-ban=5f96c7db4ea3f3.08476604
**What was the reason for your ban?** 
spam

**Why you think you should be unbanned:**
I think I was banned only for sending several messaged when I spoke. I had to do this to prevent my game from crashing as if the text reached the end of my screen in the MineTogether tab, it would crash minecraft. If the ban reason was for the emotes, they were relevant to the conversation we were having, and I would only send a few at a time in the same line as to not bog down chat

**What steps will you take to make sure this doesn't happen in the future:**
I'll be more careful with the emotes and try to keep what I want to say short so that I don't have to send several messages

**Comment by ThePaul-T** [comment]
Hi there, does your ban show at minetogether.io? It's a lot easier for us to track it and the reason.

You shouldn't get banned for spam unless you send more than 1 message a second consistently for 3 seconds. (New maths so likely to be tweaked over time)

**Comment by ArttyKun** [comment]
unfortunately, I got banned as/after my game crashed, so I could not see the messages. though with my type speed, that could have been the case?

**Comment by Shockflare** [comment]
I dont know why I got banned. I literally asked if there was any use for the seismic vibration machine in the mekanism mod and then my it deleted my comment and crashed my game.

**Comment by ThePaul-T** [comment]
Did you manage to submit your request on the website so we can find it easily?

**Comment by Shockflare** [comment]
> Did you manage to submit your request on the website so we can find it easily?

How do I do that? The in-game thing brought me here.

**Comment by ArttyKun** [comment]
I have been trying to, but for several days now, it will not let me connect my account to the website.
Sorry for not responding sooner

**Comment by ThePaul-T** [comment]
There's no flooding bans left active, so you shouldn't be banned for that if you're sure about that.

@Rushmead can help with the website stuff not working usually.

**Comment by ArttyKun** [comment]
I was just able to connect my account to the website and have submitted the appeal on there.
