### ISSUE TITLE
Group Chats Non-Functional

### ISSUE THREAD

**Issue by moon-st0ne** [CreeperHost/CreeperHostGui#378]
**Describe the bug**
Group chats are non-functional. Creating one yields a chat tab that cannot be accessed before it instantly closes. According to @ThePaul-T there are no groups created anywhere in the backend database, suggesting the feature is completely broken.

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to create a group chat with someone
2. Observe Group Chat tab appear in chat
3. Click on tab and be instantly returned to Global chat
4. Group Chat tab eventually vanishes completely

**Expected behaviour**
A group chat tab should be created

**Screenshots**

**Versions**
Please give all the versions you are using:

Minecraft: 1.12.2, FTB: University

Forge: Latest 1.12.2 or whatever FTB:Uni uses

MineTogether: Latest

**Additional context**
Reported by multiple people, ticket requested by Paul.

**Comment by ThePaul-T** [comment]
Not been able to reproduce this, we've tried a few times, unsure why.

**Comment by gigabit101** [comment]
Closed due to inactivity. Feel free to reopen with more information on the issue
