### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by Defaultyboioi** [CreeperHost/CreeperHostGui#379]
**Minecraft Username:** 
Default_G0D135

**Ban ID:**

**What was the reason for your ban?** 
I made a typo and replaced b with n in "big a deal"

**Why you think you should be unbanned:**
It was an accident and i wont do it again

**What steps will you take to make sure this doesn't happen in the future:**
Be careful when typing

**Comment by Draylynn** [comment]
Ban appeals are handled via MineTogether.io: Also, the user to quote this, is not banned (as mentioned on Discord).
Submit new issue with actual problem: You can't connect because X error.
