### ISSUE TITLE
Can't load public server list

### ISSUE THREAD

**Issue by zwamdurkel** [CreeperHost/CreeperHostGui#38]
I'm getting this error on my client: https://hastebin.com/qobanehayi.md

Forge: 1.12.2 - 2765
Using version: minetogether-1.10.2-2.1.3 (latest)
Pack: FTB Sky Adventures

I'd like to know if this is a problem with the mod or with my installation and if the latter, how to fix it

**Comment by Cloudhunter** [comment]
Ah. We switched to Let's Encrypt recently for our API endpoints. It appears this is causing issues.

Are you using the Java or the Native launcher?

**Comment by Cloudhunter** [comment]
We're going to be fixing this soon by buying a certificate, and in the future the mod will require LetsEncryptCraft - a small mod I made to allow LetsEncrypt secured sites to work.

We were under the impression that Mojang had updated the Java they use to a little higher than they have - sadly not.

**Comment by Cloudhunter** [comment]
We have a shiny new non Lets Encrypt certificate, and it should now be working for you. Let me know, @zwamdurkel and @KingDan27!

**Comment by KingDan27** [comment]
Yes this is working now thank you!
