### ISSUE TITLE
I would like to be unbanned because i have been banned but i didnt curse

### ISSUE THREAD

**Issue by NayzC** [CreeperHost/CreeperHostGui#380]
**Minecraft Username: NayzBlox

**Ban ID: 5f9a93ef0ca437.89749866

**What was the reason for your ban?
 it says that I was banned because I cursed but I did not curse 

**Why you think you should be unbanned: I think that I did not curse/swear because I have been using English                                 (unless if it is a language I do not know)

**What steps will you take to make sure this doesn't happen in the future: I will try to understand if something is a curse word

proof that I am banned:
![image](https://user-images.githubusercontent.com/73645290/97563778-1f337200-1a16-11eb-8502-f2d6cf12ed78.png)

**Comment by Draylynn** [comment]
Also, you said "Dik"... Now unless you're talking about the long-snouted genus of small antelopes in eastern and southern Africa, or a popular British pudding... Which you were not... You wrote an expletive in chat and you were immediately bot-banned for it.

Side note: Whilst you were also typing English, it was extremely poor and borderline incoherent. Make sure you're future typing is clear to avoid being bot banned.

I do like how you didn't include a complete screenshot, also showing the line that got you banned.
Ban Appeals are handled over MineTogether.io, go to that website, login, and appeal via your profile.
