### ISSUE TITLE
Issue with getting onto the discord

### ISSUE THREAD

**Issue by Samakira** [CreeperHost/CreeperHostGui#381]
hi, recently joined minetogether, ign is icewatertrap, or User#6A0A7.
it said i had 3 steps to get onto the discord, which were, link my discord account (while logged in on browser), link minecraft account, and react with lock and key.
i did all of those (and double checked that the discord tag was me, yep, Samakira#3435), and it still doesnt let me see the other discord tabs aside from rules and info, announcements, roles, and link help.
i checked both link help and info, as well as roles, but nowhere does it say anything that i have done wrong.

**Comment by gigabit101** [comment]
The bot has been updated and some changes have been made, Can you attempt this again?

**Comment by Bookrage001** [comment]
On the roles tab i didn't get any of the channels until i clicked on the unlock button attached to the message.
