### ISSUE TITLE
Cannot enable chat

### ISSUE THREAD

**Issue by AliiiiK** [CreeperHost/CreeperHostGui#382]
**Describe the bug**
i disabled the chat using the settings menu at esc screen and now the i cannot acces to settings menu it doesnt show up on esc (i still can see friends list)

**Expected behaviour**
i expected to see the settings menu or even acces to mod config trough mod list

**Versions**

Minecraft:1.12.2

Forge: 14.23.5.2847

MineTogether:2.3.9

**Comment by ThePaul-T** [comment]
Multiplayer -> Chat icon in top right -> settings cog
