### ISSUE TITLE
University not showing up in public server list despite being set to discoverability=public

### ISSUE THREAD

**Issue by crossfirearena** [CreeperHost/CreeperHostGui#383]
**Describe the bug**
Exactly as the tile says

**To Reproduce**
Steps to reproduce the behaviour:

1. Set this in server.properies
2. Restarted server 10's of times
3. Still does not show up

**Expected behaviour**
I would expect the server to show up in the community server list.

**Screenshots**
Seems pretty self-explanatory, can go into more detail if needed. 

**Versions**
Please give all the versions you are using:

Minecraft:
1.12.2
Forge:
1.12.2-14.23.5.2847
MineTogether:
1.12.2-9.8.3.390

**Additional context**
Aaronhowser1 specifically told me to post about this on here.

**Comment by crossfirearena** [comment]
Any updates on this?

**Comment by gigabit101** [comment]
The server needs to be provided with the CurseForge ID of the modpack in the config file or the ModPack needs to be insalled using the ServerPackInstaller we provide as the server will need our version.json file to grab the packID from.

**Comment by crossfirearena** [comment]
Where is the server pack installer located at?

**Comment by gigabit101** [comment]
via the FTBApp

**Comment by crossfirearena** [comment]
> via the FTBApp

Oh, This is how I install servers. I download the server install file fromt he FTB app and install it to a folder. So I am doing that properly.
