### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by jorgeUll** [CreeperHost/CreeperHostGui#386]
**Minecraft Username:** 
JorgeUll
**Ban ID:**
don't know, didn't get a code, just got my messages deleted and chat stopped working

**What was the reason for your ban?** 
don't perfectly know, probably the filter picked up something i said as rude(?)/profanity, don't remember exactly what it was but it wasn't in bad faith, we were talking about automating crops.

**Why you think you should be unbanned:**
i didn't try to use rude language or try to insult anyone for that matter, i didn't think what i wrote could be taken as profanity, i really love the chat when i'm playing by myself, it's a great addition and makes modpacks a lot more enjoyable, i loved having it when playing and would hate to lose it.

**What steps will you take to make sure this doesn't happen in the future:**
i'll do my best to be more mindful of what i write, i'll make sure to never use words that could be taken the wrong way and take care to be as clear as possible when chatting so that i can keep chatting with other players.

**Comment by Draylynn** [comment]
MineTogether.io > Submit appeal there.
