### ISSUE TITLE
Ban Appeal.

### ISSUE THREAD

**Issue by BIllyxdxd** [CreeperHost/CreeperHostGui#387]
**Minecraft Username:** 

BenShapiro999

**Ban ID:**

No clue. My message just got deleted and then chat stopped working.

**What was the reason for your ban?** 

I assume because I said quote: "Why don't you say some racist shit and find out" responding to someone who asked if you could get banned in chat, with "shit" being the profanity in question.

**Why you think you should be unbanned:**

Because I'm a very good boy and will **not** swear again.

**What steps will you take to make sure this doesn't happen in the future:**

Not swear.

**Comment by Draylynn** [comment]
Login to MineTogether.io to submit an appeal.
