### ISSUE TITLE
I was stupid and would like to be unbanned? apparently

### ISSUE THREAD

**Issue by Srslyhamerd** [CreeperHost/CreeperHostGui#388]
Srslyhamerd(IGN) BedrockBanana in minetogether

not sure

again, not sure, was explaining how to claim/ load chunks, maybe i typo'd something but i cant even see my own message to know

if i am right, then dray reads these and knows i'm on the level, follow the rules, help people when i can

shouldn't need to be any other than maybe better spell checking if that was the issue. i certainly haven't slurred anyone, or broken any of the rules knowingly

edit: ![Screenshot 2020-11-07 055120](https://user-images.githubusercontent.com/55206270/98439098-4f85ab00-20bd-11eb-961c-a3ade893c906.png)

the deleted message at the bottom was supposed to be- open inventory>click map icon top left> click to claim a chunk, shift click to load that chunk, then a mention. I am betting i forgot the f in shift

**Comment by Srslyhamerd** [comment]
account status on minetogether.io updated, i was right, missed the f in shift.

![Screenshot 2020-11-07 062749](https://user-images.githubusercontent.com/55206270/98439813-68dd2600-20c2-11eb-8e8d-d88adc36cd4e.png)

**Comment by Draylynn** [comment]
Lol... That typographical error! I got'chu BedrockBanana. Careful with the typo's.
