### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by DarkflowNZ** [CreeperHost/CreeperHostGui#389]
Caught an auto ban for saying turd I think. At least I assume that's what happened, ban was instant. If you're able and/or willing to undo that, that'd be cool. Regardless, my apologies. My in-game name is DarkflowNZ, my minetogether id is #e1333 as far as I can tell. I believe the sentence that was the issue was "Please, the English language is the lingual equivalent of a turd thrown out a window anyway" which was not aimed at someone or otherwise, in my eyes, harmful. Thanks for your time

**Comment by Srslyhamerd** [comment]
Dray (chat mod) said as much in chat right after, and said she un banned you at that time, so might just take a while to refresh
