### ISSUE TITLE
. 

### ISSUE THREAD

**Issue by megxde** [CreeperHost/CreeperHostGui#392]
.

**Comment by Draylynn** [comment]
Visit MineTogether.io, link your account and submit an appeal there.
Ban appeals are not handled over our GitHub anymore.

NOTE: Try another Minecraft version (modded or Vanilla) to link with the auth server you connect to in-game.

**Comment by megxde** [comment]
> Visit MineTogether.io, link your account and submit an appeal there.
> Ban appeals are not handled over our GitHub anymore.
> 
> NOTE: Try another Minecraft version (modded or Vanilla) to link with the auth server you connect to in-game.

I'm not playing with a premium account, so I can't connect to some servers (including the auth server I guess) so it's impossible for me to link minecraft with the minetogether.io account, can you not help from over here by any chance?

**Comment by ThePaul-T** [comment]
Only premium accounts can connect or use MineTogether now due to a third party abusing offline mode accounts to bypass bans.
