### ISSUE TITLE
I was stupid and would like to be unbanned

### ISSUE THREAD

**Issue by robster2411** [CreeperHost/CreeperHostGui#394]
**Minecraft Username:** 
robster2411
**Ban ID:**
where can i find this?
**What was the reason for your ban?** 
I said: "I'm just hunting exploding bats cause the made me pissed." not knowing "pissed" is an offensive word.

**Why you think you should be unbanned:**
Cause i didn't knew pissed could be seen as a bad word in this sentens, and i'll be really carefull not to make such a mistake agian cause i really miss the chat.

**What steps will you take to make sure this doesn't happen in the future:**
i'll think twice about my words and not make such a stupid mistake again.

**Comment by Draylynn** [comment]
Why aren't you appealing on MineTogether.io ?
