### ISSUE TITLE
MineTogether.IO - Username Selection Quality Of Life Feature Request

### ISSUE THREAD

**Issue by Guswut** [CreeperHost/CreeperHostGui#397]
Howdy,

When selecting a customish username on https://minetogether.io/profile/edit , you are give two dropdowns with a list of over 1,600 choices each. Both of these lists appear to be pulled from a global list of MineCraft items/blocks. This appears to be something put into place to tide over things during the early days of this part of MineTogether, however:

The issue is that neither list is alphabetical, and both lists appear to have duplicate entries (for reference, here is the currently list in alphabetical order with columns for the position they're in the list: https://docs.google.com/spreadsheets/d/1ECoGHxNZarT-nPyjnVZzZIPFvZD8rLQNj8WtiodtMjY/).

The solution would be running a quick deduplication, and alphabetizing them.

I've done this, and you can grab it here: https://docs.google.com/spreadsheets/d/1URgT1WpV2MqpFj12z-3Mas2iBVk_GNmQo7whP-PstFw/

Additionally, you may want to merge both lists because there are some duplicates between the lists but not all of them are duplicate weirdly enough, and if so this is the merged and de-duped list: https://docs.google.com/spreadsheets/d/1IlLYF_MG_1w0MaxDLLAuDWsht9PZ1g5PwMyuqKxysAw/

I'd suggest the latter because that should simplify it a bit, and make it so people can have whatever they want as a "first" and "last" name, although it could end up with some really obnoxious combos like "AluminumAxeAluminumAxe" (although that is currently already possible because both lists have duplicates).

Hopefully this GitHub is the right place for feature requests for the website itself.

Thank you!

**Comment by Bookrage001** [comment]
Also a search box would be nice

**Comment by Novocastrian** [comment]
Also, I recommend removing the requirement for firstname and lastname. Many people (like myself) don't want to provide real names with applications that have no reason to use them. Username is a unique identifier as far as I can see, so there's no need to require additional personal information. Workaround is to submit dummy names, but not ideal. Feels invasive when I saw it was a required field :(

**Comment by gigabit101** [comment]
The website has been updated and search boxes have been added
