### ISSUE TITLE
Discord Roles/Acces

### ISSUE THREAD

**Issue by kiwa30** [CreeperHost/CreeperHostGui#399]
Hey, Yesterday  i linked my accounts and responded to message in "Roles". I still have no access to channels nor a role.

I first created MineTogether account,
then linked it with discord, joined the Discord server, linked minecraft account and finally responded to message in "Roles"

Minecraft:
1.12.2
Forge:
8.00.99.99
MineTogether:
2.3.6
StoneBlock2:
1.21.1

Thank you for response in advance.

**Comment by gigabit101** [comment]
Is this issue still persiting?

**Comment by kiwa30** [comment]
It's alright now, few days ago reactions to the post in "Roles" on Discord got reseted and after i reacted to it, bot automatically assigned me role. Thank you for your respond.
