### ISSUE TITLE
[1.12.2, Compatibility] RPG-Hud

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#40]
_Note: Report taken from MineTogether chat_
Forge: 1.12.2 (14.23.5.2775)
MineTogether: 1.10.2-2.13
RPG-Hud: 3.6.6.2

Client crash with RPG-Hud and MineTogether (Fix: Disable RPG-HUD or MineTogether).

Updating screen events: Caused by:
java.lang.ClassCastException: net.spellcraftgaming.lib.gui.override.GuiChatRPGHud cannot be cast to net.creeperhost.minetogether.gui.chat.ingame.GuiNewChatOurs

**Comment by gigabit101** [comment]
This was fixed in the last release
