### ISSUE TITLE
(Ban Appeal) Suddenly banned for an unknown reason. 

### ISSUE THREAD

**Issue by MarchoBlue** [CreeperHost/CreeperHostGui#400]
It appears that I have been banned from MineTogether for several hours. I did not notice that I have been banned until I wanted to ask the community for some thaumcraft advice. I do not recall typing anything that has breached the MineTogether rules.

Username: Marcho_Blue

**Comment by manmaed** [comment]
Visit MineTogether.io, link your account and submit an appeal there.
Ban appeals are not handled over our GitHub anymore.

**Comment by MarchoBlue** [comment]
> Visit MineTogether.io, link your account and submit an appeal there.
> Ban appeals are not handled over our GitHub anymore.

Thank you for the clarification
