### ISSUE TITLE
A Better Way To See What Modpack Other Users Are Using

### ISSUE THREAD

**Issue by Guswut** [CreeperHost/CreeperHostGui#401]
Seeing what modpacks other users can often be hit or miss. Sometimes the friend colour overrides it (although we've discussed changing that), other times different versions make it not show, and I'm pretty sure that there might be a bit of haunted Kitteh-ness involved in some cases, too.

I can think of a few solutions (such as prefix tags, additional colour tagging, etc), but perhaps the simplest and least-intrusive way would be to add it to the context menu when clicking a user's username. Have it say something like "Modpack" and ideally have it listed right there (example: "Modpack: FTB Presents Stoneblock 2").

If need be have it so you can click the "Modpack" button to see the modpack in another window (outside of the range of this feature request, but if you want I can likely help brainstorm this better, such as linking to the modpack, creator's website/patron/discord, look up the list of mods and highlight mods that aren't in your current pack or mods that are in your current pack but not this one, etc).
You could also have a prefix for every user that uses a lookup database to put a quick tag for the pack (example: "SB2" for StoneBlock2, "Rev" for Revelations, "Ult" for "Ultimate"), however I think this would be more work than it is worth.

Not high priority at all, but it'd be nice to be able to see what pack a person is playing without having to ask (especially when trying to help someone that wants to know what armour is the best, or the like, etc).

Thank you!

**Comment by ThePaul-T** [comment]
Was a design choice not to show the actual modpack to encourage conversations about them. Too much hand holding (Like LFG in MMO's) can ruin the community interactions.
________________________________

**Comment by Guswut** [comment]
Oh, that is a point I hadn't even considered at all! Yeah, that makes perfect sense to me, so I'm closing this ticket out. Thank you!
