### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by kitghost** [CreeperHost/CreeperHostGui#403]
Connecting forever, could be my fault as i recently added a new mod (im on ftb revelations) however its not the kind of mod that should conflict i dont think?
(its glibys voice chat)
Website also seems messed up so im wondering if you guys are just having downtime. If thats the case sorry to bother just wanted to be in the know.

**To Reproduce**
Just dropped the new mod into the mods folder and launched minecraft opened multiplayer it didnt work so tried singleplayer still just says connecting.

**Expected behaviour**
Usually it connects quickly and without problem, ive had it sitting open for like 15 minutes now.

**Screenshots**
![image](https://user-images.githubusercontent.com/29662520/99889642-6f1be800-2c14-11eb-9725-9bb376159970.png)

**Versions**
Please give all the versions you are using:

Minecraft:
1.12.2 (ftb revelations)
Forge:
Couldnt tell you but whatever ftb revelations uses for 1.12.2

MineTogether:
2.3.6
**Additional context**
also is it possible to get a link to the discord? or instructions how to find one, i looked everywhere but couldnt find one, i linked my account on the website already.

Also I apologise if im just being a goof and wasting your time here, regardless thanks!

**Comment by gigabit101** [comment]
You will need to update to the latest versions of the mod 2.4.0 is the latest, If the issue continues let us know

**Comment by kitghost** [comment]
> You will need to update to the latest versions of the mod 2.4.0 is the latest, If the issue continues let us know

Did update, works every so often but usually only for the first minute or two after freshly opening the game, still 90% of the time doesnt work. :( heard it was maybe because of all the new players and just server load?

**Comment by gigabit101** [comment]
If you are connecting, this means you are not banned and that the mod is working, This might once again be caused by server load, I assume you are located in the US?

**Comment by kitghost** [comment]
I didn't think I was banned I've not really said anything controversial since I like to be friendly.
I am located in Canada.

**Comment by kitghost** [comment]
Additionally, where does the game install, as of this morning I suddenly cant find it anywhere on my computer? 
My usual search for "ftb" doesnt seem to work.

**Comment by kitghost** [comment]
nvm on that last one my bad this isnt ftb
