### ISSUE TITLE
Ban appeal on minetogether.io bugged?

### ISSUE THREAD

**Issue by BIllyxdxd** [CreeperHost/CreeperHostGui#405]
I think the ban appeal section on the minetogether.io website is bugged out. I've submitted an appeal 3 times and have not gotten an answer to wether I will remain banned or get unbanned. I dont think me saying "shit" justified a permaban with no ability to get unbanned so therefor I assume its bugged out in some way.

**Comment by ThePaul-T** [comment]
Appeal decisions are not related, if you're not back, them you was denied, try again in 2 weeks.
________________________________
