### ISSUE TITLE
Unable to invite player to server

### ISSUE THREAD

**Issue by rtm516** [CreeperHost/CreeperHostGui#406]
**Describe the bug**
When I try to invite someone to my server I get this response
```
Response from add endpoint {"status":"error","message":"Invalid code signing fingerprint.","endPoint":"grantham4-api","requestTime":0.0005419254302978516}
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the server
2. Invite a player
3. Server responds with error and user isn't invited (I compiled my self, after having issues, to fully log the output)

**Expected behaviour**
Player gets invited

**Screenshots**
N/A

**Versions**
Please give all the versions you are using:

Minecraft:
1.12.2

Forge:
1.12.2-14.23.5.2846

MineTogether:
1.12.2-2.4.0
1.12.2-2.3.6

**Additional context**
I discovered this setting up a server for FTB Revelation
I also changed [this](https://github.com/CreeperHost/MineTogether/blob/1.12-release/src/main/java/net/creeperhost/minetogether/serverstuffs/CreeperHostServer.java#L272) line to the below as my server is NAT'd so the listen IP is not the public IP and this change allowed me to change it.
```java
serverIP = manager.getStringProperty("server-ip", "");
```

If you know how I can fix it, then I will likely modify 1.12.2-2.3.6 with the needed changes since that's the version in the pack and don't want to have to get people to update their clients.

**Comment by ThePaul-T** [comment]
Detection is done server-side for handling NAT (May need improved), server-ip (and port) is used as an identifier for if there are multiple behind NAT.

I will look into the other issue today or tomorrow.

**Comment by ThePaul-T** [comment]
Oh, just realised, if you recompiled the source then you'll need to build your own API around it.

We do not allow modified or third party versions of MineTogether to access our infrastructure as it has been used to bypass bans and other nefarious reasons.

**Comment by rtm516** [comment]
> Detection is done server-side for handling NAT (May need improved), server-ip (and port) is used as an identifier for if there are multiple behind NAT.

Does this rely on having a blank server IP in the server.properties? or is it fine with 0.0.0.0? I will revert to the version from curseforge and double check but I'm pretty sure that doesn't work either.

**Comment by rtm516** [comment]
As you can see in this screenshot, inviting myself to the server from console then trying to see it in the client under closed/invite only servers it doesn't appear.
![image](https://user-images.githubusercontent.com/5401186/100082034-9f939a00-2e3f-11eb-9e6c-0ddee3b67a90.png)

**Comment by ThePaul-T** [comment]
How long are you waiting? For load considerations there is a small redis cache on each API endpoint so the primary database is not constantly hit with traffic (There's around 5k req/sec to this endpoint to give you an idea), I'd need to check the source to know how long.

**Comment by ThePaul-T** [comment]
Note: We're working on a real-time solution for invites (Evidence is in 2.4, but it's far from finished)

**Comment by ThePaul-T** [comment]
Checked the source for the NAT detection, it'll use the request IP (from the callback) if the bind IP is 0.0.0.0, blank or any RFC1918 IP.

Invite cache is invalidated on receiving an invite, so it shouldn't actually be cache, so I'll investigate further once I am working on the mod again (probably tomorrow)

**Comment by rtm516** [comment]
Its been 6 mins now with no response. This is my current terminal output. If you need any logs let me know.
![image](https://user-images.githubusercontent.com/5401186/100082990-cb634f80-2e40-11eb-98fa-158f3ff748fe.png)

**Comment by ThePaul-T** [comment]
I can confirm it's registering your server and it is registered with an IP beginning with 81, whatever issue this is, seems to be client side, I'm going to try and find your invite.

I am wondering at the moment if, the code signing implementation has not been implemented server side, so the invite call server side is not working (But would work client side)

**Comment by rtm516** [comment]
I have noticed this in both the client and server log, with the version from curseforge ([here](https://media.forgecdn.net/files/3076/765/MineTogether-1.12.2-2.3.6.jar)).
```
[10:17:13] [Server thread/WARN] [minetogether]: Invalid fingerprint detected! The file MineTogether-1.12.2-2.3.6.jar may have been tampered with. This version will NOT be supported by the author!
```

**Comment by rtm516** [comment]
> I can confirm it's registering your server and it is registered with an IP beginning with 81, whatever issue this is, seems to be client side, I'm going to try and find your invite.

I do have a server running locally and on an external box, both start with that. The one I have remote (one I want working) ends with 211, NOT 122

I get an error trying to invite myself on my local version. Likely my networking setup at home.
EDIT: It was, got rid of the error message about invites on my local server but still no invite appearing clientside from either server)

**Comment by rtm516** [comment]
Wondering if you had chance to look at this? I presume not since you said that you would look into it today. I also don't plan on releasing the server for another 20 days or so.

If its more convenient contact me on discord: rtm516#2107

**Comment by rtm516** [comment]
Any update?

**Comment by rtm516** [comment]
Any update? @ThePaul-T
