### ISSUE TITLE
Text Not Being Removed From Banned People

### ISSUE THREAD

**Issue by Guswut** [CreeperHost/CreeperHostGui#408]
**Describe the bug**
I'm still seeing messages from people that are getting bonked leaving the text, unmodified and whatnot. This is occurring even during a non-first-message instance. The vulgarity that ended up getting them banned has been censored (just in case, for some reason, the community standards of MineTogether extend to the GitHub as well).

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to MineTogether's chat system.
2. Wait for someone to say something crude and be bonked.
3. See that their message has not shown up on Discord's #in-chat channel, however it is still being displayed in the game.

**Expected behaviour**
The message should be replaced with the garbled text that has occurred rarely before.

**Screenshots**
Attached:
https://i.imgur.com/ySM7cA5.png

**Versions**
Please give all the versions you are using:

Minecraft:
1.12.2

Forge:
14.23.5.2847

MineTogether:
2.4.0

**Additional context**
This is an instance of not a first-message, and it has been a while since I last saw someone get their message deleted or garbled (however I am fairly confident I have seen it with this build of MineTogether).

Thanks!

**Comment by gigabit101** [comment]
fixed in the latest build
