### ISSUE TITLE
[request] a friends chat tab

### ISSUE THREAD

**Issue by audenga** [CreeperHost/CreeperHostGui#41]
I think it would be a good idea if there was a 3rd or 4th tab with a friend or friend chatroom, for when across servers or testing something in single player or even when on the same server and don't have an easy way to talk to a friend or group of friends, or even have the global tab configurable to switch between a friend/friends and global chat

**Comment by CH-Paul-T** [comment]
Hello Audenga,

We have plans for private chat rooms (“party” chats) in the next major release already, I believe this will fulfil your needs 😊

Paul

**Comment by gigabit101** [comment]
Group chat has already been implemented, This can be closed
