### ISSUE TITLE
I cant find on website where I can appeal a ban from chat?

### ISSUE THREAD

**Issue by Tyze123** [CreeperHost/CreeperHostGui#410]
Sorry if this is wrong but my name is Siwoow_

I made a immature word "titty" and I think I got banned because I cant write anymore lol.

Thanks for reading

**Comment by gigabit101** [comment]
https://minetogether.io/

**Comment by Tyze123** [comment]
Yea but then what? Where am I suppose to go? There are no way to get out of the front page? I only see "login" and nothing in there too.

**Comment by Bookrage001** [comment]
try https://minetogether.io/profile/standing

**Comment by Tyze123** [comment]
> try https://minetogether.io/profile/standing

I get this when I try to connect my minecraft account:
SessionNotFound: invalid_request
    at Provider.getInteraction (/home/node/mtauth/node_modules/oidc-provider/lib/provider.js:54:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /home/node/mtauth/backend/routes.js:180:45

Can I just get unbanned here? :P The website is pretty slow :/

**Comment by Draylynn** [comment]
Was this the same 'titty' in reference to a Discord ID, that was very intentionally spaced apart?
Discord ID ending #7549?
