### ISSUE TITLE
can't connect to 'mc.auth.minetogether.io' in Minecraft client

### ISSUE THREAD

**Issue by peetsmeatball** [CreeperHost/CreeperHostGui#411]
I'm trying to link my MineTogether account to my Minecraft account. I go to "Direct Connection" in the multiplayer account on Minecraft and type in 'mc.auth.minetogether.io' (not with the apostrophes) but instead of giving me a code, I receive a "Failed to connect to the server: Disconnected" message. 

I would really appreciate any advice on what to do about this/ how to connect to MineTogether.

If this is the wrong place to direct these issues, please let me know (and if you know elsewhere to send me I would appreciate it).

***Also I know this shouldn't be classified as a bug, but I didn't know which other way to tag it. In case it's not obvious I don't know what I'm doing at all and I'll take any help I can get

![Screen Shot 2020-12-03 at 11 37 13 PM](https://user-images.githubusercontent.com/75464699/101122454-8ec1f180-35c0-11eb-9e7f-4c357e9bee76.png)

Minecraft: 16.4

**Comment by gigabit101** [comment]
Currently, you will need to use Minecraft 1.16.3 or below,

**Comment by peetsmeatball** [comment]
Thank you so much!!!
