### ISSUE TITLE
Error formatting line

### ISSUE THREAD

**Issue by JadestarXL** [CreeperHost/CreeperHostGui#412]
Shortly after joining the world, the chat began to be flooded with "Error formatting line." This continued until the world was exited.

I have not been able to reproduce this issue.

Minecraft: 1.12.2
Forge: 14.23.5.2854
MineTogether: 2.4.1

I have attached the relevant log file of the session, starting from when the MineTogether mod is first mentioned.
[MineTogetherErrorLog.txt](https://github.com/CreeperHost/MineTogether/files/5640904/MineTogetherErrorLog.txt)
I added the mod to the RAD modpack, a pack which the mod is not in by default.

**Comment by gigabit101** [comment]
fixed in the latest builds
