### ISSUE TITLE
Can't communicate with anyone?

### ISSUE THREAD

**Issue by Kaukau323** [CreeperHost/CreeperHostGui#415]
Playing on FTB Academy, tried using MineTogether to talk to people and i cant get a response, even from admins. whenever i click on the minetogether tab i insta-crash and whenever i try to get the link to post here it freezes for a minute or so and then says its failed to get the link. What do i do?

**Comment by ThePaul-T** [comment]
Please include the version of the mod and the logs.

**Comment by Kaukau323** [comment]
version of MT is 1.10.2-2.2.0-RC6. Unfortunately I can't get any logs. whenever i try to get the link it just freezes and says it can't copy it. Unless there's another way of getting logs I don't know about? I'm just trying to copy the link from the crash screen I'm getting ingame since the game doesn't fully shut down because of Vanillafix. If there's any other way of getting the logs you know about I'd be happy to try it, sorry :/

**Comment by gigabit101** [comment]
You will need to update MineTogether to the latest version, Currently, this is 1.12.2-2.4.1, You can download the new version here https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/3123897

**Comment by Kaukau323** [comment]
> You will need to update MineTogether to the latest version, Currently, this is 1.12.2-2.4.1, You can download the new version here https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/3123897

how do i implement this updated version to a MutliMC modpack? Sorry if that doesn't make sense im just still new to mods and i'm not sure if theres something special i need to do.
