### ISSUE TITLE
Refresh button crashes game

### ISSUE THREAD

**Issue by Naxanria** [CreeperHost/CreeperHostGui#416]
**Describe the bug**
When pressing the refresh button in the multiplayer screen the game crashes.

Crashlog: https://paste.feed-the-beast.com/view/c805deb2

This seems to be caused by not checking/forcing cast https://github.com/CreeperHost/MineTogether/blob/1.16.2/src/main/java/net/creeperhost/minetogether/events/ScreenEvents.java#L198 here.

Minecraft: 1.16.4
Forge: 31.1.11
MineTogether: 4.1.6RC2

**Comment by gigabit101** [comment]
Fixed in RC3
