### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Gjeaneman** [CreeperHost/CreeperHostGui#418]
It says connecting but it actually never connects, what could be the problem?

**Comment by slarktheslayer** [comment]
the same thing is happening to me

**Comment by gigabit101** [comment]
You will need to update MineTogether to the latest version, Currently, this is 1.12.2-2.4.1, You can download the new version here https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/3123897

**Comment by Gjeaneman** [comment]
> You will need to update MineTogether to the latest version, Currently, this is 1.12.2-2.4.1, You can download the new version here https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/3123897

I am using 2.4.1.

**Comment by gigabit101** [comment]
Have you linked your accounts to https://minetogether.io/ yet? It is possible that you are currently banned and that is why the connection is failing, You can appeal your bans at the same link.

**Comment by gigabit101** [comment]
Closed due to inactivity. Feel free to reopen with more information on the issue

**Comment by gameplays12303** [comment]
it says that the host is unknown
