### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by timtam476** [CreeperHost/CreeperHostGui#420]
I'm not gonna even lie, I accidently swore as a heat of the moment and got banned instantly. To be honest I understand and agree with the ban, I am just asking to please be unbanned and can assure you it wont happen again! The community helps a lot and vastly improves the game as it can be an easy guide for new users especially as people are happy to give you advice when you ask.

**Comment by gigabit101** [comment]
Ban appeals can be sent here https://minetogether.io/
