### ISSUE TITLE
Crash with newer java version.

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#422]
```
Failure message: MineTogether (minetogether) encountered an error during the sided_setup event phase
		java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
```

Seems covers fixed in https://github.com/CreeperHost/MineTogether/issues/234#issuecomment-647117684
But the fix has been removed again?

MineTogether-1.16.4-4.1.6RC3.jar

**Comment by gigabit101** [comment]
I'm assuming this just got missed when merging into 1.16, I will merge this change later today

**Comment by gigabit101** [comment]
Should be fixed in the latest release
