### ISSUE TITLE
Unable to connect to chat

### ISSUE THREAD

**Issue by Neone26** [CreeperHost/CreeperHostGui#423]
Hello. I've recently started playing Direwolf20's new 1.16 pack and encountered the MineTogether chat for the first time, and I find it awesome to have a global chat on a single player world.

It worked fine at first, but now when I'm in game, I get the message 'Unable to connect to chat. Please make sure you do not have another Minecraft client open. If you have the FTBapp running, ensure that you launched Minecraft via the FTBapp.'

I do not have another Minecraft client open (I've restarted my computer since I first got this message), and I did launch via the FTBapp.

I've also noticed in the FTBapp settings that there's a toggle for 'Enable MineTogether Chat,' but it doesn't let me switch it.

But I do recall before this happened I was playing and watching chat and out of the corner of my eye I see someone say, 'I'm gay,' in the chat before it's quickly deleted. Out of curiosity, I asked something along the lines of 'Is it the word 'gay' that's not allowed or just that particular phrase,' because people who like to randomly say 'I'm gay,' tend to be trolls.

And then my game crashed. And when I relaunched and came back in, I couldn't connect.

Did I get hit by an auto-ban for using the word 'gay?' I checked the MineTogether site, under the 'Account Standing' tab, and it says I'm in good standing.

I looked around a bit to see if anyone else has gotten this message, and couldn't find anything. I just downloaded this pack yesterday so I'm positive that it's on the most recent update. Not sure what it could be.

Thank you.

**Comment by gigabit101** [comment]
Is this issue still persisting in the latest version of the mod?

**Comment by Neone26** [comment]
I'm not sure, as the modpack I played it on actually took MineTogether off (pity, that), though in the settings for the FTB launcher, I can now toggle the 'Enable MineTogether Chat' option when I couldn't before, so I would say it's fine now. Thank you.
