### ISSUE TITLE
Screenshot Sharing Support

### ISSUE THREAD

**Issue by capSAR273** [CreeperHost/CreeperHostGui#425]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
In older IRC chat mods, you could take a screenshot and have it shared to the chat you're a part of. It could also automatically upload it to imgur.com (or another hosting site), then you could paste a link into chat so people could view your screenshot easily.

**Describe alternatives you've considered**

**Additional context**
This would be very useful, as sometimes a question about a machine setup etc. is easier explained with a picture than through chat. Players could use it to share cool builds, get help with certain mods, or just to share what adventures they're on. I remember it being used very frequently by players of the Test Pack Please Ignore modpack (with the EiraIRC mod, maybe that mod's source could be used as an example to pick up and modify for MineTogether's configuration) https://www.curseforge.com/Minecraft/mc-mods/eirairc

**Comment by gigabit101** [comment]
You can take a screenshot and link it in the chat already, This is not something we have planned for this base mod.
