### ISSUE TITLE
Crash while tabbing back into the window

### ISSUE THREAD

**Issue by capSAR273** [CreeperHost/CreeperHostGui#426]
**Describe the bug**
I had minimized the client while it loaded the world, when I clicked back in and opened the chat, the crash occurred.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load a single player world
2. Change window focus to something other than the client
3. Click back in to the client and open chat

**Expected behaviour**
Client shouldn't die

**Screenshots**
N/A

**Versions**

Minecraft: 1.16.4

Forge: 35.1.13

MineTogether: MineTogether-1.16.4-4.1.6RC3 (Direwolf20 Pack version 1.0.0)

**Additional context**
Crash log: https://paste.ee/p/hG3Zr

**Comment by GrumpyChunks** [comment]
Just got the exact same crash and an identical looking [stack trace](https://pastebin.com/GgsJraGR) whilst playing DW20 1.16 (1.0.0). This happened to me just as a right clicked on a bed to sleep. I've slept in the same bed many times, so it's probably not easily reproducible.

**Comment by gigabit101** [comment]
This is already fixed in newer builds of the mod
