### ISSUE TITLE
[request] Players Modpack ID On Username

### ISSUE THREAD

**Issue by itsmekasta** [CreeperHost/CreeperHostGui#43]
Hey folks o/,

itsmekasta here. I already mentioned this idea in global chat and I got positive feedbacks from users and Draylynn as well, so that's why I'll give this one a try.

Something like **(Sky Adventures) <User 1>: Lorem Ipsum** or maybe as mouseover with tooltip.

I think this modpack tag feature would bring more chat activity and more people together, especially if they are playing the same pack as you do.

I hope you guys like this idea as well!

Respectfully,
itsmekasta

**Comment by CH-Paul-T** [comment]
As much as we'd like to do this, all we have is the curse project id.

This would mean another API call to convert the id into a human readable name, we're already expending quite a lot of resources on this on an ongoing basis.

So we won't be doing this, however we will (already planned) be highlighting users playing the same pack as you, using a simple comparison of the project ids, hopefully this provides enough functionality for the above to avoid the confusion we've been seeing and help generate conversation as people ask what pack someone is playing, after noticing they've not got the same colour name as themselves or others.
