### ISSUE TITLE
I am so confused, please help

### ISSUE THREAD

**Issue by dustyfrog9309** [CreeperHost/CreeperHostGui#473]
This is regarding the mine together modification for Minecraft, I'm aware that this isn't a bug but have no idea what to do to fix this issue.
While playing I read in chat that it had a system to auto filter curse words, one of the chatters said that it censored  words by turning them into these weird glitchy letters I had seen earlier. wanting to test this i simply said the f word alone. with no warning I was instantly banned. I then went to try to appeal but was met with me need to "link" my mine craft account with this message "Please connect to
'mc.auth.minetogether.io'
in your Minecraft client, and enter the code you get here" 
I have no idea what this means and would just like to be able to chat again. 
thank you for your time.

edit: spelling

**Comment by gigabit101** [comment]
It means you need to open a MInecraft client and join mc.auth.minetogether.io like you are joining a server

**Comment by gigabit101** [comment]
closed due to inactivity
