### ISSUE TITLE
Error formatting line

### ISSUE THREAD

**Issue by MaceoM** [CreeperHost/CreeperHostGui#474]
**Describe the bug**
Chat works initially but after 1-2 hours chats start appearing with 'Error formatting line, Please report this to the issue tracker'.
In around 30 minutes, all chats except for the moderators degrade into this. Restarting does not solve the issue for longer then a few minutes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start minecraft
2. Wait

**Expected behaviour**
Chat should display as expected with users and their chats

**Screenshots**

![2020-12-29 22_14_31-Window](https://user-images.githubusercontent.com/76733393/103281678-64c6e800-4a23-11eb-8981-60a69de8e7a1.png)

**Versions**
Please give all the versions you are using:

Minecraft: 1.12.2

Forge: 14.23.5.2847

MineTogether: 1.12.2-2.4.0 but also happens on 1.12.2-2.4.1

**Additional context**
Mod pack is Stoneblock 2 from the FTB launcher

**Comment by AshenVice** [comment]
I am having the same issue even though i have the latest version as well. I even uninstalled and reinstalled a few times but it didn't help the issue.

**Comment by Draylynn** [comment]
If this is 1.12.2, downgrade to 2.4.0 build of MineTogether in the meantime, that should help.

**Comment by FuriousGremlin** [comment]
https://imgur.com/a/Kww2rdK same problem here too

it was working yesterday, no updates either as it wouldve had to be a manual one, just a rejoined session and it started happening

**Comment by gigabit101** [comment]
Can you try build 2.4.2 and see if the issue continues?

**Comment by gigabit101** [comment]
Closed due to inactivity. Feel free to reopen with more information on the issue
