### ISSUE TITLE
Disconnect Glitch?

### ISSUE THREAD

**Issue by RyanPlayz1247** [CreeperHost/CreeperHostGui#478]
Good Afternoon. I was talking in MineTogether today (playing FTB Revelations) and after talking for a few hours it said "disconnected, now reconnecting" and it would never reconnect. Is there anyway i could fix this?

**Comment by gigabit101** [comment]
Have you tried restarting your game?

**Comment by gigabit101** [comment]
Closed due to inactivity. Feel free to reopen with more information on the issue
