### ISSUE TITLE
No confirmation on ban appeal?

### ISSUE THREAD

**Issue by XevianLight** [CreeperHost/CreeperHostGui#479]
Is there supposed to be some kind of confirmation or any info about the status of a submitted ban appeal on the website?

**Comment by JoJe3003** [comment]
I have the same problem. I appealed a week ago, nothing is happening.

**Comment by Makabriel** [comment]
Same

**Comment by gigabit101** [comment]
All of the ban appeals have been cleared, If you are still unable to access the chat then your appeal was denied.
