### ISSUE TITLE
[1.16] Quark's items in chat show when in MT tab

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#483]
**Describe the bug**
Quark makes it so if you spawn an item, the texture shows up even when in the MT tab

**Expected behaviour**
For it to not do that

**Screenshots**
![image](https://user-images.githubusercontent.com/15698722/104647019-e00cd880-5676-11eb-9e8e-712431129e04.png)
![image](https://user-images.githubusercontent.com/15698722/104647062-ef8c2180-5676-11eb-88fe-d6d924129180.png)

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.4

Forge: 35.1.29

MineTogether: MineTogether-1.16.3-4.1.5

**Comment by gigabit101** [comment]
Not a lot we can do about this without causing other issues like losing messages in the normal chat.
The best fix I can see would be for Quark to use drawnChatLines and not chatLines for rendering the item.

**Comment by gigabit101** [comment]
Fixed in newer versions of Quark
