### ISSUE TITLE
[1.16.4] Crash when adding to Enigmatica 6

### ISSUE THREAD

**Issue by Recaran** [CreeperHost/CreeperHostGui#487]
Game crashes to desktop as soon as its loaded.

**To Reproduce**
Add MineTogether to Enigmatica 6. Tried both 1.16.4 versions (4.1.6RC2 and 4.1.6RC3)

**Expected behaviour**
Not to crash and let me into the game

**Versions**

Minecraft:
1.16.4

Forge:
35.1.36

MineTogether: 
MineTogether-1.16.4-4.1.6RC3

Enigmatica 6:
0.3.6

[crash-2021-01-20_11.24.50-client.txt](https://github.com/CreeperHost/MineTogether/files/5842084/crash-2021-01-20_11.24.50-client.txt)

**Comment by gigabit101** [comment]
Should be fixed in the latest release
