### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by theejackal** [CreeperHost/CreeperHostGui#488]
Idk why i was banned. I was nicely trying to explain Sevtech Ages to another player and it banned me. Plus this happened earlier too, and each time it didnt like my message my game crashed too.  SO i guess its kind of a bug report too. Im on FTB Unstable 1.16.4. BAN ID: mtg-ban=6008de071d5b99.71990722

**Comment by bruceyboy24804** [comment]
Hey is it ok if it get unbanned i got banned for saying the word arse and was unaware that i could get banned for saying arse

**Comment by Draylynn** [comment]
Ban appeals are handled via MineTogether.io
