### ISSUE TITLE
No messages in MineTogether chat

### ISSUE THREAD

**Issue by Iamsotiredguys** [CreeperHost/CreeperHostGui#489]
I'm very confused and still very new to this whole thing. I suddenly stopped getting messages in the MineTogether chat. Not only did no other people's messages show up, but mine didn't show up even when I typed them and pressed enter. I'm not sure if this is a bug or not, but I have no idea where else to put this. I'm at a loss. I was thinking that I may have been banned from chat, but after some Googling I saw that other people were getting "ban IDs" whereas I didn't get any information. Also, I only just now made a MineTogether account and I'm still unsure on how to attach it to my client/Minecraft Account, so if that's where you're informed of bans then it makes I wouldn't know.

The messages stopped appearing last night in the middle of my game, and just now as I opened it again they're still not appearing. The last messages I saw before they stopped all together were the following:
User 1: *offensive, homophobic language that immediately gets censored.*
User 2: homophobe.
Me: minecraft is for the gays~*

It seems silly. We were just having fun in chat. If I was banned for "making things political" or whatever, I might understand (though I wouldn't think it's entirely ethical). But like I said, I wasn't informed of a ban or any sort of penalty, so I'm hoping this is a bug or an oversight of some kind.

The expected behavior is for the chat to continue as normal, and for my messages to appear.

I am using FTB Revelation v3.4.0, 1.12.2, Java Edition Minecraft. I'm not sure what else to put here.
I just joined my FTB singleplayer world one day and suddenly people were talking, and I was enjoying it.

I'm just really confused. Please help, thank you.

**Comment by Draylynn** [comment]
Ban appeals are handled on MineTogether.io
