### ISSUE TITLE
Rejoining problem

### ISSUE THREAD

**Issue by Dubl33** [CreeperHost/CreeperHostGui#49]
So I sweared in chat and got kicked but it said it was gonna "rejoin" me so I waited a few mins but nothing so I tried reinstalling and still it wasn't fixed... when i tried typing in chat there was nothing showing from others nor what I wrote appeared.

**Comment by CH-Paul-T** [comment]
Not a bug.

User broke clearly displayed rules on chat and was permanently banned.
