### ISSUE TITLE
Cannot reconnect to chat, and crash when disabling when reconnecting

### ISSUE THREAD

**Issue by stinky-lizard** [CreeperHost/CreeperHostGui#490]
After disconnecting from chat by disabling it, I cannot reconnect until I restart the game. It only says it's reconnecting indefinitely. Trying to disable the chat when it's reconnecting will crash the game.

This happens often when I try to reconnect after suspending Minecraft, for instance putting the computer to sleep with it open. MineTogether will say it's connected, but won't show any chats (another, less annoying bug), and will never reconnect. However, this reconnecting bug happens even without suspending Minecraft.

1. Start MC and load a world
2. Click on the MineTogether Chat button in the top right of the pause menu
3. Click on the settings button
4. Disable chat
5. Re-enable chat
6. Chat will now never reconnect.
7. Re-disable chat
8. Minecraft crashes.

I don't have any screenshots, but I recorded a video:
[https://drive.google.com/file/d/1qxLbzYowokViaqlKQz_I2wwF3c3e_YzT/view?usp=sharing](https://drive.google.com/file/d/1qxLbzYowokViaqlKQz_I2wwF3c3e_YzT/view?usp=sharing)

Here's the crash log that MC made in the video:
[https://pastebin.com/6YCRvhRN](https://pastebin.com/6YCRvhRN)

Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2847
MineTogether: 2.4.2

**Comment by gigabit101** [comment]
Should be fixed in the latest release
