### ISSUE TITLE
single player crash

### ISSUE THREAD

**Issue by thegameryt382** [CreeperHost/CreeperHostGui#492]
i try to join my 2 day old single player world, then it brings a page saying game has crashed and it wont let me play the world. Minecraft itself dosent crash its just the world. I dont know how to fix it says that these certain mods could be causing the problem. MineTogetherserver and mineTogether
![image](https://user-images.githubusercontent.com/77977330/105721201-ece8c200-5ee9-11eb-9337-c81f3263d750.png)

I am using curse forge version 1.1.1-1.12.2.zip

**Comment by gigabit101** [comment]
Can you provide us with the logs?
