### ISSUE TITLE
Where do I link minecraft account to Minetogether chat?

### ISSUE THREAD

**Issue by Crazynoonga45** [CreeperHost/CreeperHostGui#493]
Wanting to appeal a Ban website says connect to 'mc.auth.minetogether.io' in the minecraft client not sure what this means?

**Comment by Randomizzatore** [comment]
Add a server with that address and connect to it

**Comment by Draylynn** [comment]
auth.mc.minetogether.io - As it tells you when you click "Connect Minecraft". Join the server, get kicked, copy code.
