### ISSUE TITLE
R3th1nk ban appeal

### ISSUE THREAD

**Issue by Davidtank70** [CreeperHost/CreeperHostGui#498]
![Screenshot 2021-02-23 184027](https://user-images.githubusercontent.com/36216761/108923325-9d8bd380-7606-11eb-9980-73794cff11c3.png)
I said "shit" in chat I would like an unban I didn't realize the no cursing policy was this strict I will make sure not to say it again.
My in-game name is R3th1nk and I promise to refrain from any type of profanity whatsoever.

**Comment by gigabit101** [comment]
Ban appeals can be submitted via our website https://minetogether.io/
