### ISSUE TITLE
Multiple listings in multiplayer menu when kicked with rejections

### ISSUE THREAD

**Issue by Bennyboy1695** [CreeperHost/CreeperHostGui#5]
Just tried connecting to a server with different mod versions to my clients and each kick created a extra listing for the advertisment. Upon clicking refresh the extra's do remove themselves though. This happened in 1.7.10 FTB Infinity Evolved V2.7.1 , not sure if other packs/versions of mc have the same issue - http://i.imgur.com/3qnpTej.png

**Comment by Cloudhunter** [comment]
Thanks for reporting! I'll see what I can do to mitigate this :)

**Comment by Cloudhunter** [comment]
Fixed in the build which will be going out soon!

**Comment by Cloudhunter** [comment]
Soon was in Valve time. Fixed! https://minecraft.curseforge.com/projects/creeperhost/files
