### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by ghost** [CreeperHost/CreeperHostGui#501]
**Describe the bug**
In this case it is a very obvious one. I created a world and spawned, then followed by a crash, after I had spawned. I was in the world for several seconds.

**To Reproduce**
Steps to reproduce the behaviour:
1. I created a ->Singleplayer World
2. I have spawned in the world
3. I was in the world for some seconds
4. The game, or rather the world crashed, because VanillaFix prevented it.

**Expected behaviour**
I expected to check out what all the mods I have installed, Minetogether as well, because I was working on another Server Modpack.

**Screenshots**
It's just a Crash-Report to visualize

**Versions**
Please give all the versions you are using:

Minecraft:
The newest Version/ 1.12.2 ?

Forge:
Forge 1.12.2 14.23.5.2854

MineTogether:
minetogether as well as minetogetherserver are 1.12.2 2.4.2

**Additional context**
[crash-2021-03-01_13.07.10-client.txt](https://github.com/CreeperHost/MineTogether/files/6061663/crash-2021-03-01_13.07.10-client.txt)

**Comment by gigabit101** [comment]
Should be fixed in the latest release
