### ISSUE TITLE
Trying to link minecraft account

### ISSUE THREAD

**Issue by DoveDeoderant** [CreeperHost/CreeperHostGui#503]
I cant generate a code to link my minecraft account with my minetogether account

**Comment by planetx32** [comment]
You are given a server name/ip address(forget which) . You will need to start a new multiplayer game, choose direct connection.  Put the server name/ip in as the one you want to connect to.  You will instantly be kicked from the server and given a reason code.  That is the code you need to link the minecraft with minetogether.

**Comment by Draylynn** [comment]
auth.mc.minetogether.io - Join the server, get kicked, copy code.
