### ISSUE TITLE
Broken "Ban Appeal" Option when you click Report Bug/Ban Appeal

### ISSUE THREAD

**Issue by lambda-flux** [CreeperHost/CreeperHostGui#507]
**Describe the bug**
First of all, pressing "open" on the part of the bug report section that says "ban appeal" just leads you to the minetogether website with no indication of how to appeal a ban. Second of all, I was banned for telling people speaking french to stop speaking french. How is this a bannable offense?

**To Reproduce**
It's kinda obvious

**Comment by planetx32** [comment]
Go to minetogether.io, log in, go to account settings and select appeal ban.
