### ISSUE TITLE
Request/Fix for IP verification on virtual rental servers

### ISSUE THREAD

**Issue by DingoX3** [CreeperHost/CreeperHostGui#51]
I believe my issue is the server im renting has a wrapper that clears the ip address back to 0.0.0.0 every time i change, save,and reboot.(As im renting this server i dont have access to this) Is there a possibility of getting a config option to add the ip in the config and then the mod can read it from the config. It might be great for cases like this? Thanks in advance.

**Comment by CH-Paul-T** [comment]
This already exists, you can override the detected IP via server.properties or via the minetogether config.
