### ISSUE TITLE
False ban 

### ISSUE THREAD

**Issue by ForthaThePen** [CreeperHost/CreeperHostGui#510]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Versions**
Please give all the versions you are using:

Minecraft:

Forge:

MineTogether:

**Additional context**

I went and asked someone how I would get slimes in Ultimate Reloaded, because I need it for a recipe, and then I can’t see chat anymore and can’t message the chat, I think I got banned for no reason...

**Comment by Draylynn** [comment]
"Slime chinks" <- That's a racial slur in there.
The bot got you. I'll remove the ban, but please:
A) Be careful with your typing.
B) Use MineTogether.io to appeal future bans.
