### ISSUE TITLE
i tried to find the forum or place to email for ban apeels on your website and it doesnt exist

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [CreeperHost/CreeperHostGui#511]
**Describe the bug**
i likely have the same id as someone else from a different modpack. i just installed this mod and it says im already banned. also i tried to find the forum or place to email for ban apeels on your website and it doesnt exist

**To Reproduce**
Steps to reproduce the behaviour:
used modpack for the very first time "better living through chemistry" after trying to get it to run literally 500 times with texture packs shader packs and originally 219 mods for 1.15.2 minecraft with forge
**Expected behaviour**
i was expecting... to be able .. to chat with people in the cloud...
**Screenshots**
https://ibb.co/GRs8Dcv started the game up and saw a ban warning im like.. did i just get banned from minecrraft by installing mods?!?! then i read the message in detail.
**Versions**
Please give all the versions you are using:

Minecraft:
1.15.2
Forge:
31.2..49
MineTogether:
MineTogether-1.15.2-4.1.5.jar
**Additional context**
im pretty tech savvy so im guessing that the uuid somehow mangled with someone elses because of the bizarre combinations of mods..

changing or removing tthe mods doesnt remove the ban

help please?

**Comment by ThePaul-T** [comment]
No, you're banned for a message not appropriate for chat.

```
{"id":"mtg-ban=5ffcf78ce39983.75564209","timestamp":"2021-01-12 01:12:44","reason":"Banned for use of expletives.","offendingMessage":"the beutifull things with the womb and boobs and higher iq then men","bannedBy":"Freddy","banActive":true}
```

ID's are based on your Mojang UUID (But can't be reversed back), they're unique to your account.

Appeal via the account standing page on the website after logging in.

**Comment by tails1974seeyounextgame** [comment]
in that case ill jsut fork your mod and strip the security features out. no worries tardzooka tails in on the case.

**Comment by ThePaul-T** [comment]
Good luck, it's server authoritative. Feel free to fix some bugs while you're there.
________________________________

**Comment by tails1974seeyounextgame** [comment]
apparently your coding is garbage lol. a simple nop in some hex addresses and im already done. apparently youve never heard of a loopback spoof douchebag :)

  On Tuesday, March 23, 2021, 3:56:08 AM MDT, Paul T. ***@***.***> wrote: 
 
 Good luck, it's server authoritative. Feel free to fix some bugs while you're there.
________________________________

**Comment by ThePaul-T** [comment]
Someone has been watching too much TV trying to emulate hackers and decided they can string some words together to sound smart.

Have fun, it's server authoritative, you're not getting back in and actually be able to talk to users without a new Minecraft account.

**Comment by tails1974seeyounextgame** [comment]
and yet i did and have screenshots, when u learn to code yung scripter ill let you know
