### ISSUE TITLE
Alternate chat rooms for different age ranges. 

### ISSUE THREAD

**Issue by mikeloeven** [CreeperHost/CreeperHostGui#513]
I keep seeing a lot of people complaining about how mine together only has one available global chat server and that it is a overly sanitized general audiences room with very strict censorship and moderation. I feel like this is a major turn off to a lot of the older generation of players and one of the primary reasons for bans. I am thinking that the mod would be a bit better if there were multiple chat rooms for the different age ranges. I would like to see an Opt In chat room for older players that does not have the same filtering. There would still need to be moderation to protect against politics hate speech sexual content ect however It would be a place where older gamers could hang out without risking a ban for making off color jokes or cursing out a creeper. Again not asking for any changes to the global chat just an additional; chat channel for mature gamers. Keep in mind most of the older mine craft players are in their 30's now and they need a place to chat.

**Comment by ThePaul-T** [comment]
Being unable to control yourself, means you're asking for a cesspit not a mature chat.

Who is funding the additional moderation etc?

There's plenty of other chat services available on the internet, ours is for EVERYONE. Start a group chat.

**Comment by mikeloeven** [comment]
Not really first of all your  jumping down my throat attacking what i wrote "Being unable to control yourself, means you're asking for a cesspit not a mature chat." 

you dont know me and have no right to make assumptions on my motivations or personality! 
i have not been banned from the service nor violated any of the rules. 
I specifically stated the mature chat would still ban politics hate speech and sexual content so clearly if i wanted a cesspit I would have advocated for unfiltered chat ....

Who is funding the additional moderation etc? "You dont need funding most chats use volunteer moderators from trusted individuals" 

Try to be a little more polite please

**Comment by ThePaul-T** [comment]
You decide not to check closed issues, and thus waste our time by not checking the numerous, already closed, longer responses.

You then go full defensive, with to me, just proves my point, if this wasn't the truth, you'd not react so badly.

Asking for slave labour in 2021, no. People deserve paid for their time.

You don't get to decide what is and isn't polite here, you started this off by disrespecting our time, how did you think this would go? Check closed issues on GitHub. Want a different mod? Make one.

This may seem harsh, but if you'd checked issues as mentioned above, you'd know this has been answered numerous times.
