### ISSUE TITLE
Issue with linking account to appeal ban

### ISSUE THREAD

**Issue by WelshAssassin02** [CreeperHost/CreeperHostGui#514]
Hi, I'm currently trying to appeal a ban (At least I think it is one.). But as I cannot connect to minetogether service to connect my minecraft account. Unless permanent connecting is bug or something?

edit: typo

**Comment by Draylynn** [comment]
Are you connecting to the game server via the game client, in-game, via the Multiplayer menu, the direct connect button and NOT entering the hostname you were provided into a web browser where you'll get a dodgy API response?

**Comment by Draylynn** [comment]
No response, closing ticket.
