### ISSUE TITLE
Ban that I knew nothing about?

### ISSUE THREAD

**Issue by ElBiggus** [CreeperHost/CreeperHostGui#517]
(I have a feature request related to this.)

I got banned a while back because apparently "bung" (in the sense of "just bung X on the crafting bench") was not PG rated, but (due to reasons detailed in the feature request) I was unaware - it just stopped working. Once I found out I appealed and was unbanned (obviously). It stopped working again a couple of days ago, so first thing I did was check my account standing and it said it was good, so I figured it must be a technical issue. It randomly started working again, but has now stopped so again I checked account standing, it says it's good, but also says I have *2* previous bans - what was the second one, and why did it not show up on the system when I checked?

**To Reproduce**
No idea.

**Expected behaviour**
A couple of things; if you're banned then the account standing ought to say so, and previous bans should have some details visible.

**Versions**
Please give all the versions you are using:

Minecraft: 1.12.2

Forge:  14.23.5.2846

MineTogether: 2.4.2

**Additional context**
See feature request.

**Comment by Draylynn** [comment]
If you read the previous issues, you'd know, you can't appeal here anymore.
Appeal on MineTogether.io

**Comment by ElBiggus** [comment]
I'm not appealing the ban (as it turns out you accidentally banned me, for which you have apologised), I'm pointing out that when I checked my account standing at the time the second ban didn't show up, and there was no clue it had happened until after it was lifted - I checked pretty regularly while I was attempting to puzzle out why MT wasn't working.

**Comment by Draylynn** [comment]
Ah, sorry, ma brain was on auto-pilot.

**Comment by Draylynn** [comment]
MineTogether.io had an overhaul - Account Standing menu will show previous bans, the ban ID, the comment that was banned etc.
