### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Thysieboy** [CreeperHost/CreeperHostGui#519]
Hey guys,
First of all, cool mod!
Sadly I think I have been banned today. Probably because I "swore". Well I didn't, I did not type the complete word on purpose to avoid getting banned, sadly I did get banned. I understand, tough, I would like to be able to participate again, I used it a lot and really liked it. In any case, my username is Thysie. It will not happen again
Cheers

**Comment by gigabit101** [comment]
Ban appeals need to be done via our website https://minetogether.io/
