### ISSUE TITLE
Website all but unusable on mobile devices

### ISSUE THREAD

**Issue by ElBiggus** [CreeperHost/CreeperHostGui#520]
Attempting to use MineTogether.io on a mobile device is non-optimal - the simple act of logging in *requires* switching to portrait mode to access the sign in link.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to minetogether.io on a mobile browser with phone in portrait mode.
2. Sign in link not visible,

**Expected behaviour**
Er, it working on phones?

**Screenshots**
How it loads:
![Screenshot_20210422-134605](https://user-images.githubusercontent.com/80195860/115717227-e1365b80-a371-11eb-99a1-b6068470a155.png)

Scrolling to right does not help, there's nothing there:
![Screenshot_20210422-134614](https://user-images.githubusercontent.com/80195860/115717225-e0052e80-a371-11eb-92f0-a214a73d2153.png)
**Versions**
Android: 10 (build QKQ1.191002.002)
Chrome: 90.0.4430.66

**Comment by Draylynn** [comment]
How does it look now?
