### ISSUE TITLE
Forge is detecting this mod as 1.16.1 mod only

### ISSUE THREAD

**Issue by VirtualGaming1** [CreeperHost/CreeperHostGui#522]
**Describe the bug**

**To Reproduce**
Load MC1.16.5 with FML: 16.1.10 or newer

**Expected behaviour**
should not have any issue for loading the mod

**Screenshots**
![image](https://user-images.githubusercontent.com/20447403/116527221-0fe79100-a8a0-11eb-9c85-1914a756efc7.png)

**Versions**
MineTogether-1.16.4-4.1.6RC3.jar

Minecraft:1.16.5

Forge: 16.1.10 and newer

MineTogether:4.1.6RC3

**Additional context**
This might be a link to Forge loading to stop working in it place with out any error at 16.1.1 or lower. Between 16.1.1 and 16.1.10 I do not know if this issue happen as I update FML from 16.1.1 to .10 then 13

**Comment by gigabit101** [comment]
Should be fixed in the latest release
