### ISSUE TITLE
Crash when getting banned.

### ISSUE THREAD

**Issue by ylyxa** [CreeperHost/CreeperHostGui#524]
**Describe the bug**
Game crashed when I got banned from chat. 
(Sidenote: this is not a ban appeal. Done that one already, waiting for a reply)

**To Reproduce**
Steps to reproduce the behaviour:
1. Get banned... I guess

**Expected behaviour**
Game continues to work normally. Well, without the chat.

**Versions**
Minecraft: 1.12.2

Forge: 8.0.99.99

MineTogether: 2.4.1

**Additional context**

Modpack is FTB Revelation 3.4.0 with OreExcavation 1.4.137 added on top.

Crash report attached.

[crash-2021-05-08_10.49.05-client.txt](https://github.com/CreeperHost/MineTogether/files/6445521/crash-2021-05-08_10.49.05-client.txt)

**Comment by gigabit101** [comment]
Should be fixed in the latest release
