### ISSUE TITLE
I am so confused

### ISSUE THREAD

**Issue by Burnguard** [CreeperHost/CreeperHostGui#525]
**Describe the bug**
Um I have no idea what is going on here My roomate installed a modpack on my computer and when I joined there was a chat? It seemed like a cool idea so I was chatting on it and then it went away suddenly. My roomate said it was possible that I was banned for saying a mild curse word(I did not see any messege about being banned so I really dont know if thats what this is). Apparently there were rules that I did not see, and I honestly had no idea that there was a no swearing rule. Admittedly this is obvious in hindsight, but I was honestly caught off guard by a multiplayer chat in my single player game and was simply not thinking. I looked it up, and apparently ban appeals are done on the website, but when I tried it said that I had to connect to something from my Minecraft client, and I have next to no technical knowledge so it might as well have given me instructions in Klingon. I would really like to reconnect to that chat beacause it seems like a cool idea. If I have indeed been banned for that curse word then I deeply apologize and would really appreciate a second chance. Also, is there a place where I can see these rules if I do get unbanned?

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
I am in a constant state of confusion. I expect chaos in all things.

**Screenshots**

**Versions**
Please give all the versions you are using:

Minecraft:

Forge:

MineTogether:

**Additional context**

**Comment by gigabit101** [comment]
Ban appeals need to be made via our website here https://minetogether.io/

**Comment by Burnguard** [comment]
how do I link my minecraft account in order to to that? it says connect to something but I have absolutly no idea how to do that.
