### ISSUE TITLE
Repost of miscommunication

### ISSUE THREAD

**Issue by Burnguard** [CreeperHost/CreeperHostGui#527]
I have made a copy of a previous issue because it seems there has been a miscommunication and the other was closed prematurely. This is what my previous issue said:

Um I have no idea what is going on here My roomate installed a modpack on my computer and when I joined there was a chat? It seemed like a cool idea so I was chatting on it and then it went away suddenly. My roomate said it was possible that I was banned for saying a mild curse word(I did not see any messege about being banned so I really dont know if thats what this is). Apparently there were rules that I did not see, and I honestly had no idea that there was a no swearing rule. Admittedly this is obvious in hindsight, but I was honestly caught off guard by a multiplayer chat in my single player game and was simply not thinking. I looked it up, and apparently ban appeals are done on the website, but when I tried it said that I had to connect to something from my Minecraft client, and I have next to no technical knowledge so it might as well have given me instructions in Klingon. I would really like to reconnect to that chat beacause it seems like a cool idea. If I have indeed been banned for that curse word then I deeply apologize and would really appreciate a second chance. Also, is there a place where I can see these rules if I do get unbanned?

The response I got was to make a ban appeal on the website, however to do so I need to link my Minecraft account, and to do so I need to connect to something with my Minecraft client, which I have absolutely no idea how to do. As a result, I cannot make said website ban appeal because I cannot link my account. Please halp.

**Comment by Draylynn** [comment]
Visit MineTogether.io
Login.
Click Connections.
Click Minecraft.
Copy server address: Connect to game server.
Get kicked, copy kick code.
Add to Minecraft connected accounts on MineTogether.io
