### ISSUE TITLE
No code to use?

### ISSUE THREAD

**Issue by orrinpants** [CreeperHost/CreeperHostGui#528]
**Describe the bug**
It says you need to link Minecraft to get a code, but you never get a code from linking it. You can't ask for a code that doesn't exist.

**To Reproduce**
1. Go to the website
2. Click on 'My Profile'
3. Scroll down to 'Account Standing'
4. Click on 'connect'
5. Undefined code (even when connected)

**Expected behavior**
After linking showing a code or emailing it to the user.

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.5

Forge: Latest

**Additional context**
Connecting Minecraft just means show a website that says you connected it, nothing else. That does not connect it.

**Comment by orrinpants** [comment]
how to add labels?

**Comment by Draylynn** [comment]
The steps seem wrong...

Visit MineTogether.io
Click connections.
Click Minecraft.
Copy server address: Connect to game server.
Get kicked, copy kick code.
Add to Minecraft connected accounts on MineTogether.io?

**Comment by Draylynn** [comment]
"Scroll down to 'Account Standing' Click on 'connect'"
There's nothing to click 'connect' on in Account Standing, it's an account standing report: EG: Have you been banned.

**Comment by orrinpants** [comment]
IT HAS A CONNECT BUTTON

**Comment by Draylynn** [comment]
![image](https://user-images.githubusercontent.com/45239550/118562527-c4205d00-b764-11eb-9f04-ac6bb7e6986e.png)
Screenshot or it didn't happen.

**Comment by orrinpants** [comment]
![Screenshot 2021-05-19 7 22 59 PM](https://user-images.githubusercontent.com/69820414/118897145-b3442880-b8d7-11eb-8812-61b08340e6df.png)

**Comment by orrinpants** [comment]
By the way, I had to click a button saying "connections"

**Comment by orrinpants** [comment]
Also, I don't use a Chromebook normally this is a vacation I use a pc normally

**Comment by Draylynn** [comment]
Click 'connect' under Minecraft and you'll get given a game server address, use it in the game client that is logged in with your MC account to join the server, you'll get kicked with a code.

**Comment by orrinpants** [comment]
I can't put URLs in the client.

**Comment by orrinpants** [comment]
nor can I put it in the client

**Comment by orrinpants** [comment]
Here is the code I got:
`{"ok":true,"docs":"(https://docs.minetogether.io)"}`
btw [this](https://docs.minetogether.io) is it
Also, the code is not the correct code. Why would you make the code the thing that isn't the code?

**Comment by orrinpants** [comment]
Do I have to do this the extremely hard way?

**Comment by Draylynn** [comment]
... Apparently so. Follow my instructions.

You put it in your client, in the multiplayer menu, keywords:
**Server Address**
**Join the server**
**Copy server address: Connect to game server.**

Cheesus on a stick, how many times do I need to point this out.

**Comment by orrinpants** [comment]
That's not what I meant by the extremely hard way, but okay.

**Comment by orrinpants** [comment]
YES! It worked! I had to use the IP mc.auth.minetogether.io

**Comment by gameplays12303** [comment]
i did that it said unknown host

**Comment by Draylynn** [comment]
> i did that it said unknown host

It does exist: https://www.whatsmydns.net/#A/mc.auth.minetogether.io
Check your DNS is up to date and that your client has internet access.

If your local DNS server is not up to date, faulty etc.
If you want to use another DNS server, you can change the DNS server your computer uses in your "Change Adapter Options" or "View Network Connections" and right clicking your adapter to visit it's properties.
![image](https://user-images.githubusercontent.com/45239550/167246609-9c703eee-5428-4942-b6cf-bf6f7610ddc5.png)
There are many freely available DNS servers, for example;
CloudFlareDNS: 1.1.1.1 / 1.0.0.1
GoogleDNS: 8.8.8.8 / 8.8.4.4 
OpenDNS: 208.67.222.222 / 208.67.220.220
Etc etc. There are many to choose from online, these are but a few examples.
