### ISSUE TITLE
Renaming friends in friendslist

### ISSUE THREAD

**Issue by jonps97** [CreeperHost/CreeperHostGui#529]
**Is your feature request related to a problem? Please describe.**
I Want to rename some of my friends in the friends list, but having to remove and send a new friendrequest is a bit inconvienient.

**Describe the solution you'd like**
Add a simple rename function to the friends list

**Describe alternatives you've considered**
No idea.

**Additional context**
Just a simple request, no need to prioritize it.

**Comment by gigabit101** [comment]
Added in 5.0.2
