### ISSUE TITLE
Delete the "map - copy" folder in the texture assets

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#530]
![image](https://user-images.githubusercontent.com/15698722/118379990-575e6480-b5a4-11eb-9773-8d7b3f4025b2.png)

**Versions**
Please give all the versions you are using:

MineTogether: MineTogether-1.16.4-4.1.6RC10

This causes problems with FTB Quests `[17:37:14] [Render thread/ERROR] [FTB Quests/]: A mod has broken resource preventing this list from loading: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minetogether:textures/map - Copy/sub-saharan-africa.png`

**Comment by gigabit101** [comment]
Fixed in latest alpha https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether
