### ISSUE TITLE
Update 1.16.4-4.1.6RC10 Not connecting on fresh install of ftb endeavour 

### ISSUE THREAD

**Issue by IcemanDs** [CreeperHost/CreeperHostGui#531]
**Describe the bug**
I installed fresh copy of ftb endeavour and downloaded the new version as mentioned above.
I tried to restart client multiple times, just gives me the minetogether chat screen and does connect to show chosen user name but does not connect to chat server it seems.

**To Reproduce**
1. Go to 'multimc and install ftb endeavour download and add minetogether version 1.16.4-4.1.6RC10'
2. Start modpack 
3. See no errors for starting up
4. In-game got to minetogether chat, send message see user chosen name when sending message, no verification message or communication from chat server

**Expected behaviour**
Expected the verification screen with the chat rules.

**Screenshots**

**Versions**
MineTogether-1.16.4-4.1.6RC10.jar:

Minecraft: 1.16.5

Forge: 36.1.16

MineTogether: 1.16.4-4.1.6RC10
![2021-05-17_15 50 18](https://user-images.githubusercontent.com/45338739/118486907-70892180-b71a-11eb-8d41-520a8b635f0b.png)

**Additional context**

**Comment by Catacide** [comment]
Experiencing same issue in ATM6 skyblock, versions are same expect I have Forge 36.1.2.

**Comment by Draylynn** [comment]
Test something for me:
Close the client.
Logout of the launcher with your **MC account**, log back in with your MC account, start game.
Does it still not work?

_Few users reported a failure in MC credentials recently, being able to read chat, but not talk. If you can't validate properly against Mojang's API, you can't chat. It's not uncommon for this to happen randomly to the client (hence why some packs have Re-Auth on the Multiplayer menu, so you can re-login and update your client credentials/session token without having to restart)._

**Comment by IcemanDs** [comment]
Had a minecraft account issue that reluted in them resetting my account. Afterwards all worked 100%. Thanks
