### ISSUE TITLE
Ban appeal bug

### ISSUE THREAD

**Issue by orrinpants** [CreeperHost/CreeperHostGui#533]
Now before you delete this for duplicating, this is a different one.
**Describe the bug**
My ban appeal button reappeared a few seconds after I pressed it.
I even checked my Gmail, my notifications (Actually those aren't a thing), and everything that could say it, but none say my ban appeal was discarded.
**To Reproduce**
1. Get banned on MineTogether
2. Go to minetogether.io
3. Go to Account Standing
4. Appeal the ban (in a good way)
5. Wait a few seconds
6. The button reappears. Maybe this isn't a bug, but check everything. It doesn't say it was discarded.

**Expected behavior**
Button doesn't reappear until banned again.

**Screenshots**
![image](https://user-images.githubusercontent.com/69820414/120848439-cba47c00-c542-11eb-83ac-504dd53bdd98.png)

**Versions**
Please give all the versions you are using:

Minecraft: 1.15.2

MineTogether: 4.1.5

**Additional context**
None

**Comment by orrinpants** [comment]
Also, I was banned because I got banned from the ban that was because I was banned? I'm so confused!

**Comment by Draylynn** [comment]
Not actually finding any appeal in our appeals list, especially if you submitted one within the last week...

Press F12 in your browser, go to Networking tab, click "disable cache", then press F5 to reload the page, does it still behave the same way?
_In rare cases browser cache system can derp and cause all kinds of weird things to happen_

Are you using any browser plugins like NoScript or something that could be invasive and interfering with the site code?

**Comment by Draylynn** [comment]
A) Looks like the ban was for spam.
B) As this ticket has no updates, I will close it.
