### ISSUE TITLE
Ban appeal?

### ISSUE THREAD

**Issue by rascott1213** [CreeperHost/CreeperHostGui#535]
I have absolutely no idea what I got banned for. Username Rascott, happened a few minutes ago on Stoneblock 2. Someone was causing a ruckus about the custom names. I said three things:

- Sure are a lot of people here paying for custom names.
- I actually like the anonymity.
- Makes it easy to just come on and shoot the shit.

And then got banned/blocked out with zero warning or notification, or even directions on where to appeal.
<img width="752" alt="whatsgoingon" src="https://user-images.githubusercontent.com/36864815/121451711-0d328e00-c96c-11eb-9206-169ad50c4013.png">

**Comment by rascott1213** [comment]
Trying to follow the very unclear breadcrumbs to the minetogether.io website to appeal the ban directly, it's asking me to "Please connect to 'mc.auth.minetogether.io' in your Minecraft client, and enter the code you get here!" But I see no such option. I'm opening Stoneblock 2 from MultiMC, I don't see any mention of MineTogether anywhere or how to connect to it.

**Comment by JamR71111** [comment]
It's because you said the potty word for poop and you need to connect to the server with that ip address and it'll give you a code

**Comment by Draylynn** [comment]
_"Please connect to 'mc.auth.minetogether.io' in your Minecraft client, and enter the code you get here!"_
Where do you connect to server hostnames in your client? It's a server, a game server, join the game server...

Also, we can't identify you by your MC name, knowing your User#ID would help (it's shown on MineTogether.io).

**Comment by rascott1213** [comment]
I figured it out another half hour after my message, and already got the ban appeal submitted and resolved. I figured the issue would have been closed here eventually anyways, but I'll do that now. Thanks for attempting to help anyways!
