### ISSUE TITLE
Show the reason of ban

### ISSUE THREAD

**Issue by JamR71111** [CreeperHost/CreeperHostGui#536]
**Is your feature request related to a problem? Please describe.**
Hi, I like to use the MineTogether chat a lot but I was banned while I went AFK in my world, and I want to know what the reason was so I can make a true appeal in regards to that specific situation

**Describe the solution you'd like**
Show the message that needed banning

**Describe alternatives you've considered**
I don't really know

**Additional context**
I know it was the mighty and feared draylynn that banned me, so I want to ask why if she sees this
mtg-ban=60c1ae96e61e92.27703246
p1623287945382900
User#6B545
If any of that info helps in identifying who I am ^^^

**Comment by JamR71111** [comment]
i seem to have been already retrieved from the mythical "chat pit"

**Comment by Draylynn** [comment]
"p1623287945382900"
Seen as spam in chat, please don't face-mash your keyboard. Spam is against the rules.
