### ISSUE TITLE
I need my discord link to reset

### ISSUE THREAD

**Issue by iSnuup** [CreeperHost/CreeperHostGui#537]
I'm MintCicada#1BD98 and I tried to link into the MineTogether discord, but I didn't login to discord through browser before I linked them, please help, thanks! I'm trying to get into voice but I am locked out.

**Comment by Draylynn** [comment]
Could probably be helpful if there were 'reset' link options on MineTogether.io's profile - Especially for Discord:
Users who authenticate often don't notice when they're linking Discord via browser, that they have to be logged in first.
Failing to login to Discord in the browser before linking results in the link containing an anonymous Discord ID.

**Comment by Draylynn** [comment]
MineTogether.io got an overhaul, click the red X next to the link you want to remove in the Connections menu.
