### ISSUE TITLE
Minetogether not working

### ISSUE THREAD

**Issue by Shadowb1ood** [CreeperHost/CreeperHostGui#538]
**Describe the bug**
When trying to use the minetogether chat in stoneblock2 , nothing shows up, or it randomly works.

**To Reproduce**
Press "t" or "/" to open chat/message window.

**Expected behaviour**
Should see other users messaging via the minetogether mod.

**Screenshots**
[Commands tab]
![image](https://user-images.githubusercontent.com/85945256/122090034-5869f800-cdd5-11eb-901d-732969106624.png)
[Minetogether chat tab]
![image](https://user-images.githubusercontent.com/85945256/122090189-7fc0c500-cdd5-11eb-8abe-fa71e7d8876c.png)

**Versions**
FTB StoneBlock 2 via CurseForge

Minecraft:  1.12.2

Forge: 14.23.5.2846

MineTogether:
version 2.4.5

**Additional context**

**Comment by Draylynn** [comment]
Are you able to provide a debug.log from the time of the event? Logs like this are in the clients /logs/ folder in the clients installation directory.
_Note: The log might be quite big, you may need to link it in here. **Do not paste the entire thing raw in here.**_

**Comment by Draylynn** [comment]
No response, closing issue.
