### ISSUE TITLE
Crash as someone get banned/removed from chat

### ISSUE THREAD

**Issue by IcemanDs** [CreeperHost/CreeperHostGui#539]
**Describe the bug**
For the past week noticed occasional crashing as someone is being banned/removed from chat. Was fast enough to take a screen shot as it was happening (discussed with Dray) and confirmed it, images will be attached as well as crash reports.

**To Reproduce**
Steps to reproduce the behaviour:
Start game play chat read, some idiot swears and get banned, game freezes crash game and throws crash report

**Expected behaviour**
The past and present text from banned to be unreadable text/removed.

**Screenshots**

**Versions**
Please give all the versions you are using:

Minecraft:

Forge: 36.1.16

MineTogether: MineTogether-1.16.4-4.1.6RC10

**Additional context**
NA
![20210618_072650](https://user-images.githubusercontent.com/45338739/122512334-027d9600-d009-11eb-8530-a221eacbf42b.jpg)
.
[crash-2021-06-12_17.04.39-client.txt](https://github.com/CreeperHost/MineTogether/files/6674869/crash-2021-06-12_17.04.39-client.txt)
[crash-2021-06-17_20.55.56-client.txt](https://github.com/CreeperHost/MineTogether/files/6674870/crash-2021-06-17_20.55.56-client.txt)
[crash-2021-06-18_09.22.16-client.txt](https://github.com/CreeperHost/MineTogether/files/6674871/crash-2021-06-18_09.22.16-client.txt)

**Comment by gigabit101** [comment]
Fixed in latest Alpha https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether
