### ISSUE TITLE
[Suggestion] Minetogether friendly name generation

### ISSUE THREAD

**Issue by FreeFull** [CreeperHost/CreeperHostGui#54]
Currently, the names in the chat consist of `User` + some number, and are rather hard to keep track of. Instead, names could be generated using a list of words, resulting in easy to understand names such as for example "SurprisedPuppy" or "ConfusedPineapple". The lists of words would have to be chosen to avoid generating non-PG13 names.

**Comment by TheBluEngineer** [comment]
The main problem with the current system right now is, that if you just want to say a number for example:
"My PC budget is 1800 monopoly dollars" It will replace the number with a User's which is close enough.
A quick fix / alternative solution is to require a prefix (or suffix if you're mad). For example: "Hello @4400"

**Comment by CH-Paul-T** [comment]
Yeah that auto complete is going away in the next version (Changed to having @ in front or the word "User"), a later version may include a word list for creation of names, but I can imagine people changing their word list for swears and then spreading screenshots right now, I'll try and get comfortable with the idea in a way and get it added in.

Chances are will probably generate the names server-side so we can update the list etc on the fly.

**Comment by CH-Paul-T** [comment]
No longer required as superseded by issue #146
