### ISSUE TITLE
on the minetogether site i cant send my ban appeal the submit butten just wont work

### ISSUE THREAD

**Issue by MedicinalPsycho** [CreeperHost/CreeperHostGui#540]
**Describe the bug**
i cant submit my appeal ticket

**Expected behaviour**
i expected it to send...

MineTogether: what ever the current site version is

**Additional context**
i said something along the lines of "you got 2 juggs of blood in your smeltery"
i meant it as a joke as someone was complaining of how it shows wonky amounts of blood were shown in the smeltery

**Comment by Draylynn** [comment]
"Jugs" wouldn't have got you banned.
Ban removed.

If you're using any invasive browser plugins, they may be interfering with operation of the website. Eg: NoScript.
