### ISSUE TITLE
Can't submit my ban appeal on website

### ISSUE THREAD

**Issue by NolanTheGamer2741** [CreeperHost/CreeperHostGui#541]
**Describe the bug**
I can click the appeal button, and I can write it out, but if I click submit, nothing happens

**Expected behaviour**
I was hoping to appeal my ban as I feel like my message was within guidelines. I did not say any explicit words, nor did I insult anyone, nor did I attempt to bypass filters. I wrote the message in line with the topic, and kept it PG.

**Versions**

Minecraft: N/A

Forge: N/A

MineTogether: 4.1.5

**Additional context**
We were discussing what I believed was a joke rule, and my comment was "not licking walls? sounds like boomer talk" I do not see how this violated any rules, but if I did violate rules, then I apologize as I was unaware that my statement was in violation.

**Comment by gigabit101** [comment]
Can you attempt to submit an appeal again for us?

**Comment by NolanTheGamer2741** [comment]
I went to the website to submit another appeal, but it seems that I've been unbanned. I go to the account standing, and it says that I've have "previous violations", or something like that.

**Comment by gigabit101** [comment]
Perfect, Please note that ban appeals are manual and can take some time to be approved or denied
