### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by ZephyrusSky** [CreeperHost/CreeperHostGui#542]
**Describe the bug**
Hello I was hoping to appeal my ban I don't exactly remember what I said but I will keep everything G-Rated for the sake of anyone in the chat.

**Expected behaviour**
I will be good I just want to be a part of the conversation.

**Versions**
1.12.2

Minecraft:

Forge: FTB Revelations

MineTogether: ZephyrusSky

**Additional context**
Muchos thank yous if you can help me out with this

**Comment by gigabit101** [comment]
Ban appeals need to be made at https://minetogether.io/
