### ISSUE TITLE
Mine together Ban Appeal

### ISSUE THREAD

**Issue by bocha5858** [CreeperHost/CreeperHostGui#544]
Hello, I'm from Russia, for some reason my minetogether account is blocked, I don't know why, how can I unblock it?

![unknown](https://user-images.githubusercontent.com/87498561/125849462-e0569bef-5877-45ab-9280-36ddc68b7f4c.png)
![unknown (1)](https://user-images.githubusercontent.com/87498561/125849506-d5d3bafb-a4cb-429c-b355-2affc8dec500.png)

**Comment by bocha5858** [comment]
I still can't link my account, I click connect, and I have this

![image](https://user-images.githubusercontent.com/87498561/125849703-3e5716ef-78ac-44fa-ada6-f06f1e7ace39.png)
![image](https://user-images.githubusercontent.com/87498561/125849766-c646bd3e-d307-4fd3-8ac5-6b09fa2bb5d9.png)

**Comment by bocha5858** [comment]
![image](https://user-images.githubusercontent.com/87498561/125853186-825e0d7f-156c-4903-ad70-e6b11198741c.png)

**Comment by gigabit101** [comment]
Account linking should be working again now, Sorry for the inconvenience
