### ISSUE TITLE
Reconnecting

### ISSUE THREAD

**Issue by PdSXBoosted** [CreeperHost/CreeperHostGui#545]
**Describe the bug**
Keeps saying Reconnecting forever on chat after barely starting minecraft.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Minecraft
2. Load in My Save
3. Reconnecting

**Expected behaviour**
For the chat to connect

**Versions**
Please give all the versions you are using:

Minecraft: 1.12.2 (StoneBlock 2)

Forge: 14.23.5.2847

MineTogether: 2.3.6

**Additional context**
Tried to reconnect by going through disabling the Main Chat and Enabling it again (Sometimes this removes my options for MineTogeter by itself...) The only way (that seems to be working) to fix it is by either restarting my PC OR reinstalling the whole mod... Reloading the world itself doesn't help either.

**Comment by Draylynn** [comment]
MineTogether: 2.3.6 - We do not offer support for this MT build. Update your mod.
Older builds will fail chat verification.
