### ISSUE TITLE
I cant find how to ban appeal for chat so i will put it hear

### ISSUE THREAD

**Issue by fallenplayer** [CreeperHost/CreeperHostGui#547]
I was trying to type "It" but instead I miss pressed a letter and typed tit im sorry that i said it and I will try to be more careful about typing if i get unbanned

**Comment by fallenplayer** [comment]
i really want to be unbanned because im new to Direwolf and would like to ask for help from the community i really
 didnt mean to type it

**Comment by fallenplayer** [comment]
also i dont know if im banned? but when i typed it and entered all my my messages were replaced with *MESSAGE DELETED*

**Comment by gigabit101** [comment]
Ban appeals can be submitted via https://minetogether.io/
