### ISSUE TITLE
i was talking in the minetogether chat in ftb rev and suddenly it said i was disconnected

### ISSUE THREAD

**Issue by spidertiger** [CreeperHost/CreeperHostGui#548]
**Describe the bug**
i was chatting and was trying to help someone join my server(i have gotten the server working, it was just me) when it started lagging and then said i was disconnected and wouldn't let me chat. minetogether chat still works in other packs but i can't chat in ftb rev

**To Reproduce**
idk how
**Expected behaviour**
i was chatting and didn't expect for it to stop working

**Screenshots**

**Versions**
Please give all the versions you are using:

Minecraft: 1.12.2

Forge: unsure, ftb revelation 3.5.0

MineTogether:1.12.2-2.4.5

**Additional context**

**Comment by gigabit101** [comment]
Can you please provide your log files?

**Comment by spidertiger** [comment]
sorry, how to i get the log files?

**Comment by gigabit101** [comment]
https://wiki.creeper.host/books/minecraft-java-edition/page/retrieving-modpack-logs-from-twitch

**Comment by Draylynn** [comment]
As there has been no further activity on this issue, I will close it.
Please comment if/when, with logs if you wish to receive help with the mod.
