### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by xXmilchzombieXx** [CreeperHost/CreeperHostGui#549]
**Describe the bug**
My friend want to write something into the global chat but everytime he clicks "t" for opening the game crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the game.
2. Click on 't'.
3. wait some time
4. and then it crashes

**Expected behaviour**
If you click 't' the global chat should open that you can write with your friends.

**Screenshots**
![image](https://user-images.githubusercontent.com/72553828/128423055-68529f38-592b-4317-a791-af3db255164a.png)

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.5

Forge: 3.11

MineTogether: 1.16.4 - 4.1.6RC8

**Comment by gigabit101** [comment]
Update the mod to 5.0.0+
