### ISSUE TITLE
MP Tab ad pile

### ISSUE THREAD

**Issue by TheBluEngineer** [CreeperHost/CreeperHostGui#55]
Encountered a bug about a week ago. Still decided to post the issue, even though I couldn't replicate the bug today.

I run FTB Continuum1.6.0 and my Java version is: 1.8.0_191

A new creeperhost server hosting ad appeared every time I toggled Full screen mode while being in the Multiplayer tab. The issue could be resolved by either refreshing the server list or by leaving the mp tab.
I'm not sure if there are any more steps to replicate this bug, as I couldn't do it today.

**Comment by CH-Paul-T** [comment]
Can you confirm which version this was in?

We did have this bug in early versions and as far as we are aware, we killed that horrible bug asap (We're still mildly uncomfortable about the ad-like nature of that bit of the mod, but unfortunately, servers cost and as a business we need to off-set the cost of the other features).

Given what I've said above, we're absolutely devoted to making sure bugs like this, which makes the worst part of this mod, significantly worse, not happen.

**Comment by CH-Paul-T** [comment]
I believe we've had feedback that this happens when toggling full screen - Going to put this here as it's a good place to track progress.

**Comment by TheBluEngineer** [comment]
I've tried to search for the mod in the mod directory and in MC's mod-list and couldn't find it. So how do I find out which version Continuum (1.6.0) uses?

**Comment by gigabit101** [comment]
The mod is built in a way that allows the mod to load in multiple Minecraft versions.

**Comment by gigabit101** [comment]
This was fixed in the last release
