### ISSUE TITLE
Crash when clicking Community and Closed in Server List

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#550]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15698722/129965501-ec011e7c-66e9-400d-af17-c30d375c9ab4.png)
This crashes when I click it

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.5

Forge: 36.2.2

MineTogether: 1.16.5-5.0.0Alpha6

**Additional context**
https://pastebin.com/AKmcrK8u

**Comment by aaronhowser1** [comment]
Get this crash from clicking Closed: https://pastebin.com/k4FCGyGZ

**Comment by aaronhowser1** [comment]
Modpack is FTB University 1.16

**Comment by aaronhowser1** [comment]
All three crash when launching via MultiMC

**Comment by gigabit101** [comment]
Fixed in 5.0.2
