### ISSUE TITLE
chat can not see my text

### ISSUE THREAD

**Issue by zombie5layr12** [CreeperHost/CreeperHostGui#552]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Versions**
Please give all the versions you are using:

Minecraft:

Forge:

MineTogether:

**Additional context**

**Comment by zombie5layr12** [comment]
ill type in chat and know one will respond have been trying for a few days now even when chat is popping no one says anything or responds to me, playing stone block 2 this is my fisrt mod pack so maby i just did something wrong

**Comment by gigabit101** [comment]
StoneBlock 2 comes with an outdated version of MineTogether by default, You will need to update the mod to the latest version, This can be found at https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether
