### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by yanderking** [CreeperHost/CreeperHostGui#555]
I'm trying to verificate my email but i'm not getting anything. Therefore i can't use the Minetogether chat and that's upsetting

**Comment by krustymk** [comment]
Ill second this. No other way to report it either

**Comment by gigabit101** [comment]
Check your spam folder, I have tested and confirmed that the email is being sent

**Comment by krustymk** [comment]
> Check your spam folder, I have tested and confirmed that the email is being sent

To you, not to me. Pretty sure everyone knows to check spam before posting a bug report on github

**Comment by gigabit101** [comment]
> > Check your spam folder, I have tested and confirmed that the email is being sent
> 
> To you, not to me. Pretty sure everyone knows to check spam before posting a bug report on github

You would think so but this is not the case...
If you are still having the issue can you open a ticket at https://www.creeperhost.net/contact
