### ISSUE TITLE
[Bug]: Minetogether crashes client when closing connection on server

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#558]
FTB OceanBlock 1.2.0
Minecraft 1.16.5
Apparently mixins for Minetogether cause a crash when the client gets disconnected for X reason from a server.
See FTBTeam/FTB-Modpack-Issues#67 for the whole logs and info, everything should be there, at me if anything.

**Comment by Raidobw2** [comment]
I think FTBTeam/FTB-Modpack-Issues#96 might also be related, although it's crashing for a server when `/stop` is ran.
Another very similar problem, let me know if i need to make a 2nd issue for it or if this one works.
Same mod version, the mod file is `minetogether-1.16.5-5.0.1-forge.jar` for both my first comment and this one.

**Comment by gigabit101** [comment]
Fixed in 5.0.2
