### ISSUE TITLE
Nobody else ever chats in global chat

### ISSUE THREAD

**Issue by Yaco-Taco** [CreeperHost/CreeperHostGui#560]
I am using the mine together mod on FTB Interactions modpack. The chat says it is connected, but I never see anyone say anything. I can see the minetogether background in the chatbox and send messages, but I don't think anyone else sees them. I can also see my friends who I added in the past when the mod was working on the first release of Interactions, though they are not available to try a private chat. I have tried other versions of mine together available for 1.12, but they all say disconnected or eternally remain on connecting. Only the 1.10.2-2.2.5 version of mine together shows it's connected, which is the version that comes with the modpack. Maybe this is an issue with another mod in the modpack but if someone knows anything else I could try, I would love to have people to chat with in my game again. Maybe there's just no one talking in the chat at all, but I have played for long enough and enough times that I think I would have seen at least someone by now. Is only the minecraft 1.16 mod version active now, or should the 1.12.2 version work too?

Steps to reproduce the behaviour:
1. Download the FTB App
2. Download FTB Interactions 2.0.9
3. Start a singleplayer world or join a server
4. Open chatbox, and click on minetogether

**Expected behaviour**
In the past the chat just connected automatically, and I would see people talking.

**Versions**
Minecraft: 1.12.2

Forge version: 14.23.5.2847

Mine Together: 1.10.2-2.2.5

Modpack: FTB Interactions 2.0.9
![Picture1](https://user-images.githubusercontent.com/92287073/137210769-af005c7a-09cd-41e0-a197-be7ceee07fe3.png)

![Picture2](https://user-images.githubusercontent.com/92287073/137210776-5ddf0317-ecf5-4963-bdb4-6f0e7377e825.png)

**Comment by gigabit101** [comment]
Make sure you are using the latest version of the mod for Minecraft 1.12.2, If the issue continues please provide us with the log files

**Comment by Yaco-Taco** [comment]
Ok I installed version 1.12.2-2.4.5, which I think is the latest version. The chat just says disconnected now, so here's my log files. I'm not sure which ones to send so here's all of them.
[logs.zip](https://github.com/CreeperHost/MineTogether/files/7349169/logs.zip)

**Comment by gigabit101** [comment]
[14:11:44] [Client thread/WARN] [minetogether]: Invalid fingerprint detected! The file MineTogether-1.12.2-2.4.5.jar may have been tampered with. This version will NOT be supported by the author!

Can I ask where you downloaded this file from?

**Comment by Yaco-Taco** [comment]
From curseforge.com. Here: https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files

**Comment by Yaco-Taco** [comment]
I just fixed it. I had to change false to true in the ingameChatFile.txt file which I didn't know existed in the modpack's local folder. Thanks for reading through all my logs though :) Sorry for making you do that. I'm not the best with minecraft mods.
