### ISSUE TITLE
MineTogether always failing verification

### ISSUE THREAD

**Issue by kjhamlin** [CreeperHost/CreeperHostGui#563]
**Describe the bug**
MineTogether always failing to verify my account

**To Reproduce**
Steps to reproduce the behaviour:
*Bug is client specific*
1. Start Minecraft
2. Resume playing any single player world
3. MineTogether then repeatedly prints 'Attempting verification. Please wait!

**Expected behaviour**
MineTogether connects to and verifies my MineTogether account

**Screenshots**
![image](https://user-images.githubusercontent.com/78889440/137942694-bb7f40d9-c31e-445d-8494-f22b2956be36.png)

**Versions**
Please give all the versions you are using:

FTB Revelation: 3.5.0

Minecraft: 1.12.2

Forge: 8.0.99.99

MineTogether: 2.4.5
MTServer: 2.4.5

**Additional context**
Previously MineTogether was behaving properly and was connecting to chat successfully. After about a week and a half of working, MineTogether stopped being able to complete verification step. Attaching debug logs in follow up comments....

_Issues seem to start around line 47768 in log-1 with line:_ '[10:25:30] [ForkJoinPool.commonPool-worker-10/INFO] [minetogether]: Starting new Chat thread'

**Comment by kjhamlin** [comment]
Broken log:
[debug-1.log.gz](https://github.com/CreeperHost/MineTogether/files/7374777/debug-1.log.gz)
(unzipped log didn't want to upload, sorry)

**Comment by kjhamlin** [comment]
Working log:
[debug-5.log.gz](https://github.com/CreeperHost/MineTogether/files/7374783/debug-5.log.gz)

**Comment by gigabit101** [comment]
We made a change to the server last night, Are you able to connect now?

**Comment by kjhamlin** [comment]
No :c as of right now I am still getting the awaiting verification messages.

**Comment by gigabit101** [comment]
closed due to inactivity
