### ISSUE TITLE
Multiplayer Screen CreeperHost Advertisement returns after dismissal upon pack reload

### ISSUE THREAD

**Issue by SephirothWS** [CreeperHost/CreeperHostGui#564]
**Describe the bug**
CreeperHost advertisement in Multiplayer Menu returns after having been dismissed when the pack reloads.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the modpack.
2. Click on Multiplayer.
3. Click the X on the CreeperHost advertisement pinned to the top of the multiplayer menu
4. Watch as the advertisement disappears.
5. Return to main menu.
6. Click on Multiplayer again
7. Watch as the advertisement is still dismissed.
8. Close the pack.
9. Relaunch.
10. Click on Multiplayer.
11. Observe as the advertisement has returned.
12. ???
13. Cry as you realize advertisement are forced upon users.

**Expected behaviour**
Dismissing the advertisement is REMEMBERED across separate play sessions and should NOT return after reloading the pack

**Screenshots**
![Image](https://camo.githubusercontent.com/99fc5886fda01668f50b928c543776e7a88f4876714878e347697e5854cf5785/68747470733a2f2f692e696d6775722e636f6d2f383866353453562e706e67)

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.5

Forge: ~Whatever is in FTB OceanBlock v1.4.1~ 36.2.8

MineTogether: ~Whatever is in FTB OceanBlock v1.4.1~ 1.16.5-5.0.2

**Additional context**
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/168

**Comment by Cloudhunter** [comment]
I've edited the issue to make it more respectful. Thank you for your report.

**Comment by gigabit101** [comment]
Fixed in 1.16.5-5.0.5
