### ISSUE TITLE
Restart Crash

### ISSUE THREAD

**Issue by burg5204** [CreeperHost/CreeperHostGui#565]
Using Pterodactyl Panel if server is set to restart it will process an error on loop for a "discoverability=public" server. When it's switch to "unlisted" crashing restart error disappears. Error does not occur on stop or start commands, just restart.

**Versions**
Please give all the versions you are using:

Minecraft: 1.16.5

Forge: 36.2.8

MineTogether: 5.0.2-forge

Server Crash Log:
https://pastebin.com/MBR8GxJ7

**Comment by gigabit101** [comment]
Fixed in 1.16.5-5.0.5
