### ISSUE TITLE
Disabling MineTogether breaks chat

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#567]
**Describe the bug**
Disabling MineTogether breaks chat

**To Reproduce**
1: Go to singleplayer
2: Disable the Minetogether chat
3: Try to say something in chat or use a command
4: It doesn't work. You can't do anything chat related anymore.

**Expected behaviour**
To be able to use commands and the chat.

minetogether-1.16.5-5.0.2-forge.jar

**Comment by sportsziggy** [comment]
Yep, had to delete the minetogether mod, then reinstall it to get chat back working.

**Comment by gigabit101** [comment]
Fixed in 1.16.5-5.0.5
