### ISSUE TITLE
Mentions are viewed as code rather than a name for the person mentioned

### ISSUE THREAD

**Issue by Ironcanon** [CreeperHost/CreeperHostGui#569]
**Describe the bug**
As per the title, when you get mentioned instead of your name it is a TextComponent object

**To Reproduce**
Steps to reproduce the behaviour:
1. Join the chat
2. Have someone mention you
3. See error

**Expected behaviour**
My name to be written as regular text

**Screenshots**
![IssuesWithMentions](https://user-images.githubusercontent.com/24834993/140590629-0fd767b2-8c21-481e-9057-b79b710f3478.png)

**Versions**
Please give all the versions you are using:

Minecraft:
1.16.5

Forge:
36.2.8

MineTogether:
minetogether-1.16.5-5.0.2-forge

**Additional context**
As seen here (https://imgur.com/a/Fcj65A9) for the person not being mentioned no text is wrong.

**Comment by gigabit101** [comment]
Fixed in 1.16.5-5.0.5
