### ISSUE TITLE
Banned - Contact Admins?

### ISSUE THREAD

**Issue by CakeArmy** [CreeperHost/CreeperHostGui#57]
Hi,

I was banned from using the chat for using a curse word (fuck) and like the other issues posted for similar things, I was not insulting anyone, merely stating my frustration for dying... again. I'd like to plead my case to a staff member and the website (minetogether.io) appears to be down. What is the proper way to contact a staff member?

Thanks!

**Comment by CH-Paul-T** [comment]
All bans are final, rules are clearly displayed on entering.
