### ISSUE TITLE
MineTogether Account Standing does not reflect account status.

### ISSUE THREAD

**Issue by JayLocke226** [CreeperHost/CreeperHostGui#570]
**Describe the bug**
MineTogether website indicates my account is in good standing but, Minecraft Client Indicates that I am banned.

**To Reproduce**
1. Get banned from MineTogether chat (Verify in the client)
2. Log into https://minetogether.io
3. Click on Account Standing
3. View status of the account, appears as Good Standing

**Expected behavior**
Expected to be in poor standing or a ban screen.

**Screenshots**
![Banned](https://user-images.githubusercontent.com/51032821/140635324-3e9ad05a-4dca-48b9-a78c-2590cb7ca805.JPG)
![Good Standing](https://user-images.githubusercontent.com/51032821/140635326-1039428a-c890-4196-8a85-db9c17908ce4.JPG)

**Versions**
Please give all the versions you are using:

Minecraft: 1.16

Forge: 36.2.8

MineTogether: 5.0.2

**Additional context**

I did wait several hours between the initial ban and this post to allow for any delay that may have occurred in the standing system but, at this point I believe it may be a bug.

If possible, I would also like to appeal my ban. I assume it is because I broke the rule "No swearing". I was responding to someone who earlier asked "What is wheaton's law?" and I replied "Dont be a dick". I believed I would not get in trouble as that is directly referencing a rule. I apologize for violating the no swearing policy and, if I am allowed to return, I will refrain from further infractions.

Thank you.

**Comment by gigabit101** [comment]
closed due to inactivity
