### ISSUE TITLE
Spawn protection problem

### ISSUE THREAD

**Issue by ghost** [CreeperHost/CreeperHostGui#575]
I can't change spawn protection for a friend joining my server

Steps to reproduce the behaviour:
1. Invite friend to your game
2. He can't destroy any blocks in 16 block radius

**Expected behaviour**
Change spawn-protection integer

**Versions**
Newest

Minecraft:
1.16.5

Forge:
36.2.9

MineTogether:
1.16.5-5.1.1

**Comment by gigabit101** [comment]
I don't think that "Lan worlds" support spawn protection, I will have to check the code to confirm

**Comment by gigabit101** [comment]
Can confirm that "lan" worlds do not have spawn-protection rules or a few other options.
