### ISSUE TITLE
DMs not rendering within the darkened background area

### ISSUE THREAD

**Issue by Gaz492** [CreeperHost/CreeperHostGui#576]
**Describe the bug**
When sending/receiving a DM from a friend the text is rendered outside the box depending on the GUI scale set

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to friends list
2. Click on a friend
3. Send any message 
4. Message will not render in the correct place

**Expected behaviour**
Message shows up within the darkened message box area

**Screenshots**
https://i.wuffs.dev/2021/11/javaw_2021-11-24_19-52-36.png

**Versions**
5.1.1

Minecraft:
1.16.1

Forge:
36.2.0

**Comment by gigabit101** [comment]
Fixed in 1.18+
