### ISSUE TITLE
[Bug]: encountered an error during the side_event event phase

### ISSUE THREAD

**Issue by rowle1tj** [CreeperHost/CreeperHostGui#583]
### Describe the bug

During a fresh install, I get an error with a null pointer exception that causes startup to fail.

### Steps to reproduce

1. Create new MuliMC instance (the FTB APP breaks even worse than this).
2. Select FTB Endeavour from the list of FTB modpacks
3. Update Instance settings to use a java 8 runtime and memory settings to 8 gigs min, 8 gigs max
4. Launch and get the error

Error Report: https://pastebin.com/GV965TNg

### Expected behaviour

The modpack loads and allows me to play it.

### Version

minetogether-1.16.5-5.1.2-forge.jar

### Minecraft Version

1.16.5

### Forge Version

36.2.19

**Comment by gigabit101** [comment]
It looks like getUUID() is returning null, This is got from the GameProfile and if this is null there is a larger problem here, I am going to add a fix for this but this will cause MineTogether to not load.

Can I ask if you are using offline mode or do you not "own" Minecraft?

**Comment by rowle1tj** [comment]
I am not using offline mode and I do own Minecraft.  For some more context I had just moved my account to a Mojang account so maybe that has something to do with it.  I ended up reinstalling FTB App and the client finishes loading and lets me play now.  Still a weird issue.

**Comment by gigabit101** [comment]
This should be fixed in the 1.18+
