### ISSUE TITLE
[Bug]: Crashed shortly after going to the multiplayer screen.

### ISSUE THREAD

**Issue by frikinjay** [CreeperHost/CreeperHostGui#586]
### Describe the bug

I clicked on the multiplayer button and it loaded for a couple seconds and then crashed.

### Steps to reproduce

1. Have this mod present with some other mods.
2. Click the multiplayer button on main screen.
3. Crashes after a second or so into the screen.

### Expected behaviour

To not crash.

### Version

5.2.0

### Minecraft Version

1.18.1

### Forge Version

fabric loader 12.12

**Comment by gigabit101** [comment]
Can you please provide us with the log?

**Comment by frikinjay** [comment]
The issue seem to have resolved itself.
