### ISSUE TITLE
[Bug]: MineTogether Connect

### ISSUE THREAD

**Issue by BreathWhisper** [CreeperHost/CreeperHostGui#587]
### Describe the bug

Can't open world for friends

### Steps to reproduce

1. Open Minecraft
2. Opened the world
3. pressed ESC and open world to friends

### Expected behaviour

The world is open to the web

### Screenshots

![unknosadsdwn](https://user-images.githubusercontent.com/86289670/151218058-b68219b7-0c67-4a0f-8caa-cbea7a276a15.png)

### Version

1.16.5-5.1.2

### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Additional Information

Yesterday we played with a friend and everything was fine, but today the world opened once. After some time, the friend flew out and was no longer able to join. When trying to open the world, messages from the screenshot appeared. It is strange that a friend could open the world. After reinstalling the assembly, the error did not go away.

**Comment by BreathWhisper** [comment]
It's FTB Oceanblock 1.11.0 modpacks

**Comment by gigabit101** [comment]
This should have been fixed a while ago with a server-side update, If this issue continues please feel free to reopen
