### ISSUE TITLE
[Bug]: Minecraft Acct Link Certificate Revoked

### ISSUE THREAD

**Issue by Targren** [CreeperHost/CreeperHostGui#589]
### Describe the bug

It looks like the certificate for mc.auth.minetogether.io wasn't renewed before the mass revocation

### Steps to reproduce

1. Login to Minetogether.io
2. Go to "Connections"
3. Click on the "Link" icon on the "Minecraft" card
4. Get "Certificate Revoked" Error 

### Expected behaviour

Load page with secure transport

### Screenshots

![Capture](https://user-images.githubusercontent.com/11566412/153422442-d8965a80-5245-4dc7-a15c-c17afdffc5ad.PNG)

### Version

N/A - Website

### Minecraft Version

N/A - Website

### Forge Version

N/A - Website

### Additional Information

Website Issue

**Comment by gigabit101** [comment]
You need to connect to mc.auth.minetogether.io in-game and not via your browser

**Comment by Targren** [comment]
The link on the website still tries to open it instead of giving the instructions/code input like in the docs

**Comment by gigabit101** [comment]
![image](https://user-images.githubusercontent.com/5615438/153428456-ed22454d-a4ce-467f-9b56-259f99d3e889.png)

After you attempt to connect you will get kicked with a message that contains a code for you to put in the box

**Comment by Targren** [comment]
I did that, but I don't get a box. I get the screenshot I pasted

**Comment by gigabit101** [comment]
Once again, You should not be opening mc.auth.minetogether.io in your web browser, You need to connect to it as a Minecraft server in your Minecraft Client
