### ISSUE TITLE
Banned from chat

### ISSUE THREAD

**Issue by almamooth** [CreeperHost/CreeperHostGui#59]
I created a hamachi server with my friend, We added eachother as friends in the game and decided to test out if being friends changed anything in the chat. Not knowing I was in General chat I typed "Hello bish" because I thought it was a private hamachi server so no one would read and my friend replied with "hello. bish" and the next thing I know an admin said "I spy with my little eyes. 2 players about to get banned" and I got banned without a warning, I didn't even get to talk with the admin.

Edit: I didn't realise someone said "Hello guys" right above my message until I looked at the screenshot

![screenshot_10](https://user-images.githubusercontent.com/47742771/52947618-ae0e7100-3390-11e9-8c95-c19df56047ad.png)

**Comment by CH-Paul-T** [comment]
The rules are clearly visible in your screenshot.

"Any profanity, disrespect or defamation will be met with a permanent ban".

You where banned, in jest or not, for being disrespectful.
