### ISSUE TITLE
[Bug]: People looks like doesn't see my messages

### ISSUE THREAD

**Issue by ZitrYz** [CreeperHost/CreeperHostGui#591]
### Describe the bug

When im on my singleplayer and im typing it looks like noone see my messages. I can see other people messages but I think they dont see my messages. They are typing and when im asking if they see my messages they are not even responding.

### Steps to reproduce

1. You have to get banned.
2. Go to minetogether side and appel for unban.
3. Get unban
4. Restart minecraft
5. Connect to your world.
6. There it is. Noone see your messages but you can see other people messages.

### Expected behaviour

I expected that after unban I could write again and text with people.

### Screenshots

![2022-02-19_12 27 08](https://user-images.githubusercontent.com/84678399/154798912-07cea3d4-53c6-4a25-ab38-e80c8d747f82.png)

### Version

MineTogether-1.12.2-2.3.6.jar

### Minecraft Version

1.12.2

### Forge Version

14.23.5.2847

**Comment by gigabit101** [comment]
Update the mod to the latest version on CurseForge for Minecraft 1.12.2 https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files
