### ISSUE TITLE
[Bug]: Online mode check, srsly!?

### ISSUE THREAD

**Issue by Chaoschaot232** [CreeperHost/CreeperHostGui#593]
### Describe the bug

It is agains any means checking if the game is in online or offline mode

### Steps to reproduce

Start either a 2nd MC Instance or try to play in SP because you don't have internet for what ever reason and MTG tells you that it will be disabled ALL FEATURES until you are back online.

### Expected behaviour

No online/offline check as this is against any means because nobody is allowed to check against online/offline mode since this is rude and does not even cover the fact that sometimes your internetconnection can get lost which disables MTG and does not re-enable itself without restarting the hole client!

### Version

latest MTG for 1.12.2

### Minecraft Version

1.12.2

### Forge Version

Forge for MC 1.12.2 latest

**Comment by Draylynn** [comment]
If you have no internet; MineTogether goes into offline mode during startup - chat and server advertising features disabled.
If you are started in online mode and lose connection, chat will disconnect - Newer builds have some reconnection logic built in.

**If reconnection is failing, please submit a new ticket with complete details on MineTogether version and build, and, mod pack version and build, Forge version and build.** '1.12.2 - latest version' is not nearly enough information for investigation, there are many builds on this version and many mod packs that may conflict.
