### ISSUE TITLE
[Bug]: Username's not appearing in in-game-chat 1.18.2 ver 5.2.3

### ISSUE THREAD

**Issue by BrewingCoder** [CreeperHost/CreeperHostGui#599]
### Describe the bug

According to moderator and other uses they see my registered username.  In the local chat window I see I only see moderators user names. All other's are the shadow user names  (USER#FOO, etc)

### Steps to reproduce

Use DW20 1.18.2 pack as an example.  Connect up with a verified account, attempt to chat.

### Expected behaviour

that you see your, and other players, registered user names.

### Version

5.2.3

### Minecraft Version

1.18.2

### ModLoader Version

40.1.19

**Comment by gigabit101** [comment]
I can not reproduce this issue everything seems to be working fine.
Please note that these requests to get the username are done on threads and require a web request, We have recently increased the timeout time on these requests so this might have resolved the issue for you, You will need to update the version of MineTogether you are using to get this fix
