### ISSUE TITLE
Can't find documentation on /chpregen

### ISSUE THREAD

**Issue by Huene** [CreeperHost/CreeperHostGui#6]
I'm looking for a way to stop it, I apologize for opening an issue, but I couldn't find a discord, irc, or other less formal place to question it and I didn't think it appropriate to open a ticket with creeperhost proper

**Comment by Naxanria** [comment]
Looking through the code there is indeed no way to stop it for now.
My suggestion would be to stop the server, find the pregenData.json file in the world save folder, remove it.

Would be nice to have the command handle that though.

**Comment by Cloudhunter** [comment]
Hi! It indeed doesn't exist, but I don't mind adding it, and it will be added Soon(tm) :)

**Comment by Cloudhunter** [comment]
Features have now been added as of the latest version :)
