### ISSUE TITLE
Moderators are abusing their function

### ISSUE THREAD

**Issue by Iwitrag** [CreeperHost/CreeperHostGui#60]
Good day,

I really enjoy the possibility to global chat across servers with other players and share knowledge and information about modpacks.

There is one problem - chat moderators. I don't know how are they being chosen as moderators but I've witnessed a lot of permanent bans for nothing - myself included. I am not aware of breaking any rules and I have been permanently banned on nickname Iwitrag.

Maybe there is some system of autobanning which is malfunctioning?

**Comment by Draylynn** [comment]
Moderators do not 'randomly' ban. The rules are quite clear;
Keep the channel PG (safe for kids), English-only, follow Wheaton's law and generally be respectful to other players in the chatroom.

**Comment by Iwitrag** [comment]
It seemed quite random to me. I have seen lot of people complaining about their friends being banned for no reason and then even those people who were complayining were banned. And then one day I could not connect to the chat server - banned without any reasonable reason.

**Comment by Draylynn** [comment]
We have no way of finding our your ID to un-ban you or even investigate this. We do not store your nicknames. If you had a screenshot of the chat or a timestamp (UK) we could see if the logs are still available to find your ID and investigate further.
A lot of people who complain about being 'banned for no reason' have let an F-word slip, or, have popped in chat and just called everyone 'gay', or, generally breaking the rules.

**Comment by Iwitrag** [comment]
![2019-02-19_00 50 06](https://user-images.githubusercontent.com/6575704/53082727-c0f28400-34fd-11e9-8a39-efdac7fd960e.png)

**Comment by CH-Paul-T** [comment]
![image](https://user-images.githubusercontent.com/7502714/53082876-b59b5a80-34f5-11e9-8b1c-1e6907cb5fb0.png)

I think you got your answer.

Closing this issue.

**Comment by Iwitrag** [comment]
I was asking about the ban above, it was not meant to be disrespectful in any means, that's why I even censored the word. I was not calling anybody like that nor being disrespectful or abusive to anyone ever.

**Comment by CH-Paul-T** [comment]
Yet, you still saw it acceptable to send an offensive word with only one letter censored to several thousand potential children.

This issue is finished.

**Comment by CH-Paul-T** [comment]
FYI - The wording "Was that racial slur bannable", or "Was the n-word bannable?" would've been acceptable. (Clarified from our own discord questions regarding this issue.)
