### ISSUE TITLE
[Suggestion]: Don't ban for typos

### ISSUE THREAD

**Issue by CrossOnDiscord** [CreeperHost/CreeperHostGui#601]
### Is your feature request related to a problem? Please describe.

It's been a month and a half since I was banned off the platform for a typo. I put "Have fu", immediately afterwards typed "fun*" and was banned the next day for "Using Expletives". I put in an appeal the same day, and again it's been a **MONTH AND A HALF**. I've been told this process is usually quick for Minetogether, taking a week or two max. 

 It's frustrating me since being able to talk while in single-player made me able to enjoy it as I get extremely bored extremely quickly while on my own.

### Describe the solution you'd like

A solution I'd like to see is to look at the context of the situation for a report and the surrounding text messages, before acting upon a report. Currently it seems like they see a report for a message, look at one message, and if it's even remotely explicit they'll end up banning you.
Please just quit slacking off, look into these better, and stop permanently banning for a typo that was _immediately_ corrected.

### Additional context

I'll give the BanID if need be, but this is infuriating.

**Comment by gigabit101** [comment]
A lot of the bans are automated, If you believe the ban was invalid you can appeal the ban at our website https://minetogether.io/
