### ISSUE TITLE
[Bug]: Can't add friends

### ISSUE THREAD

**Issue by ScoredKinkajou** [CreeperHost/CreeperHostGui#602]
### Describe the bug

Can't add friends

### Steps to reproduce

1. Launch any FTB Modpack
2. Go to Friends List
3. No add friend button
4. Right clicking name in chat to add causes game to lag, then nothing happens

### Expected behaviour

Expected to add friends

### Version

5.2.3

### Minecraft Version

1.18.2

### ModLoader Version

Forge

**Comment by gigabit101** [comment]
Can you provide your debug.log file, please?

**Comment by ScoredKinkajou** [comment]
[debug-1.log.gz](https://github.com/CreeperHost/MineTogether/files/8818703/debug-1.log.gz)
[debug.log](https://github.com/CreeperHost/MineTogether/files/8818706/debug.log)
Not sure which one you needed, so uploaded one from May 26th, and one from today.

**Comment by KaiserThompson** [comment]
I'm having the same issue. I turned on debug mode in the configs and recorded some attempts to add friends without any other mods installed.
[debug.log](https://github.com/CreeperHost/MineTogether/files/8820593/debug.log)
[latest.log](https://github.com/CreeperHost/MineTogether/files/8820594/latest.log)
[superdebug.txt](https://github.com/CreeperHost/MineTogether/files/8820731/superdebug.txt)

**Comment by DJJolty257** [comment]
Same sort of issue - 1.16.5 version. No option to add friends and the FTB app thinks I've already sent a friend request to them. Tried to change accounts, no luck

**Comment by DJJolty257** [comment]
> Same sort of issue - 1.16.5 version. No option to add friends and the FTB app thinks I've already sent a friend request to them. Tried to change accounts, no luck

I can provide some additions if you need - this issue seems to be for most versions

**Comment by Draylynn** [comment]
Is this still occurring on updated MT builds? In the last week the friends system has been smacked around and has been working normally.

**Comment by Classified3939** [comment]
So, I just installed this mod and made an account, but I can't seem to even SEE the add friends button. 
![image](https://user-images.githubusercontent.com/102702965/180591265-4b047f9e-c401-4432-b714-76810bb954d5.png)

Is there something I'm missing? This is on Fabric 1.19 btw, latest version on CurseForge.
