### ISSUE TITLE
[Bug]: MineTogether sits at "Verifying" 

### ISSUE THREAD

**Issue by MadCat256** [CreeperHost/CreeperHostGui#603]
### Describe the bug

My mineTogether client never verifies so I cannot chat.

### Steps to reproduce

Launch game, Click chat icon, see that it's verifying, wait as long as you like it will never move off of "verifying"

### Expected behaviour

Client verifies and enables chat.

### Screenshots

![image](https://user-images.githubusercontent.com/103010441/171270613-2791a2ab-ad78-4965-bde8-7541be96e21c.png)

### Version

Happens in multiple, including forge-1.18.2-5.2.4 (Direwolf20) and 1.16.5-5.1.2-forge (Oceanblock)

### Minecraft Version

Again multiple, including 1.18.2 and 1.16.5

### ModLoader Version

Again multiple, including Forge 40.1.25 and Forge 36.2.33 

### Additional Information

Even if I load a world and play for hours I never get chat. As it affects multiple versions in multiple modpacks I'm assuming it's a setting on my computer somewhere but I don't know where and I've had no luck finding an answer using Google.

Logs attached
[Logs 1.18.2.zip](https://github.com/CreeperHost/MineTogether/files/8808874/Logs.1.18.2.zip)
[Logs 1.16.5.zip](https://github.com/CreeperHost/MineTogether/files/8808880/Logs.1.16.5.zip)
.

**Comment by gigabit101** [comment]
Can you turn on the debug option in the config and try to start the game again, This will add a lot more information to your log?

**Comment by MadCat256** [comment]
Have at em. This set is from my 1.18.2 Direwolf20 modpack instance. I can pull a set from the 1.16.5 Oceanblock this evening after work if needed
[Logs 1.18.2.zip](https://github.com/CreeperHost/MineTogether/files/8814848/Logs.1.18.2.zip)
.

**Comment by MadCat256** [comment]
Oh for Pete's sake.

I finally managed to link my Minecraft account with the website and may have figured out what the problem is. I apparently got banned back in November for sending the message "Windows can be set to turn stickykeys back on if you hold the shift key a certain amount of time" Ban reason: use of expletives.

So the client appears to be silently failing at the "verifying" stage and never informing me that I've been banned. This should probably get fixed to at least inform the user what is going wrong so steps can be taken to address the issue.

Also, someone needs to teach Freddy what an expletive is and isn't...
