### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Devekusu03** [CreeperHost/CreeperHostGui#606]
### Describe the bug

Minetogether "Open to Friends" button is not even clickable ...

### Steps to reproduce

We were playing on the "Eggblock" modpack on Aternos, but after some bugs in the roost mod, we needed to update it. After updating it, because of modpacks on "Aternos" that are not customizable, we needed to find another way to play co-op. We tried "Hamachi" but a friend with a potato PC got stuck on the logging in screen. We tried "Essential mod" but the same thing happened and it was a little bit laggy as well, so lastly, we tried MineTogether mods' open to friends feature but it wasn't clickable. When we tried to invite friends, it said "Couldn't invite-server not public/mod not on server." I can't get it and I can't figure out what to change public if I need to do so. Can anyone help me please?

### Expected behaviour

I would expect to be able to directly open my world to friends.

### Screenshots

![unknown](https://user-images.githubusercontent.com/107549103/173807384-60be56e7-bfba-4966-8749-bcf4cacc4b99.png)
![unknown](https://user-images.githubusercontent.com/107549103/173808055-3bfc0fb3-a9ee-464b-aca1-c1ab8aecb853.png)

### Version

2.4.5

### Minecraft Version

1.12.2

### ModLoader Version

Forge

### Additional Information

My Email Adress : devekusu03.1@gmail.com

**Comment by Devekusu03** [comment]
By the way "Open to Lan" button was clickable before but i clicked it to allow cheats .

**Comment by DJJolty257** [comment]
It honestly feels like Minetogether is very broken - the friends feature hardly works and it's a pain if neither side can send a friend request to each other

**Comment by gigabit101** [comment]
This should be better now, There was some issues with the api that have now been resolved
