### ISSUE TITLE
[Suggestion]: Anchor "Friends List" in the Escape menu to the top right of the screen

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#607]
### Is your feature request related to a problem? Please describe.

Hi, if a mod that modifies the Escape menu in-game adds a button for example, the MineTogether button is moved.

Versions:
Minecraft `1.18.2`
Forge `40.1.52`
MineTogether `minetogether-forge-1.18.2-5.2.7.jar` (latest in 1.18.2)
Better Mods Button `BetterModsButton-v3.2.2-1.18.2-Forge.jar` https://www.curseforge.com/minecraft/mc-mods/better-mods-button

Here is what is normally shown with a normal instance:
![image](https://user-images.githubusercontent.com/17010632/176601238-7113389b-4c66-442f-be22-24b77d311561.png)
Here is what shows if you add Better Mods Button for example:
![image](https://user-images.githubusercontent.com/17010632/176601279-973909d4-68df-4377-8b9f-7f56485a5ae7.png)

### Describe the solution you'd like

I'd like to suggest anchoring that button to the top right instead of a child button such as "Back to game", if that is currently the case and could be changed. This would allow better compatilibity with mods that change the Escape menu I think

### Describe alternatives you've considered

Removing Better Mods Button, since that is the only "solution"

### Additional context

This is happening in FTB Plexiglass Mountain on Forge 1.18.2.

Thanks for reading my suggestion!

**Comment by gigabit101** [comment]
closed due to inactivity
