### ISSUE TITLE
[Bug]: Weird Ban

### ISSUE THREAD

**Issue by Onylxis** [CreeperHost/CreeperHostGui#609]
### Describe the bug

I somehow got banned on a day I wasn't even playing on, And I don't know why

### Steps to reproduce

I'm unsure.

### Expected behaviour

I got banned by draylynn with a weird reason and message.

### Screenshots

![image](https://user-images.githubusercontent.com/108771271/177435805-04569c69-0187-4adb-b375-3e5c831157ff.png)

### Version

None

### Minecraft Version

None

### ModLoader Version

None

### Additional Information

I have sent an appeal at least a week ago, and draylynn still has not responded, The appeal read as such:
"I'm having difficulties understanding the reason for my ban, and the message as well.. If you could please provide some clarification as to the ban reason and ban message, I would be more than happy to send a proper appeal stating as to why I should be forgiven of my crime." 

On another note, I am well aware that I sent this in the bug report section, because without a proper reason as to why I was banned, I have my own reason as to suspect that the system has some how glitched. Sorry in advance if I am incorrect...

**Comment by Onylxis** [comment]
Also to back this up that I was not playing at that time, I was still in summer school on 2022-06-23 00:11:33

**Comment by Onylxis** [comment]
@Draylynn Please answer my call for action. ^

**Comment by Draylynn** [comment]
Should know by now if you're calling me by name, Discord is much faster at getting a response from me.
The ban code is a chat timestamp of sorts because a moderator issued the ban and not a bot...
'Smash or pass', we don't make references like that in chat. Behave.
