### ISSUE TITLE
[Bug]: Verifying

### ISSUE THREAD

**Issue by DaiXD97** [CreeperHost/CreeperHostGui#611]
### Describe the bug

Verifying

### Steps to reproduce

Dont know i how to reporduce but i was just playing and then i was not verifyed anymore, and my friend cant get the verifying at all even after doing all the steps correctly

### Expected behaviour

Might have something to do with with the discord 

### Version

1.16.5

### Minecraft Version

1.16.5

### ModLoader Version

Forge

### Additional Information

everything worked perfect but now after useing the mod for 2-3h me and 2 of my friends went for verifyed to verifying, while one of the friends didnt get verifyed at all after doing all the steps correctly

**Comment by gigabit101** [comment]
closed due to inactivity
