### ISSUE TITLE
[Bug]: Failing to verify to chat

### ISSUE THREAD

**Issue by LogQa1234** [CreeperHost/CreeperHostGui#612]
### Describe the bug

Its not verifying my game session

### Steps to reproduce

It just happens?
![image_2022-08-03_094654925](https://user-images.githubusercontent.com/65518083/182638112-f0a40697-521f-4ec3-9cd6-8b338c015ca5.png)

### Expected behaviour

I'd expect it to verify my game session in a few seconds or minutes to let me say something in chat but its just not

### Screenshots

screen shot is in the steps to reproduce

### Version

1.16.5-5.1.2

### Minecraft Version

1.16.5 Not Too Complicated 2

### ModLoader Version

36.2.35

### Additional Information

This has been happening for a few days now

**Comment by gigabit101** [comment]
closed due to inactivity
