### ISSUE TITLE
[Bug]: Public server list does not show any servers

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#616]
### Describe the bug

On the Minetogether public server list nothing shows up, which is odd because my server used to show up in 1.1.1 but after updating it to 1.2.0 nothing shows up, nothing in the public, community and private sections.

### Steps to reproduce

1. Install and play FTB Plexiglass Mountain 1.1.1, the public server list shows up
2. Update to FTB Plexiglass Mountain 1.2.0, which updates MineTogether to `minetogether-forge-1.18.2-5.2.8.jar`
3. Public server list is empty apparently

### Expected behaviour

I'm assuming the public server list should not be empty

### Screenshots

Sorry, don't have any :/

### Version

minetogether-forge-1.18.2-5.2.8.jar

### Minecraft Version

1.18.2

### ModLoader Version

40.1.76

### Additional Information

This is relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1314

I don't know if it's a technical issue or something with MineTogether, I'm looking for help towards this or why that user cannot see the public server listings

I'm one of the devs for FTB Plexiglass Mountain and the only changes between 1.1.1 and 1.2.0 is the MT version updated and Sentry was enabled again in the config

Thanks in advance for any info!

**Comment by Draylynn** [comment]
Is this still happening on MT 6.0.11?

**Comment by Raidobw2** [comment]
Haven't updated MT in Plexiglass yet, but it will be today (Nov 8). I'll assume this will fix it since its been rewritten, so I'll close this. If it happens again I'll report it :)
