### ISSUE TITLE
[Suggestion]: I'm still wrongfully banned

### ISSUE THREAD

**Issue by CrossOnDiscord** [CreeperHost/CreeperHostGui#617]
### Is your feature request related to a problem? Please describe.

I've been banned for saying 'have fu'. I've already inputted an appeal. I know it's a valid appeal. It's been over 6 months since I've put it in.
My previous issue #601 was closed by gigabit101 telling me to appeal, and that most bans are automated. I had already appealed on the day I was banned, and unless the name of the system that automatically bans takes 4 hours and is named 'Freddy', I highly doubt it was automatic. I had already appealed on the day I was banned.
I'm unable to appeal again, I know it was an invalid ban. Someone said they were heading to an event in their real life, I mean to say "have fun", mis typed the n and typed "have fu". I immediately corrected with 'have fun'. I was banned later that night for use of explicatives.

It's extremely infuriating that I've been banned off the platform for so long for a mistype.

### Describe the solution you'd like

Look into chat history before issuing a manual ban. Typos happen and quite a big reason there's still humans to do these jobs is because automation has a tough time looking into context.

### Additional context

I apologize for my rude behavior but you have to see where I'm coming from. It's extremely annoying that I'm unable to chat with people while playing in singleplayer.

![image](https://user-images.githubusercontent.com/105819281/196327826-95c74ae2-8ab3-4be6-a828-0e4e7ebb3f0a.png)

**Comment by Draylynn** [comment]
I can't seem to find your appeal, however the ban is reversed. Unfortunate typo, careful with typo's, the bot is programmed to detect and ban possible shorthand vulgar language... It's not so great on context.
