### ISSUE TITLE
Request for Assistance

### ISSUE THREAD

**Issue by TemporaryUsernameForToday** [CreeperHost/CreeperHostGui#62]
[resolved]

**Comment by Draylynn** [comment]
Hi there,

A) Thanks for the screeny, it really helps to locate the chat in question.
B) I'm not seeing anything against the rules here, let alone "Inappropriate Language", I'll have a word with the staff member that issued it.
C) You're un-banned.

~Draylynn_T

**Comment by Draylynn** [comment]
After a natter with the staff member, they may have 'mis-clicked' on your ID. Whilst they assured me that they had un-banned you moments after, I did not see this event take place.
As a result, well be replacing her make-up with whipped cream (cocoa blended to mix in with the rest of her make-up tray - Make-up roulette!), sabotaging her PC to routinely play "Techno Chicken" very loud, every few hours, and have rearranged the keys on her keyboard.

**Comment by TemporaryUsernameForToday** [comment]
Draylynn,

Thank you kindly.

I tried to reconnect after being disconnected to no avail. However, perhaps the reversion wasn’t processed yet.

I’ll give it another go in around nine hours from now. I’ll provide a status update at that time.

Thank you for the assistance!

**Comment by Draylynn** [comment]
Hi there,

You're definitely not on the ban list; ban requests are handled really quickly by the system. Did you restart the client?

~Draylynn_T

**Comment by TemporaryUsernameForToday** [comment]
Hi,

I'm back! I did restart at the time but I suppose it didn't process before I attempted a reconnect.

Issue resolved. Thank you!
