### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by streambrooke** [CreeperHost/CreeperHostGui#620]
### Describe the bug

Only one friend can join server

### Steps to reproduce

2 of my friends and I have been trying to start a server. We have all added each other as friends. One of us started a world and opened it to friends. It shows up in the multiplayer servers for all of us, but when one guest joins the server, the other gets a time-out request error when we try to load in.

### Expected behaviour

the expected behavior would be that we would both be able to join, as the three of us are below the player limit

### Version

1.16.5-5.1.2

### Minecraft Version

1.16.5

### ModLoader Version

CurseForge

### Additional Information

we also cant add eachother in a party, while the notification shows up in the top right, none of us have been able to figure out how to accept the party invitation

**Comment by DavidLXXV** [comment]
I'm having the same issue in the same version, have you been able to fix this problem?

**Comment by gigabit101** [comment]
closed due to inactivity
