### ISSUE TITLE
[Bug]: Cannot add friends to friends list

### ISSUE THREAD

**Issue by mmgery** [CreeperHost/CreeperHostGui#621]
### Describe the bug

Option to add friends does not display in game

### Steps to reproduce

1. Start Feed the Beast Plexiglass Mountain v1.1.1 or 1.2.0.
2. Enter single player world.
3. Press ESC to pull up menu.
4. Click on "friends list" in the top right.
5. Button to add friends does not display. The screen says "You have no friends :("

### Expected behaviour

Expected a way to add friends and did not find one. My MineTogether account is linked to Minecraft and when I write in the MineTogether chat in game it knows my display name from minetogether.io, so it's clearly connected in some sense.

### Version

5.2.7

### Minecraft Version

FTB Plexiglass Mountain 1.1.1 & 1.2.0

### ModLoader Version

FTB Plexiglass Mountain (Forge)

### Additional Information

Thank you!

**Comment by covers1624** [comment]
Can you please check if this issue persists with MineTogether 6.0.X? Most of the mod has been rewritten.
