### ISSUE TITLE
[Bug]: Disconnected

### ISSUE THREAD

**Issue by Avalonzo** [CreeperHost/CreeperHostGui#622]
### Describe the bug

The MineTogether chat seems down for the past 12 or do hours

### Steps to reproduce

1. Start FTB Inferno
2. Start a world
3. Open MineTogether
4. Says disconnected in bottom left

### Expected behaviour

MineTogether/Chat to be online

### Screenshots

https://www.dropbox.com/s/6mu9otme90n7t6y/Screenshot%202022-10-31%2008.59.32.png?dl=0

### Version

5.2.8

### Minecraft Version

1.18.2

### ModLoader Version

Forge

### Additional Information

Been trying to add a friend to MineTogether we eventually found we needed to enable Minetogether intergration in FTB APP setting which gave access to the FTB chat APP Basically MineTogether chat outside of Minecraft. Sent each other our special code we both got a weird string of number and letters as a friend.  We assume that we cannot play together as it seems MineTogether/Chat is disconnected.

**Comment by Gaz492** [comment]
Would you be able to test if the issue also happens with our new beta version available at https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/4062829.

**Comment by Avalonzo** [comment]
I just gave it a go and at 1st I got a error about needing language provider 43 and I had 40 did a little bit googling and realised the you link you provided was for the beta for 1.19.2 instead of beta 1.18.2. Once I installed the correct version the chat was connected. My friend lives in America but I'm in the UK so we will test to see if we're able to connect to each other in 5-6 hours from now.

**Comment by Avalonzo** [comment]
We still can't connect to each other and but the chat is connected for both 6.0.7 and 6.0.8 we both tried both versions and eventually managed to add each other but when I open my world friends it doesn't show up as server for my friend and vice versa. If you consider this fixed please feel free to close.

**Comment by ThePaul-T** [comment]
Is connecting working on 6.0.11 now? We're working on the connect to friends stuff at the moment, it's an ongoing effort.

**Comment by Avalonzo** [comment]
I don't know since the friend that was going to play the pack with me has given up on trying to connect to each other via MineTogether for now. I guess it was the constant waiting on me to load the modpack as it takes me 5-8 mins to load the modpack but it only take 1-2 mins for him.
