### ISSUE TITLE
[Bug]: Empty MT Chat

### ISSUE THREAD

**Issue by Gaz492** [CreeperHost/CreeperHostGui#623]
### Describe the bug

The in-game MT chat is empty and never shows anything.

### Steps to reproduce

Download and launch stoneblock 3 then go to singleplayer or multiplayer and open MT chat.
The chat box will just stay empty and not update with any incoming messages

### Expected behaviour

In-game chat shows MOTD on first connection and update with user messages.

### Screenshots

![](https://i.wuffs.dev/2022/11/javaw_2022-11-02_22-24-06.png)

### Version

6.0.7

### Minecraft Version

1.18.2

### ModLoader Version

40.1.84

### Additional Information

Debug log can be found at https://pste.me/@/SeJPU-r9bGc

**Comment by covers1624** [comment]
This has been fixed in dev.

**Comment by covers1624** [comment]
This has been fixed in MineTogether 6.0.8. Pending review on CurseForge.
