### ISSUE TITLE
[Bug]: 1.12.2 MineTogether sometimes prevent app load

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#627]
### Describe the bug

Loading stock FTB Sky Odyssey on the FTB App sometimes locks at the end and the game never opens

### Steps to reproduce

(Happens only for some users, I cannot replicate)

1. Open the FTB App
2. Load FTB Sky Odyssey
3. The log will stop at some point, and the game is stuck

Close the game;

1. Remove MineTogether from the mods folder
2. Load the same modpack again
3. You will reach main menu this time

### Expected behaviour

To reach main menu on every load regardless if MineTogether is installed

### Screenshots

None sorry I cannot reproduce.

The only info I have is from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1483, with log:
[debug.log](https://github.com/CreeperHost/MineTogether/files/9926814/debug.log)

The important bit in that log might be at the end:

`[21:19:07] [Client thread/TRACE] [FML]: Sending event FMLPreInitializationEvent to mod minetogether`

![image](https://user-images.githubusercontent.com/17010632/199680236-2fc97bf2-02c3-4acb-a872-dbf1a2ed0677.png)

### Version

MineTogether-1.12.2-2.4.4RC1.jar

### Minecraft Version

1.12.2

### ModLoader Version

Forge 14.23.5.2857

### Additional Information

FTB Sky Odyssey does not have the latest MT for 1.12.2 installed:
![image](https://user-images.githubusercontent.com/17010632/199680548-25196a46-e427-4455-bb8d-60a3dc33da78.png)

Please let me know if that could be the issue and thanks!

**Comment by covers1624** [comment]
I would highly suggest updating to that version to see if the issue persists.

I'm not sure what exactly changed between those two versions, though.

**Comment by Raidobw2** [comment]
Hmm. I'll ask the users who had the issue if they can test since I can't reproduce this myself. I'll get back to you then, at the worse I'll blind push the fix and stay on guard for a few days, thanks

**Comment by Raidobw2** [comment]
Users confirmed updating the mod fixed the problem and allowed loading normally (1.12). Cheers Covers
