### ISSUE TITLE
[Bug]: Crash when spamming chat toggle

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#629]
### Describe the bug

If you spam the chat button in the settings (a lot), you crash

### Steps to reproduce

1. Click the MT gear to access to settings
2. Locate the chat button
3. Spam it as much as you can till your cursor is frozen
4. Game crashes shortly after

### Expected behaviour

That the chat button have some antispam/timeout mechanic so you don't crash

### Screenshots

![image](https://user-images.githubusercontent.com/17010632/199696718-3e774392-0d96-4e7a-8170-e7427df3db43.png)

Log:
[crash-2022-11-03_06.08.34-client.txt](https://github.com/CreeperHost/MineTogether/files/9927390/crash-2022-11-03_06.08.34-client.txt)

### Version

minetogether-forge-1.18.2-6.0.8.jar

### Minecraft Version

1.18.2

### ModLoader Version

Forge 40.1.84

### Additional Information

Thank you for looking into it as well!

**Comment by covers1624** [comment]
This is now resolved in MineTogether 6.0.9.
