### ISSUE TITLE
[Bug]: Beta fabric instead of forge

### ISSUE THREAD

**Issue by Avalonzo** [CreeperHost/CreeperHostGui#630]
### Describe the bug

You have replaced the beta version of minetogether forge with fabric on curseforge

### Steps to reproduce

1. go to https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/4065027
2. it fabric instead of forge
3. Thankfully I was able to grab the older version from my recycle bin 

### Expected behaviour

N/A

### Version

N/A

### Minecraft Version

N/A

### ModLoader Version

N/A

**Comment by gigabit101** [comment]
That link is to the Fabric version and is set correctly, The forge version is here https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/4065023

**Comment by Avalonzo** [comment]
Ok I see it now if you go to all files I can find I meant if you go by the right hand and don't notice I like I did you end up getting the fabric instead of forge. It list it as release forge then beta fabric I was expecting it just to be the forge version on the right. So my bad

**Comment by gigabit101** [comment]
Yeah, It depends on the order they are uploaded due to how Curses site works
