### ISSUE TITLE
[Bug]: Banned messages not being scrambled

### ISSUE THREAD

**Issue by Gaz492** [CreeperHost/CreeperHostGui#633]
### Describe the bug

Banned messages are not being deleted/scrambled

### Steps to reproduce

Watch chat, when someone is banned their message is still visible 

### Expected behaviour

When someone is banned their message should be scrambled or deleted

### Version

6.0.8

### Minecraft Version

1.18.2

### ModLoader Version

40.1.84

**Comment by covers1624** [comment]
This is now resolved in MineTogether 6.0.9.
