### ISSUE TITLE
[Bug]: MT format bug HTTPS.

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#634]
### Describe the bug

Https links have an f in front of them if a chat moderator submits a link to chat.

### Steps to reproduce

Write https://url.here in MT admin mod access, watch users complain URL's aren't working when clicked on them for additional 'f' character.

### Expected behaviour

Https urls don't start with an f.

### Version

6.0.8

### Minecraft Version

1.18.2

### ModLoader Version

Forge

### Additional Information

Common on SB3 1.0.1, 1.0.2.

**Comment by covers1624** [comment]
This is now resolved in MineTogether 6.0.9.
