### ISSUE TITLE
[Bug]: Missing Chat after mention

### ISSUE THREAD

**Issue by RViper80** [CreeperHost/CreeperHostGui#635]
### Describe the bug

Users mentioned at the start of a chat line, don't see any other chat in-game, and it looks like a random user tag.

### Steps to reproduce

Get mentioned at the start of a chat line, and nothing shows but your name in red.

### Expected behaviour

Text shows up after the mention.  Have not tested if mentioning after chat shows it all or not.

### Screenshots

![Chatbug](https://user-images.githubusercontent.com/5312414/199886796-0458d20f-130c-47ae-94c3-ecd49491a259.png)

### Version

6.0.8

### Minecraft Version

1.18.2

### ModLoader Version

Forge

**Comment by RViper80** [comment]
Found a line with a bit of text before the mention, and everything after was just gobbled up.
![Chatbug2](https://user-images.githubusercontent.com/5312414/199887652-8d7b272e-6a42-4795-9f99-4d1d636af783.png)

**Comment by covers1624** [comment]
This is now resolved in MineTogether 6.0.9.
