### ISSUE TITLE
[Bug]: server listing SB3

### ISSUE THREAD

**Issue by rafalohaki** [CreeperHost/CreeperHostGui#636]
### Describe the bug

Server is not listed to public

### Steps to reproduce

stoneblock 3 
set
discoverability=public
displayname=namedwadwadwa

### Expected behaviour

server listing

### Version

1.18.2

### Minecraft Version

1.18.2

### ModLoader Version

1.18.2-40.1.84

**Comment by covers1624** [comment]
Closing in favour of: https://github.com/CreeperHost/MineTogether/issues/637
