### ISSUE TITLE
[Bug]: Minetogether stuck on Verifying

### ISSUE THREAD

**Issue by chawbaka** [CreeperHost/CreeperHostGui#638]
### Describe the bug

MineTogether seems to not be able to Verify

### Steps to reproduce

Start the game up and its just not verifying client, and getting no chats in or out.

### Expected behaviour

To be able to chat

### Version

Stoneblock 3 Modded

### Minecraft Version

1.18 

### ModLoader Version

Feedthebeast APP

**Comment by steveno36** [comment]
having same problem

**Comment by chawbaka** [comment]
Might add friend is having same issue, have tried updating the specific mod itself.

**Comment by steveno36** [comment]
idk but it went from working to not working at all for me

**Comment by steveno36** [comment]
lol im tempted to just make a server lol

**Comment by steveno36** [comment]
staff just told me It could be a bug with the mod or a network issue, as I am also having the same issue at the moment.
Unfortunately, the only thing to do is wait until either the issue is resolve or an update to the mod fixing the issue has been released.

**Comment by Draylynn** [comment]
Have you tried updating MT to 6.0.11?

**Comment by gigabit101** [comment]
closed due to inactivity
