### ISSUE TITLE
[Suggestion]: Website, countdown timer.

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#639]
### Is your feature request related to a problem? Please describe.

Request by multiple users for a visible 'countdown timer' or expiry date of the name change lockout that takes 48 hours, so they can track when to return to the site to change the name.
Some new users are picking names without 'realising' exactly what they're doing, somehow.

### Describe the solution you'd like

Either a countdown timer or expiry date on lockout located near the name selection profile options.

### Describe alternatives you've considered

I considered telling the users I would do it for a massive stack of diamonds, but seeing as I can't change it myself, I could not make that promise and it would be dishonest.
Also the possibility of allowing X (1~5) unrestricted changes for new users, however I _think_ this would require vastly more work to the naming system to accommodate it.

**Comment by RViper80** [comment]
Yeah, I was expecting to be able to pick my own name, and was trying to use the search boxes to type it in...  After typing in the search bar, then nothing came up in the lists.  Just basic user error, not sure much can be improved there :P

**Comment by brandon3055** [comment]
The latest versions now tell you when you can next change your name. 
![](https://ss.brandon3055.com/478a4.png)
