### ISSUE TITLE
I Would Like a Repeal on my Ban (Mine Together, but I can't seem to find any twitter or github place for that!)

### ISSUE THREAD

**Issue by MLGMaccDaddy** [CreeperHost/CreeperHostGui#64]
I said "I'm going to the nether Bi*ches" and got banned... I did say fu** earlier, but it completely slipped my mind, and I just forgot. Me and some new friends I found were talking, and I really relied on User 9345, because he helped me learn FTB Ultimate Reborn. I just think it's ridiculous on how I can get banned that easy. I get the whole "kids shouldn't learn these words", but, as far as I know, there was only 5 - 6 people talking, and all seemed like teens to adults. I had a lot of fun with these people. I laughed all day, and then for it to say "YoU hAvE bEeN bAnNeD" is absolutely insane.

**Comment by CH-Paul-T** [comment]
Irrelevant, rules are rules, you showed blatant disrespect for them.
