### ISSUE TITLE
[Bug]: Not honoring disabled in FTB settings

### ISSUE THREAD

**Issue by fuelhauler** [CreeperHost/CreeperHostGui#640]
### Describe the bug

MineTogether/FTB Launcher not honoring disabled setting

### Steps to reproduce

1 - Set "Enable MineTogether Chat" set to disabled

2 - Enter world in Stoneblock 3

3 - Get flooded with chat messages

### Expected behaviour

I expect settings that purport to disable connectivity to third-party sites to do so.

### Version

Which is is included with Stoneblock 1.0.3 unable to check due to unistalling FTB launcher

### Minecraft Version

1.18.2

### ModLoader Version

Which ever is Forge version is used in Stoneblock 3

**Comment by covers1624** [comment]
I'm not sure what setting your referring to.

Can you please provide a screenshot?

**Comment by fuelhauler** [comment]
The setting is in the FTB Launcher. I can't show a screenshot, having uninstalled it until the issue is resolved.

**Comment by covers1624** [comment]
That is a completely different setting for enabling MineTogether chat _inside_ the FTBApp, it is completely unrelated to the MineTogether mod.
