### ISSUE TITLE
[Bug]: Weird UI Bug 

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [CreeperHost/CreeperHostGui#642]
### Describe the bug

All of my UI was pushed to the very bottom of the screen with the only thing visible being the Friend button. Crash immediately followed. Amy Kitteh mentioned in Discord that this bug started after someone in chat said f{

### Steps to reproduce

Not sure? I'm not even sure if the f{ was what caused it or if it was just coincidental and I don't want to try to reproduce something that affected many people. It did work fine again after the restart.

### Expected behaviour

Normal UI, no crashing?

### Screenshots

There is a screenshot posted in the Discord channel

### Version

6.0.9

### Minecraft Version

1.18.2

### ModLoader Version

40.1.84

### Additional Information

Using Stoneblock 3 modpack with 2 extra mods. Here is my crash log;

https://paste.ee/p/7yDdl

**Comment by covers1624** [comment]
Can you please provide your full client log?

**Comment by Glitched-Fox-Studios** [comment]
Hmm, not sure where to put it. The log is so large that none of the paste services I know of will allow it. I will more than likely need to upload the file somewhere. Any particular host you would prefer?

**Comment by ThePaul-T** [comment]
Http://Pste.ch<Http://Pete.ch> should accept it

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Glitched-Fox-Studios** [comment]
https://pste.ch/uxuvugekoh.pl

Here it is, though no guarantee you can actually view it. Every time I try, my browser crashes, all 3 of them.

**Comment by covers1624** [comment]
This should be fixed in MineTogether 6.0.10.
