### ISSUE TITLE
[Bug]: Attempting to click Minetogether tab sets it back to commands tab near-instantly

### ISSUE THREAD

**Issue by JakeThatDog** [CreeperHost/CreeperHostGui#650]
### Describe the bug

I am currently playing Stoneblock 3, and when I try to click the minetogether tab in the chat box it forces me back into the Commands section.

### Steps to reproduce

1. Press T or / in Minecraft
2. Click the tab labelled "Minetogether"

### Expected behaviour

The ability to use the chat function.

### Version

6.0.8

### Minecraft Version

1.18.2

### ModLoader Version

Forge 40.1.84

### Additional Information

The chat is initially shown when booting up my world, but when I attempt to open chat and talk with them, it will force me into the commands menu.

**Comment by JakeThatDog** [comment]
Fixed the problem, it was related to some windows defender issues

**Comment by marc-cwm** [comment]
How did you fix this?  I don't have Windows Defender enabled and I'm having this exact issue.

**Comment by JakeThatDog** [comment]
You HAVE to use T for chat, if you use / it will lock you into the command. Sorry, I just didn't want to admit the solution was that easy to see, especially since I said to use T in the steps even though I had never used it.
