### ISSUE TITLE
[Bug]: Typographical error.

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#651]
### Describe the bug

Typo in the connecting message in chat...

### Steps to reproduce

Start client.
Open chat before it's able to connect and verify.
Witness the typo in all it's typographical glory:
Unable to send messages while client is **conmnecting** to chat.

### Expected behaviour

"connecting" not "conmnecting"

### Screenshots

![connecting](https://user-images.githubusercontent.com/45239550/200212641-38c22a07-faa6-45d9-9018-591a21a031cd.png)

### Version

6.0.11 Forge

### Minecraft Version

1.19.2

### ModLoader Version

1.19.2 - 43.1.47

**Comment by covers1624** [comment]
This has been resolved in MineTogether 6.0.12.
