### ISSUE TITLE
[Bug]: Cannot remove friends.

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#652]
### Describe the bug

Removed friends reappear in the friends list.

### Steps to reproduce

Friends list
Remove friend
Appears removed
Check list mins later, friends reappeared.
Issue persists after restart (tried for a few days now).

Related log entry:
[02:25:28] [MT Friends Thread 0/ERROR] [ne.cr.mi.li.ch.pr.ProfileManager/]: Failed to remove friend. Api returned: Friend does not exist.

### Expected behaviour

Remove friend, friend removed, permanently.

### Version

6.0.8, 6.0.9, 6.0.11

### Minecraft Version

1.18.2

### ModLoader Version

1.18.2 - 40.1.84

### Additional Information

During one of my earlier MT tests on 1.12.2 I believe, I managed to also add myself to my friends list, apparently under the name of another MT user, somehow... This causes my chat messages to display me with this other name in yellow.
This _may_ be related to this and solely a "Dray problem", because you know I love to break things.

**Comment by covers1624** [comment]
This is caused by aggressive caching on the API side.

MT removes the friend, but the API keeps telling you it exists when it doesn't.

**Comment by Draylynn** [comment]
Aggressive API stance; On a friend entry I haven't been able to remove for months?

**Comment by Draylynn** [comment]
Additional note about additional notes: Randomly ObserverPistachio asked me about this issue, it turns out the whole "Dray added herself/blocked herself" etc thought to be during testing builds and the whole "using a friends name" instead of displaying your name, is not a "Dray" problem and similarly, cannot be removed from friends list.

**Comment by gigabit101** [comment]
closed due to inactivity
