### ISSUE TITLE
[Bug]: Unable to connect to the MineTogether client.

### ISSUE THREAD

**Issue by drtammr** [CreeperHost/CreeperHostGui#653]
### Describe the bug

Unable to connect to the MineTogether client, despite account in good-standing.

### Steps to reproduce

1. Load up the modpack and join a singleplayer world.
2. Client fails to connect to the MineTogether client and no messages are able to be retrieved or sent.

### Expected behaviour

I expected the client to connect successfully as it has done in the past. After updating to the newest version specifically used in the modpack Stoneblock 3, this issue began.

### Version

6.0.10

### Minecraft Version

1.18.2

### ModLoader Version

40.1.0

**Comment by ThePaul-T** [comment]
6.0.10 was pulled from release and disabled, please update to 6.0.11

**Comment by drtammr** [comment]
> 6.0.10 was pulled from release and disabled, please update to 6.0.11

Ah I see, SB3 must have not had the time to update yet. Thank you for the clarification and your time!
