### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zookeper** [CreeperHost/CreeperHostGui#654]
### Describe the bug

Failure to update modpack

### Steps to reproduce

Install modpack,

update modpack, 

if minetogether is not the EXACT updated version, it refuses to connect on MP world

Playing stoneblock 3, I've had to reinstall the updated version of minetogether directly from curseforge and install it into stoneblock3 manually every time there is an update, the minetogehter is 0.1 ahead of everything else.

### Expected behaviour

It should just work and let me type, its a multiplayer world, why wouldn't I be able to communicate with a mod called Mine together?

### Version

all versions

### Minecraft Version

1.19

### ModLoader Version

1.10

### Additional Information

stoneblock3 updates and breaks minetogether because minetogther seems like it feels it wants to be ahead of the race but no modpacks have ensured they are properly updated.

**Comment by ThePaul-T** [comment]
Not sure, it should be optional and not care about version too, thanks for the report.

**Comment by gigabit101** [comment]
closed due to inactivity
