### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FluxCrystal** [CreeperHost/CreeperHostGui#655]
### Describe the bug

Friends not Showing up

### Steps to reproduce

add a friend, then let them accept the friend request, then go to friends list, then there is no friends

### Expected behaviour

they are supposed to show up after adding or accepting friend requests

### Screenshots

![Screenshot 2022-11-07 155754](https://user-images.githubusercontent.com/117688875/200424264-835a14f6-f0e0-42d0-9402-e5fdf0dce544.png)
![Screenshot 2022-11-07 155735](https://user-images.githubusercontent.com/117688875/200424267-19353bb7-abe7-43b1-bfb5-e645b8076f0a.png)
![Screenshot 2022-11-07 155705](https://user-images.githubusercontent.com/117688875/200424269-113a2133-dd12-4a6d-8130-c9809a07c16a.png)

### Version

6.0.11

### Minecraft Version

1.18.2

### ModLoader Version

202211021238-4322c4d8d1-release

**Comment by gigabit101** [comment]
closed due to inactivity
