### ISSUE TITLE
[Bug]: Not really a bug, this is a policy issue.

### ISSUE THREAD

**Issue by Nightcaste** [CreeperHost/CreeperHostGui#656]
### Describe the bug

again, not really a bug

### Steps to reproduce

The roles channel of the MineTogether Discord says to message a staff member if you're having issues.

Every single staff member has their messages set to "Friends only", so you CAN'T message them.

### Expected behaviour

A pathway where you CAN communicate with staff that actually works.

### Version

0.0

### Minecraft Version

1.18.2

### ModLoader Version

I don't know

**Comment by Draylynn** [comment]
How are people messaging me on Discord?
A lot of staff Discords are locked down to DM requests, due to abuse.
DM me? Or even add me as a friend. It is possible. I've SEEN it man, I've seen things.

**Comment by Nightcaste** [comment]
![Screenshot_20221116-213144](https://user-images.githubusercontent.com/11658474/202340334-f22d991f-0e0a-4705-aa93-ad4043de2557.png)


I tried to DM you and three other people.  ALL of them are set to "friends only", so this solution doesn't fix the problem.  I added a screenshot of what happened when I try.

You even pointed out that "a lot of staff discords are locked down".  Then **give another method that people can actually use**.

**Comment by SephirothWS** [comment]
This is a major problem when needing to contact staff of a discord only to be unable to  do so. Implement some alternative **non discord** method of contact.

**Comment by Draylynn** [comment]
My Discord can (and does):
Accept friend requests
Accept messages from people on the same servers as me
Accept messages from unknown people on the same servers as me
![image](https://user-images.githubusercontent.com/45239550/202816421-e2102384-106d-43c5-91d2-5737c76ef3f1.png)

Mobile bug, Discord bug?
Wild theory to test... Our MT Discord privacy settings are shown open, obviously... But if you leave the FTB Discord temporarily can you then message/friend etc? I'm wondering if FTB (who sometimes lock their server from allowing direct messages from server members) may have had to toggle it on (as sometimes they need to) and Discord is using that server as a basis for your communication possibilities and ignoring the fact you also share a server with the other user via MineTogether. A lot of staff also are present in FTB's Discord.

**Comment by Nightcaste** [comment]
I just tested that idea, Same result.  Being that the bot that responds is Clyde, it's Discord saying "your message cannot be delivered", not a particular server.

**Comment by Draylynn** [comment]
Are you actually part of MineTogether's Discord? A verified user? Or do you only see 4 channels (rules, announcements, roles and link-help)? "not a particular server".

**Comment by Nightcaste** [comment]
MineTogether is rejecting my authorization code.  That's why I went to the discord in the first place.  The welcome page in discord says to DM staff if you're having issues, and since I couldn't link any of the accounts, I figured that qualified.
