### ISSUE TITLE
[Suggestion]: Highlight mentions in chat

### ISSUE THREAD

**Issue by EfficiencyVI** [CreeperHost/CreeperHostGui#657]
### Is your feature request related to a problem? Please describe.

There are no colors in chat. You have to read every message when you ask a questions and if you have a name like "User#xyz12" it is pretty much impossible the see in chat when someone answers you unless you stop playing and just read chat for the next 2 minutes.

### Describe the solution you'd like

Highlight the message eg. by adding a background color in chat.

### Describe alternatives you've considered

You an also give at least your username a color so you can actually see when someone mentions you.

### Additional context

It would also be great if you could mentions people by using @username. In fast moving chats it is not that easy to right click a username.

**Comment by covers1624** [comment]
Colors were not applied due to a bug, closing in favor of https://github.com/CreeperHost/MineTogether/issues/659
