### ISSUE TITLE
[Suggestion]: Anchor the cog and friends list to the top right of the screen

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#658]
### Is your feature request related to a problem? Please describe.

Yes, if you have a mod that modifies the height/size of the in-game menu this happen:
![image](https://user-images.githubusercontent.com/17010632/200500473-9b56d001-76c8-4833-9e8f-55fbc72264ea.png)
The button is shifted outside the screen, my guess is it's anchored to one of the button in the menu instead of the top right corner (if that's at all possible)

### Describe the solution you'd like

Anchoring it to the top right of the screen should solve this, if possible

### Describe alternatives you've considered

Removing mods that increase the size of the menu

### Additional context

Version: `minetogether-forge-1.18.2-6.0.11.jar`

**Comment by covers1624** [comment]
It is anchored to the top of the screen, it just sets Y to 5.

What mod is adding this menu button?

My guess is they are moving all the buttons except options, etc, up themselves, moving the MT buttons off the screen.

**Comment by Raidobw2** [comment]
Hi Covers sorry for the late reply, the mod that is adding this "Mods" button is https://www.curseforge.com/minecraft/mc-mods/better-mods-button

**Comment by covers1624** [comment]
This is not a bug with MineTogether. Better Mods Screen is just moving every single button up 12 pixels.

https://github.com/Fuzss/bettermodsbutton/blob/1.19/Forge/src/main/java/fuzs/bettermodsbutton/client/handler/ModScreenHandler.java#L173

**Comment by Raidobw2** [comment]
Oh I see, thanks Covers 😄
