### ISSUE TITLE
[Bug]: Mention colours missing

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#659]
### Describe the bug

Mentioning a player is supposed to flag the text red.

### Steps to reproduce

Mention player.
The mentioned players name is not red to that player as it should be to indicate someone is focusing a message towards them.

### Expected behaviour

Mention of your name should flag your name in red to you.

### Version

6.0.11

### Minecraft Version

1.18.2

### ModLoader Version

Varied

**Comment by covers1624** [comment]
This has been resolved in MineTogether 6.0.12.
