### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#660]
### Describe the bug

Crash

### Steps to reproduce

Game launch 

### Expected behaviour

To not crash

https://hastebin.com/vecelafeli.rb
https://hastebin.com/eqofuduwim.yaml

### Version

minetogether-forge-1.18.2-6.0.11.jar

### Minecraft Version

1.18.2

### ModLoader Version

Forge

**Comment by Raidobw2** [comment]
Continuation of https://github.com/CreeperHost/MineTogether/issues/641

Also happens on https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1811

**Comment by covers1624** [comment]
This has been resolved in MineTogether 6.0.12.
