### ISSUE TITLE
[Bug]: Minetogether friend opens world but can't see it on muliplayer

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#663]
### Describe the bug

minetogether friend opens world cant see it on muliplayer

### Steps to reproduce

minetogether friend opens world
cant see it on muliplayer

### Expected behaviour

opens world to friend friend joins

### Version

6.0.10/6.0.11

### Minecraft Version

1.18.2

### ModLoader Version

Forge

**Comment by ThePaul-T** [comment]
We confirmed this was broken night before last and have been investigating it further.

**Comment by covers1624** [comment]
Please try this again on 6.0.12.

If you are unable to connect to your friends, we will require either your fill client logs, or the full Minetogether logs `./logs/minetogether`

**Comment by brandon3055** [comment]
We are currently in the process of developing a replacement for MineTogetehr Connect.
Once this is finished, it should resolve these issues.

In the meantime, we are currently looking for people to test the new system.
If you (or anyone else watching this issue) are interested,
Please join the MT discord and express your interest in the #general channel.
Please be aware, the current test builds are for 1.19.2.
[https://discord.com/invite/J4hYB6M](https://discord.com/invite/J4hYB6M)

**Comment by gigabit101** [comment]
closed due to inactivity
