### ISSUE TITLE
[Bug]: Chat will not apear in game

### ISSUE THREAD

**Issue by Connorray1234** [CreeperHost/CreeperHostGui#664]
### Describe the bug

Chat will on apear ig

### Steps to reproduce

idk
This is my pack
not an FTB one

### Expected behaviour

Chat dosent apear ig only in the chat ui

### Screenshots

![Screenshot_1434](https://user-images.githubusercontent.com/85777151/201492502-a482199c-0ef5-481b-bdc6-c53ddcb4530d.jpg)
![Screenshot_1433](https://user-images.githubusercontent.com/85777151/201492503-59b9840f-e6da-4813-a480-6d7f2198b3eb.jpg)

### Version

minetogether-forge-1.18.2-6.0.11.jar

### Minecraft Version

1.18.2

### ModLoader Version

Forge  40.1.84

### Additional Information
https://www.curseforge.com/minecraft/modpacks/the-daylight-pack
this is the pack in question

**Comment by Draylynn** [comment]
There is a new build of MT available if you want to see if  6.0.12 works any better?

**Comment by Connorray1234** [comment]
> There is a new build of MT available if you want to see if 6.0.12 works any better?

its still not working even when i updated it

**Comment by gigabit101** [comment]
closed due to inactivity
