### ISSUE TITLE
[Bug]: Can't see friend's world even though it is opened to multiplayer

### ISSUE THREAD

**Issue by miolio0** [CreeperHost/CreeperHostGui#665]
### Describe the bug

Friend made a modpack including MineTogether but I can't see his world when I go to multiplayer even though he has opened it to multiplayer through the escape menu and he is showing up as online on my friend list.

### Steps to reproduce

Minetogether friend opens world,
Go to multiplayer,
Friend's world doesn't show up.

### Expected behaviour

Can't see friend's world show up.

### Version

5.1.2

### Minecraft Version

1.16.5

### ModLoader Version

Forge 36.2.39

**Comment by miolio0** [comment]
![image](https://user-images.githubusercontent.com/118137653/202027158-7aad3034-8709-49ef-aa9a-67ca62d95787.png)

If I add minetogether to a custom modpack do I need to edit the curseProjectID in the .json file?

**Comment by gigabit101** [comment]
closed due to inactivity
