### ISSUE TITLE
[Bug]: Crash - Multiplayer Selection

### ISSUE THREAD

**Issue by burg5204** [CreeperHost/CreeperHostGui#666]
### Describe the bug

Crash upon clicking "Server List"

### Steps to reproduce

1. Load Mod/Pack (Stoneblock 3)
2. Multiplayer
3. Click Server List
4. Click Option, I did Public
5. Game Crashes Completely

### Expected behaviour

Crash

### Version

BETA MineTogether 1.18.2-6.0.12 [Forge]

### Minecraft Version

1.18.2

### ModLoader Version

Forge

### Additional Information

[crash-2022-11-14_17.45.59-client.txt](https://github.com/CreeperHost/MineTogether/files/10007903/crash-2022-11-14_17.45.59-client.txt)

**Comment by covers1624** [comment]
This should be resolved in MineTogether 6.0.13.
