### ISSUE TITLE
[Bug]: Crash on opening "Public" under Server List tab

### ISSUE THREAD

**Issue by riifter** [CreeperHost/CreeperHostGui#667]
### Describe the bug

Minecraft crashes when trying to open public servers using the Server List tab.

### Steps to reproduce

1. Click "Multiplayer".
2. Click "Server List".
3. Click "Public".
4. Crash.

### Expected behaviour

The Public Servers list would appear, allowing me to then select a server and join.

### Version

6.0.12

### Minecraft Version

1.18.2

### ModLoader Version

Forge

### Additional Information

Alc_cleanup: 1 device not closed

**Comment by Draylynn** [comment]
Crashing here too: https://pste.ch/asakehopum.md

**Comment by covers1624** [comment]
Closing in favour of: https://github.com/CreeperHost/MineTogether/issues/666

Please be sure to check for duplicates before submitting new issues.
