### ISSUE TITLE
[Bug]: Chat join overlay [Random].

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#668]
### Describe the bug

Chat join buttons greyed out and difficult to interact with, occurs randomly on client start.

### Steps to reproduce

Launch client.
Open chat on main menu.
Chat obscured by 'join' overlay and dodgy button interaction.
Requires restart to fix.

### Expected behaviour

Join chat and be able to click the button to dismiss overlay.

### Screenshots

![image](https://user-images.githubusercontent.com/45239550/201824708-ea91dd76-55ee-425d-993d-71a20a09a3c4.png)

### Version

6.0.12

### Minecraft Version

1.18.2

### ModLoader Version

40.1.84

### Additional Information

Can still talk in-game via T command and see chat without overlay when chat window is not active.
If user name present behind overlay buttons, will activate the user interaction buttons instead behind the overlay buttons.

**Comment by covers1624** [comment]
Related to https://github.com/CreeperHost/MineTogether/issues/646

**Comment by covers1624** [comment]
This should be resolved in MineTogether 6.0.13.
