### ISSUE TITLE
I have a doubt for how to link your minecraft account in minecraft together

### ISSUE THREAD

**Issue by ruan12354** [CreeperHost/CreeperHostGui#669]
### Is your feature request related to a problem? Please describe.

I have a doubt for how to link your minecraft account in minecraft together

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/75855177/202488851-ccbdfb20-0cfc-468e-836d-b903c188afca.png)
![image](https://user-images.githubusercontent.com/75855177/202490372-14dccf72-2241-4128-a8d0-3a052c53d170.png)

![image](https://user-images.githubusercontent.com/75855177/202490433-8e90dcd9-2328-4fae-a8b3-6fe10b5095aa.png)
I do as the site said to enter minecraft but the code does not appear

### Describe alternatives you've considered

.

### Additional context

.

**Comment by Mineablechn** [comment]
So how do you complete it?
