### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ruan12354** [CreeperHost/CreeperHostGui#670]
### Describe the bug

I can't get into minetogether chat

### Steps to reproduce

I can't get into minetogether chat

### Expected behaviour

.

### Screenshots

![image](https://user-images.githubusercontent.com/75855177/202513046-2318dfa0-4b20-4591-8d23-158d0792a564.png)
![Uploading image.png…]()

### Version

last

### Minecraft Version

1.18

### ModLoader Version

.

### Additional Information

I can't get into minetogether chat

**Comment by ThePaul-T** [comment]
Provide actual version numbers and logs.

**Comment by ruan12354** [comment]
![image](https://user-images.githubusercontent.com/75855177/202513176-067d2ee2-2ef9-43d0-8401-f0a90df72b9d.png)
version : 
![image](https://user-images.githubusercontent.com/75855177/202513443-386d7e13-8dff-474c-8bc6-f2a3cc65fd4a.png)

log:
[latest.log](https://github.com/CreeperHost/MineTogether/files/10033956/latest.log)
