### ISSUE TITLE
[Bug]: Got banned for no reason

### ISSUE THREAD

**Issue by Evalynndewinters** [CreeperHost/CreeperHostGui#671]
### Describe the bug

Was banned for asking if there was an easy way to get nethrite scrap from netherite.

### Steps to reproduce

Unban me?

### Expected behaviour

To get un banned.

### Screenshots

![image](https://user-images.githubusercontent.com/60989596/202735303-f8bc60da-8d86-4feb-9bd0-1c595659836b.png)

### Version

1.18? not sure

### Minecraft Version

Java

### ModLoader Version

FTB app

**Comment by Evalynndewinters** [comment]
oh and my minecraft name is Eveydewinters dont know if that is something you need or not.

**Comment by Nexemis** [comment]
Did you ever get unbanned ? I literally got banned for saying "You done me a spookin" meaning "you scared me" in a jokingly manner. Crazy stuff.

**Comment by gigabit101** [comment]
Ban appeals need to be done at https://minetogether.io/
