### ISSUE TITLE
[Suggestion]:  Reactivation of the ability to turn MineTogether off in the FTB launcher

### ISSUE THREAD

**Issue by JRSofty** [CreeperHost/CreeperHostGui#672]
### Is your feature request related to a problem? Please describe.

I've created no ticket, but it seems the ability to disable the MineTogether in my game has been disabled in the FTB launcher. 

### Describe the solution you'd like

I want to play the game without a bunch of constant random comments appearing in chat. Especially since I play singleplayer. I have no desire for this "feature" and would like to have the ability to disable it as it appears it used to have.

### Describe alternatives you've considered

Not playing FTB games since this seems to now be a constant "feature".

**Comment by JRSofty** [comment]
Currently fixed it by manually turning it off in the .json configuration files.

**Comment by covers1624** [comment]
You can disable MineTogether via the Settings cog in-game. You can find this via the 'big chat screen', this can be accessed via the Pause menu, or via the Main menu (depending on how customized it is.)
