### ISSUE TITLE
[Bug]: Friends cannot join my world

### ISSUE THREAD

**Issue by DavidLXXV** [CreeperHost/CreeperHostGui#673]
### Describe the bug

Friends cannot see my world on the multiplayer list when I open it to Friends

### Steps to reproduce

Currently I am using a custom modpack I put together for me and my friends to play on together using Minetogether to connect but when I open to Friends they cannot see it in the friendlist despite them being able to in premade modpacks. 
I am in the process of uploading my modpack to curseforge if that helps troubleshoot the issue.

### Expected behaviour

They should be able to see and join my world from the multiplayer tab.

### Screenshots

![image](https://user-images.githubusercontent.com/87132507/202821639-f376886f-f518-4769-8f37-a8e63058f618.png)

### Version

5.1.2

### Minecraft Version

1.16.5

### ModLoader Version

36.2.34

### Additional Information

I am also unsure whether I need to edit the .json file in the config to make the mod work.

**Comment by ThePaul-T** [comment]
The configuration above is incomplete, is this the configuration you're trying to use? If so, it will not work.

**Comment by DavidLXXV** [comment]
How can I complete the configuration?

**Comment by DavidLXXV** [comment]
![image](https://user-images.githubusercontent.com/87132507/209475822-5c54ae96-0769-4127-82cf-6cde458bc796.png)
I've added the ID and it still doesn't work,

Here's the link to the modpack: https://www.curseforge.com/minecraft/modpacks/joe-bidens-lightweight-pixelmon-modpack
