### ISSUE TITLE
[Bug]: banned for s spelling mistake

### ISSUE THREAD

**Issue by mattmasterv** [CreeperHost/CreeperHostGui#674]
### Describe the bug

in context of the complemeting the creeperhost sytem i meant to say its good  but i said tits good

### Steps to reproduce

could i be unbanned 
also eith im stupid but i cant find any ban appeals

### Expected behaviour

unbanned?

### Screenshots

couldnt screenshot cause i forgot

### Version

1.2

### Minecraft Version

1.18?

### ModLoader Version

1.18?

### Additional Information

i cannot find the bann appeal.

**Comment by mattmasterv** [comment]
if someone could guide me to the actual ban appeal thanks?

**Comment by mattmasterv** [comment]
![image](https://user-images.githubusercontent.com/118615350/202855690-9b950902-cd9e-4697-9bc8-32588eefe46b.png)

**Comment by rbnzdave** [comment]
Theres also no instruction on what to do when you have been banned and submitted an appeal, it just sits there.
