### ISSUE TITLE
[Bug]: minetogether api.creeper.host instability causes game to crash

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#678]
### Describe the bug

While playing the game crashed with the message "Close externally"

### Steps to reproduce

On linux.

1. Open your game
2. ensure that you receive messages from minetogether.
3. check the api.creeeper.host 
```
➜ dig +short api.creeper.host
185.57.191.115
```
4. Drop it on iptables
```
iptables -A OUTPUT -s 185.57.191.115-j DROP
```
5. Wait and the game will crash.

### Expected behaviour

Game do not crash case the API stop responding. 

### Version

minetogether-forge-1.18.2-6.0.13

### Minecraft Version

1.18.2

### ModLoader Version

Forge

### Additional Information

Logs: https://pste.ch/osiqorejug.sql

**Comment by gigabit101** [comment]
closed due to inactivity
