### ISSUE TITLE
kicked from server and cannot reconnect

### ISSUE THREAD

**Issue by Goten87** [CreeperHost/CreeperHostGui#68]
i was kicked from the chat today and i still cant connect back
i know i made a misstake but i hope someone can help me get back sins its my first time and i dint read the rules in full sorry about that

(reason for kick was cursing) hope we can sort it out

**Comment by Goten87** [comment]
i sayed well i f*** up big time 
and i timezone is EU and when that was i have no clue
if the swearing is the only one then thats me i think
was also asking some help for a mob spawner in the pack oddesy
then a few sec after thet i let that slip becose i had my whole base with cursed earth
hope this helps

**Comment by Draylynn** [comment]
Took over 3GB of RAM to load the log that far back.
"5:54PM: ok i f***** up xD"
"5:54PM: my whole base is now cursed earth"
I'll make an exception this once for you. Consider the ban a temporary time out in the naughty corner.
Don't let it happen again, there are young children in chat (PG7) - The ban won't be lifted again.

**Comment by Goten87** [comment]
ty so much it will not happen again
It was out befor I knew it
This can be closed ^^

**Comment by gigabit101** [comment]
Once you have been unbanned you will need to restart your game to connect to the chat.
I am now going to close this issue
