### ISSUE TITLE
[Bug]: wont let me connect 

### ISSUE THREAD

**Issue by nocturnalfoxboi** [CreeperHost/CreeperHostGui#680]
### Describe the bug

i enter the auth server and when it kicks me it dosent give me a code

### Steps to reproduce

go to mc.auth.minetogether.io in the server menu, join and not get a coe

### Expected behaviour

i would get my player code

### Version

the latesr

### Minecraft Version

unsure

### ModLoader Version

forge

**Comment by tylerl** [comment]
make sure you're trying to connect with a vanilla client (not modded)

**Comment by DavidLXXV** [comment]
> make sure you're trying to connect with a vanilla client (not modded)

Hello, I'd just like to ask, does the Mod not work on a custom made modpack? If so how could I get it to work?

**Comment by Draylynn** [comment]
Kick code may not appear on 1.19.3+, try an earlier MC version.

**Comment by gigabit101** [comment]
closed due to inactivity
