### ISSUE TITLE
[Bug]: (not really a bug, rather an issue) [Fixed]

### ISSUE THREAD

**Issue by Kuchinator69** [CreeperHost/CreeperHostGui#681]
### Describe the bug

I can't sign into my mine together or creeper host website accounts

### Steps to reproduce

I got to mine together or creeper host websites and try to sign in and it loads forever..

### Expected behaviour

I expected to be signed into my account

### Version

current

### Minecraft Version

current

### ModLoader Version

current

### Additional Information
none

**Comment by Tazzy074** [comment]
how did you fix this issue?
