### ISSUE TITLE
[Bug]: Can't connect

### ISSUE THREAD

**Issue by BaldTango** [CreeperHost/CreeperHostGui#684]
### Describe the bug

Can't connect to friend's world

### Steps to reproduce

Stuck on connecting to server, we tried both sides opening it and the result is the same.

### Expected behaviour

Should be able to connect given that the server shows up in the multiplayer tab

### Version

5.1.2

### Minecraft Version

1.16.5

### ModLoader Version

Forge 36.2.35

**Comment by brandon3055** [comment]
We are currently in the process of developing a replacement for MineTogetehr Connect.
Once this is finished, it should resolve these issues.

In the meantime, we are currently looking for people to test the new system.
If you (or anyone else watching this issue) are interested,
Please join the MT discord and express your interest in the #general channel.
Please be aware, the current test builds are for 1.19.2.
[https://discord.com/invite/J4hYB6M](https://discord.com/invite/J4hYB6M)

**Comment by gigabit101** [comment]
closed due to inactivity
