### ISSUE TITLE
[Bug]: Can't connect Minecraft account to MineTogether account

### ISSUE THREAD

**Issue by algamoda** [CreeperHost/CreeperHostGui#686]
### Describe the bug

When trying to connect my Minecraft account to my MineTogether account, it times out and gives an error.

### Steps to reproduce

1. Go to your account on the MineTogether Website
2. Click on the "Connections" tab
3. Join the Minecraft server to get your code
4. Click the link button on the Minecraft box
5. Try inputting the code, it freezes for a few seconds then errors.

### Expected behaviour

The ability to connect my Minecraft account with my MineTogether account

### Screenshots

![image](https://user-images.githubusercontent.com/58119650/205512936-43b25b2c-610c-49bf-bf86-1d70af24f3f8.png)

### Version

1.18.2-6.0.13

### Minecraft Version

1.18.2

### ModLoader Version

Forge

**Comment by janddbtwo** [comment]
Was there a fix for this?

**Comment by Mr-A-Designs** [comment]
Bump. Still an issue unable to link minecraft account same error msg. Also unable to protest ban since unable to link account.

**Comment by gigabit101** [comment]
closed due to inactivity
