### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by slay-mithos** [CreeperHost/CreeperHostGui#687]
### Describe the bug

The chat box shows "unable to send messages while client is unverified" but it does not verify even after nearly half an hour

### Steps to reproduce

1. On the main menu, either go to multiplayer or load a single-player file.
2. Open the chat
3. "unable to send messages while client is unverified" will be written in the input box.

Restarting the FTB launcher or the computer did not change it.

### Expected behaviour

Any day prior to today, the verification is over before the loading of the single-player world finishes.

### Screenshots

![Capture](https://user-images.githubusercontent.com/16986/206033989-ed14bb2e-d856-4184-9a2d-c5143c77ddc2.PNG)
![Capture d’écran 2022-12-06 230426](https://user-images.githubusercontent.com/16986/206034001-827d461c-6945-4ce0-b1cb-1b32f04cbb3b.png)

### Version

6.0.13

### Minecraft Version

1.18.2

### ModLoader Version

forge 40.1.84

### Additional Information

FTB laucher
Stoneblock 3 version 1.4.3

minetogether log:
[latest.log](https://github.com/CreeperHost/MineTogether/files/10170603/latest.log)

It is likely not something only affecting me since the chat is very unpopulated which is not normal for this time of the day.

**Comment by WinterWolfGames** [comment]
I'm having the exact same issue

**Comment by DamondSword2247** [comment]
I believe the servers for MineTogether have gone down or are currently experiencing issues cause my client can't connect either.

**Comment by TheTwistyTie** [comment]
It could be because you were banned, check the website and see. That’s what is been telling me starting when I was banned.

**Comment by slay-mithos** [comment]
It ended up being the servers having issues at the time, only people that logged in before the problem started (and never disconnected) were able to post at the time.


If you are banned you shouldn't even be able to read new messages in the chat as far as I know.
