### ISSUE TITLE
Banned for nothing?

### ISSUE THREAD

**Issue by Nexemis** [CreeperHost/CreeperHostGui#688]
### Describe the bug

Literally banned for nothing.

### Steps to reproduce

Use Minetogether, get banned? I don't get it.

### Expected behaviour

Not be banned! :D

### Screenshots

![banned](https://user-images.githubusercontent.com/120067766/206324982-ced7f4b6-ed71-4e4a-a089-6cd1f234a491.png)

### Version

Whatever version is in StoneBlock 3

### Minecraft Version

1.18.2

### ModLoader Version

ATLauncher? Stoneblock 3.

### Additional Information

Apparently I was banned for swearing? Please check the screenshot, as I didn't swear at all. 
"You done me a spookin bud" isn't swearing, it was a jokingly way to say "You scared me" 
Quite confused. 

I also tried to appeal on the website, however nothing has been done and I have not been contacted in any manner regarding this.

**Comment by ThePaul-T** [comment]
We have an appeal system, if you don't get unbanned, your appeal was denied.

**Comment by Nexemis** [comment]
"you done me a spookin"

Can you please just explain to me if any of those 5 words are
cursing/explicit ? Clearly I was falsely banned here.

**Comment by Nexemis** [comment]
I didn't use any expletives??? None of those 6 words I said are even close
to bad words ???
You done me a spookin, it was a joking/funny way to say you scared me.
Can I please be unbanned? I was banned for nothing here.
