### ISSUE TITLE
[Bug]: Friend list deleted

### ISSUE THREAD

**Issue by daeGrighen** [CreeperHost/CreeperHostGui#690]
### Describe the bug

My friend list looks empty on my client, but on my friend's client I look online

### Steps to reproduce

1. Go to the friends tab
2. Open friends tab
3. Empty :(

### Expected behaviour

The friends tab should not be empty, as last time I had two friends

### Version

Last

### Minecraft Version

1.18.2

### ModLoader Version

Best for 1.18.2

**Comment by gigabit101** [comment]
closed due to inactivity
