### ISSUE TITLE
[Bug]: paid subscription but still free account

### ISSUE THREAD

**Issue by nessy91** [CreeperHost/CreeperHostGui#691]
### Describe the bug

i paid for a subscription but the website hasnt changed my account status

### Steps to reproduce

go to the website make a sub, you will remain free 

### Expected behaviour

should switch to paid sub

### Version

na

### Minecraft Version

na

### ModLoader Version

na

**Comment by Draylynn** [comment]
Use the "contact" menu on Creeperhost.net's site, they can investigate your account.
