### ISSUE TITLE
[Bug]: can’t see messages or text

### ISSUE THREAD

**Issue by Rongorn1** [CreeperHost/CreeperHostGui#694]
### Describe the bug

I play FTB stoneblock3 modpack and I can’t see or text messages in game. I just see the inscription “unable to send messages while client is uverified” How do I deal with this problem? How do I verify my account?

### Steps to reproduce

Just play

### Expected behaviour

I want to text with other players

### Screenshots

![5F59352C-8DD7-422A-AA0B-280E2D6E29F1](https://user-images.githubusercontent.com/122788652/212664180-cfdd022a-5aef-4023-ba9c-7aa5dd453108.jpeg)
![699917BC-E68F-46F4-B27A-A6E0E8FA96D9](https://user-images.githubusercontent.com/122788652/212664186-9eb5270a-b2d4-4bda-9a41-c69c4769a842.jpeg)

### Version

6.0.13

### Minecraft Version

1.18.2

### ModLoader Version

40.1.92

**Comment by Rongorn1** [comment]
This has been going on for many days and I do not know what to do.

**Comment by Draylynn** [comment]
Are you banned? (Check MineTogether.io > Account standing).

**Comment by gigabit101** [comment]
closed due to inactivity
