### ISSUE TITLE
[Bug]: Banned by automod

### ISSUE THREAD

**Issue by codyjohnson2836** [CreeperHost/CreeperHostGui#695]
### Describe the bug

I was banned by the automod a very long time ago and have yet to be unbanned.

### Steps to reproduce

I apologize for creating a report for this, but I see no other option besides waiting for an unknown amount of time.
I was banned on July 11, 2021 by the automod for an answer to another user's question. The user asked what the slang "cap" meant, and I explained, "cap is like 'bullcrap,'" and was immediately banned from the chat. I'm assuming that the word "bullcrap" was automatically flagged by the automod.

### Expected behaviour

I would really appreciate being unbanned, as I love having chat to read while I play, and playing without feels much lonelier. I had no intention of using malicious language, and have no future intention to.

### Screenshots

![image](https://user-images.githubusercontent.com/37808393/213595812-f052bb18-bd00-4c03-b4e8-d27cad751fa2.png)

### Version

1.12.2-2.4.5

### Minecraft Version

1.12.2

### ModLoader Version

1.12.2-forge-14.23.5.2858

### Additional Information

Ban ID: mtg-ban=60ea6fb2476c06.05213254

Moderator: Freddy

Reason: Banned for use of expletives.

Message: cap is like "bullcrap"

Timestamp: 2021-07-11 05:12:34

**Comment by rbnzdave** [comment]
Yep, and I've been waiting maybe a month now, they arent reviewing appeals, there is no accountability. I said Wow, silverfish are just such pricks. Its not profanity, its a figure of speech in new zealand. I presume the garbage mod would also trigger if i explained to get blood for my glucose meter i prick my finger. A person who is annoyed with another is said to get the prick with them.

Fact is, its slack, lazy, highly inaccurate and punishes insignificant words.

As are the moderators reviewing appeals.

**Comment by ThePaul-T** [comment]
We are reviewing them, we just don't approve ones where the contents of the appeal show they have zero respect for the rules or the service, like you.

Stop hijacking other peoples issues.
