### ISSUE TITLE
[Bug]: Cannot Verify Chat

### ISSUE THREAD

**Issue by JragonGamer** [CreeperHost/CreeperHostGui#696]
### Describe the bug

Hello, I was recently banned on the Minetogether chat for saying s**t and I aplogize for that, but what I'm confused on is why my client now says can't connect to Minetogether chat because my client is unverified?

### Steps to reproduce

I honestly could not recreate this, It just happens

### Expected behaviour

The chat to not says the msssage stated in the description

### Version

?

### Minecraft Version

1.18.2

### ModLoader Version

?

### Additional Information

I'm on StoneBlock 3

**Comment by TheTwistyTie** [comment]
It says this because you’re banned.

**Comment by Dmdu44** [comment]
> It says this because you’re banned.

How can you get unbanned?

**Comment by gigabit101** [comment]
Unban requests can be submitted at https://minetogether.io/
