### ISSUE TITLE
[Bug]: MineTogether Not Linking To FTB App

### ISSUE THREAD

**Issue by rainingforest** [CreeperHost/CreeperHostGui#699]
### Describe the bug

After going into the integrations menu in the FTB client, I click log in and it brings up the MineTogether website. After successfully logging in (a message says it was successful), I go back to the client and integrations still does not list MineTogether as active. In-game, my username in the MineTogether chat is still random and not the one I set. Thus my account is not linking correctly.

### Steps to reproduce

1. Open the FTB App.
2. Click on settings.
3. Go to Integrations.
4. Click "Login to setup" on the main window.
5. Log in via the MineTogether website.
6. After a success message, go back to the client.
7. Nothing changes and no MineTogether account is linked.

### Expected behaviour

I expected the MineTogether website to correctly link to my FTB app so I can use my username in chat (Stoneblock 3). I can chat, but my username is not what I set it to.

### Screenshots

![Overwolf_jRe7eD1ZXM](https://user-images.githubusercontent.com/2401621/216235456-13c52257-da17-4b0e-84f5-affb035ee108.png)
![firefox_fU5cqqAt5l](https://user-images.githubusercontent.com/2401621/216235486-0d360181-3d65-4c9a-89a6-328e65b10af6.png)

### Version

Latest version in the app (6.0.13 in Stoneblock 3)

### Minecraft Version

Not an issue in-game, but 1.18.2

### ModLoader Version

Not sure as the mod list doesn't say but this isn't an MC issue.

**Comment by rainingforest** [comment]
I logged in for a fifth time today and I was finally able to get it to link successfully.

**Comment by ThePaul-T** [comment]
We're investigating this at the moment, something seems to be causing issues with the session persistence and it's a bit of a pain to track.
