### ISSUE TITLE
2s freeze about every 5-20s

### ISSUE THREAD

**Issue by Leosky** [CreeperHost/CreeperHostGui#7]
https://gist.github.com/Leosky/2f625172fbcfdcce4ec1f4ccd65d9aa2

i disabled MineTougether and the freezes stopped.

**Comment by CH-Paul-T** [comment]
Can you confirm if this is client or server, and what features are enabled in the configs? We have an idea what is causing this but more information will help.

**Comment by Leosky** [comment]
Hum, im quite new to minecraft modding so i play on solo so i guess its client-server setup.

Here is the latest config i had the issue : https://gist.github.com/Leosky/8ac681feb7310558c85ea0df02adeedf

i got this error with default param too (default for lastest version of FTB Present Direwolf20)

**Comment by CH-Paul-T** [comment]
Strange, shouldn't be anything running on any kind of loop with that configuration, I'll ask @Cloudhunter to take a look at this.

**Comment by Leosky** [comment]
Ho yeah one more detail, i disconnected from internet during my investigation and, it was fine but it started again as soon as i was reconnecting.

**Comment by CH-Paul-T** [comment]
That's strange, basically assuming operating as expected, there shouldn't be any network-based callbacks running with those configs, so it's probably a bug that it's even happening, but then combine that with the lag as well, I think you may have found 2 separate bugs at once.

**Comment by Cloudhunter** [comment]
Do you have a copy of your fml-client-log? This is rather confusing - I can't think of any code path which could be causing this with your config or even default.

**Comment by Cloudhunter** [comment]
Is the log you provided from the session which you had your Internet connection turned off? If so, would you be able to provide one with the connection on with the lag happening?

**Comment by Leosky** [comment]
i could if i knew where to find this, i tryed but i can't find it :/ i made full minecraft directory research and i didn't find it, .minecraft in appdata neither

**Comment by Cloudhunter** [comment]
Yeah, any log will do to be honest - not quite sure how this is happening but I'll search the code!

**Comment by Leosky** [comment]
latest.log with connection (lots of freeze noticed) : https://gist.github.com/Leosky/8e93995263e0b708879bcaf24feb40f2
latest.log without connection (not freeze) : https://gist.github.com/Leosky/5ad658f98a2fe5e3131e5bf81230ab29

note1: ,note  that i had trouble to reproduce the issue on a good connection, i had to switch to a bad wifi to reproduce it. So may be a running course issue, and it when i'm happy to not have to do lots of debugging atm.
note 2: there is a bunch of Couldn't render entity but its ForegoingIndustry related,i suspected this mod first but they have been warned and after investigation, we arrived here.

**Comment by Cloudhunter** [comment]
I think I've found the issue. Can you try this build and see if it works better?  If so I'll push it to Curse and then poke snowshock to update the dw20 pack!

https://transfer.sh/gQlj8/minetogether-1.12.1-1.8.1.jar

**Comment by Leosky** [comment]
testing now

**Comment by Leosky** [comment]
okay so no noticiable freeze to report for now, i will play with this today if encounter any error i will report here.
first : https://gist.github.com/Leosky/a2d08ae6daaff34072e456a90694fff1 @line 2969

**Comment by Leosky** [comment]
(oops miss clicked)

**Comment by Cloudhunter** [comment]
Turns out I gave you the wrong file, hence the error - but it shouldn't affect much, just you won't be able to configure it from the menu. I'm going to push the build as I'm confident the fix is working as it was a very stupid issue, but if you receive any more freezes please give me a log :)

Will leave this open for the next 24 hours regardless!

**Comment by Leosky** [comment]
https://gist.github.com/Leosky/aa272994d5ceaa44962380217efbef32 crashlog, i disable minetogether to see if its related but there is a shit load of error coming from it

**Comment by CH-Paul-T** [comment]
Crash in that log is cofh.thermalfoundation

Other error is fixed (nobody else is having it) if you use the latest release and not the debug release linked here.

**Comment by Cloudhunter** [comment]
Gonna close this as fixed :)
