### ISSUE TITLE
[Suggestion]Timestamps

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#70]
Sometimes there is a long pause between active chats, with players closing the chat to play the game and then re-opening it later, it is difficult to see when the last recorded message was posted.

Suggestion to add timestamps to chat, preferably as a toggle option (due to the size of chat interfaces, not all players would appreciate text being further cramped by a timestamp).

**Comment by CH-Paul-T** [comment]
Imagine this'd mean two lots of design work when changing things - I propose a tooltip, that way it's out of the main flow and doesn't need to be a consideration when adjusting chat in the future etc.

**Comment by Melodeiro** [comment]
2 minor bugs with it: it disappears for 0.1s when you click message, and also it shows only when hovering first line of the multi-line message
