### ISSUE TITLE
[Bug]: Crashes and bugs with Quilt

### ISSUE THREAD

**Issue by DanMeadWasTaken** [CreeperHost/CreeperHostGui#702]
### Describe the bug

Crash when opening get a server page or loading a world

### Steps to reproduce

Literally do anything related to the mod, and either it doesn't work as intended or crashes the game completely

### Expected behaviour

not crashing, being able to connect to creeper host services etc

### Version

6.0.15

### Minecraft Version

1.19.2

### ModLoader Version

Quilt 0.17.11

### Additional Information

[Latest.log](https://mclo.gs/F0H70nP)
[Another log](https://mclo.gs/nAUxvef)
[A crash](https://mclo.gs/oQYvio2)
[Another crash](https://mclo.gs/74oEujQ)

**Comment by gigabit101** [comment]
We do not offer support for Quilt currently
