### ISSUE TITLE
Unable to verify server issue is back

### ISSUE THREAD

**Issue by Gunner76th** [CreeperHost/CreeperHostGui#71]
Starting a new thread, as the previous one found here was marked as closed: https://github.com/CreeperHost/CreeperHostGui/issues/15

So it looks like this problem is back  and alive. Modpack is https://www.feed-the-beast.com/projects/ftb-interactions FTB Integrations. the server_ip= field in server.properties is empty. the IP and Port used to connect to the server is 107.210.94.69:25565

![image](https://user-images.githubusercontent.com/5566872/57042474-bb6a9600-6c32-11e9-8670-7012f583d070.png)
<details>
  <summary>Click for server.properties information</summary>
#Minecraft server properties<br/>
#Wed May 01 20:54:35 UTC 2019<br/>
spawn-protection=16<br/>
max-tick-time=-1<br/>
query.port=25565<br/>
generator-settings=<br/>
force-gamemode=false<br/>
allow-nether=true<br/>
enforce-whitelist=true<br/>
gamemode=0<br/>
dc_preset=notSet<br/>
enable-query=true<br/>
player-idle-timeout=15<br/>
difficulty=3<br/>
spawn-monsters=true<br/>
op-permission-level=4<br/>
pvp=true<br/>
snooper-enabled=true<br/>
level-type=voidworld<br/>
hardcore=false<br/>
enable-command-block=true<br/>
max-players=20<br/>
network-compression-threshold=256<br/>
resource-pack-sha1=<br/>
max-world-size=29999984<br/>
rcon.port=25575<br/>
server-port=25565<br/>
debug=false<br/>
server-ip=<br/>
spawn-npcs=true<br/>
allow-flight=true<br/>
level-name=world<br/>
view-distance=10<br/>
resource-pack=<br/>
displayname=Team IHOC Presents FTB Interactions Version 1.4.2 https\://discord.gg/0hQAXZIOgrb5RFRG<br/>
discoverability=public<br/>
spawn-animals=true<br/>
white-list=true<br/>
rcon.password=*Redacted*<br/>
generate-structures=true<br/>
online-mode=true<br/>
max-build-height=256<br/>
level-seed=53832741<br/>
use-native-transport=true<br/>
prevent-proxy-connections=false<br/>
enable-rcon=true<br/>
motd=\u00A72Team \u00A7aIHOC \u00A77Presents \u00A71F\u00A72T\u00A74B \u00A73Interactions \u00A75Version 1.4.2<br/>

</details>

**Comment by Gunner76th** [comment]
I also tried the suggestion of setting the server-ip= field, which did not work. Even though I had set a specific port in the server-port=25565 field, it was erroring saying ti was unable to bind to the specified port.

**Comment by gigabit101** [comment]
@Cloudhunter Any idea why this issue has returned?

**Comment by Cloudhunter** [comment]
If you go to https://www.whatismyip.com from the server box, what is the result?

**Comment by Gunner76th** [comment]
Because this is a linux system accessed over an ssh connection doing that
is not possible.  However the IP address listed is the same address used to
connect to the server with the minecraft client as well as to the OS via
winscp and putty, along with an app I use on my android phone to monitor
the overall health of the linux server and its hardware

**Comment by tomtenberge** [comment]
i have the same problem, getting "Unable to do call to server list - will try again in 90 seconds. Reason: Unable to verify server."

i also log into the system trough SSH

**Comment by gigabit101** [comment]
Is this still an issue?

**Comment by tomtenberge** [comment]
I have long since moveed on to both a new server and different modpack, so no idea

**Comment by gigabit101** [comment]
I am going to close this for now if this issue pops back up please do let us know
