### ISSUE TITLE
[Bug]: crashes when you hit open to friends

### ISSUE THREAD

**Issue by BasicWhisper** [CreeperHost/CreeperHostGui#710]
### Describe the bug

Crashes when opening to friends

### Steps to reproduce

1. open the direwolf 20 pack 1.19
2. when in a world click on open to friends

### Expected behaviour

game crashes

### Version

6.1.0.15

### Minecraft Version

1.19.2

### ModLoader Version

forge

**Comment by Cruors** [comment]
Same problem with my Fiancé, we have been fine for weeks and randomly she cant see my worlds anymore and crashes on hosting her own, also her name has changed to a random string on numbers and letters from her edited name and it wont change when I change it.

**Comment by NGminecraft** [comment]
Same. Me and my friend have had this problem for a while.

**Comment by covers1624** [comment]
Fixed in 6.0.18
