### ISSUE TITLE
[Bug]: Any FTB modpack crashes when clicking "open to friends" button

### ISSUE THREAD

**Issue by defdeed** [CreeperHost/CreeperHostGui#717]
### Describe the bug

Client crashes when opening world to friends

### Steps to reproduce

1. Open single player world
2. Click open to friends
3. Crash

### Expected behaviour

Open to friends menu

### Version

6.0.16

### Minecraft Version

1.19.2

### ModLoader Version

Forge

### Additional Information

I first noticed this happening to me while hosting a Stoneblock 3 server; I hosted the server for about a month and then Minetogether started crashing whenever I clicked "open to friends" now with the release of FTB Skies I know it wasn't just the modpack causing it to crash

https://pastebin.com/A7K585H6

**Comment by covers1624** [comment]
Fixed in 6.0.18
