### ISSUE TITLE
[Bug]: It's said "Unable to send messages while client is unverified " that I can't see messages and can't communicate with other

### ISSUE THREAD

**Issue by NOBBUP** [CreeperHost/CreeperHostGui#720]
### Describe the bug

Today, when I communicate with other happily. I asked a lot of questions, they are glad to help to sovlve them. When I asked "Whether I can use my Minecarft ID as my Minetogether ID" They told me "NO!". And I said "f@@k" that without thinking. And then I was banned . I'm so regretful and sorry and sad. I beg you can unban me and solve the problem ,which is "Unable to send messages while client is unverified ". I promise I won't say that word anymore. QAQ

### Steps to reproduce

Today, when I communicate with other happily. I asked a lot of questions, they are glad to help to sovlve them. When I asked "Whether I can use my Minecarft ID as my Minetogether ID" They told me "NO!". And I said "f@@k" that without thinking. And then I was banned . I'm so regretful and sorry and sad. I beg you can unban me and solve the problem ,which is "Unable to send messages while client is unverified ". I promise I won't say that word anymore. QAQ

### Expected behaviour

Unban me and solve the problem ,which is "Unable to send messages while client is unverified ". I promise I won't say that word anymore. 

### Screenshots

![1681821491665](https://user-images.githubusercontent.com/131165602/232779652-decc8b7f-260a-431b-b36a-9830950fee6a.jpg)

### Version

1.19.2

### Minecraft Version

1.19.2

### ModLoader Version

1.19.2

**Comment by Draylynn** [comment]
Ban appeals are submitted via MineTogether.io
