### ISSUE TITLE
[Bug]: Forge version requires sodium AND crashes

### ISSUE THREAD

**Issue by BraveCaperCat2** [CreeperHost/CreeperHostGui#721]
### Describe the bug

The forge version of Minetogether for 1.19.x requires the sodium mod, which isn't available for forge

### Steps to reproduce

1. Install the latest version of minetogether in the curseforge app (latest ALPHA)
2. Launch minecraft

### Expected behaviour

Minecraft launches without any errors.

### Screenshots

![Screenshot 2023-04-18 165749](https://user-images.githubusercontent.com/113925022/232835107-82ce86e8-658b-4f6c-96a6-fe660211bac5.png)
![Screenshot 2023-04-18 165611](https://user-images.githubusercontent.com/113925022/232835083-0c2e2b61-94b5-4616-a3e0-dd16078c0d83.png)
![Screenshot 2023-04-18 165630](https://user-images.githubusercontent.com/113925022/232835099-c67c912e-8d2d-4482-8790-655ff0c93661.png)

### Version

minetogether-forge-1.19.2-6.0.16

### Minecraft Version

1.19.4

### ModLoader Version

44.1.23

### Additional Information

Logs:
[latest.log](https://github.com/CreeperHost/MineTogether/files/11263816/latest.log)

**Comment by gigabit101** [comment]
MineTogether does not require sodium, However it does require PolyLib and to loaded on the correct version of Minecraft

```[18Apr2023 16:39:05.675] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'polylib', Requested by: 'minetogether', Expected range: '[1900.0.2,)', Actual version: '[MISSING]'
	Mod ID: 'minecraft', Requested by: 'minetogether', Expected range: '[1.19.2,1.19.2]', Actual version: '1.19.3'```

**Comment by BraveCaperCat2** [comment]
Firstly, minetogether 1.19.2 should work on 1.19.3 and 1.19.4.
And secondly, poly lib is NOT in the dependancies section of the forge page:
![Screenshot 2023-04-18 172230](https://user-images.githubusercontent.com/113925022/232841623-f33ce8b0-84ed-402e-9541-5efd8b92d1c0.png)

**Comment by gigabit101** [comment]
These are set per file, 
![image](https://user-images.githubusercontent.com/5615438/232848274-6e6bdcb1-7f26-4f4c-82f6-033b389c3ee5.png)

There are changes in Minecraft's chat system in 1.19.2 > 1.19.3 so it is not compatible

**Comment by BraveCaperCat2** [comment]
> These are set per file, ![image](https://user-images.githubusercontent.com/5615438/232848274-6e6bdcb1-7f26-4f4c-82f6-033b389c3ee5.png)
> 
> There are changes in Minecraft's chat system in 1.19.2 > 1.19.3 so it is not compatible

oh.
