### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nessy91** [CreeperHost/CreeperHostGui#724]
### Describe the bug

Paid Subscription not updating to account

### Steps to reproduce

log in and subscribe after subscribing account status not updated, 

subscribed on the 25th and still today the second it hasnt updated out of free account, 

creeper host not helpful either

### Expected behaviour

subscription updates to accoutn and provides status

### Version

website

### Minecraft Version

na

### ModLoader Version

na

**Comment by gigabit101** [comment]
Please open a ticket at https://www.creeperhost.net/contact
