### ISSUE TITLE
ban appeal draylynn 

### ISSUE THREAD

**Issue by GrimmCapybara** [CreeperHost/CreeperHostGui#726]
i got banned while talking wiht you and others today, i accidentally said crap, surprised about the sensitivity of the filter but i need an unban
It says i am unverified now so i dont know how to check my id
_Originally posted by @Draylynn in https://github.com/CreeperHost/MineTogether/issues/535#issuecomment-859335227_

**Comment by GrimmCapybara** [comment]
i was asking about tree farms and steam engines in chatlogs

**Comment by Draylynn** [comment]
Ban appeals are submitted on MineTogether.io
