### ISSUE TITLE
[Bug]: Minetogether is intercepting crashlogs 

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/CreeperHostGui#727]
### Describe the bug

Check crashlog only to see minetogether in the stacktrace

### Steps to reproduce

Cause a mod pack with minetogether in it to crash, FTB Skies, FTB Inferno, Direwolf20 1.19 all work. Once it crashes you'll get a log that looks like this:
https://gist.github.com/Saereth/15f9b07cf4403b0a9b59ee74c8022c98

This is not actually the underlying cause of the crash though so players need to disable minetogether then reproduce the crash to get a real crashlog.

### Expected behaviour

I would expect the actual crashlog to be generated for the problem without having to disable minetogether.

### Version

1.19.2-6.0.16 and 1.18.2-6.0.16

### Minecraft Version

1.19.2 and 1.18.2

### ModLoader Version

43.2.11 and 40.1.93

**Comment by covers1624** [comment]
Fixed in 6.0.18
