### ISSUE TITLE
[Suggestion]: Chat box in F1 mode

### ISSUE THREAD

**Issue by AdamOlanAdam** [CreeperHost/CreeperHostGui#728]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/CreeperHost/MineTogether/assets/107753692/718da396-513d-4cc5-a5ae-c00344a3a1c8)
The chat box does not go away in F1 mode, sometimes when I'm streaming with my friends I alt+tab a lot out of the game, to not get the pause menu open I open chat instead. When MT is installed this big ugly box shows up.

### Describe the solution you'd like

I'm not sure about how MT works but you can probably make it 100% opacity when f1 is on

**Comment by gigabit101** [comment]
![make-it-so-picard](https://github.com/CreeperHost/MineTogether/assets/5615438/c23d40e9-9535-4cc8-a83b-60cb6ee8c8d6)

@brandon3055

**Comment by BraveCaperCat2** [comment]
> ![make-it-so-picard](https://user-images.githubusercontent.com/5615438/237758524-c23d40e9-9535-4cc8-a83b-60cb6ee8c8d6.gif)
> 
> @brandon3055

That has nothing to do with the mod.

**Comment by gigabit101** [comment]
This should have already been fixed and released
