### ISSUE TITLE
[Bug]: No response on ban appeal

### ISSUE THREAD

**Issue by Denace84** [CreeperHost/CreeperHostGui#729]
### Describe the bug

No response on ban appeal

### Steps to reproduce

1. Accidently use the word "shit" in a sentence.
2. Get banned for writing "shit"
3. Explain yourself in an appeal
4. Wait for 2,5 weeks and getting no response

### Expected behaviour

I'm a 40 year old Computer Scientist, playing Minecraft since Beta and hosted several MC-Servers myself. I tried MineTogether and thought about using it on my server aswell. Since I didn't offend or hurt anyone, I figured a friendly explanation would be enough to get unbanned. However, it looks like you're just being ignored. I should at least be able to expect to get an answer if there's an option to send an appeal. If you have a zero tolerance policy on swearing, that's perfectly fine. Your mod, your rules. But then don't give people the opportunity to explain their mistake, only to then ignore it. If I did that, my servers would be empty by now.

Ban ID: mtg-ban=644b0ccc5e5089.97645238

### Version

all

### Minecraft Version

1.18.2

### ModLoader Version

all

**Comment by Draylynn** [comment]
Swears/vulgar language is often an insta-ban more often by the automated bot, but chat mods too if they see it.
This ban appeal is handled.

**Comment by rockrevenchy** [comment]
Honestly, same for me, I've been ghosted for 6 months after saying the word "arse" as a silly joke regarding the "ars nouveau" mod and appealing twice didn't get me much.

No clue what the point of the appeal even is.

**Comment by rockrevenchy** [comment]
It is also unfortunate how the blacklisted words seems very random and there is no reference nor list of it, ass was fine and commonly used when i was around but arse isn't, the lack of rule precision or even warnings/other punishments before makes it feel highly arbitrary and random in my opinion.

**Comment by Draylynn** [comment]
If your MT profile has an active appeal button; resubmit the appeal.
Appeals may be denied for a number of reasons, or accepted.
Appeals rarely sit awaiting attention longer than 24 hours, most are handled within mins.

**Do not hijack other peoples issues, if you require help with a possible bug in the ban system, create your own issue and list your ban ID for investigation**.
