### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by Ponkerlista** [CreeperHost/CreeperHostGui#732]
### Is your feature request related to a problem? Please describe.

Another player was confused about the differences between Blood magic's Dagger of Sacrifice and its Sacrificial Dagger counterpart, i had sent them a message in minetogether saying that the one that has the description of "Just a prick of the finger" is the one that uses your own hearts to pool blood to your altar, which is useful if you have a heart amulet or if you have enough saturation for your hearts to restore, whereas the other one was used to sacrifice other mobs and it exceptionally useful if you have a mob farm or 2 you wouldn't mind sacrificing for the Altar's Blood pools. I believe i may have been banned from the word "Prick" in the "just a prick of the finger" description, so please correct this, i dont wanna be banned everytime i talk about blood magic.

### Describe the solution you'd like

If possible, please implement a chance for freddy to ping an admin to check the ban decision for words like "prick" because i said it because i was trying to help someone. If not, mabye have a whitelisted set of keywords that could be used in the same sentence to avoid freddy publically executing you. Thank you.

**Comment by BraveCaperCat2** [comment]
do ban appeal on creeperhost website.

**Comment by gigabit101** [comment]
Ban appeals can be submitted at https://minetogether.io/
