### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by amors10** [CreeperHost/CreeperHostGui#733]
### Describe the bug

Cannot Appeal Ban

### Steps to reproduce

1. Log in and start world
2. open chat and click on minetogether tab
3. Cant send messages - chat says "Unable to send messages while client is unverified"

### Expected behaviour

Should be able to send messages

### Version

6.0.18

### Minecraft Version

1.18

### ModLoader Version

43.2.11

### Additional Information

This is likely related to getting banned. I did not read the rules properly and let a curse word slip into chat. I cant connect my account to MC due to being banned and cant submit a ban appeal due to not having my account connected.

**Comment by BraveCaperCat2** [comment]
Use creeperhost website to do ban appeal - MC can't do a ban appeal

**Comment by gigabit101** [comment]
Ban appeals can be submitted at https://minetogether.io/
