### ISSUE TITLE
[Suggestion]: Movable links

### ISSUE THREAD

**Issue by Catacide** [CreeperHost/CreeperHostGui#734]
### Is your feature request related to a problem? Please describe.

Hey! 

I have been keeping adding Minetogether on minecraft packs I play to have server like feel in my singleplayer worlds, and it works perfectly! Only one thing is little annoying and it it those links to "Get a server" and "Friends list", mostly get server link since its so in middle of the screen and in some packs it will be on top of singleplayer button :)

### Describe the solution you'd like

So simply, would it be possible for players to move those in future versions? :)

**Comment by BraveCaperCat2** [comment]
Use fancy menu if the modpack developers don't have it to move around the buttons - if they do, just tweak the buttons with the mod configuration.

**Comment by gigabit101** [comment]
I'm pretty sure we have a config to disable these buttons
