### ISSUE TITLE
[Bug]: "language" is automatically replaced with the real language name

### ISSUE THREAD

**Issue by aaronliu0130** [CreeperHost/CreeperHostGui#739]
### Describe the bug

I see "English" when the word "language" is sent out on its own and my MC language is English or Pirate Speak and "简体中文" on Simplified Chinese

### Steps to reproduce

1. Send "language" using the in-game Minetogether chat, all lowercase and in its own message without anything else

### Expected behaviour

I see "language"

### Screenshots

![image](https://github.com/CreeperHost/MineTogether/assets/11874211/b40d557a-2c18-4c9e-8f71-e61513079f33)
![image](https://github.com/CreeperHost/MineTogether/assets/11874211/d6aa79fa-a904-4d9f-bc6a-b7823a7ec7c6)
![image](https://github.com/CreeperHost/MineTogether/assets/11874211/9bd6b7a6-f101-4ac0-9661-92a65aadfc98)
![image](https://github.com/CreeperHost/MineTogether/assets/11874211/f16e193c-2c2e-4c77-aacf-a655ba2941bb)

### Version

6.0.18

### Minecraft Version

1.19.2

### ModLoader Version

Forge 43.2.11

### Additional Information

Using FTB Skies 1.2.1
Apparently dev team is already investigating but a tracking issue is better regardless

**Comment by aaronliu0130** [comment]
Additionally, if you type certain keys like "language.name" or "item.<modnamespacename>.<itemID>" (e.g. "item.minecraft.debug_stick") they will turn into fake links and turn into their corresponding name, regardless if there are other characters in the message or not

**Comment by brandon3055** [comment]
This issue will be fixed in the next release of Mine together

**Comment by brandon3055** [comment]
This issue should now be fixed.
