### ISSUE TITLE
banned from server, but minetogether says account is in good standing[Bug]: 

### ISSUE THREAD

**Issue by satmeister** [CreeperHost/CreeperHostGui#741]
### Describe the bug

i am banned from stoneblocks 3 public server (Unnamed #279) in Gb but i can still chat to people, and i cannot appeal or remove ban. i also do not know why I was banned I was just playing on my own on the server

### Steps to reproduce

Play the game open the public server and click on server unnamed 279 to play and it says i am blocked

### Expected behaviour

To enter the game and play on my server

### Version

1.7.1 Stoneblock 3

### Minecraft Version

1.18.2

### ModLoader Version

1.7.1 stoneblock 3 FORGE

**Comment by ThePaul-T** [comment]
We don't control the servers (unless explicitly mentioned in their MoTD), just provide a list of them which are validated as online.
