### ISSUE TITLE
[Bug]: Got unbanned but chat still cant verify

### ISSUE THREAD

**Issue by itsjermey** [CreeperHost/CreeperHostGui#742]
### Describe the bug

Chat Wont verify

### Steps to reproduce

I just log on and chat says its unverified 

### Expected behaviour

Log on and I am able to chat on minetogether Stoneblock 3

### Version

Stoneblock 3

### Minecraft Version

1.18.2

### ModLoader Version

FTB

**Comment by Draylynn** [comment]
MineTogether name? Logs? Which MineTogether build?
