### ISSUE TITLE
[Bug]: Unable to appeal ban 

### ISSUE THREAD

**Issue by ExNando** [CreeperHost/CreeperHostGui#746]
### Describe the bug

Ban Appeal

### Steps to reproduce

Hello Draylynn, I made a ban appeal, recently I was banned for some reason regarding rules I think and it was unintentional. It's probably because I spoke another language in the chat but as soon as I was notified I stopped. I would like you to read my ban appeal.

BAN ID: mtg-ban=64d05ab7281086.87315527

### Expected behaviour

I believe it's because I texted in another language making it happen

### Version

N/A

### Minecraft Version

N/A

### ModLoader Version

N/A

### Additional Information

I'm playing FTB StoneBlock 3

**Comment by Draylynn** [comment]
I already explained to you on the other issue you hijacked; If the appeal failed, try again in 2 weeks.
There is nothing wrong with the appeal system, your appeal failed, I know this, I'm the one that failed it.
**Try again in 2 weeks**
