### ISSUE TITLE
[Bug]: Ban appeal got ghosted for more than 3 weeks

### ISSUE THREAD

**Issue by DilithiumNitrate** [CreeperHost/CreeperHostGui#748]
### Describe the bug

While talking about Redstone Arsenal's weapons over MineTogether chat in FTB Skies, I used a curse word and got banned automatically. Soon after I realized what I did, I submitted an appeal apologizing for what I said, but now after more than 3 weeks it seems the ban (ID: `mtg-ban=64bbd7bad7c362.09874863`) got ghosted altogether. I'm pretty sure it wasn't rejected because the ban entry in my account standing still says "appeal submitted".

### Steps to reproduce

1. Talk about Redstone Arsenal's flux-infused bow and quiver, focusing on their 1.12.2 iterations
2. Say the following in global chat (censored word referring to the aforementioned bow):
> put multishot on that [*other word for a female dog*] and it stays relevant all the way through Draconic Evolution
3. See all your messages disappear and get `Banned for NLP detected toxic/obscene/insult message`
4. About 30 minutes later (making a MineTogether account in the meantime), submit an appeal

### Expected behaviour

Before I knew that swear words were a ban on first offense, after I realized what I said I expected to see the message get autocensored and myself warned or temporarily muted. After I got banned and made a MineTogether account to see what happened, I read up on what the appeal process looks like and from what I could gather, I expected my appeal to get handled (in either direction) in 3 days max.

### Screenshots

![obraz](https://github.com/CreeperHost/MineTogether/assets/38111406/b3f298c8-d648-45f5-8b99-39178df63577)

### Version

6.0.18

### Minecraft Version

1.19.2; FTB Skies 1.2.1

### ModLoader Version

Forge 43.2.11

**Comment by SourceIPCMS** [comment]
jeah thats realy toxic behavior, i think thats got banned for an long time

**Comment by rockrevenchy** [comment]
You better be comfy being banned, they don't unban, just remove the mod

**Comment by brandon3055** [comment]
Ban appeals can be submitted via https://minetogether.io
create & link your account if you have not done so already.
Then you should be able to see your ban status and/or submit an appeal.

**Comment by DilithiumNitrate** [comment]
> Ban appeals can be submitted via https://minetogether.io create & link your account if you have not done so already. Then you should be able to see your ban status and/or submit an appeal.

Thanks for the concern, @brandon3055 (did you get here by searching for your own mod's name?), but the whole point of my issue is that I did, in fact, connect and submit an appeal 3 weeks before filing the issue. It's **still** at "appeal submitted" at the time of writing this comment, for the record.

**Comment by gigabit101** [comment]
We have no unban requests, If you are still banned then your appeal has been denied.
You are welcome to try again once your last appeal has expired

**Comment by DilithiumNitrate** [comment]
> We have no unban requests, If you are still banned then your appeal has been denied. You are welcome to try again once your last appeal has expired

Understandable but the issue is that my appeal hasn't expired, that or your web interface is bugged. The account standing entry is stuck at "appeal submitted" where the button for submitting an appeal was before I did so. (Also are you saying that all bans for rule violations are permanent?)

**Comment by ThePaul-T** [comment]
Basically, you can appeal once every 14 days, it goes into a slack channel and we've not really figured out how to feedback from what buttons the team click (I know there are ways, but honestly, it's low priority).

Almost all appeals are approved unless they're rude, entitled or show lack of remorse (Or they're particularly bad like targeted racism etc)

Hopefully the ban appeal feedback etc will be improved when we finally get around to the new website we've been trying to find time to do for the last 18 months or so, but we've been focusing on the mod it's self and our day jobs.

**Comment by DilithiumNitrate** [comment]
> Basically, you can appeal once every 14 days, it goes into a slack channel and we've not really figured out how to feedback from what buttons the team click (I know there are ways, but honestly, it's low priority).

Thanks for the info in theory, but my issue is that no, I cannot appeal it again. It has been almost 4 months and the ban is still visible on my profile, and more importantly, **the button for submitting appeals** on my account standing still – just like in the screenshot – says "appeal submitted" and is *not* clickable. Or are you saying that there are alternate ways of sending an appeal?

You mentioned that you're trying to move to a new website – if my issue is a bug, hopefully appeal submissions will be fixed by then. If it's not a bug, then I probably really was ghosted, which as far as I can tell isn't – or at least should not be – normal, and is why I filed my issue in the first place, with no resolution to this day in spite of gigabit101 incorrectly marking this issue completed.

**Comment by DilithiumNitrate** [comment]
If anyone looks at this issue again, you can in good conscience _keep it closed_. Somewhere in the 3.5 months since my last message, my MineTogether account connection got removed, I reestabilished it and now it's in good standing. Whoever's responsible, thank you, and if it wasn't intentional, guess I'll thank the bug.
![MineTogether.io account standing tab, saying: "Your account is in good standing"](https://github.com/CreeperHost/MineTogether/assets/38111406/eac02e9a-5c34-4e92-9d25-cb11f0f6b585)
