### ISSUE TITLE
[Bug]: MT Chat won't connect

### ISSUE THREAD

**Issue by Nandead559** [CreeperHost/CreeperHostGui#749]
### Describe the bug

Unable to connect to minetogether

### Steps to reproduce

1. Open minecraft 
2. click multiplayer
3. bottem left stuck on connecting or may change to disconnected

### Expected behaviour

connects to minetogether

### Screenshots

![Screenshot 8_13_2023 3_35_15 PM](https://github.com/CreeperHost/MineTogether/assets/141856575/ac666666-c234-4309-9d27-b2b84c2b3c64)

### Version

All

### Minecraft Version

1.12.2

### ModLoader Version

Forge - 14.23.5.2860

**Comment by SourceIPCMS** [comment]
smels like Banned Acc. see on minetogether.io to your account standing.

**Comment by gigabit101** [comment]
Can you check your account status at https://minetogether.io/
