### ISSUE TITLE
Reordering Of Chat Dropdown List In Full Screen Chat Window

### ISSUE THREAD

**Issue by Guswut** [CreeperHost/CreeperHostGui#75]
Hello,

Could we please get the drop down list of chats/friends changed to alphabetical order, with the exception of "Main" which should always be at the top, instead of the order they're currently being rendered in?

Attached screenshots of the list in both a private chat as well as main chat:

![2019-05-30--11-19-30---](https://user-images.githubusercontent.com/3208397/58655134-4ee4c480-82ce-11e9-82af-6d6b29a49e6e.png)
![2019-05-30--11-19-46---](https://user-images.githubusercontent.com/3208397/58655135-4f7d5b00-82ce-11e9-99f7-b12c3169aec9.png)

Thank you!

**Comment by CH-Paul-T** [comment]
This was actually the expected behavour (your request), however it seems hashset doesn't keep ordering so switching to linkedhashset should fix this.
