### ISSUE TITLE
[Bug]: Ban Appeal

### ISSUE THREAD

**Issue by SourceIPCMS** [CreeperHost/CreeperHostGui#750]
### Describe the bug

Ban automatism

### Steps to reproduce

no clue because i do nothing

### Expected behaviour

got ban for what ? nothing ? Dray ?! 

### Version

latest

### Minecraft Version

1.19.2

### ModLoader Version

forge

**Comment by SourceIPCMS** [comment]
why whe got ghostet on Ban Apeal ?


minetogehter Name Zorgimp #87B9D

Ban ID: mtg-ban=64e9d80fafae62.86386295

Moderator: draylynn

Reason: Banned

Message: p1692770489423959

Timestamp: 2023-08-26 10:46:39

sorry for my bad english, but understand me i want to resolve this Problem

**Comment by brandon3055** [comment]
Ban appeals can be submitted via https://minetogether.io
create & link your account if you have not done so already.
Then you should be able to see your ban status and/or submit an appeal.

**Comment by SourceIPCMS** [comment]
for ur record, a ban appeal is summited weaks ago, but just got ghostet.

**Comment by BullxMoose** [comment]
i submitted a ban appeal months ago i dont even know if its been looked at. To be honest I really dont even know why i was banned i usually refrain from talking to others on the chat unless its to ask a question.
My user name is NetherStarRabbit#5b3f4

Ban ID: mtg-ban=63dcd33fb8fe95.89061826

Moderator: draylynn

Reason: Banned

Message: p1675390384615459

Timestamp: 2023-02-03 09:26:23

**Comment by Draylynn** [comment]
There's a Discord and a ban appeals system, this GitHub is for bugs and issues with the mod itself.

If you submitted a ban appeal and it failed, try again in 2 weeks.
One of you used dictionary defined vulgar language and the other was discussing a highly inappropriate topic - If that helps refresh your memories for your next appeal.
