### ISSUE TITLE
[Bug]: MT Chat not working after unban

### ISSUE THREAD

**Issue by Pridey12** [CreeperHost/CreeperHostGui#752]
### Describe the bug

Cant send a messages on minetogether

### Steps to reproduce

when i open chat. it seems that i cant send a message to mine together column

### Expected behaviour

I was banned for atleast 3 days. I got unbanned then the day after it only worked for a day.

### Screenshots

![image](https://github.com/CreeperHost/MineTogether/assets/24918241/1f386a5d-341a-4be7-88eb-9a43c17f0d36)

### Version

6.10

### Minecraft Version

1.18.2

### ModLoader Version

Forge

**Comment by gigabit101** [comment]
Have you tried restarting your game?
If this continues please do let us know
