### ISSUE TITLE
[Bug]: Minetogether is still obfuscating crash reports

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/CreeperHostGui#757]
### Describe the bug

If you have minetogether installed and you crash during load it appears to be a minetogether crash

### Steps to reproduce

install minetogether, remove a mod's dependency, instead of the actual crash log telling you the missing dependency you'll get a crash that seems to indicate minetogher. You have to manually remove minetogether every time to get an actual crash log. 

### Expected behaviour

For minetogether not to crash/show the actual cause of the crash. 

### Version

minetogether-forge-1.18.2-6.1.4

### Minecraft Version

Multiple versions, 1.18.2, 1.19.2

### ModLoader Version

forge multiple versions but 43.3.5 for 1.19.2

### Additional Information

crashlog example, in this example I forced the crash by removing codechickenlib which was needed for enderstorage, but it can be just about any thing that causes a crash during loading

[mtg.txt](https://github.com/CreeperHost/MineTogether/files/13430765/mtg.txt)

Originally reported here
https://github.com/CreeperHost/MineTogether/issues/727

**Comment by covers1624** [comment]
This is resolved in `6.2.0`+
