### ISSUE TITLE
[Bug]:  1.19.2 clientside crash

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/CreeperHostGui#758]
### Describe the bug

Several users reporting a crash related to minetogether

### Steps to reproduce

Unsure, conflicting steps of reproducibility, most seem to be switching around in windows

### Expected behaviour

No crash

### Version

minetogether-forge-1.19.2-6.2.0

### Minecraft Version

1.19.2

### ModLoader Version

43.3.5

### Additional Information

crash log:
https://gist.github.com/Saereth/ef4185985e69c180ff1c9637e95b7dab

**Comment by aaronhowser1** [comment]
This happens when chat is opened after disabling MT chat in the config. 

`because "this.chatWidthSlider" is null` It's likely null because it's disabled.

**Comment by aaronhowser1** [comment]
This happens in 1.18 as well: https://gist.github.com/aaronhowser1/ac15526ae984ea6fe456babe3a434ea8

**Comment by schmintendo** [comment]
Happens to me as well

Crash log:
https://gist.github.com/schmintendo/235febb47918450c65f22b5b733953f2

**Comment by covers1624** [comment]
This has been resolved in `6.2.1`+
