### ISSUE TITLE
Username Colors In Chat Change Request

### ISSUE THREAD

**Issue by Guswut** [CreeperHost/CreeperHostGui#76]
Hello,

Could we please have it so your own message's name was not in the same white as the non-friend users, such as dark green, or gold for example?

And could we have it so non-friend users are dark grey or something instead of the same color as the chat text?

Attached is a screenshot showing the current chat window, yay for screenshots!

![2019-05-30--11-41-47---Minecraft 1 12 2](https://user-images.githubusercontent.com/3208397/58656014-4ee5c400-82d0-11e9-9afb-e817c4dc3c1a.png)

Thank you!

**Comment by CH-Paul-T** [comment]
Hello,

Honestly, I was thinking of implementing this already, only just getting around to reading the issue tracker.

So this is almost certainly a yes, I was planning a light grey (just enough that it's not white, and noticably not) for usernames.

Regards,
Paul
