### ISSUE TITLE
[Bug]: cant sign in to mine together for appeal at all.

### ISSUE THREAD

**Issue by 40niner** [CreeperHost/CreeperHostGui#762]
### Describe the bug

i click on the ban appeal and everytime i try to sign in, it fails

### Steps to reproduce

you probably cant reproduce it since your a mod or use with some sort of randome access

### Expected behaviour

unexpected something, wont let me log in and request an appeal

### Version

idk

### Minecraft Version

idk

### ModLoader Version

idk

### Additional Information

all i said was nazis, i got banned immediately, but my friend said hiroshima and nagasaki and didnt get banned... wth

**Comment by Draylynn** [comment]
Are you still having issues accessing the ban appeals page?
