### ISSUE TITLE
[Bug]: Freeze at startup, very last step

### ISSUE THREAD

**Issue by KuronoKira** [CreeperHost/CreeperHostGui#763]
### Describe the bug

The game freezes just before exiting the load screen at startup

### Steps to reproduce

1. Add MT to the modpack "UltimateAlchemy" (1.12)
2. Start the game

### Expected behaviour

Game should start up just fine

### Version

2.5.5-2.5.6

### Minecraft Version

1.12

### ModLoader Version

Forge ?

### Additional Information

[latest.log](https://github.com/CreeperHost/MineTogether/files/13843536/latest.log)

**Comment by Draylynn** [comment]
Lots of things happen when aspects finish loading, do you have a debug.log?
