### ISSUE TITLE
[Bug]: Game crash MTChat

### ISSUE THREAD

**Issue by idontusethisotherthanforthis** [CreeperHost/CreeperHostGui#767]
### Describe the bug

game crashes when booting because (something something) minetogetherchat

### Steps to reproduce

1, open curseforge modpack. 2, start minecraft like normal. 3, when the loadingbar is beginning to go, it crashes and I get and errorcode. 

### Expected behaviour

for the game to start up and take me to the main menu

### Screenshots

![felkod-1](https://github.com/CreeperHost/MineTogether/assets/157237861/6b735093-0f61-44ea-815a-3fc99f86eb4f)

### Version

6.2.1

### Minecraft Version

Modded minecraft 1.20.1

### ModLoader Version

Forge

### Additional Information

My game is in swedish, but the main thing is the code that crashed. And that is still in English

**Comment by brandon3055** [comment]
In order to troubleshoot this issue, we will need the full crash report.
This can be found in the "crash-reports" folder in the minecraft instance folder.
You can use our paste service to upload the crash report: https://pste.ch/

The "latest.log" file from the logs folder may also be useful.

**Comment by idontusethisotherthanforthis** [comment]
I'm sorry for not writing in a while, I did the exact same thing again and copied the note folder with the crashreport. Should I paste it here? I updated and I still have the same problem

**Comment by Draylynn** [comment]
In order to troubleshoot this issue, we will need the full crash report.
This can be found in the "crash-reports" folder in the minecraft instance folder.
You can use our paste service to upload the crash report: https://pste.ch/

The "debug.log" or "latest.log" file from the logs folder may also be useful.
