### ISSUE TITLE
[Ban Appeal]: False banned and my appeal wont be seen on website

### ISSUE THREAD

**Issue by RealPapaCal** [CreeperHost/CreeperHostGui#768]
### Describe the bug

First off, I'm sorry for make a ban appeal here, but it has been a week since I submitted my ban appeal and it still says "appeal submitted" and most likely hasn't even been viewed yet.

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Screenshots

![image](https://github.com/CreeperHost/MineTogether/assets/132599386/0c4c4636-00c6-4d45-b387-32ad726bc4ec)

### Version

N/A

### Minecraft Version

N/A

### ModLoader Version

N/A

### Additional Information

Ban ID: mtg-ban=65c06baa006b42.96746363
Moderator: draylynn
Reason: Banned
Message: p1707108934445909
Timestamp: 2024-02-05 05:01:30

**Comment by Draylynn** [comment]
It wasn't a false ban. You were clearly heavily and inappropriately spamming in chat. If your appeal failed, try again in 2 weeks.

**Comment by RealPapaCal** [comment]
Heavily? and in inappropriately? I didn't realize how big a single message was, and I sure would like to know how "p1707108934445909" is inappropriate.

**Comment by ThePaul-T** [comment]
That is an internal id to a timestamp of the message.
________________________________

**Comment by RealPapaCal** [comment]
Can you share what the messages were then? Cause i do not remember ever "heavily and inappropriately spamming"

**Comment by Draylynn** [comment]
You and one other user were spamming nonsense in chat.
Again: If your ban appeal failed, there is a 2 week cooldown to try again.
