### ISSUE TITLE
Banned for seemingly no reason

### ISSUE THREAD

**Issue by DjAlEx234** [CreeperHost/CreeperHostGui#77]
Earlier (Around 9AM CST), I was talking in the MineTogether global chat and the moderator kicked me for "Profanity/Swearing". It happened after someone said "cyka", and someone else responded "Can someone be banned for swearing in another language?". And I responded "yes". And for some reason, I was banned/kicked from the global chat. Also, if it helps, I was in FTB Interactions at the time. IGN:djalex234

**Comment by DjAlEx234** [comment]
Also, this issue occurred on June 1st, in case timezones cause an interference.

**Comment by gigabit101** [comment]
Bans are permanent, the rules are displayed on connecting to chat for a reason.

**Comment by DjAlEx234** [comment]
But I didn't break any of the rules
