### ISSUE TITLE
[Bug]: No "Appeal ban" button in the MTG website

### ISSUE THREAD

**Issue by bluestarKun** [CreeperHost/CreeperHostGui#771]
### Describe the bug

No "Appeal ban" button in the MTG website. Looked up how to appeal a MineTogether ban, brought me to a previous ban appeal, I clicked "new Issue" it brought me to a page with 3 options, with the 3rd being labeled "Ban Appeal" so I clicked it, I was brought back to the MineTogether homepage rather than any Appeal Claim page. I can go to my Account Standing and see a previous ban, with no clear description as for WHY I was banned, and no button to for Appeal there either

### Steps to reproduce

think this is more of a visual bug or you just screwing me over

### Expected behaviour

To be taken to a distinct page to enter my Ban ID that's labeled Appeal

### Screenshots

![Screenshot 2024-03-30 135033](https://github.com/CreeperHost/MineTogether/assets/165509087/b25ea735-ef74-42b0-9fd5-69c047ae0704)

### Version

no idea

### Minecraft Version

1.12.2

### ModLoader Version

FTB

**Comment by Draylynn** [comment]
If your account is in good standing, there's a chance the ban was already reversed, for example; If you got caught in the cross-fire of another user being banned. _Toggle chat off for a few mins, then back on in ESC > chat bubble/options_
Technically not a bug and the accidental ban was entirely my fault and already reversed.

**Comment by bluestarKun** [comment]
well there wasn't a way to post about "webpage design flaws" so I picked the next best thing which was Bug Report

**Comment by Draylynn** [comment]
The dev's have your feedback; The ban appeals page has plans for a rework in the future.

**Comment by bluestarKun** [comment]
good to know. thanks for understanding
