### ISSUE TITLE
[Bug]: Open to Friends button overlaps "save and quit" button

### ISSUE THREAD

**Issue by Lil-GreenApple** [CreeperHost/CreeperHostGui#773]
### Describe the bug

the "open to friends" button overlaps with the "save and quit" button so I can't click the open to friends button without closing the game.

### Steps to reproduce

1. Using BigChadGuys Plus modpack from CurseForge, added MineTogether mod + Polylib mod.
2. Created single player world, hit Esc to see Menus.
![ddfdasdfsafd](https://github.com/CreeperHost/MineTogether/assets/166647741/13e5d026-137a-45dc-9c95-7cc08746d9f3)
3.  Unable to click the Open to Friends button as doing so also clicks/only clicks? the "Save and Quit" button.
4. I tried to change the GUI scale in settings in case that would help but it did not.

### Expected behaviour

Expected the Open to Friends button to be on its own line separate from other buttons.

### Version

minetogether-fabric-1.20-6.2.3

### Minecraft Version

1.20.1

### ModLoader Version

Fabric 0.91.0

**Comment by ThePaul-T** [comment]
Doesn't look like a bug, probably another mod is either adding or moving buttons. You'll need to add a menu mod to move them around.
