### ISSUE TITLE
[Bug]: Neoforge 1.20.4 Minetogether Crashes when you click the Get a Server Button

### ISSUE THREAD

**Issue by Saereth** [CreeperHost/CreeperHostGui#774]
### Describe the bug

Crashing when click Get a Server

### Steps to reproduce

- Install Minetogether and dependencies in a fresh Neoforge instance, no other mods.
- Click Get a server on the main menu
- Crash

### Expected behaviour

To be able to open the get a server screen

### Version

minetogether-neoforge-1.20.4-6.2.4.jar

### Minecraft Version

1.20.4

### ModLoader Version

NeoForge 20.4.233

### Additional Information

Crashlog:
https://mclo.gs/6xxN07B

**Comment by brandon3055** [comment]
This issue is resolved with the latest versions of MineTogetehr and PolyLib
