### ISSUE TITLE
[Bug]: java.lang.nullpointerexeption: updating screen events

### ISSUE THREAD

**Issue by ShadowEnder7111** [CreeperHost/CreeperHostGui#775]
### Describe the bug
**I had realised this was the incorrect area to complain about this issue, i am sorry i had clicked the incorrect place**
unable to use optifine to use a shaderpack on minecraft java - shaderpack is complementary shaders unbound

### Steps to reproduce

install curseforge, download optifine, place optifine into mod section, download complimentary shaders unbound, load game, enter shaders in settings, click on shaderpack, crash

### Expected behaviour

my expectation would have been to load the minecraft version, enter settings, set the shaders to complimentary shaders unbound, made a world and play the modded world with the shaderack

### Version

1.12.2

### Minecraft Version

1.12.2

### ModLoader Version

14.23.5.2860

**Comment by ShadowEnder7111** [comment]
could someone possibly be able to send me to the correct area where this issue could be helped? i am unable to find where this issue could be resolved

**Comment by gigabit101** [comment]
You will need to report this to the author of the shader pack or the optifine devs
