### ISSUE TITLE
[Bug]: i cant verify my email because it wont send my email

### ISSUE THREAD

**Issue by Drkumi2721** [CreeperHost/CreeperHostGui#778]
### Describe the bug

i cant verify my email because it wont send my email

### Steps to reproduce

?

### Expected behaviour

send me the email and i can verify

### Version

?

### Minecraft Version

?

### ModLoader Version

?

**Comment by Draylynn** [comment]
Check spam folders etc. Is there a chance you typo'd the email?

**Comment by gigabit101** [comment]
closed due to inactivity
