### ISSUE TITLE
[Bug]: mouseClicked event handler

### ISSUE THREAD

**Issue by Draylynn** [CreeperHost/CreeperHostGui#779]
### Describe the bug

Crashing when opening Friends Chat.

### Steps to reproduce

Install pack.
Open friends chat.
Crash.

`Caused by: java.lang.IllegalAccessError: class dev.ftb.packcompanion.integrations.minetogether.MineTogetherPauseProvider tried to access private method 'void net.creeperhost.minetogether.chat.gui.FriendChatGui.<init>()' (dev.ftb.packcompanion.integrations.minetogether.MineTogetherPauseProvider is in module ftbpc@20.4.2+mc1.20.4 of loader 'TRANSFORMER' @4c296f0a; net.creeperhost.minetogether.chat.gui.FriendChatGui is in module minetogether@6.3.1 of loader 'TRANSFORMER' @4c296f0a)`

### Expected behaviour

No crashing.

### Version

6.3.1

### Minecraft Version

1.20.4

### ModLoader Version

Neoforge-20.4.237

### Additional Information

This crash seems restricted to certain users, I myself cannot replicate it.

FTB NeoTech - 1.4.1
Latest and MT-latest logs included.
[minetogether-latest.log](https://github.com/user-attachments/files/16194225/minetogether-latest.log)
[neoforge-latest.log](https://github.com/user-attachments/files/16194226/neoforge-latest.log)
Affected user: DirtLava#DF2C1 (And one of their friends is crashing too).

**Comment by ThePaul-T** [comment]
Not a MineTogether issue.
