### ISSUE TITLE
I was banned even though I didn't break any rules.

### ISSUE THREAD

**Issue by DjAlEx234** [CreeperHost/CreeperHostGui#78]
Yesterday early in the morning, I was banned from the server even though I did nothing wrong. The conversation went as follows: (person1): "cyka" (person2): "Can you get banned for swearing in a different language?" (me): "yes". Then I was banned. Can someone explain to me what rule I broke and if there is any way I can be unbanned?

(IGN: djalex234)

**Comment by Draylynn** [comment]
Are you able to connect now?
It appears your ID was mis-clicked when the ban was issued.

**Comment by DjAlEx234** [comment]
Yes I can, thank you
