### ISSUE TITLE
[Bug]: Crash when trying to open FTB Genesis with MineTogether

### ISSUE THREAD

**Issue by ArtpokeBr** [CreeperHost/CreeperHostGui#786]
### Describe the bug

In the Latest Version of FTB Genesis, Adding Minetogether causes the pack to crash during load.

### Steps to reproduce

1. Try to add Minetogether to FTB Genesis to 1.8.0
2. The game won't boot.
3. Removing the Mod seems to.. fix the issue?

### Expected behaviour

Be able to properly boot into the pack with no issues.

### Screenshots

![image](https://github.com/user-attachments/assets/00b49114-d2c1-4062-a71a-8c9e543bc5d7)

### Version

1.19.2-6.2.4

### Minecraft Version

1.19.2

### ModLoader Version

Forge - 43.3.13

### Additional Information

Here's the Crash Report. It seems to be something related to Mixins?
[crash-2024-09-09_19.29.38-client.txt](https://github.com/user-attachments/files/16937296/crash-2024-09-09_19.29.38-client.txt)

**Comment by covers1624** [comment]
The version of MineTogether you are adding is incredibly old, with known issues.

Can you please try again with MineTogether `1.19.2-6.3.1`?

From my testing, adding this version to a fresh FTB Genesis instance works as expected.

**Comment by ArtpokeBr** [comment]
Sure, now that you've mentioned a new version I've just noticed that for some reason CurseForge downloaded this old version by default -_-

**Comment by ArtpokeBr** [comment]
Ok, tested with the latest version on CF, things are working properly. Sorry for my rookie mistake here on trusting CF haha.

**Comment by covers1624** [comment]
Fantastic, thanks for the testing.

We archived those old known broken versions (we probably should have done that sooner..), and promoted the latest version to a Release, instead of Beta.
