### ISSUE TITLE
Quark's item rendering in chat shows on the Global chat too

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#82]
![image](https://user-images.githubusercontent.com/15698722/61977213-734ddc00-afb3-11e9-8e72-6ed720c3efb4.png)
![image](https://user-images.githubusercontent.com/15698722/61977216-75b03600-afb3-11e9-9d40-ebd8dc17adfe.png)

Posted on Quark issue tracker, they sent me here
Vazkii/Quark/issues/1402

**Comment by Cloudhunter** [comment]
I don't entirely agree with @yrsegal in Vazkii/Quark/issues/1402 that "it's on them" - it's not really anyones issue, just a clash in the implementations leading to side effects. Quark and our mod are both changing what gets rendered to some extent - and Quark has no understanding that the Vanilla chat isn't being rendered right now, and we have no understanding that something else is rendering expecting Vanilla chat to be there.

This is difficult to fix without constantly changing the vanilla variable to match ours, or without completely overriding Vanilla rendering which isn't ideal as I would like our implementation to leave Vanilla as untouched as possible.

I'll give it some thought as to possible solutions.

**Comment by Cloudhunter** [comment]
Oops, accidental closure.

**Comment by yrsegal** [comment]
If you aren't changing the chatLines being rendered, then we have no way to detect it. Any mod trying to render anything in chat will have the same issue.

**Comment by Cloudhunter** [comment]
Yep - as noted in my response. I'm not saying it is "your bad" - but it isn't really "our bad" either for doing our own chat implementation and rendering!

Will look into fixes regardless, wasn't trying to be dismissive :)

**Comment by yrsegal** [comment]
I didn't mean "on them" as a blame, I meant "on them" as a "the fix has to be on their side".

**Comment by gigabit101** [comment]
This should be resolved as of 2.2.0-RC6
