### ISSUE TITLE
Chat context menu glitch

### ISSUE THREAD

**Issue by Melodeiro** [CreeperHost/CreeperHostGui#83]
In the latest version (RC4), its now hard to click on menu sometimes, because the messages on the background has the higher priority to handle the mouse click event:
![image](https://user-images.githubusercontent.com/2702567/62011276-e2c3f700-b17e-11e9-8a6f-4763c71e82ad.png)
If you click "befriend", for example, instead the message on background would get clicked, highlighted with red rectangle

**Comment by Cloudhunter** [comment]
Same root cause as #96, fix works for both

**Comment by gigabit101** [comment]
This should be resolved as of 2.2.0-RC6
