### ISSUE TITLE
[Request] Ability to stop/resume pregen 

### ISSUE THREAD

**Issue by exultanthabit** [CreeperHost/CreeperHostGui#9]
For one /chpregen 0 0 = GG not invalid. It would be nice to have a stop ability that didn't involve restarting server and clearing the creeperhost pregen data file. (I've said this before but comments have been disabled) additionally the whitelist optional would be a cool feature, can have pregen on back burner to allow players to come on still.

**Comment by Cloudhunter** [comment]
This is already in the latest version.

I've rewritten the command handling too - can you test whether 0 0 works in the latest?

**Comment by Cloudhunter** [comment]
Gonna close this for now as it should be in the latest version. Let me know if you have any more queries!
