### ISSUE TITLE
Chat defaults to MineTogether instead of server, is it possible to change that?

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#90]
This is using minetogether-1.10.2-2.2.0-RC4

I don't see an option to make it default to server chat in the config menu.

**Comment by CH-Paul-T** [comment]
This was reported, on multiplayer servers, server should be the default chat (followed by whatever tab was chosen last after one has been picked).

This will be resolved.

**Comment by aaronhowser1** [comment]
I would also like to be able to disable it in single player too, so I have to purposefully open the chat instead of seeing it by default when I launch the world

**Comment by Cloudhunter** [comment]
Fixed in dev to respect last tab, and config option to disable the MT chat opening on first open.

**Comment by gigabit101** [comment]
This should be resolved as of 2.2.0-RC6
