### ISSUE TITLE
MineTogether logo in background of chat makes it hard to read, and can't really be read itself

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#91]
Using minetogether-1.10.2-2.2.0-RC4

![image](https://user-images.githubusercontent.com/15698722/62169119-ed040380-b2ec-11e9-99c7-0d0af89b0d06.png)

Text on text isn't really a good idea, plus you can't even read the background text at all because the chat gets in the way. I like the idea of having a thing saying what mod it's from and that it's more clear that it isn't the server chat, but it's a bit in the way.

**Comment by aaronhowser1** [comment]
Another example
![](https://cdn.discordapp.com/attachments/552245600721174528/608339100730261529/unknown.png)

**Comment by gigabit101** [comment]
This should be resolved as of 2.2.0-RC6
