### ISSUE TITLE
My username is grey instead of purple (?)

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#95]
![image](https://user-images.githubusercontent.com/15698722/62636297-e4b85380-b8fe-11e9-9489-0838985855b0.png)
Using `minetogether-1.10.2-2.2.0-RC4`
(also, why is it 1.10.2 instead of 1.12.2?)

**Comment by CH-Paul-T** [comment]
Username should be grey.

Purple usernames are other people on the same modpack as you.
White are third parties on other modpacks
Cyan are staff/moderators.

**Comment by aaronhowser1** [comment]
That's super cool! Does it say that anywhere in-game?

**Comment by CH-Paul-T** [comment]
Not yet, but the plan is to add more tooltips before release, but we have a very tight timetable for getting this RC into production (Friday...) So may not make it until the next incremented version.
