### ISSUE TITLE
Timestamps showing on hover makes it hard to click links

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#96]
minetogether-1.10.2-2.2.0-RC4
![image](https://user-images.githubusercontent.com/15698722/62636193-b0dd2e00-b8fe-11e9-8222-86ded57dd4df.png)
![image](https://user-images.githubusercontent.com/15698722/62636204-b5a1e200-b8fe-11e9-9044-e8465ad6e47e.png)
![image](https://user-images.githubusercontent.com/15698722/62636215-b9cdff80-b8fe-11e9-8421-c4c0534bce8e.png)

**Comment by CH-Paul-T** [comment]
The bug here is more we should be padding the string to the end somehow so that hover remains intact for the whole line.

**Comment by Cloudhunter** [comment]
I did originally have this feature in, but probably during a change to how hover worked it got removed. Fixed!

**Comment by gigabit101** [comment]
This should be resolved as of 2.2.0-RC6
