### ISSUE TITLE
[Request] Force reconnect when disconnected

### ISSUE THREAD

**Issue by billbertking1** [CreeperHost/CreeperHostGui#97]
Hi,
So for users with bad internet that cuts out randomly or just MineTogether disconnects, it would be handy to have a "Reconnect" button that forces reconnect as to not have to start the game to reconnect.

**Comment by CH-Paul-T** [comment]
Duplicate of #56 - Reconnection logic already implemented in RC.

**Comment by gigabit101** [comment]
This should be resolved as of 2.2.0-RC6
