### ISSUE TITLE
Allow users to opt in to revealing their username to other players

### ISSUE THREAD

**Issue by 0x4323** [CreeperHost/CreeperHostGui#98]
It's quite hard to differentiate one player from another when everyone is called names like user4323. Tonight, a number of players discussed the possibility of being able to opt in to publicly revealing their username in the minetogether chat, and it seemed quite popular with the players chatting at the time. This could be an option on the GDPR ToC acceptance UI, or even just an option in the .cfg file.

Please consider this feature request.

Thanks,
User4323 :)

**Comment by Jake-E** [comment]
We don't wish to store any PII on our end, we won't be doing this anytime soon.
